### ISSUE TITLE
Unable to access the public bucket

### ISSUE THREAD

**Issue by shreyanshmohnot** [awslabs/aws-data-wrangler#1006]
Unable to create lambda layers with this.
`aws s3 cp s3://aws-data-wrangler-public-artifacts/releases/2.12.1/awswrangler-layer-2.12.1-py3.8.zip .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

**Comment by jaidisido** [comment]
Slight naming issue on our end, should now be fixed. Thanks for raising!
