### ISSUE TITLE
Avro support?

### ISSUE THREAD

**Issue by tooptoop4** [awslabs/aws-data-wrangler#1007]
awswrangler.redshift.copy says "Load Pandas DataFrame as a Table on Amazon Redshift using parquet files on S3 as stage." but is it really limited to parquet or can it import any pandas df to redshift? ie my pandas df might be composed of Avro or json data

**Comment by kukushking** [comment]
It can import any Pandas DataFrame. Parquet is only used as an intermediate step: `DataFrame -> Parquet -> Redshift`, meaning DataFrame will be converted to Parquet first, and then loaded into Redshift.
