### ISSUE TITLE
Handling fixed width columns csv files 

### ISSUE THREAD

**Issue by mpr1** [awslabs/aws-data-wrangler#101]
Requesting to  handle fixed width columns csv files as similar to panda dataframes which can read fixed width files with 'widths' parameter

**Comment by igorborgest** [comment]
Hi @mpr1! Thanks for the message.

Would you like only the read or the write as well?
Would you want to query these files through Athena?

I'm not sure if you could just use the [pandas.read_fwf()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_fwf.html#pandas.read_fwf) or if you need something more elaborated.

**Comment by mpr1** [comment]
I would like to add the feature for read csv only .it would helpful
querying from Athena also.

Thank you,
Prasad

**Comment by igorborgest** [comment]
Hi @mpr1! Thanks for contributing.

Now we already have it available on in [version 0.3.1](https://github.com/awslabs/aws-data-wrangler/releases/tag/0.3.1).

- [Pandas.read_fwf()](http://localhost:63342/aws-data-wrangler/docs/build/html/api/awswrangler.pandas.html#awswrangler.pandas.Pandas.read_fwf)
- [Pandas.read_fwf_list()](http://localhost:63342/aws-data-wrangler/docs/build/html/api/awswrangler.pandas.html#awswrangler.pandas.Pandas.read_fwf_list)
- [Pandas.read_fwf_prefix()](http://localhost:63342/aws-data-wrangler/docs/build/html/api/awswrangler.pandas.html#awswrangler.pandas.Pandas.read_fwf_prefix)
