### ISSUE TITLE
dtype cast is case sensitive

### ISSUE THREAD

**Issue by Dearkano** [awslabs/aws-data-wrangler#1011]
1. Create the table schema on AWS Glue with array type, AWS console suggests using uppercase like ARRAY<DOUBLE>
2. Try to call `wr.s3.to_parquet()`, will return error "awswrangler.exceptions.UnsupportedType: Unsupported Athena type: array<double>"

The issue is [here](https://github.com/awslabs/aws-data-wrangler/blob/52e551e82139c56bc32ef384ae6897b9080b5f8c/awswrangler/_data_types.py#L606), it only checks the lowercase while the uppercase is valid.

Change to lowercase on AWS Glue will mitigate the issue. However, I suggest check both uppercase and lowercase here.
Thanks!

**Comment by kukushking** [comment]
Hi @Dearkano, It's true that in the Athena queries you can use case-insensitive data types, however [Athena data types](https://docs.aws.amazon.com/athena/latest/ug/data-types.html) documentation suggests using lowercase, same as Glue console so that's the convention we're following.
