### ISSUE TITLE
Arrow v6 Support

### ISSUE THREAD

**Issue by gabrielmagno** [awslabs/aws-data-wrangler#1012]
Now that [Arrow 6.0.0](https://arrow.apache.org/release/6.0.0.html) was released, and [pyarrow is already updated in v6.0.0 in conda-forge](https://anaconda.org/conda-forge/pyarrow), I was wondering rather/when an awswrangler version supporting Arrow v6 will be released in conda-forge.

Thank you for the work on this helpful package!

**Comment by jaidisido** [comment]
Arrow 6.0 will indeed be available in the next [release](https://github.com/awslabs/aws-data-wrangler/blob/main/pyproject.toml#L40). Thanks
