### ISSUE TITLE
athena.read_sql_query support for UNLOAD instead of CTAS

### ISSUE THREAD

**Issue by lucasmo** [awslabs/aws-data-wrangler#1015]
In a large, governed data lake environment, we can't always support CTAS queries. With the addition of UNLOAD to Athena's capabilities, it would be useful to use UNLOAD to create Parquet files directly in S3 without the need to modify the Glue catalog.

https://docs.aws.amazon.com/athena/latest/ug/unload.html

**Comment by kukushking** [comment]
Good idea, we'll look into it.
