### ISSUE TITLE
Glue Catalog: allow setting of partition parameters

### ISSUE THREAD

**Issue by gvogel-hh** [awslabs/aws-data-wrangler#1016]
For managing retention times, I would like to set partition-specific parameters in the Glue Catalog. However, the 'parameters' argument to wr.s3.to_parquet() instead affects the table-level parameters, and the lower-level wr.catalog.add_parquet_partitions() does not have a corresponding argument either.

(Suggestions for alternative approaches to handling retention times are also welcome. One of the requirements is to be able to selectively increase retention time after writing the data, so things like prefix-based S3 lifecycle policies won't work.)

**Comment by jaidisido** [comment]
@gvogel-hh could you please clarify which specific argument you would like to pass on when creating a partition in the catalog? I don't see a corresponding "retention period" parameter in the [batch_create_partition](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.batch_create_partition) method

**Comment by gvogel-hh** [comment]
I am sorry for being unclear. The issue is about managing partition-specific parameters using the library. The part about retention times is purely motivational: since there is no native support for retention times, I intend to use partition-specific parameters for storing the information about how long a specific partition should be retained, with actual removal being performed by a separate service.

**Comment by jaidisido** [comment]
Ok, please let me know if the above PR addresses your need. Thanks

**Comment by gvogel-hh** [comment]
Thank you very much for implementing the change, and I am sorry, I did not get around to test your change with our codebase yet. For completeness, it would be nice to make the parameters available for reading via catalog.get_partitions() as well, but I do not see how the output format could be changed in a backwards-compatible manner.
