### ISSUE TITLE
catalog.add_column() without column_comment triggers exception

### ISSUE THREAD

**Issue by gvogel-hh** [awslabs/aws-data-wrangler#1017]
**Describe the bug**

In wr.catalog.add_column(), leaving column_comment unset raises an exception:

> botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter TableInput.StorageDescriptor.Columns[3].Comment, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

Documentation says that the default value None is acceptable as well.

**Environment**

awswrangler==2.12.1

**To Reproduce**

`wr.catalog.add_column(database="a",
    table="b",
    column_name="c",
    column_type="string")`

**Comment by jaidisido** [comment]
Thanks for raising, fixed by PR #1018 and available in the next release
