### ISSUE TITLE
NoFilesFound error when the file is empty

### ISSUE THREAD

**Issue by karim-soufi** [awslabs/aws-data-wrangler#1019]
`wr.s3.read_json` will return NoFilesFound error when the file exists but is actually empty. 

python 3.8
awswrangler 2.8.0

**Comment by jaidisido** [comment]
[wr.s3.read_json](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.read_json.html#awswrangler.s3.read_json) has an `ignore_empty` parameter which is set to `True` by default. Switching that to False will not raise the exception but obviously the method will fail regardless given that the file is empty

**Comment by karim-soufi** [comment]
shouldnt it return an empty dataframe instead of failing if the `ignore_empty `is set to `True`? if not what's the proper usage of the paramter?
