### ISSUE TITLE
Is there anyway to select from multiple parquet files?

### ISSUE THREAD

**Issue by mandywoo** [awslabs/aws-data-wrangler#1022]
I unloaded a table from Redshift to S3 with parallel on, which resulted in the table splitting into multiple parquet files. Is there anyway to use s3.select_query on these multiple parquet files at once?

**Comment by jaidisido** [comment]
The [S3 Select](https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html) API call only applies to one file at a time. It should be used for single, large S3 objects.

Is there any reason why the [wr.s3.read_parquet](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet.html#awswrangler.s3.read_parquet) method is not meeting your needs? When supplied with an S3 path, it reads all objects within the prefix and loads them into a pandas dataframe.

**Comment by mandywoo** [comment]
I want to be able to run SQL queries on the parquet files rather than loading it into a pandas dataframe and then manipulating the dataframes.

**Comment by jaidisido** [comment]
Understood, sadly the S3 Select api call is limited to a single file at the moment.

You could leverage [wr.athena.read_sql_query](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) but that would require creating a Glue catalog table when storing the parquet files (using wr.s3.to_parquet for example) which perhaps is something you don't wish to do.

Cannot think of another option beyond this.

**Comment by foadgr** [comment]
This is also a limitation within "Data Wrangler" in SageMaker Studio, which uses the S3 Select API call. Should be able to select multiple parquets or all files within an S3 object's path.

**Comment by jaidisido** [comment]
As mentioned the S3 Select API does not support reading from a prefix at the moment as it's meant to be used with single, large objects. `wr.s3.read_parquet` and `wr.athena.read_sql_query` are the only alternatives at the moment.
