### ISSUE TITLE
Manged redshift secrets for a cluster in a different VPC uses endpoint field not host field

### ISSUE THREAD

**Issue by jfelectron** [awslabs/aws-data-wrangler#1033]
**Is your idea related to a problem? Please describe.**

Secrets Manager has a RedShift secrets option, which is fully managed with rotation.
The JSON body of the secret value contains a host key as well as an endpoint key.
If the cluster is in a different vpc and being connected to over VPCE, the endpoint must be passed as the host
to the client:

```
conn_params = secrets.get_json_secret(secrets_client, secret_name)
    if "endpoint" in conn_params:
        conn_params["host"] = conn_params.pop("endpoint")
```

**Describe the solution you'd like**
Given secret_id and a managed Redshift secret with endpoint field, the connection is established as exepcted

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
@jfelectron could you please share the piece of documentation where this is specified:
```
Secrets Manager has a RedShift secrets option, which is fully managed with rotation.
The JSON body of the secret value contains a host key as well as an endpoint key.
```
I cannot seem to find a reference to endpoint being used instead of host for a Redshift connection when the cluster is in a different VPC.
