### ISSUE TITLE
ValidationException: An error occurred (ValidationException) when calling the Query operation: Requested database 'abc' not found for identifier 'abc.sampleDB' at line 1:36

### ISSUE THREAD

**Issue by aditshah2112** [awslabs/aws-data-wrangler#1036]
I'm using the AWS Data Wrangler with the Boto3 client and getting an unusual error for not being able to read the data from the timestream query.

```
import awswrangler as wr
import pandas as pd
from datetime import datetime

df=pd.DataFrame()

df=wr.timestream.query(
    'SELECT * FROM "abc"."sampleDB" LIMIT 10')
```

**Comment by sethusrinivasan** [comment]
@aditshah2112 - Can you post the error you are observing?

**Comment by aditshah2112** [comment]
ValidationException: An error occurred (ValidationException) when calling the Query operation: Requested database 'abc' not found for identifier 'abc.sampleDB' at line 1:36

**Comment by kukushking** [comment]
Looks like you are running the query against `abc` database, and `sampleDB` table, and `abc` database does not exist. Make sure database that you'd like to query exists. 

You can read more info about Timestream in [Timestream Developer Guide](https://docs.aws.amazon.com/timestream/latest/developerguide/) as well as check out [AWS Data Wrangler Timestream tutorial](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/026%20-%20Amazon%20Timestream.html).

Feel free to reopen if any more issues.
