### ISSUE TITLE
Atomic transactions using lakeformation

### ISSUE THREAD

**Issue by nicor88** [awslabs/aws-data-wrangler#1037]
**Is your feature request related to a problem? Please describe.**
I would like to have datawrangler supporting Atomic transactions on the lake, as demonstrated by [this article](https://aws.amazon.com/blogs/big-data/part-3-effective-data-lakes-using-aws-lake-formation-part-3-using-acid-transactions-on-governed-tables/). I think that for some workload its not always needed to use Spark/Glue.

**Describe the solution you'd like**
If datalake transactions are available via boto3, is just matter to start a transaction, write to s3, then commit the result. Doing so the lake will enable atomicity.

**Comment by jaidisido** [comment]
The [PR](https://github.com/awslabs/aws-data-wrangler/pull/571) for this feature is ready but we are awaiting GA before it can be released.

You can explore what it will support in this [notebook](https://github.com/awslabs/aws-data-wrangler/blob/main-governed-tables/tutorials/032%20-%20Lake%20Formation%20Governed%20Tables.ipynb). Thanks!
