### ISSUE TITLE
catalog.set_columns_comment

### ISSUE THREAD

**Issue by liquidcarbon** [awslabs/aws-data-wrangler#1047]
**Is your feature request related to a problem? Please describe.**
First, thanks a lot for creating this awesome tool!

I create a lot of tables using this pattern:
```
awswrangler.s3.to_parquet(
    df=df,
    columns_comments=data_dict,
)
```
Once the tables are created, it's difficult to update the comments if the data dictionary is changed.
Similarly, it's hard to put in comments into tables created with CTAS.

**Describe the solution you'd like**
It would be great to be able to update the comments to the Athena tables.
There is  `awswrangler.catalog.get_columns_comment`; it would be great to also have `awswrangler.catalog.set_columns_comment`

I've searched around and the only alternative I found is to go [through Glue client](https://stackoverflow.com/questions/59166027/adding-comments-to-database-columns-and-retrieving-from-aws-glue), which is a bit awkward.  Please let me know if there's another simple option.

**Comment by jaidisido** [comment]
You should be able to achieve this with a combination of `get_table_types` and `create_parquet_table`. For example:

```
import awswrangler as wr
import pandas as pd

df = pd.DataFrame(
    [["a", "b"], ["c", "d"]],
    columns=["col_1", "col_2"],
)

path = "s3://my_bucket/table_comments"
database = "default"
table = "table_comments"

# Create table with on col comment
columns_comments = {"col_1": "my comment"}
wr.s3.to_parquet(
    df=df,
    path=path,
    dataset=True,
    database=database,
    table=table,
    columns_comments=columns_comments,
)

# Update table with new column comments
columns_comments = {"col_1": "my new comment", "col_2": "my col2 comment"}
wr.catalog.create_parquet_table(
    path=path,
    table=table,
    database=database,
    columns_types=wr.catalog.get_table_types(database=database, table=table),
    columns_comments=columns_comments,
)
```
I appreciate that it's not as straightforward as a `add_column_comment` method, but from our perspective adding such a method would open the door to similar asks in the future for similar ones (e.g. `add_table_parameters`, `add_table_types`...) which is not in the spirit of this library.

**Comment by liquidcarbon** [comment]
Thank you for your answer.  This solution nuked my existing data:
- on a table created via  `wr.s3.to_parquet`
- on a table created via CTAS
- both S3 folders that had parquet files ended up empty

**Comment by jaidisido** [comment]
Could you please elaborate or share code to reproduce? `wr.catalog` methods only interact with Glue metadata and do not touch the underlying data. So not sure how using those methods would have "nuked" your existing data...
