### ISSUE TITLE
Visualization labels un-readable in JupyterLab Light theme

### ISSUE THREAD

**Issue by jellomoosie** [awslabs/aws-data-wrangler#1048]
When I use Data Wrangler in SageMaker Studio with the JupyterLab Light theme, none of the labels are visible. The colors for the visualizations do not change in response to a theme change, so the labels end up being white-on-white.

Dark theme: 
![image](https://user-images.githubusercontent.com/53490889/144622837-09dfe0fc-1302-4e03-8b6b-774de235b134.png)

Light theme: 
![image](https://user-images.githubusercontent.com/53490889/144622880-639c4512-3e12-4bbc-8ef5-b0b41cc706ef.png)

**Comment by jaidisido** [comment]
I am afraid this not the right project to raise this issue. This is the AWS Data Wrangler Python library, not the AWS SageMaker Data Wrangler service
