### ISSUE TITLE
parquet file extension 

### ISSUE THREAD

**Issue by mpr1** [awslabs/aws-data-wrangler#105]
I have all aws glue jobs  creating  parquet files with <filename>.snappy.parquet extension. 
To match with the existing files to a common standard, Requesting to change the function pandas.to_parquet save the files with same extension.
I see  its saving parquet files when saving pandas df to parquet file '<file>.parquet.snappy'  extension instead of <file>.snappy.parquet.
example :
sess.pandas.to_parquet(
            dataframe=csvdf,
            path=output_file_path,
            mode= Mode, # :param mode: "append", "overwrite", "overwrite_partitions"
            compression="snappy"
            ,partition_cols= [file_load_date,file_name]

Thanks,

**Comment by igorborgest** [comment]
@mpr1 good catch!

Will be updated in the next release later today (0.2.1)

Thank you
