### ISSUE TITLE
Does AWS Data Wrangler Support updates or upserts on records in a governed table?

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#1050]
Hello, If I create a governed table, is it possible to perform an update on specific records or an upsert without having to overwrite the entire partition? 

I've been reading through the documentation but can't seem to find any method that would help support this on a governed table.

**Comment by jaidisido** [comment]
Only partition level operations are supported with Governed tables at the moment.

**Comment by jaidisido** [comment]
Yes I do believe that record level operations are on the roadmap but no confirmed released date
