### ISSUE TITLE
Allow to override parameters on Glue catalog operations

### ISSUE THREAD

**Issue by dstockstad** [awslabs/aws-data-wrangler#1055]
Hi,

I have a need for overriding request parameters when doing the following operations in Glue:
* Add partition
* Create table

Examples of parameters would be:
* InputFormat
* OutputFormat

At the moment I can see that these parameters are hardcoded when we add a parquet table/partition:
https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/catalog/_definitions.py#L30

I think this can be a useful escape valve when we for whatever reason want to customize the resulting table in the Glue catalog. I see two options:
* Add generic versions of create_parquet_table and add_parquet_partitions (create_table and add_partitions) where we can have full control over the parameters
* Allow existing create_parquet_table and add_parquet_partitions to accept a dictionary with overrides where we can selectively override the parameters we want to such as {Input,Output}Format etc. but otherwise use the predefined ones.

I am happy to submit a PR for this but figured an issue would be a good place to discuss this and whether you'd be open to such a change.

Kind regards,
Dag

**Comment by jaidisido** [comment]
Hi @dstockstad, there are private methods in the library [`wr.catalog._create_table`](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/catalog/_create.py#L27) [`wr.catalog._add_partitions`](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/catalog/_add.py#L22) which accept generic input arguments. They are used by the public methods you mentioned (`create_parquet_table` and `add_parquet_partitions`) to pass in parquet specific arguments.

We don't wish to expose these methods because the Wrangler library avoids implementing methods that are already supported in the boto3 library. Instead it attempts to augment them and implement/abstract specific logic, in this case creating a parquet table. Hope this explains our perspective on this

**Comment by dstockstad** [comment]
Hi @jaidisido, 

I agree one would not want to get into the habit of reinventing the wheel. My problem is that I want to reuse almost all existing parameters for a parquet table/partition but override a few specific ones. 

So while possible to use _create_table and _add_partitions, it seems unnecessary when I just want to override the odd parameter, namely InputFormat and OutputFormat. create_parquet_table and add_parquet_partitions do not support overriding those particular parameters (I think, correct me if I'm wrong).

I experimented with putting in a dictionary with overrides. In my experimentation, I would call something like this:
```
        awswrangler.catalog.create_parquet_table(
...
            table_override={
                "StorageDescriptor": {
                    "InputFormat": "org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat",
                    "OutputFormat": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
                }
            },
...
        )
```

And the _create_parquet_table would understand how to apply those overrides i.e. merge the overrides into the final request to Glue. 

It could also be adding two parameters to create_parquet_table, add_parquet_partitions called input_format and output_format if you think that's cleaner. Or some other version that you like better :) Let me know your thoughts. 

This is to create a Glue schema for a special delta lake table which as covered here requires a particular Input/OutputFormat:
https://docs.databricks.com/delta/presto-integration.html
https://docs.databricks.com/delta/redshift-spectrum-integration.html

Hope that makes sense. Let me know if you have any questions. 

Kind regards,
Dag

**Comment by jaidisido** [comment]
Thank you @dstockstad, I understand what you are trying to achieve here. However as you can see the `create_parquet_table` method is already overloaded. Allowing every specific use case like the one you described to add more input arguments would just lead to a situation where we are reproducing the same method that is available in the boto3 library, but worse. And we don't see the value of that, particularly when the private method is available.

**Comment by dstockstad** [comment]
Sure, I understand. Would creating a new method called create_delta_table/add_delta_partition be an option that you'd be open to? Just asking, using _create_table is an option even if it would result in duplicating large amounts of code. 

I've seen some other issues around delta tables like:
https://github.com/awslabs/aws-data-wrangler/issues/873

So I guess there is some interest for this out in the community, hence it would be useful to know if you'd welcome contributions of the corresponding methods on the catalog side. 

The main issue is that we're not able to use a Glue crawler (as far as I can tell) for these types of tables which made us look at this library in the first place.

**Comment by jaidisido** [comment]
That is a fair point. There does seem to be interest in `delta` so a new method might make sense. A PR would be appreciated indeed

**Comment by dstockstad** [comment]
Great, give me some time to put something together and get more familiar with this project. Will reference this issue when creating the PR.
