### ISSUE TITLE
Broken link in to_parquet docs

### ISSUE THREAD

**Issue by mdavis-xyz** [awslabs/aws-data-wrangler#1058]
In the docs for [`to_parquet`'s `mode` argument](https://aws-data-wrangler.readthedocs.io/en/2.7.0/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet), there's a link to a "tutorial". But that link is the page that the viewer is already on.

There is no tutorial on that page. There are examples, but none of them use mode.

Is that link supposed to point to [here](https://aws-data-wrangler.readthedocs.io/en/2.7.0/tutorials/004%20-%20Parquet%20Datasets.html)?

**Comment by mdavis-xyz** [comment]
Note that the ["upsert" mode tutorial](https://aws-data-wrangler.readthedocs.io/en/2.7.0/tutorials/004%20-%20Parquet%20Datasets.html#Upserting-partitions-(overwrite_partitions)) is not clear, since the existing partition has identical values.

**Comment by kukushking** [comment]
Thanks for opening this. Not quite sure what you mean by "existing partition has identical values" in your last message. In the tutorial, the partition with `id=1` has not been affected while the partitions with `id=[2, 3]` have been updated.
