### ISSUE TITLE
Athena returns empty set when queried with a bucketing key

### ISSUE THREAD

**Issue by moykeen** [awslabs/aws-data-wrangler#1061]
Athena returns empty set when queried with a bucketing key. It happens randomly.
I made a bucketed table with the following very simple code.

```
df = pd.DataFrame({
	"some_data1": [1, 2, 3, 4, 5],
	"some_data2": [1, 2, 3, 4, 5],
	"bucketing_key": [...],  # tried various values for bucketing key
])

n_bucket = 3
wr.s3.to_parquet(
	df,
	path="s3://...",
	dataset=True,
	database="my database",
	table="my_table",
	bucketing_info=(["bucketing_key"], n_bucket)
)
```

And, I tried to fetch data from Athena by a query like
```
SELECT * FROM my_table WHERE bucketing_key = 'some_key'
```

Unexpectedly, my query returns empty set, even if the provided key does exist in the original `df`.
By experiment, I found it happens when the value of bucketing key are:
- string with medium to long length
- large positive integer
- negative integer

**Comment by moykeen** [comment]
I succeeded to detect the reason. The current code fails to simulate Hive hashing.

https://github.com/awslabs/aws-data-wrangler/blob/d0cbd9fe443b546cf0bce08543f774a4e7e63935/awswrangler/s3/_write_dataset.py#L134
Although this hash computation looks identical to the Hive hashing, the resulting hash value can be different, because _Python's integer never overflows_. Also, hashing for large and negative integers needs some fix.

I rewrote `_get_bucket_number` and `_get_value_hash` as follows. 

```
def _simulate_overflow(value, bits: int = 31, signed: bool = False):
	base = 1 << bits
	value %= base
	return value - base if signed and value.bit_length() == bits else value


def _get_bucket_number(number_of_buckets: int, values: List[Union[str, int, bool]]) -> int:
    hash_code = 0
    for value in values:
        hash_code = 31 * hash_code + _get_value_hash(value)
        hash_code = _simulate_overflow(hash_code)
        
    return hash_code % number_of_buckets


def _get_value_hash(value: Union[str, int, bool]) -> int:
    if isinstance(value, (int, np.int_)):
    	value = int(value)
    	bigint_min, bigint_max = -2**63, 2**63 - 1
    	int_min, int_max = -2**31, 2**31 - 1
    	if not (bigint_min <= value <= bigint_max):
    		raise ValueError  # I suggest to raise error as Athena cannot handle integer larger than bigint.
    	if not (int_min <= value <= int_max):
    		value = (value >> 32) ^ value
    	if value < 0:
    		return -value - 1
    	return int(value)
    if isinstance(value, (str, np.str_)):
        value_hash = 0
        for byte in value.encode():
            value_hash = value_hash * 31 + byte
            value_hash = _simulate_overflow(value_hash)
        return value_hash
    if isinstance(value, (bool, np.bool_)):
        return int(value)
```

With this revise, the bug reported above has been resolved. Please review my code.

**Comment by moykeen** [comment]
Furthermore, consider we apply both bucketing and partitioning. In such a case, the numbers of buckets in partitions can be variable, which is very problematic. This often happens when the number of data in a partition is not sufficient to distribute over all the buckets.

Let's say, a partition A has 5 buckets whereas another partition  has only 3 buckets.
Athena, then, returns error saying the partitions have different number of buckets.

In order to properly control the number of buckets, I suggest to modify 
https://github.com/awslabs/aws-data-wrangler/blob/d0cbd9fe443b546cf0bce08543f774a4e7e63935/awswrangler/s3/_write_dataset.py#L117

change to `observed=False`. And, prior to this loop, add a line:
```
bucket_number_series = bucket_number_series.astype(pd.CategoricalDtype(range(bucketing_info[1])))
```

**Comment by jaidisido** [comment]
Hi @moykeen, thank you for deep diving this, it's very much appreciated. Do you mind opening a PR for this? It would help us review it and also see the impact it would have on the overall test suite which we cannot do at the moment.

**Comment by jaidisido** [comment]
Suggested changes have been merged and will be available in the next release. Thanks again
