### ISSUE TITLE
Failing to query governed table successfully with partitions: Spectrum Scan Error: FindGovernedTableObjects

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#1062]
Using AWS Data Wrangler, I have successfully created and added data to my governed table in us-east-1 using the` wr.s3.to_parquet` method using: 

```
wr.s3.to_parquet(df,
    path='s3://s3bucket-to-upload-to/animal_locations_governed_table/',
    index=False,
    dataset=True,
    dtype={'id': 'int', 
                   'animal': 'string',
                   'longitude': 'double', 
                   'latitude': 'double'},
    partition_cols= ['date'],
    compression= 'snappy',
    database = 'animals',
    table='animal_locations_governed',
    description= 'animal location table',
    columns_comments= {'id': 'unique id of animal', 
                      'animal': 'Animal Name', 
                      'logitude': 'x coordinate',
                      'latitude': 'y coordinate',
                      'date': 'date animal was located'},
    table_type = "GOVERNED",
    transaction_id=transaction_id_write)
```

I can successfully see that my dataset has been added to lakeformation:

![image](https://user-images.githubusercontent.com/33879968/145689877-95c00926-31e9-4556-a2ab-395954b5a923.png)

However, when attempting to query the table using the same user that created it  with aws data wrangler using 
`df = wr.lakeformation.read_sql_query(
    sql=f"SELECT * FROM {'animal_locations_governed'};",
    database='animals')`

I get this error:
```
QueryFailed: Internal service error: Could not process message with error: Failed running query: ERROR:  Spectrum Scan Error: FindGovernedTableObjects 
DETAIL:  
  -----------------------------------------------
  error:  Spectrum Scan Error: FindGovernedTableObjects 
  code:      15005
  context:   Error calling GetTableObjects Message: {"__type":"InternalServiceException"}
  query:     5
  location:  scan_range_manager.cpp:1448
  process:   query2_79_5 [pid=4238]
  -----------------------------------------------
```

When I make this table **without partitions**, I seem to **not get any errors**. Any suggestions on what might be causing this error and why I can't query my data successfully?

**Comment by jaidisido** [comment]
From the error it looks like a server side exception. Have you tried querying the data in Athena? Is the same error thrown there too?

**Comment by AdrianoNicolucci** [comment]
So when I query the table in my "primary" Athena wrok group with the query:

`SELECT * FROM "animals"."animal_locations_governed_partitioned" limit 10;`

I get the error message: 

`HIVE_METASTORE_ERROR: com.amazonaws.services.glue.model.InvalidInputException: Specify Either Transaction Id or Query AsOf Time (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 01145a88-b6d9-4e4e-964e-2bb2ce173f25; Proxy: null)
This query ran against the "animals" database, unless qualified by the query. Please post the error message on our forum  or contact customer support  with Query Id: b607c8df-5578-427a-ba4f-2977eb0f42fa`

However, When I query the same table from the "AmazonAthenaLakeFormation" work group, I don't get any errors:
but no records appear. If i modify my query to use the time travel feature in this workgroup,

`SELECT * FROM "animals"."animal_locations_governed_partitioned"
FOR SYSTEM_TIME AS OF TIMESTAMP '2021-12-12 18:25:00 UTC'
limit 10;`

I then get the error message 
`Encountered an exception executed in context[retrieving meta-data] with message[Table not found Please check your query.
This query ran against the "animals" database, unless qualified by the query. Please post the error message on our forum  or contact customer support  with Query Id: 874aacc1-220a-475a-b0c8-40a7bf5f5340`

Perhaps it would be helpful to know that I attempted to repair partitions with: `wr.athena.repair_table(table='animal_locations_governed_partitioned', database='animals')`

However, this results in the error message:

`FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask`

**Comment by jaidisido** [comment]
I get the feeling that there are many issues here and we need to identify the root cause. At the moment I can't tell if it's an issue with:
- You underlying data and how the table was created
- Your Lake Formation setup and permissions in the account
- A server side issue with the LF governed tables engine (spectrum)

Could you please first try to run this [tutorial](https://aws-data-wrangler.readthedocs.io/en/latest/tutorials/032%20-%20Lake%20Formation%20Governed%20Tables.html#2.1.1-CSV-table)? Specifically steps 2.1.1 or 2.1.2 to create the table. I have just tested these steps in my own account so I know they work and I can query that table/data with both Wrangler and in Athena.

If this step works, then we will know that it's not a LF setup/permissions issue and will go from there

**Comment by AdrianoNicolucci** [comment]
So I went through steps 2.1.1, 2.1.2, and 2.2.3, and all successfully created tables. I was able to query those tables in both wrangler and in Athena successfully.

**Comment by jaidisido** [comment]
Good, so that tells us that it's not your LF setup but something specific to the table you created. I would need a way to reproduce it so if you can share a minimal example of how to recreate your table it would be helpful

**Comment by AdrianoNicolucci** [comment]
Sure see sample data and method below. Even with the subset dataset below, I still can't get Athena or Wrangler to query it. 


**dataframe:** 
```
df = pd.DataFrame({
    "id": [1,2,3],
    "animal": ["dog","cat", "pig"],
    "logitude": [23.56,47.64,13.56],
    "latitude": [57.34,43.46,31.46],
    "date": ["2021-12-09","2021-12-09","2021-12-10"]
})
```

**function used to create table:**


```
table = "animal_locations_governed_partitioned"
database = 'animals'
transaction_id_write = wr.lakeformation.start_transaction(read_only=False)
print (transaction_id_write)
wr.s3.to_parquet(
    df=df,
    path=f's3://bucket/{database}/animal_locations_governed_partitioned/',
    dataset=True,
    compression= 'snappy',
    database=database,
    table=table,
    table_type="GOVERNED",
    partition_cols=['date'],
    description="animal location table",
    columns_comments={'id': 'unique id of animal', 
                      'animal': 'Animal Name', 
                      'logitude': 'x coordinate',
                      'latitude': 'y coordinate',
                      'date': 'date animal was located'},
    mode='overwrite',
    transaction_id=transaction_id_write
)
```

**Comment by jaidisido** [comment]
I believe `date` is a reserved keyword in Redshift Spectrum.

I have rerun your example replacing the `date` column with `dt` and it worked fine:
```
import awswrangler as wr
import pandas as pd

df = pd.DataFrame(
    {
        "id": [1, 2, 3],
        "animal": ["dog", "cat", "pig"],
        "longitude": [23.56, 47.64, 13.56],
        "latitude": [57.34, 43.46, 31.46],
        "dt": ["2021-12-09", "2021-12-09", "2021-12-10"],
    }
)

database = "animals"
table = "animal_locations_governed_partitioned"
path = f"s3://my_animals_bucket/{database}/{table}/"

wr.s3.delete_objects(path)
wr.catalog.delete_table_if_exists(table=table, database=database)

transaction_id_write = wr.lakeformation.start_transaction(read_only=False)
wr.s3.to_parquet(
    df=df,
    path=path,
    dataset=True,
    compression="snappy",
    database=database,
    table=table,
    table_type="GOVERNED",
    description="animal location table",
    columns_comments={
        "id": "unique id of animal",
        "animal": "Animal Name",
        "longitude": "x coordinate",
        "latitude": "y coordinate",
        "dt": "date animal was located",
    },
    mode="overwrite",
    transaction_id=transaction_id_write,
    partition_cols=["dt"],
)

wr.lakeformation.commit_transaction(transaction_id_write)

print(
    wr.lakeformation.read_sql_table(
        table=table,
        database=database,
    )
)
```

**Comment by AdrianoNicolucci** [comment]
Thanks for clarifying this, I'm sure a lot of people will encounter this issue, given that columns named as "date" would probably be the most common field that people will use as a partition.
