### ISSUE TITLE
Read Parquet Chunks

### ISSUE THREAD

**Issue by jgcaza** [awslabs/aws-data-wrangler#107]
Currently when reading very large Parquet datasets using AWS Glue Python Shell a memory error is thrown. I suspect this is due to the fact that Python Shell does not have alot of allocated memory.

It would be great to have the ability to chunk the Parquet read and write to Parquet snappy.

**Comment by ankurshri** [comment]
Sorry to barge into someone else's issue thread. Yes even we are looking at this feature

**Comment by igorborgest** [comment]
Thank you for the contribution. Please, reopen the issue if it persists even after the version `1.0.0`.
