### ISSUE TITLE
Date/time mapping from database to pandas data frame

### ISSUE THREAD

**Issue by imanebosch** [awslabs/aws-data-wrangler#1075]
Hi,

We've been using data-wrangler for a while, but still do not fully understand the logic behind the mapping between database date/time and final pandas formats when querying data.

For instance in redshift a database type (datetime, timestamp, date) can be converted to pandas `datetime64[ns]` , `Timestamp()` or `datetime.date`.

To get one unique data type we read the database metadata to know which are date columns. Then we apply the pandas function `to_datetime()` to them to be sure that they are in the datetime64[ns] format. However, we'd appreciate whether someone could add some light to this puzzle and show us the most convenient way to deal with this date conversion.

Many thanks for your answer and amazing job

**Comment by jaidisido** [comment]
Hi @imanebosch, thanks for this question. If I understand correctly, you are trying to figure out how are date/timestamp types handled in general within Wrangler? If so, this data types [file](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/_data_types.py) contains most of the methods used to perform these conversions. As you can see the answer depends on a number of factors. One of them is the data types of the source/destination (e.g. Redshift vs MySQL vs Athena types). Sometimes a conversion to PyArrow types is also required which makes a bit more complex. For instance, when writing to Athena from a pandas dataframe, we might have to first convert the data frame to a pyarrow table and then convert again to Athena types.
