### ISSUE TITLE
Avoid breaking changes for Lambda SAM layers

### ISSUE THREAD

**Issue by mccauleyp** [awslabs/aws-data-wrangler#1076]
**Is your feature request related to a problem? Please describe.**

The format of the Lambda [SAM layer](https://serverlessrepo.aws.amazon.com/applications/us-east-1/336392948345/aws-data-wrangler-layer-py3-9) changed today to remove the `Suffix` parameter and add `ExportName` and `LayerName` parameters instead. These provide the same functionality of allowing the layer to be deployed to multiple CloudFormation stacks in the same account, but the template change also causes deployments that rely on the SAM resources to fail unexpectedly. This happened once before in my experience when the layers for different Python versions were split into separate SAM resources instead of a consolidated one. 

**Describe the solution you'd like**
In the future, it'd be nice if the SAM resources were changed only after some announcement with time allowed for migration. Perhaps the existing resource can be maintained for some time and the updated version can be the way to consume a newly released version of the code, which could be covered in the Release Notes.

**Comment by kukushking** [comment]
Hi @mccauleyp, thanks for opening this. Apologies for breaking changes - we're still trying to work out the best format of the template to accommodate various requirements. It should be stable now though with he latest change that allows to completely override both layer and export names.
