### ISSUE TITLE
wr.s3.to_parquet not supporting to camelCase columns event after rename

### ISSUE THREAD

**Issue by dileepjavadeveloper** [awslabs/aws-data-wrangler#1077]
I want aws S3 parquet file should have camelCase Column but to_parquet function writing it with underscore.
using import awswrangler as wr in aws lambda 

ex: 
df.rename(columns = {'serialnumber':'serialNumber'}, inplace = True)

expected : 
{
  "**serialNumber**": "ABCDEF",
  "date": "2021-12-17 00:00:00"
}
Actual     : 
{
  "**serial_number**": "ABCDEF",
  "date": "2021-12-17 00:00:00"
}

when I used s3 select to see data in parquet file in json format ,below is json:
{
  "serial_number": "ABCDEF",
  "date": "2021-12-17 00:00:00"
}

is it possible to have camelCase?

Thanks

**Comment by jaidisido** [comment]
From the [docs](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet), the `to_parquet` method has a `sanitize_columns` parameter which is set to True by default. When set to False, it won't sanitize your columns.

**Comment by dileepjavadeveloper** [comment]
Hi Jaidisido,

Still have same issue.

I tried with sanitize_columns but still have same issue ,please look below code

`def lambda_handler(event, context):
    print("test_sanitize_columns start")
    wr.s3.to_parquet(
        df=pd.DataFrame({
            'serialNumber': ['1', '2', '3'],
            'year' : ['2021','2021','2021'],
            'month' : ['12','12','12'],
            'day' : ['16','16','16']
            }),
            path='s3://mybucket/refined/time_and_distance_daily/',
            dataset=True,
            database='dev_db',  # Athena/Glue database
            table='time_and_distance_daily',  # Athena/Glue table
            partition_cols=["year","month","day"],
            sanitize_columns=False
    )
    print("test_sanitize_columns done")`

output written in file is : 
{
  "serial_number": "1"
}
{
  "serial_number": "2"
}
{
  "serial_number": "3"
}

**Comment by dileepjavadeveloper** [comment]
FYI :   sanitize_columns=False  work  only if database and table are not used.

def lambda_handler(event, context):
print("test_sanitize_columns start")
wr.s3.to_parquet(
df=pd.DataFrame({
'serialNumber': ['1', '2', '3'],
'year' : ['2021','2021','2021'],
'month' : ['12','12','12'],
'day' : ['16','16','16']
}),
path='s3://mybucket/refined/time_and_distance_daily/',
dataset=True,
#database='dev_db', # Athena/Glue database
#table='time_and_distance_daily', # Athena/Glue table
partition_cols=["year","month","day"],
sanitize_columns=False
)
print("test_sanitize_columns done")
