### ISSUE TITLE
read_parquet_metadata fails on Columns with only NULLS

### ISSUE THREAD

**Issue by xtrearer** [awslabs/aws-data-wrangler#1082]
Each table location on S3 has multiple files. The schema is consistent through out all of these files. However, in some files, the Columns may be NULL, due to the nature of the data. When one of these files are picked up in the Sampling of read_parquet_metadata, it results in a "awswrangler.exceptions.UndetectedType: We can not infer the data type from an entire null object column" exception.

I feel this is something that can be overcome by introducing an override data type. So if it cannot infer the data type, it uses the value from the override parameter. 

P.S. this library has changed my life!

**Comment by kukushking** [comment]
Thanks @xtrearer for the feedback! Glad you're enjoying the library.

I've created a PR with a small fix that would let you override types with `dtype`:
```
wr.s3.read_parquet(path)
Out[2]: 
   c0    c1
0   0  None
1   1  None
2   2  None

wr.s3.read_parquet_metadata(path, dtype={'c1': 'bigint'})
Out[3]: ({'c0': 'bigint', 'c1': 'bigint'}, None)
```
You can install and try it out via:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@feat-override-nulls
```
However, can you elaborate a bit more your use case? What are you doing with the schema after you've read it?

**Comment by xtrearer** [comment]
Hi!

Thank you for the reply! 

I've made the pull and read your response, and this is not exactly what I was looking for. So yes, let me give some context on the Use Case as well as why this current solution will not work.

**Use Case:**
AWS Glue Crawler has failed me for the last time and I basically went, "fine, I'll do it myself". So I wrote a Lambda based alternative that can crawl my Data Lake, looking for any new Partitions and or Schema changes, and taking the required actions.  It works REALLY well. In order to achieve the Schema part, I needed to be able to do 1 of 2 things: 1.) Read the metadata from the Parquet files, or 2.) Read the Parquet files themselves into a Dataframe. 

I wanted to avoid option 2.) as it would be memory intensive on a Lambda and run longer, making this more expensive than it needs to be. Option 1.) was perfect - low memory usage and faster run times. In my lake, some of the event data streams have fields that are optional. So it sometimes occurs that one entire Parquet file would have that column as NULL. My Custom Crawler takes X amount of Sample Paths to determine the Schema. In my tests, it sometimes grabbed files where these Columns are all NULL. This causes the Exception I mentioned.

To summarize, the Custom Crawler creates its version of the Schema by reading the metadata from the actual Parquet files. This means that the Custom Crawler does not know which columns exists before reading the metadata. So the solution you have provided - while it does work - will not work for my application, as it depends on API call knowing which Columns exist prior to reading the metadata.

So the function would need to offer some override functionality that is blind to the Columns. For consistency, updating the "dtype" parameter to function like it does on the "read_csv" function could sort of work, i.e. input of "dtype=str" would force all columns retrieved to be of type "string". However, this will cause other issues and does not satisfy the requirement of simply overriding certain columns if their dtype is NULL. 

So ultimately having some form of parameter that only triggers IF the column dtype could not be confirmed would probably be best. So either make it default behavior, which leads to lots of regression testing I guess, or make a new parameter that only triggers when a column dtype is NULL, something like dtype_na?

Hope this helps to make sense out of it and thanks again for spending time on this!

Cheers,
Leo

**Comment by kukushking** [comment]
The issue I see with overriding `dtype` for columns with `NULL` is that you might have multiple columns with different types containing `NULL`s and with that solution you would force them to the same type when they are not. You can see this would work in a very narrow range of use cases. Is that assumption true for your case?

**Comment by xtrearer** [comment]
That is true, I agree... is it perhaps then possible to not have the code
fail and just have the response contain NULLs for the columns where the
data type could not be determined? That way it becomes the end users task
to deal with NULL data types in whatever way they see fit.

Your thoughts?
