### ISSUE TITLE
partition values in _build_table_objects() in _utils.py in lakeformation

### ISSUE THREAD

**Issue by clarkebishop** [awslabs/aws-data-wrangler#1096]
_build_table_objects() lets you pass in a partition parameter. Line 58 and 59 of _utils.py intends to add PartitionValues data to the table object.

`
if partitions_values:   

    table_object["PartitionValues"] = partitions_values[f"{path.rsplit('/', 1)[0].rstrip('/')}/"]
`

​I don't see how this code can work properly.

The end result needs to be an AddObject as described in the documentation, https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#:~:text=Client.exceptions.EntityNotFoundException-,update_table_objects,-(**kwargs)%C2%B6

PartitionValues inside the Write Operation should be a list of strings. The above code does not produce a list and the f-string creates an S3 path fragment instead of a partition value. The correct format is shown below.

'PartitionValues': [
                    'string',
                ]

**Comment by jaidisido** [comment]
It does return a list, not a string. The f-string itself is not returned, but rather used to access the key within the `partition_values` dictionary. Here is an example mocking the behaviour of the [_build_table_objects](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/lakeformation/_utils.py#L42) method:

```
path = 's3://my-bucket/par0=1/par1=a/my-parquet.snappy.parquet'

partitions_values = {'s3://my-bucket/par0=1/par1=a/': ['1', 'a'], 's3://my-bucket/par0=1/par1=b/': ['1', 'b'], 's3://my-bucket/par0=2/par1=b/': ['2', 'b']}

table_object = {
  "Uri": "s3://my-bucket/par0=1/par1=a/my-parquet.snappy.parquet",
  "ETag": '"5631f5dd16942e004bdab9e0797a9c82"',
  "Size": 7823,
}

if partitions_values:
            table_object["PartitionValues"] = partitions_values[f"{path.rsplit('/', 1)[0].rstrip('/')}/"]

print(table_object)
```

which as you can see below returns a list for the "PartitionValues" entry, not a string:
```
{'Uri': 's3://my-bucket/par0=1/par1=a/my-parquet.snappy.parquet', 'ETag': '"5631f5dd16942e004bdab9e0797a9c82"', 'Size': 7823, 'PartitionValues': ['1', 'a']}
```
