### ISSUE TITLE
Docs: Incomplete guidance to CDK layer usage

### ISSUE THREAD

**Issue by RigoIce** [awslabs/aws-data-wrangler#1097]
**Is your idea related to a problem? Please describe.**
The description is of how to use the Serverless Application Repository within CDK is not complete as it does not describe how the Application could be used within a stack. Especially for beginners, this might be confusing or hard to get in touch with that.

**Describe the solution you'd like**
The documentation could be improved with a more extensive example like on the docs for the Lambda Powertools, see [Link](https://awslabs.github.io/aws-lambda-powertools-python/latest/).

I'd be happy to provide a proposed improvement in a pull request if desired.

**Comment by jaidisido** [comment]
Hi @RigoIce, thanks for raising this. The SAR doc section can indeed be improved and a PR would be more than welcome. Here is the [file](https://github.com/awslabs/aws-data-wrangler/blob/main/docs/source/install.rst) you would need to change. Cheers

**Comment by RigoIce** [comment]
Great, @jaidisido. I'll prepare something.

**Comment by jaidisido** [comment]
Changes available in [latest](https://aws-data-wrangler.readthedocs.io/en/latest/install.html) docs and will be visible in stable in the next release. Thanks again for the contribution.
