### ISSUE TITLE
Not possible to SELECT data in Athena from a Governed Partitioned Parquet table.

### ISSUE THREAD

**Issue by leanbc** [awslabs/aws-data-wrangler#1099]
**Describe the bug**

When writing a `GOVERNED` partitioned parquet table to S3 I cannot read the data from Athena because I get this error:
`QueryFailed: HIVE_METASTORE_ERROR: com.amazonaws.services.glue.model.InvalidInputException: Specify Either Transaction Id or Query AsOf Time (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: ba34c34e-3f6c-412f-b0d6-2aaef437d94e; Proxy: null). You may need to manually clean the data at location 's3://aws-athena-query-results-031440329442-eu-west-1/tables/f99abdb0-9f17-4d86-8314-bfe27214b819' before retrying. Athena will not delete data in your account.
`
**Environment**

awswrangler        2.13.0

**To Reproduce**

```
import pandas as pd
import awswrangler as wr

table = "gov_company_card_card"
bucket = "a_bucket"
database = "glue_database"



#create a transaction
transaction_id = wr.lakeformation.start_transaction(read_only=False)

df = pd.DataFrame({"event_name":{"1365":"activated","1366":"pin_set","1367":"device-bound"},"year":{"1365":"2022","1366":"2022","1367":"2022"},"month":{"1365":"01","1366":"01","1367":"01"},"day":{"1365":"01","1366":"01","1367":"01"},"hour":{"1365":"13","1366":"13","1367":"13"}})

#write 
wr.s3.to_parquet(
    df=df,
    path=f"s3://{bucket}/{database}/{table}/",
    dataset=True,
    database=database,
    table=table,
    table_type="GOVERNED",
    partition_cols=['year','month','day','hour'],
    transaction_id=transaction_id
)

#Transaction is not commited so table is not visible yet for Athena
wr.lakeformation.describe_transaction(transaction_id=transaction_id)
#commit transaction and Table is visible in Athena
wr.lakeformation.commit_transaction(transaction_id=transaction_id)
wr.lakeformation.describe_transaction(transaction_id=transaction_id)

read_from_athena = wr.athena.read_sql_table(
    table=table,
    database=database)

```

When reading from Athena I get this error:

`QueryFailed: HIVE_METASTORE_ERROR: com.amazonaws.services.glue.model.InvalidInputException: Specify Either Transaction Id or Query AsOf Time (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 6176cd4f-2c15-45c3-97ba-4ee8cb013741; Proxy: null). You may need to manually clean the data at location 's3://aws-athena-query-results-031440329442-eu-west-1/tables/27a280b9-a250-495c-9e2a-3b3ef42ea5c6' before retrying. Athena will not delete data in your account.`

If I write to s3 without partitions:

```
#write 
wr.s3.to_parquet(
    df=df,
    path=f"s3://{bucket}/{database}/{table}/",
    dataset=True,
    database=database,
    table=table,
    table_type="GOVERNED",
    # partition_cols=['year','month','day','hour'],
    transaction_id=transaction_id
)
```

It works

**Comment by jaidisido** [comment]
Querying a governed table with Athena must be done via the `AmazonAthenaLakeFormation` workgroup (see AmazonAthenaLakeFormation workgroup in Considerations and Limitations [section](https://docs.aws.amazon.com/athena/latest/ug/lf-governed-tables.html)). Once you have created the workgroup, you can make the same call but with the Athena workgroup as an input:

```
read_from_athena = wr.athena.read_sql_table(
    table=table,
    database=database,
    workgroup="AmazonAthenaLakeFormation",
)
```

If you do not wish to use the workgroup, you can also read the data via the dedicated LF method instead:

```
read_from_lakeformaiton = wr.lakeformation.read_sql_table(
    table=table,
    database=database,
)
```
