### ISSUE TITLE
Enhance pandas.to_aurora() to specify target columns based on df header

### ISSUE THREAD

**Issue by josecw** [awslabs/aws-data-wrangler#110]
#74 

Request enhancement for to_aurora() function to specify target columns from the header of dataframe / athena.get_query_columns_metadata().

postgres copy command expect csv file have same order with table column. In scenario where not all fields are mapped or structure changed, the operation will fail. 

Quick workaround is set default value and ensure dataframe column order is according to table meta.

**Comment by igorborgest** [comment]
Done. Will be shipped in the next release on the Weekend!

**Comment by josecw** [comment]
tested and it works!
