### ISSUE TITLE
store_parquet_metadata not accepting list of strings as path

### ISSUE THREAD

**Issue by koberghe** [awslabs/aws-data-wrangler#1109]
Here is a minor observation in version 2.13.0:
According to the docstring, `store_parquet_metadata` should accept `path : Union[str, List[str]]`. But in the definition it's only `path: str`

PS: Thank you for this awesome library. I only started working with it a couple of days ago.

**Comment by jaidisido** [comment]
Glad to hear you enjoy the library @koberghe. You are right, the docs are incorrect, path should be `str` only. I have updated the documentation and it will be visible in the next release.

While the method could support a list of paths, I don't believe it makes sense. The underlying Glue table would have a path that references the entire prefix, not just certain parquet files within it. So I can't see a reason why a user would only want to read metadata from a subset within the prefix.

**Comment by koberghe** [comment]
Let's say I have an existing parquet dataset with a Glue catalogue to which I add some more parquet files. Then I thought I could use `store_parquet_metadata` with `mode='append'` to update the Glue catalogue for those new files.

(Later I realized that this is not what I needed. I have a fixed schema and partitions well suited for projection. So now I just do 'create_parquet_table' once.)
