### ISSUE TITLE
wr.redshift.copy into table with an Identity column?

### ISSUE THREAD

**Issue by jeyalee** [awslabs/aws-data-wrangler#1110]
My table has a primary key set to type Identity. Is there a way for Wrangler to copy to the table without me including the identity column in the dataframe?

**Comment by jaidisido** [comment]
Yes, you shouldn't have to specify it in the dataframe. Here is an example:
```
import pandas as pd
import awswrangler as wr

con = wr.redshift.connect("aws-data-wrangler-redshift")

schema = "public"
table = "id_test"

with con.cursor() as cursor:
    cursor.execute(f"DROP TABLE IF EXISTS {schema}.{table}")
    cursor.execute(f"CREATE TABLE {schema}.{table}(hist_id BIGINT IDENTITY NOT NULL, business_key varchar(10), PRIMARY key(hist_id));")

df = pd.DataFrame(
    {
        "business_key": ["A", "B", "C"],
    }
)

wr.redshift.to_sql(
    df=df,
    table=table,
    schema=schema,
    con=con,
    use_column_names=True
)

print(
    wr.redshift.read_sql_table(
        table=table,
        schema=schema,
        con=con,
    )
)

con.close()
```

which returns:
```
   hist_id business_key
0        1            A
1        2            B
2        3            C
```

where `hist_id` was auto-incremented.

**Comment by jeyalee** [comment]
@jaidisido It doesn't seem to be working for me. Here is the error.
`{'S': 'ERROR', 'C': 'XX000', 'M': 'Cannot insert a NULL value into column transcription_id', 'D': '\n  -----------------------------------------------\n  error:  Cannot insert a NULL value into column transcription_id\n  code:      8007\n  context:   query execution\n  query:     509945\n  location:  column:1\n  process:   query1_99_509945 [pid=24814]\n  -----------------------------------------------\n', 'F': '/home/ec2-user/padb/src/sys/xen_execute.cpp', 'L': '10051', 'R': 'pg_throw'}`

Here is my table.
```sql
create table transcription
(
    transcription_id      bigint    default "identity"(1325615, 0, '1,1'::text)                  not null
        primary key,
    meta                  varchar(65535)                                                         not null,
    info                  varchar(65535)                                                         not null,
    create_timestamp      timestamp default ('now'::character varying)::timestamp with time zone not null encode az64
)
    sortkey (transcription_id);
```

**Comment by jeyalee** [comment]
Hi @jaidisido. I was able to get it to work with `redshift.to_sql` but not `redshift.copy`. Is that expected?

**Comment by achillesheel02** [comment]
I can confirm that I get an error when trying to load into table with identity column.
