### ISSUE TITLE
Support easier StreamingBody handling for non-tidy objects

### ISSUE THREAD

**Issue by brainstorm** [awslabs/aws-data-wrangler#1111]
When working with AWS wrangler, I find it really convenient to just `wr.s3.read_json()` and have a tidy dataframe to work with in pandas (and AWS) right away.

Unfortunately, there are times where the initial data is not as straightforward to import directly into a dataframe, i.e:

```
wr.s3.read_json("s3://bucket/problematic.json.gz")
(...)
ValueError: All arrays must be of the same length
```

On a local filesystem I'd just go with the following prefix lines and carry on with data cleaning and tidying it afterwards:

```
with gzip.open("problematic.json.gz", 'r') as fin:
    d = json.load(fin)

tidyer_df = pd.json_normalize(d)
```

But with `boto3`, it seems to get a bit more complicated, isn't it?: https://alexwlchan.net/2019/02/working-with-large-s3-objects/

What would be a more elegant fix for this other than rolling my own workarounds for `StreamingBody`?

**Comment by kukushking** [comment]
@brainstorm perhaps in some cases you'd be able to get around it using server-side filtering with S3 SELECT [(tutorial)](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/029%20-%20S3%20Select.html), although that of course depends on how badly your JSON is broken... Taking `ValueError: All arrays must be of the same length` as an example you could retrieve each column (or all columns of the same length) separately and join them after
