### ISSUE TITLE
to_parquet changing data during unloading bigint (with nulls)

### ISSUE THREAD

**Issue by noviksv** [awslabs/aws-data-wrangler#1115]
**Describe the bug**

Silent data changes occurs when casting data with nulls to bigint. It looks like intermediate converting to occurs, then casting to bigint. 

**Environment**

awswrangler        2.13.0

**To Reproduce**

Steps to reproduce the behavior.

```
import awswrangler as wr
import pandas as pd

path = "s3://{bucket}/history/"
 
df = pd.DataFrame({
...     "id": [1, 2],
...     "value": ["foo", "boo"],
...     "big_values": ["","1378260489959724228"]
... })
wr.s3.to_parquet(
...     df=df,
...     path=path,
...     dataset=True,
...     mode="overwrite",
...     dtype={'big_values':'bigint
... )
```
result from s3 select
```
{
  "id": 1,
  "value": "foo"
}
{
  "id": 2,
  "value": "boo",
  "big_values": 1378260489959724288
}
```
number changed from 137826048.....**28** --> 137826048......**88**

Looks like pandas issue (NaN is float in pandas) https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html 
But may be it possible to do it another way or add warning message.

**Comment by kukushking** [comment]
Hi @noviksv, in your original data frame`big_values` is an `object` type column. Wrangler fails to  easily convert that to Athenas `bigint` because it's confused by the empty string. You'll have to cleanse your original data frame and make sure the source column is of a type that can be converted expected `bigint` type, such as `int64` (or perhaps a nullable type like`float64`), otherwise wrangler can't do much unfortunately

**Comment by noviksv** [comment]
Hi @kukushking, thanks for your answer.
In my opinion, every potential data loss have to be **emphasized** (warnings, etc). 
Especially convertation string->bigint it is not a precision-lost operation. 
This moment should be described in documentation if it is normal behaviour

**Comment by kukushking** [comment]
@noviksv From the example you provided:
```
wr.s3.to_parquet(
     df=df,
     path=path,
     dataset=True,
     mode="overwrite",
     dtype={'big_values':'bigint'},  # conversion here
)
```
Wrangler is explicitly instructed to perform the conversion to `bigint` by `dtype` argument

**Comment by noviksv** [comment]
@kukushking exactly, but awswrangler firstly implicitly convert to float, secondly to bigint, as a result values have changed.
If I have dataset with no empty values wrangler do a direct conversion and values will not change.

**Comment by noviksv** [comment]
@kukushking fyi how similar warning realized in mlflow library
> WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: 
.../python3.9/site-packages/mlflow/models/signature.py:129: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>_ for more details.
