### ISSUE TITLE
wr.athena.read_sql_query  error:Unsupported Athena type: map

### ISSUE THREAD

**Issue by nivcoh** [awslabs/aws-data-wrangler#1118]
**Describe the bug**

We have an Athena table having a complex type (map type) such as: 
{Temp=314, AbsHumidity=6, Humidity=26, SHumidity=61, SAbsHumidity=9}

When I query this field using wr.athena.read_sql_query :
`select id, resolvedfield from db.table;`
I get the following error: 
**_Unsupported Athena type: map_**
instead of the expected return as: "{Temp=314, AbsHumidity=6, Humidity=26, SHumidity=61, SAbsHumidity=9}"

but when I query as follow:
`select id, resolvedfield['Humidity'] as Humidity from db.table;`
it works well and returns the Humidity value of 26.

When I run the first query within the AWS Athena console or directly using boto3 it also works fine. 
seems like an issue only for the wrangler.

**Environment**

awswrangler==2.13.0
boto3==1.20.37
botocore==1.23.37

**Comment by kukushking** [comment]
Unfortunately I'm not able to reproduce this:
```
df = pd.DataFrame({"c0": [1, 2], "c1": [[(1, 2), (3, 4)], [(1, 10), (3, 30)]]})
    wr.s3.to_parquet(
        df=df,
        path=path,
        dataset=True,
        database=glue_database,
        table=glue_table,
        dtype={"c0": "double", "c1": "map<bigint, double>"},
    )

df_out = wr.athena.read_sql_query(sql=f"SELECT c1 FROM {glue_database}.{glue_table}", database=glue_database)

>    c1
> 0 [(1, 2.0), (3, 4.0)]
> 1  [(1, 10.0), (3, 30.0)]
```
Can you please share stack trace, or any other details that would help to reproduce?
