### ISSUE TITLE
AWS Data Wrangler Athena Query Failure

### ISSUE THREAD

**Issue by cojmcc** [awslabs/aws-data-wrangler#1127]
I couldn't find any existing issues which covered this scenario but if one does exist please pass along that info. 
I've also posed this [question ](https://repost.aws/questions/QURr8NUteXQoikIr6lf00CAA/aws-data-wrangler-athena-query-failure)in the re:post forum. Any guidance is appreciated.

I'm attempting to run an Athena query using AWS Data Wrangler which is failing with an error indicating a column cannot be resolved. However when I view the failing query in the Athena console and rerun it there, it succeeds. I have a feeling it has something to do with the formatting with table or column names but I've been unsuccessful finding a work around. When I attempt the same query using vanilla boto3, it also fails with the same error. Here is an example of the code which fails followed by the same successful query ran in the console. (with some names anonymized for security) Adding to the strangeness further, if I remove the joins, it will error indicating the first column in the select cannot be resolved but the same query runs successfully in the console.

### Python Code
```
import awswrangler as wr

query = """
SELECT 
    t1.description, 
    t1.model_number as model, 
    t1.p_id as p_id, 
    t1.created_at as createdAt, 
    t1.updated_at as updatedAt, 
    t3.description as platform, 
    t2.name as module
FROM 
    database_with_underscores.first_table t1 
LEFT JOIN
    database_with_underscores.other_table t2
ON
    t2.id = t1.module_id
LEFT JOIN
    database_with_underscores.lasttable t3
ON  
    t1.platform_id = t3.id
"""

df = wr.athena.read_sql_query(query, workgroup="primary", database="database_with_underscores")
```
### Python Result
`awswrangler.exceptions.QueryFailed: SYNTAX_ERROR: line 19:5: Column 't2.id' cannot be resolved`

### AWS Athena Console
```
SELECT 
    t1.description, 
    t1.model_number as model, 
    t1.p_id as p_id, 
    t1.created_at as createdAt, 
    t1.updated_at as updatedAt, 
    t3.description as platform, 
    t2.name as module
FROM 
    database_with_underscores.first_table t1 
LEFT JOIN
    database_with_underscores.other_table t2
ON
    t2.id = t1.module_id
LEFT JOIN
    database_with_underscores.lasttable t3
ON  
    t1.platform_id = t3.id
```
### Console Result
Successful

An execution diff which shows not even whitespace changes between the successful and failing queries.
![image](https://user-images.githubusercontent.com/198616/150019333-88495214-ca6f-4b18-b0f0-4bc54e12bcb1.png)

**Comment by jaidisido** [comment]
It will be pretty difficult to understand the underlying problem without being able to reproduce it or without a clearer error message. Based on the above, I would guess something about the formatting of the sql query string is causing the issue. Have you tried being more explicit in the quoting of columns ("t2.id") and strings ('') in the sql query?

**Comment by cojmcc** [comment]
I was able to find the root cause of the issue. It turns out the true cause of the error was a Lake Formation permission issue where my console user had the proper select/describe permissions but my CLI account did not. Upon granting those permissions, the error no longer appeared. We've also seen similar behavior when using the ODBC drivers and PowerBI connectors to Athena, all resolved by adjusting permissions.
The error message indicating the column could not be resolved was not accurate. Further, this error did not generate an authorization error in our CloudTrail logs, making the issue more difficult to track down.

**Comment by jaidisido** [comment]
I see that is a weird one and I agree that the error message is not helpful in this case. Unless it's exposed to us in boto3 I am not sure how we can surface it in Wrangler though. Glad you found the underlying issue though
