### ISSUE TITLE
read_sql_table allows passing timestamp_as_object=True to internal to_pandas call

### ISSUE THREAD

**Issue by dennyau** [awslabs/aws-data-wrangler#1130]
Please update `read_sql_table`
https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.postgresql.read_sql_table.html
to allow passing the `timestamp_as_object=True` parameter to the internal `to_pandas` call.

Since https://github.com/awslabs/aws-data-wrangler/issues/592 was addressed we can read timestamps of values beyond the range of nanoseconds.

However, after the data is inserted into a database column - a subsequent read of the same table via `read_sql_table` will encounter the same issue.  The query will complete, hold the data in memory, attempt to create the dataframe via `to_pandas` and fail.

**Comment by jaidisido** [comment]
Adding a `timestamp_as_object` argument to all `read_sql_table` database methods should do it. Will raise a PR
