### ISSUE TITLE
_sanitize_name removal of camel case

### ISSUE THREAD

**Issue by grembeck** [awslabs/aws-data-wrangler#1143]
Hello,

In December there was a [change](https://github.com/awslabs/aws-data-wrangler/commit/d0cbd9fe443b546cf0bce08543f774a4e7e63935#:~:text=def%20_sanitize_name(name%3A%20str)%20%2D%3E%20str%3A,lower()%20%20%23%20Replacing%20non%20alphanumeric%20characters%20by%20underscore) in the '_sanitize_name' function, removing the converting of CamelCase to snake_case with only lower case.
What was this decision based on? And why was this part of a minor version change? Shouldn't it consider to be a breaking change?

We had many processes where this caused schema discrepancies since we did not lock the minor version.

With regards,
Alon Grembeck

**Comment by jaidisido** [comment]
We indeed had to change the sanitizing regex after issues (https://github.com/awslabs/aws-data-wrangler/issues/579 / https://github.com/awslabs/aws-data-wrangler/issues/533) were raised pointing out that it did not match the way the Glue metadata catalog sanitizes its names, which was the point of the method in the first place. For instance, in Glue `MyTable` becomes `mytable` with no underscore. It is pointed out as a breaking [change](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.13.0) in the release logs, but appreciate that it would be a significant change if you are unaware. It was the lesser of two evils at that point I am afraid
