### ISSUE TITLE
Jceks support

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [awslabs/aws-data-wrangler#1148]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
Hi,

Is it possible to use data-wrangler with jceks? So we would get accessKey and secretKey from that repository?

**Comment by jaidisido** [comment]
I am not sure how Java key stores relate to aws-data-wrangler when the library is Python based. Likewise why would it be used to access access/secret keys?

**Comment by LuisMoralesAlonso** [comment]
It's the standard wa we deliver credentials to projects in spark when accesing S3. So, would be nice to have it in python as we move into pure python projects. 

We could use jceks or an equivalent one if it exists language-agnostic or in python.

**Comment by jaidisido** [comment]
I am not sure I understand what you are trying to achieve with Wrangler here? Could you please be more specific?
