### ISSUE TITLE
awswrangler s3 Failing with SSL Verification

### ISSUE THREAD

**Issue by rachakonda03** [awslabs/aws-data-wrangler#1157]
### Describe the bug

Hi .

I am trying to read parquet files from an S3 bucket , my download is failing because of SSL Verification. I do not se an option to pass  argument to  specify the cert path, Can you please Help!!!

Thanks
Srikanth

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
`
boto3.setup_default_session(aws_access_key_id='xxxxxxxx', aws_secret_access_key='xxxxxxxxxxx', aws_session_token='xxxxx')

dirs = wr.s3.list_directories('bucket')
for path in range(len(dirs)):
    dfs = wr.s3.read_parquet(path=dirs[path], dataset=True)
 

- [ ] 

- [ ] 

`

### Environment

```
Provide your `pip list` output, particularly the version of the AWS Data Wrangler library you used. Providing this information may significantly improve resolution times.
```

### OS

Win

### Python version

3.7

### AWS DataWrangler version

2.14.0

**Comment by malachi-constant** [comment]
Hi @rachakonda03, 

Are you able to interface with the bucket with the `boto3` library directly or are you having SSL verification issues there as well?

```
client = boto3.client('s3')
bucket = "yourbucketname"
response = client.list_objects(
    Bucket=bucket,
)
```

**Comment by rachakonda03** [comment]
Yes , followed one of other issues added monkey patch client to pass verify with awsrangler , it is working locally with boto3 and also awswrnagler with patched client but when running in aws lambda erroring out with SSL issuse even monkey patch client

```

@apply_configs
def patched_client(
        service_name: str, session: Optional[boto3.Session] = None,
        botocore_config: Optional[botocore.config.Config] = None
) -> boto3.client:
    """Create a valid boto3.client."""
    endpoint_url: Optional[str] = _get_endpoint_url(service_name=service_name)
    return ensure_session(session=session).client(
        service_name=service_name,
        endpoint_url=endpoint_url,
        use_ssl=True,
        verify=ca_cert,
        config=default_botocore_config() if botocore_config is None else botocore_config,
    )

def ctr_pull(event, context):
    try:
        wr._utils.client = patched_client
        dirs = wr.s3.list_directories(ctr_path)
        logger.info(dirs)
   
```

**Comment by rachakonda03** [comment]
> Hi @rachakonda03,
> 
> Are you able to interface with the bucket with the `boto3` library directly or are you having SSL verification issues there as well?
> 
> ```
> client = boto3.client('s3')
> bucket = "yourbucketname"
> response = client.list_objects(
>     Bucket=bucket,
> )
> ```
I am having , had to veirify with  cert path

**Comment by rachakonda03** [comment]
Nevermind it is something to do wiht my local setup. Appreciate your help for looking into it,

**Comment by daichigb** [comment]
@rachakonda03 Can you elaborate on what was the local setup issue?
I'm seeing a similar issue.
