### ISSUE TITLE
awswrangler.s3.to_json adds __index_level_0__ to table column in glue catalog

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#1168]
### Describe the bug

When using to.json to write json files s3 and create a glue table at the same time using "orient='records' and lines=True, there appears to be no way to not get __index_level_0__ to **not** appear as a column even with this data does not appear in the json files as seen below. These two parameters was the only way I was able to get aws athena to read my json files correctly in s3. 

![image](https://user-images.githubusercontent.com/33879968/153766007-ae84f3f0-1545-4943-acab-6abbe8aaf9b2.png)

    table_name = 'authorization_log'
    database_name = 'customer'
    column_names = ['order_id', 'amount', 'approver_name', 'timestamp', 'approve_date' ]

    written_datasets = wr.s3.to_json(df, path="s3://bucket_name/raw/auth_logs/", 
                                     sanitize_columns=True, columns=column_names,
                                     dataset=True, database=database_name, table=table_name,
                                     description='manual approvals for customer orders', 
                                     partition_cols=['approve_date'],
                                     mode='overwrite', index=True, orient='records', lines=True)

### How to Reproduce

See steps in aws data wrangler to replicate the issue. You can't make "index"=False or that will throw an error for the orient=records

```
table_name = 'authorization_log'
database_name = 'customer'
column_names = ['order_id', 'amount', 'approver_name', 'timestamp', 'approve_date' ]
auth_log_dict = {"order_id": [1,2], "amount": [20,30], 
"approve_date": ['20210102', '20210103'], "approver_name": ['bob, 'mark'], 
"timestamp": ['20210120 030303, 20210120 040404']}
df= pd.DataFrame(auth_log_dict)
df = {'order_id]
written_datasets = wr.s3.to_json(df, path="s3://bucket_name/raw/auth_logs/", 
                                 sanitize_columns=True, columns=column_names,
                                 dataset=True, database=database_name, table=table_name,
                                 description='manual approvals for customer orders', 
                                 partition_cols=['approve_date'],
                                 mode='overwrite', index=True, orient='records', lines=True)
```

### Expected behavior

__index_level_0__ to **not** appear in the glue catalog on write.

### Environment

```
Provide your `pip list` output, particularly the version of the AWS Data Wrangler library you used. Providing this information may significantly improve resolution times.
```

### OS

linux

### Python version

python 37

### AWS DataWrangler version

2.14

**Comment by AdrianoNicolucci** [comment]
Yea I tried this as well and came to the same conclusion. so I guess the answer is if we are writing JSON with the orient being recorded, it might not be possible? I found that orient=records was the only way to get Amazon Athena to be able to query the data as a JSON.

**Comment by jaidisido** [comment]
Sorry for the late reply, yes I don't see a solution here besides living with it. Wrangler is doing what is being told to do when `index=True` is specified, that is to add the index to the Glue catalog table. At the same time Pandas rejects `index=False` when `orient` is `records`.

Closing for now but feel free to reopen if you can think of a solution
