### ISSUE TITLE
modify varchar length of a field of a Pandas data frame when calling awswrangler.redshift.to_sql()

### ISSUE THREAD

**Issue by eychih** [awslabs/aws-data-wrangler#1173]
Hi,

I try to load (in overwrite mode) a Pandas DataFrame to Redshift using awswrangler.redshift.to_sql().  An instance of the DataFrame has a text field, Memo,  of which the length is 264 characters.  I try to pass in the parameter varchar_lengths to awswrangler.redshift.to_sql() to set the datatype of the corresponding column of the redshift table to varchar(65535).  But it turns out the datatype of the column is still varchar(256).  As a result, the loading fails.  

I appreciate if your can let me know how to change the datatype of the column to varchar(65535).     

Best regards,

Ey-Chih Chow

**Comment by eychih** [comment]
The error message of the above loading is:

[ERROR] ProgrammingError: {'S': 'ERROR', 'C': '22001', 'M': 'value too long for type character varying(256)', 'F': '/home/ec2-user/padb/src/pg/src/backend/utils/adt/varchar.c', 'L': '511', 'R': 'varchar'}
Traceback (most recent call last):
  File "/var/task/kraken-lambda-st****-******-*****.py", line 203, in lambda_handler
    wr.redshift.to_sql(df=sub_df, con=con, table=table_name, schema="call_center_stage", mode="overwrite",
  File "/opt/python/awswrangler/_config.py", line 417, in wrapper
    return function(**args)
  File "/opt/python/awswrangler/redshift.py", line 839, in to_sql
    cursor.executemany(sql, (parameters,))
  File "/opt/python/redshift_connector/cursor.py", line 236, in executemany
    self.execute(operation, parameters)
  File "/opt/python/redshift_connector/cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "/opt/python/redshift_connector/core.py", line 1273, in execute
    self.handle_messages(cursor)
  File "/opt/python/redshift_connector/core.py", line 1356, in handle_messages
    raise self.error

**Comment by eychih** [comment]
The varchar_lengths I passed in to the API is { "MEMO":65535 }.

**Comment by jaidisido** [comment]
Hi @eychih - I am trying to reproduce this but am unable at the moment. Can you please share a short script to reproduce please?

With the below:
```
import awswrangler as wr
import pandas as pd

df = pd.DataFrame({
    "id": [1, 2],
    "MEMO": ["foo", "boo"]
})

con_redshift = wr.redshift.connect("aws-data-wrangler-redshift")
wr.redshift.to_sql(df, con_redshift, schema="public", table="memo", mode="overwrite", varchar_lengths={"MEMO": 65535})
```

the varchar length is correctly set to 65535:
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/16362107/157508452-ca1bdc7a-6d84-419e-a92b-600f1dc2b16e.png">
