### ISSUE TITLE
is it possible to update documents in an index in OpenSearch with AWS Data Wrangler?

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#1174]
OpenSearch supports updating documents in an index. Is it possible to update documents in an OpenSearch Index using AWS Data Wrangler? It would be great if I could pass a dataframe to the index_df method with the keys that I want to use to make my update. It's hard to tell from the documentation if there is some "kwargs" argument that would indicate that I am trying to do an update.

**Comment by AssafMentzer** [comment]
Hi @AdrianoNicolucci, 
yes you can pass `id_keys` (List[str]) arg to index_df, and to any of the index_* methods, if you want to update your OpenSearch index.
Please see this [tutorial](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/031%20-%20OpenSearch.html#Index-dataframe) for example.

The documentation of [awswrangler.opensearch.index_df](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.opensearch.index_df.html#awswrangler.opensearch.index_df) specifies that you can pass **kwargs – KEYWORD arguments forwarded to [index_documents()](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.opensearch.index_documents.html#awswrangler.opensearch.index_documents) which is used to execute the operation.

Please let us know if this helps.
Thanks

**Comment by AdrianoNicolucci** [comment]
Thank you @AssafMentzer! This is exactly what I was looking for.
