### ISSUE TITLE
How can I execute the saved queries on Athena with Python?

### ISSUE THREAD

**Issue by diegopmayer** [awslabs/aws-data-wrangler#1177]
## Objective
* Execute or extract data with `saved queries` on Athena.

## Context
* I created a query with AWS Athena and saved that query "saved_query_name", and in Python awaqrangler I want call that query saved, such as wr.read_sql_query(sql="Select col1 from table", database=gold), but using the name such as wr.read_sql_query('saved_query_name") or some like that.

## Tries
* Tried execute a wr.athena.get_query_execution('saved_query_name') -> didn't run, cause it needed of id

I couldn't find the solution on documentation.

**Comment by jaidisido** [comment]
Oh yeah, what I am saying is that we will work to add this in Wrangler
