### ISSUE TITLE
Run analyze on copy command

### ISSUE THREAD

**Issue by rodolfo-picoreti** [awslabs/aws-data-wrangler#1180]
Hi,

Is it possible to do a copy statupdate using this library?  https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-load.html#copy-statupdate

I found the SQL for the copy command but there is no apparent way to customize it to do the statupdate:

https://github.com/awslabs/aws-data-wrangler/blob/111ff27fbc155efc44b54c9b044b41c17e96646b/awswrangler/redshift.py#L147

**Comment by kukushking** [comment]
Thanks, there is no way to pass copy params at the moment but this is definitely possible.
