### ISSUE TITLE
A new generated diff is ready to view: https://github.com/awslabs/aws-sdk-kotlin/compare/__generated-main...__generated-feat-cred-providers

### ISSUE THREAD

**Issue by Sleekbobby1011** [awslabs/aws-data-wrangler#1181]
A new generated diff is ready to view: https://github.com/awslabs/aws-sdk-kotlin/compare/__generated-main...__generated-feat-cred-providers

_Originally posted by @github-actions[bot] in https://github.com/awslabs/aws-sdk-kotlin/issues/469#issuecomment-995231360_

**Comment by jaidisido** [comment]
Invalid bot created issue.
