### ISSUE TITLE
Redshift copy operation does not support map type

### ISSUE THREAD

**Issue by svdimchenko** [awslabs/aws-data-wrangler#1185]
### Describe the bug

when I'm trying to load parquet files from S3 to Redshift, I'm getting following error:
```
awswrangler.exceptions.UnsupportedType: Unsupported Redshift type: map<string, string>
```
One of my fields has map type and can be saved as `super` type.

### How to Reproduce

Create athena table with field of type `map<string, string>` and try to load it into Redshift table with following script.

```
import logging

import awswrangler as wr
from redshift_connector import Connection


logging.basicConfig(level=logging.INFO, format="[%(name)s][%(funcName)s] %(message)s")
logging.getLogger("awswrangler").setLevel(logging.DEBUG)
logging.getLogger("botocore.credentials").setLevel(logging.CRITICAL)

con = Connection(
    user='---',
    password='---',
    host='---',
    port=---,
    database='---'
)

entity = "---"

wr.redshift.copy_from_files(
    path=f's3://prod-dwh-transformed/inc/{entity}',
    con=con,
    table=entity,
    schema="---",
    iam_role='---',
    serialize_to_json=True,
    parquet_infer_sampling=0.1
)

con.close()
```

### Expected behavior

data is loaded

### OS

Mac

### Python version

3.10.0

### AWS DataWrangler version

2.14.0

**Comment by jaidisido** [comment]
PR #1186 with the fix merged, thank you for your contribution.
