### ISSUE TITLE
'Index' object has no attribute 'head'

### ISSUE THREAD

**Issue by matteosantama** [awslabs/aws-data-wrangler#1188]
### Describe the bug

`wr.s3.to_parquet` fails when writing a `DataFrame` with an `ExtensionDType` index with the error 

```
AttributeError: 'Index' object has no attribute 'head'
```

Specifically, the failure happens when using `pandas==1.4.1` but NOT with `pandas==1.3.0`. This behavior is consistent on both `pyarrow==5.0.0` and `pyarrow==7.0.0`.

### How to Reproduce

```python
import pandas as pd
import awswrangler as wr


df = pd.DataFrame(
    {"col1": [1, 2, 3], "col2": [1, 2, 3]}, dtype=pd.Int64Dtype()
).set_index("col1")

wr.s3.to_parquet(
    df,
    path="s3://bucket/tmp.parquet",
    index=True,
    dataset=False,
)
# throws error
```

### OS

Mac

### Python version

3.8

### AWS DataWrangler version

2.12.1

**Comment by kukushking** [comment]
Hi @matteosantama I recommend upgrading the wrangler to 2.14 - the issue doesn't reproduce there. 2.12 wasn't ready for newer pandas I think.
