### ISSUE TITLE
wr.opensearch.search_by_sql() is missing records

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#1192]
### Describe the bug

I have written records to an index using `wr.opensearch.index_df()`. However, when I attempt to read them back using `wr.opensearch.search_by_sql()`, the records do not appear in the query, however records previously written using "POST" in the open search console are successfully returned. 

It appears that the only way to retrieve these records successfully with aws data wrangler is using the  `opensearch.search()` api and only when `is_scroll = True`

```
        df = wr.opensearch.search(
            client = client,
            index = es_index,
            is_scroll = True,
            search_body = {
                "query": {
                    "match": {
                        "column1": "A"
                    }
                }
            }
        )
```

Am I missing something here on why `wr.opensearch.index_df()` is missing records on when it queries the index? 

### How to Reproduce

1. insert records through the open search dev tool
2. insert records into the same index using `wr.opensearch.index_df()`

```
df = pd.DataFrame({"column1": ["A", "A","A"],
                      "column2": ["20220121", "20220107", "20210125"])
```
3. attempt to read back the records using:

```
    sql_query = f'select * from test_index WHERE column1 = "A"'
    df = wr.opensearch.search_by_sql(
            client=os_client,
            sql_query=sql_query)
    return df`
```

### Expected behavior

When querying an index using `wr.opensearch.search_by_sql()` all the records are returned based on your sql query

### OS

Win

### Python version

Python 3.6

### AWS DataWrangler version

2.14.0

**Comment by kukushking** [comment]
Hi, I am unable to reproduce. Can you try running the below, please?

```
import awswrangler as wr
import pandas as pd

df = pd.DataFrame({"column1": ["A", "A","A"], "column2": ["20220121", "20220107", "20210125"]})

# Connect
opensearch_host = ...
client = wr.opensearch.connect(host=opensearch_host)

# Create index
wr.opensearch.create_index(client, "index1192")

# Index dataframe
wr.opensearch.index_df(client, df, index="index1192")

# Search
wr.opensearch.search_by_sql(client, 'select * from index1192 WHERE column1 = "A"')
Out[10]: 
      _index _type  ... column1   column2
0  index1192  _doc  ...       A  20210125
1  index1192  _doc  ...       A  20220121
2  index1192  _doc  ...       A  20220107
```

**Comment by AdrianoNicolucci** [comment]
@kukushking thanks for looking into this issue, I found that the issue is nothing to do with these functions and was related to bad testing data. I'm closing this ticket.
