### ISSUE TITLE
s3.read_parquet() handling NA value differently from Pandas

### ISSUE THREAD

**Issue by aeryen** [awslabs/aws-data-wrangler#1197]
### Describe the bug

When reading a parquet file containing Null values, awswrangler convert these values into pd.NA instead of None, which is the Pandas behavior.

### How to Reproduce

Find a parquet file that contains null values and compare the loaded DataFrame using the following functions:
* wr.s3.read_parquet()
* pd.read_parquet()

For my case, the column with all string data was inferred to "string[python]" as **dtype** , with null values represented using pd.NA when using awswrangler. When the DF is loaded using pandas, the same column was inferred to "dtype('O')", with null values represented using None.

While i actually prefers the awswrangler behavior in this case, I wonder if this is intended as when migrating from using Pandas to WR this might be a unexpected surprise for some developers.

### OS

Amazon Linux 2012

### Python version

Python 3.9.5

### AWS DataWrangler version

2.14.0

**Comment by jaidisido** [comment]
From the [docs](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet.html#awswrangler.s3.read_parquet), `wr.s3.read_parquet` has a `map_types` parameter set to `True` by default. It converts pyarrow DataTypes to pandas ExtensionDtypes.

By default, pyarrow uses NA. Setting the parameter to False returns None
```
import pandas as pd
import awswrangler as wr

path = "s3://<my-bucket>/1197.parquet"

df = pd.DataFrame({
    "c0": [2, 1, 1, 2],
    "c1": ["test", None, None, None],
})

wr.s3.to_parquet(df=df, path=path)

df = wr.s3.read_parquet(path=path, map_types=False)
df
   c0    c1
0   2  test
1   1  None
2   1  None
3   2  None

df = wr.s3.read_parquet(path=path, map_types=True)
df
   c0    c1
0   2  test
1   1  <NA>
2   1  <NA>
3   2  <NA>
```

**Comment by liquidcarbon** [comment]
Can an argument like this be added to `athena.read_sql_query`?  It has the same issue.

**Comment by koberghe** [comment]
> Can an argument like this be added to `athena.read_sql_query`? It has the same issue.

Also addressed here:
https://github.com/awslabs/aws-data-wrangler/issues/1265
