### ISSUE TITLE
User specified s3_output not handled correctly in athena.read_sql_query with unload_approach=True

### ISSUE THREAD

**Issue by kopachev** [awslabs/aws-data-wrangler#1200]
### Describe the bug

When using `unload_approach=True` and passing custom `s3_output` path this path is ignored in `awswrangler.athena._utils._get_s3_output()` if `wg_config.enforced` is `True`. That flag is set based on workgroup "EnforceWorkGroupConfiguration" value which maps to "Override client side settings" from the Workgroups console UI. The "primary" workgropu has this set to `False` but custom workgroups ones may have it set to `True`.
In this case the code tries to use the workgroup output location which is likely to have existing files (results of previous regular queries) and attempt to use `UNLOAD` fails with:
`awswrangler.exceptions.QueryFailed: HIVE_PATH_ALREADY_EXISTS: Target directory already exists`

### How to Reproduce

Try to query Athena with Unload approach and passing custom workgroup and S3 path:

```
wr.athena.read_sql_query(
        sql=query,
        workgroup="<custom workgroup>",  # Make sure "Override client side settings" is "Enabled" for this groups
        ctas_approach=False,
        unload_approach=True,
        s3_output="<custom empty S3 path>",
        boto3_session=session
```

Call fails with:
`awswrangler.exceptions.QueryFailed: HIVE_PATH_ALREADY_EXISTS: Target directory already exists`

### Expected behavior

In general when using UNLOAD the user must take care to provide "empty" S3 path, process the result (Parquet) files, and eventually clean-up the result objects when no longer needed. Hence it makes sense for `s3_output` supplied when calling `read_sql_query` to be always honored regardless of `wg_config.enforced` value. I think workgroup "Query result location" should only be used as fallback in case optional `s3_output` is omitted.

### OS

Win

### Python version

3.8.10

### AWS DataWrangler version

Latest code from "main" (repro depend on fix for #1178)

**Comment by jaidisido** [comment]
Thank you for raising this @kopachev, it's well explained and detailed.

While I agree with the ask, I am slightly concerned about the security aspect of using UNLOAD. The whole idea behind enforcing `Query Result Location` in a workgroup is to ensure users cannot output results outside the S3 path specified in the workgroup configuration. However, it seems that UNLOAD allows you to output results anywhere you want, even outside the workgroup location.

The security aspect is outside the scope of the library. If Athena allows this behaviour, then Wrangler should too. So I will work on PR fix based on your comments.

**Comment by kopachev** [comment]
Thanks!
I agree the security aspect is a bit murky. You cannot really enforce it in the lib as people would monkey-patch it (as I did for now).
And allowing people to write UNLOAD result in any location can be dangerous. Even if it requires the path to be empty, someone may (un)intentionally dump incompatible Parquet files into location registered as Glue table and break the queries against that table.
