### ISSUE TITLE
Make redshift.connect a context manager

### ISSUE THREAD

**Issue by WillAyd** [awslabs/aws-data-wrangler#1205]
With the current code base, users have to manually close a connection, often within a try...finally block. If redshift.connect were converted to a context manager we would much more easily be able to do something like:

```python
with wr.redshift.connect(...) as conn:
   ...
```

And have the manager automatically clean up for us. 

Both sqlalchemy and pyodbc have this, so should be familiar to many downstream users

**Comment by jaidisido** [comment]
Great idea, I am transferring the issue to the redshift connector team.
