### ISSUE TITLE
Add aws-wrangler to Conda

### ISSUE THREAD

**Issue by vfrank66** [awslabs/aws-data-wrangler#121]
It would be nice to see this package available via conda so that it can be utilized with conda.

**Comment by impredicative** [comment]
Isn't it already there as `awswrangler`? Yes, it is: https://anaconda.org/conda-forge/awswrangler

**Comment by igorborgest** [comment]
Hi @vfrank66!

As @impredicative already told. Our official conda package is under: https://anaconda.org/conda-forge/awswrangler

**Comment by impredicative** [comment]
Is this supported for Mac? I can't seem to install it on Mac via conda. For some reason conda installed v0.3.1 which is an old version.

**Comment by maxispeicher** [comment]
[This](https://github.com/awslabs/aws-data-wrangler/issues/628#issuecomment-812367692) should install the latest version:
> A install from conda-forge in the default environment installs a very old version of awswrangler. So probably installing in a newly created environment should fix the issue. You can have a look at #577 for some more information.
