### ISSUE TITLE
Repeated calls to read_parquet/to_parquet accumulating memory

### ISSUE THREAD

**Issue by jakemiller649** [awslabs/aws-data-wrangler#1213]
### Describe the bug

I have a program that reads parquet files from one directory (partitioned by a column called `label` and a month column) does a few trivial computations, then writes them to another directory, partitioning again by label but this time by date instead of month. I am using `s3.read_parquet`'s `chunked=True` argument because the source directory is much too large to be read into memory.

It seems like _something_ is being kept in memory after each iteration. If I do enough files -- this might happen because a certain label has a lot of data, or a do a longer time period -- the process will get killed. I've thrown in some pympler/psutil statements, and even though the size of the chunks goes up and down, the total memory being used keeps going up.

### How to Reproduce

```python
import logging
from operator import eq, ge, le
import fire

import awswrangler as wr
import pandas as pd
import psutil

from pympler import asizeof


logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s|%(asctime)s|%(message)s"
)

# SOURCE_FOLDER = [REDACTED]
# DEST_FOLDER = [REDACTED]
# SOURCE_LABEL = [REDACTED]
# TIMESTAMP_COL = [REDACTED]

def make_partition_filter(filters):
    def partition_filter(obs):
        truth_vals = [func(obs[column], value) for column, value, func in filters]
        return all(truth_vals)
    return partition_filter


def main(label: str, min_date: str, max_date: str):
    # date format YYYY-MM-DD
    partition_filter = make_partition_filter([
        (SOURCE_LABEL, label, eq),
        ("month", min_date[:7], ge),
        ("month", max_date[:7], le)
    ])

    df_list = wr.s3.read_parquet(
        SOURCE_FOLDER,
        dataset=True,
        chunked=True,
        partition_filter=partition_filter,
        use_threads=False
    )
    for df in df_list:
        df = process(df)
        upload(df)

        mem = psutil.virtual_memory()
        size_of_df = asizeof.asizeof(df)
        msg = "|".join([
            str(amt) for amt in [mem.percent, mem.used, size_of_df]
        ])
        logging.info(msg)


def process(df):
    df[TIMESTAMP_COL] = pd.to_datetime(df[TIMESTAMP_COL])
    df["date"] = [
        dat.strftime("%Y-%m-%d")
        for dat in df["published_at"]
    ]
    return df


def upload(df):
    wr.s3.to_parquet(
        df=df,
        path=DEST_FOLDER,
        index=False,
        use_threads=False,
        dataset=True,
        partition_cols=[SOURCE_LABEL, "date"],
        mode="append"
    )


if __name__ == "__main__":
    fire.Fire(main)
```

### Expected behavior

I'm expecting memory usage to fluctuate based on how big the chunk is. I'm reading it in chunks so I don't get Killed, but if I do enough chunks, I get Killed.

### Screenshots

Green is the output from pympler's `asizeof` for each df chunk. Blue is memory percentage as told to me by psutil; orange is what psutil says my `used` memory is. Df size has been scaled by 10e6, and used memory by 10e8, so they all fit on the same plot. Green goes up and down; blue and orange keep going up.
 
![image](https://user-images.githubusercontent.com/26314969/157754728-8805e1dd-7787-4efe-a6ba-b442c4a2bb5e.png)

### OS

Ubuntu 20.04.3 LTS

### Python version

3.9.5

### AWS DataWrangler version

2.12.1

**Comment by kukushking** [comment]
I haven't been able to reproduce this so far with my synthetic test -- the memory does grow but at some point gc kicks in and cleans it up back to reasonable values. Could you try running this on the latest wrangler 2.15.0?

**Comment by 123385918** [comment]
I meet the same issue . i'm using clear python10 env:
`conda create -n py10 python=3.10 awswrangler`
and I get awswrangler's version :3.4.0
then i run the python code:
`import awswrangler as wr
source=wr.s3.read_parquet('s3://bucket/to/path/',chunked=True)
a=next(source)`
then the cpu percent in `htop` comes to 100% for a while and get killed later.
