### ISSUE TITLE
Write multi-measure records to Timestream

### ISSUE THREAD

**Issue by mateogianolio** [awslabs/aws-data-wrangler#1214]
**Is your idea related to a problem? Please describe.**

Can't write multi-measure records?

**Describe the solution you'd like**

Multi-measure records were added in boto3 1.20.13 (see https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#12013).

Few suggestions on how to solve this:

* replace `measure_col` with `measure_cols` (breaks backwards compatibility, so probably no go)
* letting `measure_col` optionally take `list` (a bit weird)
* adding a `measure_cols` parameter to `timestream.write()` which overrides `measure_col`
* adding a new method `timestream.write_multi()`

**Comment by jaidisido** [comment]
Thanks for flagging this @mateogianolio, it seems that the [API](https://docs.aws.amazon.com/timestream/latest/developerguide/API_WriteRecords.html) call lists both `MeasureValue` and `MeasureValues` so I would be in favour of accepting both

**Comment by RohanKarthikeyan** [comment]
I just tried it out in a Jupyter notebook; and it failed on the _test_multimeasure_scenario_ function.
