### ISSUE TITLE
metadata_to_glue: incomplete docstring

### ISSUE THREAD

**Issue by JPFrancoia** [awslabs/aws-data-wrangler#122]
Hi,

Looking at the docs for `metadata_to_glue` for the `awswrangler.glue` here:
https://aws-data-wrangler.readthedocs.io/en/latest/api/awswrangler.glue.html

I noticed that the parameter `path: str` is misplaced in the docstring (it should be second in the docstring). But that's not super important.

What does `metadata_to_glue` actually do? There is no docstring explaining its purpose in the doc. I would like to use it to catalog the schema of a dataframe. Is it intended for this use?

Cheers

**Comment by igorborgest** [comment]
Improved on #124. It will be released in the next version on the weekend!
