### ISSUE TITLE
Does it support pandas >= 1.4.0?

### ISSUE THREAD

**Issue by datlife** [awslabs/aws-data-wrangler#1223]
Current `awswrangler` doesn't support pandas >= 1.4.0. Is there a reason for it? I couldn't find the issues related to it.

**Comment by kukushking** [comment]
Hi @datlife yes, pandas 1.4.0 have some changes regarding indexes that have broken wrangler so we limited the version until there is permanent fix.

**Comment by kukushking** [comment]
@datlife just a quick heads up - we're unpinning pandas version so you should be able to use pandas 1.4.1+ in the next 2.14.0 release which is coming this week.

**Comment by datlife** [comment]
wonderful!!! Thank you very much :D <3
