### ISSUE TITLE
Support for ORC file

### ISSUE THREAD

**Issue by Ritika-Singhal** [awslabs/aws-data-wrangler#1225]
Hello,

Is there a plan to implement the ORC file format support in the aws-wrangler?

https://github.com/awslabs/aws-data-wrangler/blob/4b9f27023057c359860669e44607c0825e08bf7b/building/lambda/build-lambda-layer.sh#L56

Thanks!

**Comment by jaidisido** [comment]
Please see this issue https://github.com/awslabs/aws-data-wrangler/issues/615
