### ISSUE TITLE
Adding an option to easily associate metadata (i.e. s3_path, last_modified, content_type, bytes, etc.) with S3 data reads

### ISSUE THREAD

**Issue by walter9388** [awslabs/aws-data-wrangler#1234]
**Is your feature request related to a problem? Please describe.**
In my data workflow I read in a lot of separate files from s3 and awswrangler works great :) However, after much piping and manipulation, it can be often difficult to trace the root of the issues on the frontend without knowing the origin. For that reason, I tend to add the metadata to side of the dataframe (i.e. s3_path, last_modified, content_type, bytes, etc.) to help trace issues in the development stage.

To achieve this, I generally use `awrwrangler.s3.describe_objects` with read functions in this sort of approach:
```python
import pandas as pd
import awswrangler as wr
from awswrangler.s3._read import _union


def _add_metadata_to_df(df, path):
    """
    function which takes metadata from
    wr.s3.describe_objects(path=path)
    and returns it as columns on the right
    hand side of df
    """
    return df


def main(paths):
    df = _union(
        [_add_metadata_to_df(wr.s3.read_csv(path=path), path) for path in paths],
        ignore_index=True,
    )


if __name__ == "__main__":
    paths = ["s3//bucket/path1.csv", "s3//bucket/path1.csv"]
    main(paths)
```

Clearly, this is a pretty dumb approach for several reasons:
1. There is no longer the use of a multithreaded workflow when reading in a long list of files (i.e. `_read_dfs_from_multiple_paths()` in [s3._read](https://github.com/awslabs/aws-data-wrangler/blob/c685abb74f2fe05c3d70fb23160cee932455ceb4/awswrangler/s3/_read.py)).
2. It is not very scalable for additional kwargs.
3. It is not repeatable for the other s3 read functions (json, parquet, etc.).
4. It is super janky.
 _probably many other reasons too_

**Describe the solution you'd like**
An additional optional kwarg for adding metadata to dataframes in read functions. This could be either of type boolean or list; where 

- **False(default)** does nothing different,
- **True** appends all possible metadata, 
- **List[strs]** appends metadata with keys that are in list, including the option of the s3 path (see [s3.describe_objects](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.describe_objects.html#awswrangler.s3.describe_objects) or [s3.Client.head_object](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.head_object) for metadata options).

For example, for reading in csv files, this would look something like this:
```python
def read_csv(
    ...
    append_metadata: Optional[Union[bool, List[str]]] = False,
    ...
) -> Union[pd.DataFrame, Iterator[pd.DataFrame]]:
```
which would then lead to something in the different deeper read functions that append the necessary metadata to the right of the dataframe depending on the value of `append_metadata`. For example:

```python
# if "False" ignore
if append_metadata:
    # if "True" get all possible metadata
    if isinstance(append_metadata, bool):            
        append_metadata=__all_metadata_tags__()
    # if "List[str]" check input is valid
    elif not all(item in __all_metadata_tags__() for item in append_metadata):             
        raise ValueError("metadata tag/s in 'append_metadata' are not possible, see ... for possible inputs")

    # append metadata to side of the read in dataframe
    df[append_metadata] = pd.DataFrame([_get_metadata(append_metadata, kwargs)], index=df.index)
```
where
```python
def __all_metadata_tags__()  -> List[str]: 
    return ["last_modified", ..., "content_type"] # hard code possible list options from boto3

def _get_metadata(append_metadata: List[str], **kwargs: Any)  -> List[str]:
    """
    get metadata using the existing underlying
    functions for wr.s3.describe_objects()
    """
```

**Describe alternatives you've considered**
One issue of appending metadata to the side of the dataframes in this way is the large amount of unnecessary memory that may be taken up if a very large number of files are read in. I still think this is ok in practice as this should be a feature to aid development, and should be not used in production. However, an alternative more scalable approach may be to add a column of keys to the main dataframe which then correspond to a separate dataframe containing all the distinct metadata. This may be a better idea for scalability, but would not be easy to add to the current structure of the code as the output types of the read functions would change to `List[pd.DataFrame]` or `Dict[str,pd.DataFrame]`. 

There may be better ways of implementing this that I haven't thought of, like somehow parsing the necessary existing read function into some sort of "get_metadata" function which returns the additional "metadata dataframe" separately with the normal dataframe... but I can't see anything as simple as the suggested approach off the top of my head.

**Final Thoughts**
This might be a pretty niche request, so I understand if you decide it isn't a good idea to consider right now. I definitely would use something like this a lot in my workflow, but my approach to this may not be for everyone. I'm looking forward to hearing your thoughts, and if you do think it's possible, the best way to implement it. I am also happy to create a PR if that is the case (although I don't claim to have contributed a huge amount to OSS, so I might need a bit of help with some of the finer details).

**Comment by kukushking** [comment]
To be honest this indeed looks like a very niche request to justify putting that into the library

**Comment by walter9388** [comment]
yeah that is fair, I'll make my own fork for my workflow :) Cheers
