### ISSUE TITLE
Glue job is failing with  - botocore 1.24.25 is installed but botocore<1.25.0,>=1.24.26 is required by {'boto3'}

### ISSUE THREAD

**Issue by rsingh-821** [awslabs/aws-data-wrangler#1235]
### Describe the bug

During installation of awswrangler when glue job starts. I'm getting error - "Command failed with exit code 1". When I looked into error log it says  - "botocore 1.24.25 is installed but botocore<1.25.0,>=1.24.26 is required by {'boto3'} ".

### How to Reproduce

Try Running glue job with 
Python lib path - awswrangler-1.7.0-py3.6.egg

### Screenshots

![image](https://user-images.githubusercontent.com/102376854/160161115-8970ec40-1a14-4b51-954d-59a3532e6695.png)

### OS

Linux86_64

### Python version

3.6

### AWS DataWrangler version

1.7.0

**Comment by jaidisido** [comment]
Hi @rsingh-821, version 1.7 of aws-data-wrangler is quite an old one. It had a dependency on an older version of botocore (1.24<) but underlying Glue image now requires a later version. So I would recommend using a newer of the library (version 2+)
