### ISSUE TITLE
Please Specify Missing Keys During 'Not Found' Error

### ISSUE THREAD

**Issue by knoam** [awslabs/aws-data-wrangler#1246]
### Describe the bug

Calling _read_csv_ on multiple keys, when certain keys don't exist on S3 gives a 404 error but does not specify which key was not found
```python
wr.s3.read_csv([f's3://{bucket}/{key}' for key in s3_keys])
```
Could this be added?

Here's the error: `ClientError: An error occurred (404) when calling the HeadObject operation: Not Found`

### How to Reproduce

```python
wr.s3.read_csv([f's3://{bucket}/{key}' for key in s3_keys])
```
Where one of the keys is not available on S3.

### Expected behavior

Ideally, the error message would specify which keys are missing.

### OS

Linux

### Python version

3.6.13

### AWS DataWrangler version

2.14.0

**Comment by kukushking** [comment]
By the 404 object not found it looks like it is _object_ key that is missing. Perhaps one of the items in s3_keys is empty?

**Comment by knoam** [comment]
@kukushking the problem arises when you provide a list argument to path. With a string argument, the error message specifies the file missing, but with a list argument, you get the 404 message.

**Comment by kukushking** [comment]
@knoam thanks, I've publish a PR that fixes that - you should now be able to catch all 404's by catching `wr.exceptions.NoFilesFound`
