### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable on calling awswrangler.s3.read_parquet

### ISSUE THREAD

**Issue by sak1sham** [awslabs/aws-data-wrangler#1247]
### Describe the bug

There seems to be some issue when I try reading some parquet file with NaT or None values in datetime columns.

### How to Reproduce

I tried reading a parquet file from my S3 bucket. 
```
from dotenv import load_dotenv
load_dotenv()
path = 's3://bucket-name/file.snappy.parquet'
df = wr.s3.read_parquet(path = path)
```

However, it gave the the following error:
```
File "/Users/sakshamgarg/Desktop/my-folder/temp.py", line 13, in <module>
    df = wr.s3.read_parquet(path = path)
  File "/Users/sakshamgarg/opt/anaconda3/envs/temp_env/lib/python3.10/site-packages/awswrangler/s3/_read_parquet.py", line 768, in read_parquet
    return _read_parquet(
  File "/Users/sakshamgarg/opt/anaconda3/envs/temp_env/lib/python3.10/site-packages/awswrangler/s3/_read_parquet.py", line 531, in _read_parquet
    return _arrowtable2df(
  File "/Users/sakshamgarg/opt/anaconda3/envs/temp_env/lib/python3.10/site-packages/awswrangler/s3/_read_parquet.py", line 326, in _arrowtable2df
    df = _apply_timezone(df=df, metadata=metadata)
  File "/Users/sakshamgarg/opt/anaconda3/envs/temp_env/lib/python3.10/site-packages/awswrangler/s3/_read_parquet.py", line 280, in _apply_timezone
    timezone: datetime.tzinfo = pa.lib.string_to_tzinfo(c["metadata"]["timezone"])
TypeError: 'NoneType' object is not subscriptable
```

However when I tried to read the same file using S3FS library, it was working. Seems to be a problem when the parquet file contains datetime fields with pd.NaT or None values.

### Expected behavior

Instead, I expected the read_parquet() function the return the dataframe after reading from the file.

### OS

Mac and Linux both

### Python version

3.8

### AWS DataWrangler version

2.15.0

**Comment by jaidisido** [comment]
Hi @sak1sham, could you please provide a small snippet of code to reproduce this? We can then have a look at it. Sadly we can't accept actual files for security reasons.

**Comment by mohithg** [comment]
@jaidisido is this done? if so can you please mention which version this is fixed, I'm also facing a similar issue.

**Comment by malachi-constant** [comment]
@mohithg This was closed as we don't have a reproducible example. Are you able to provide a snippet of your code where you are encountering this bug?

**Comment by mohithg** [comment]
Actually I found that this is fixed in https://github.com/aws/aws-sdk-pandas/commit/9fcdf3d2caeca21e51e0374ab5d29562eb84fdcf, when is the next release happening?

**Comment by malachi-constant** [comment]
We have not scheduled the next release, but we would probably be looking at sometime in mid-January.
