### ISSUE TITLE
Support pandas 1.0.0

### ISSUE THREAD

**Issue by impredicative** [awslabs/aws-data-wrangler#125]
I currently get the following warning:

    ERROR: awswrangler 0.2.6 has requirement pandas~=0.25.3, but you'll have pandas 1.0.0 which is incompatible.

**Comment by igorborgest** [comment]
Thanks @impredicative!

Now we support Pandas 1.0.0 starting from AWS Data Wrangler 0.3.0!

**Comment by impredicative** [comment]
@igorborgest I see it on PyPI but not at https://anaconda.org/conda-forge/awswrangler

Assuming the above conda-forge repo is managed by awslabs, can awswrangler please also be released there whenever it is published to PyPI? Until then I'll have a hard time installing it.

Or is the conda-forge repo unofficial and maintained by someone else? In this case, maybe awslabs should petition to take over it and publish there themselves.

**Comment by impredicative** [comment]
I now see it on conda-forge.

**Comment by igorborgest** [comment]
Yeah, I'm trying to understand this workflow to accelerate it.

https://github.com/conda-forge/awswrangler-feedstock/issues/38
