### ISSUE TITLE
Neptune dependencies -- possibility of moving to optional/extras?

### ISSUE THREAD

**Issue by jmahlik** [awslabs/aws-data-wrangler#1252]
**Is your idea related to a problem? Please describe.**
The addition of Neptune support in #1085 introduced 3 direct dependencies in the 
`pyproject.toml`. These expand out to 14 additional dependencies when installed.

The main concern is `rdflib`, as a transitive dep of `SPARQLWrapper`, which has a [SSRF issue](https://github.com/RDFLib/rdflib/discussions/1543).  It doesn't seem like this would cause issues in the context of wrangler (seems mostly related to json). Just having the dependency listed/installed can cause issues/extra work for some users in controlled environments.  The additional deps are also starting to become a concern for those using wrangler in a docker image (starting to bloat). 

A possible workaround would be to manually uninstall the additional deps and the transitives but this cases import errors due to the import structure with everything in `__init__`. All deps and their transitives are imported by `import awswrangler` (1225 imports) . Might be worth looking in to this in a separate issue, since the import time is pretty high. 

Would consideration be given to moving these to extras/optional dependencies? Similar to how pyodbc is handled.
That would give users the ability to opt in to these extra dependencies being installed.

## 2.14.0
```console
python -m pip freeze | wc -l
35
```

## 2.15.0
Added the following:

```toml
gremlinpython = "^3.5.2"
backoff = "^1.11.1"
SPARQLWrapper = "^1.8.5"
```

```console 
python -m pip freeze | wc -l
49
```

**Describe the solution you'd like**
Optional dependencies for neptune support? Possible rework of the import structure? 

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by kukushking** [comment]
Hi @jmahlik - done in release `1.15.1`. To install the optional dependency run pip install with `sparql` extra e.g.:
```
> pip install awswrangler[sparql]
```
This will install `SPARQLWrapper` and all it's dependencies including `rdflib`
