### ISSUE TITLE
EMR Job with Docker image always use the deploy mode as cluster

### ISSUE THREAD

**Issue by mdrmuhaimin** [awslabs/aws-data-wrangler#1253]
### Describe the bug

Calling the submit_emr_job function
```python
wr.emr.submit_spark_step(
    cluster_id,
    s3_path,
    deploy_mode="client",
    docker_image=image_path
)
```

Always yield deploy_mode as cluster despite explicitly mentioning otherwise

### How to Reproduce

```python
wr.emr.submit_spark_step(
    cluster_id,
    s3_path,
    deploy_mode="client",
    docker_image=image_path
)
```

### Expected behavior

Deploy mode should be client

### OS

Mac

### Python version

3.9.9

### AWS DataWrangler version

2.15

**Comment by jaidisido** [comment]
Good catch, thank you for the fix. It will be available in the next release, in the meantime you can install it from the `main` branch
