### ISSUE TITLE
Parallelise Pandas

### ISSUE THREAD

**Issue by jdbodyfelt** [awslabs/aws-data-wrangler#1255]
User story: I do not want to wait three days for a single-core calculation. All modern calls should be parallelised. 

Possible solution: Modify source code to implement Modin (parallel Pandas thru Ray or Dask). This should have a default, and be completely configurable.

**Comment by jaidisido** [comment]
Thanks, this is indeed in our roadmap. We don't have an ETA yet but are actively working on it
