### ISSUE TITLE
awswrangler.s3.to_parquet seems to ignore requests to convert integers to categorical types

### ISSUE THREAD

**Issue by drabbit17** [awslabs/aws-data-wrangler#1258]
### Describe the bug

When loading data using `awswrangler.s3.to_parquet` and passing the name of an integer column to the `categories` argument these columns seem to be ignored. 

### How to Reproduce

```python
In [2]: import pandas as pd
   ...: import awswrangler as wr
   ...: import sys
   ...:
   ...:

In [3]: print(f"python version: {sys.version} \n")
   ...: for lib in [pd, wr]:
   ...:     print(f"{lib.__name__}: {lib.__version__}")
   ...:
python version: 3.7.3 (default, Jun 11 2019, 01:05:09)
[GCC 6.3.0 20170516]

pandas: 1.3.1
awswrangler: 2.14.0

In [4]: foo = pd.DataFrame({"a": [1, 2, 3], "b": [1, 2, 3], "c": ["a", "b", "c"]})
   ...: foo.dtypes
   ...:
   ...:
Out[4]:
a     int64
b     int64
c    object
dtype: object

In [5]: _ = wr.s3.to_parquet(foo, S3_PATH)


In [6]:

In [6]: bar = wr.s3.read_parquet(S3_PATH, categories=['a', 'c'])
   ...: bar.dtypes
   ...:
   ...:
Out[6]:
a       Int64
b       Int64
c    category
dtype: object

In [7]: bar['a'] = pd.Categorical(bar["a"])
   ...: bar.dtypes
   ...:
   ...:
Out[7]:
a    category
b       Int64
c    category
dtype: object
```

### Expected behavior

I would expect all the columns passed to the `categories` argument to be loaded as categoricals. As per last cell execution output in the `How to Reproduce` section above

### OS

Debian GNU/Linux 9.9 (stretch)

### Python version

3.7.3

### AWS DataWrangler version

 2.14.0

**Comment by kukushking** [comment]
Pyarrow seem to have [addressed](https://issues.apache.org/jira/browse/ARROW-5480) it but only for string categoricals - in 7.0.0 numeric categoricals still don't survive round trips. I've added the comment on the issue -- let's see what they say.
