### ISSUE TITLE
Function read_parquet throws an error for an 'and' clause in the partition_filter parameter

### ISSUE THREAD

**Issue by theandrewdodson** [awslabs/aws-data-wrangler#1263]
### Describe the bug
Can't use an 'and' condition in the partition_filter parameter when reading a parquet file

### How to Reproduce

**Succeeds**
```
    df = wr.s3.read_parquet(path="s3://bucket/folder, 
                            boto3_session=session,
                            dataset=True,
                            partition_filter=lambda x: x["year"] == "2018" or x["month"] == "1")

```
**Fails**
```
    df = wr.s3.read_parquet(path="s3://bucket/folder, 
                            boto3_session=session,
                            dataset=True,
                            partition_filter=lambda x: x["year"] == "2018" and x["month"] == "1")

```
**Error received**
NoFIlesFound: No files found on s3://bucket/folder

### Expected behavior
and conditions would perform the same as an or clause

I also tried to match the format of the documentation to no avail.

![image](https://user-images.githubusercontent.com/33064378/162046965-1b1820dc-ed19-4f76-b5bf-221bd167d7bf.png)

### Your project
No response

### Screenshots
No response

### OS
Linux/Windows

### Python version
3.8.5

### AWS DataWrangler version
2.14.0

### Additional context

**Comment by kukushking** [comment]
Wrangler throws an error after listing the bucket if there are no objects matching your criteria. Looks like there are just no files in `/year=2018/month=1/` partition
