### ISSUE TITLE
How to use regex in s3.list_directories API?

### ISSUE THREAD

**Issue by kumar-abhishek** [awslabs/aws-data-wrangler#1273]
`Use case`: List folders inside "s3://v12345".

**What I tried**
```
import awswrangler as wr
wr.s3.list_directories('s3://v[0-9]{5}')
```
Is that the right way to use regex in `list_directories()`?

[Referenced this documentation](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.list_directories.html)

**Comment by jaidisido** [comment]
Hi @kumar-abhishek, the method accepts [unix shell glob patterns](https://teaching.idallen.com/cst8207/15w/notes/190_glob_patterns.html#shell-glob-metacharacters), not regex. Examples of how to build these patterns can be found in this [test](https://github.com/awslabs/aws-data-wrangler/blob/main/tests/test_s3.py#L340)

**Comment by guonengamazon** [comment]
The test link doesn't work.
