### ISSUE TITLE
Difference between writing file with and without dataset option

### ISSUE THREAD

**Issue by luvk1412** [awslabs/aws-data-wrangler#1277]
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
At many place in documentation it is written 
> The concept of Dataset goes beyond the simple idea of ordinary files and enable more complex features like partitioning and catalog integration (Amazon Athena/AWS Glue Catalog).
Ref : [to_parquet](https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.s3.to_parquet.html?highlight=dataset#awswrangler.s3.to_parquet)

I want to know is there any difference in actual single file written in S3 when dataset is True or False besides the storage structure could be different when partitions are there, but is there actual difference in files ?

For example if i have some non partitioned data would there be any difference in file written with dataset is true and dataset false ?
```python
def read_and_write_to_s3():
    df = wr.s3.read_parquet(path='s3://wr_test/')
    wr.s3.to_parquet(
        df=df,
        path='s3://common-staging-bucket/wr_test/',
        compression='gzip',
        dataset='true'
    )

def read_and_write_to_s3():
    df = wr.s3.read_parquet(path='s3://wr_test/')
    wr.s3.to_parquet(
        df=df,
        path='s3://common-staging-bucket/wr_test/',
        compression='gzip'
    )
```

Would both functions above write an identical file ? even though dataset is True or dataset is False ?

**Comment by malachi-constant** [comment]
Hi @luvk1412, thanks for the question!

Taking a simple example.
```
df = pd.DataFrame({
    "id": [1, 2],
    "value": ["foo", "boo"],
    "date": [date(2020, 1, 1), date(2020, 1, 2)]
})

wr.s3.to_parquet(
    df=df,
    path=path,
)
```

Should yield a failure as `dataset=False` (the default setting) requires that the path be a S3 key and not a path.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hansonlu/.pyenv/versions/wrangler-tester/lib/python3.9/site-packages/awswrangler/_config.py", line 450, in wrapper
    return function(**args)
  File "/Users/hansonlu/.pyenv/versions/wrangler-tester/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 509, in to_parquet
    _validate_args(
  File "/Users/hansonlu/.pyenv/versions/wrangler-tester/lib/python3.9/site-packages/awswrangler/s3/_write.py", line 64, in _validate_args
    raise exceptions.InvalidArgumentValue(
awswrangler.exceptions.InvalidArgumentValue: If <dataset=False>, the argument <path> should be a key, not a prefix.
```

From the API docs: 
```
path (str, optional) – S3 path (for file e.g. s3://bucket/prefix/filename.parquet) (for dataset e.g. s3://bucket/prefix). Required if dataset=False or when dataset=True and creating a new dataset
```
[to_parquet() docs](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet)

**Comment by luvk1412** [comment]
@malachi-constant I am not sure how your comment is answering my question, i wanted to know if there is any difference in file when written with dataset=true or dataset=false or not. For example the both code i gave in my question, would both write identical files in terms of file structure, or dataset=true would bring any special changes to the file ?

**Comment by malachi-constant** [comment]
In the example you gave, the call to `to_parquet()` with `dataset=False` would fail so no file would be written to S3.

```
def read_and_write_to_s3():
    df = wr.s3.read_parquet(path='s3://wr_test/')
    wr.s3.to_parquet(
        df=df,
        path='s3://common-staging-bucket/wr_test/',
        compression='gzip',
        dataset='true'
    )

# This does not work 
def read_and_write_to_s3():
    df = wr.s3.read_parquet(path='s3://wr_test/')
    wr.s3.to_parquet(
        df=df,
        path='s3://common-staging-bucket/wr_test/',
        compression='gzip'
    )
  ```

**Comment by luvk1412** [comment]
@malachi-constant  sorry my bad, my intention of asking this question is just to verify wether file written would actually be different or not , so code would change to, 
```python
def read_and_write_to_s3():
    df = wr.s3.read_parquet(path='s3://wr_test/')
    wr.s3.to_parquet(
        df=df,
        path='s3://common-staging-bucket/wr_test/',
        compression='gzip',
        dataset='true'
    )

def read_and_write_to_s3():
    df = wr.s3.read_parquet(path='s3://wr_test/')
    wr.s3.to_parquet(
        df=df,
        path='s3://common-staging-bucket/wr_test/data.gz.parquet',
        compression='gzip'
    )
```
Now i guess both functions will run, so now apart from different file names, will there be any structural difference in files written to s3 due to datatset flag being different in both ?

**Comment by malachi-constant** [comment]
No worries ! Yea there would be no structural difference between the two files. Reading back both the dataset and non-dataset parquet would yield an identical dataframe in this case.
