### ISSUE TITLE
Transactional behaviour of awswrangler.s3.to_parquet in overwrite mode

### ISSUE THREAD

**Issue by luvk1412** [awslabs/aws-data-wrangler#1278]
No Information regarding transactional behaviour is mentioned in Docs for [awswrangler.s3.to_parquet](https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.s3.to_parquet.html?highlight=dataset#awswrangler.s3.to_parquet) when used with mode='overwrite'.

I wish to know wether overwrite is transactional ? i.e is it guaranteed that if call fails, the original files in the bucket will always be there(if new file is not written in bucket) ? 

I went inside the code of the library a bit and I saw that deletion of files happen before the write of new file.  If deletion succeeds and write fails, wouldn't it result in a situation where target s3 location will be empty and hence leading to lose of data ?

**Comment by cnfait** [comment]
Indeed overwrite is not transactional. If writing new data fails for any reason, old data will be gone and cannot be relied upon. However the loss of data is admittedly expected given the nature of overwriting. We can add this information to the documentation, thanks for the suggestion!
