### ISSUE TITLE
CDC support for Opensearch

### ISSUE THREAD

**Issue by snikolakis** [awslabs/aws-data-wrangler#1285]
**Is your idea related to a problem? Please describe.**
To the best of my knowledge, when using DataWrangler for CDC from RDS to Redshift, it works like a charm without needing to manually handle the operation code (I, U, D) passed to the .csv file. When trying to perform CDC from RDS to Opensearch it breaks and cannot index the new documents passed to Opensearch.

**Describe the solution you'd like**
I believe that it would be really helpful if DataWrangler handled operation codes internally, without forcing the engineer using it to do this manually. Below you may find the code that could be used to reproduce the aforementioned behavior.

```python
import os
import pandas as pd
import awswrangler as wr

# The first insertion of data, lets say the "Full Load" operation
FIRST_INSERT = pd.DataFrame([{"id": 1, "data_value": 10}])
# The .csv file should look like: I,2,20 where I is OP, 2 is the id and 20
# is the data_value
SECOND_INSERT = pd.DataFrame([{"id": "I", "data_value": 2}])

if __name__ == "__main__":
    HOST = os.getenv("HOST_IP")
    USERNAME = os.getenv("USERNAME")
    PASSWORD = os.getenv("PASSWORD")

    table_name = "test_table"

    opensearch_client = wr.opensearch.connect(
        host=HOST,
        username=USERNAME,
        password=PASSWORD,
    )
    wr.opensearch.index_df(client=opensearch_client, df=FIRST_INSERT, index=table_name)
    # This should break and display an error like the following:
    # [ERROR] Exception: ('1 document(s) failed to index.', [{'index': {'_index': 'test_table', '_type': '_doc', '_id':
    # 'df186dec-5e2d-483e-ae81-d313d7086592', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason':
    # "failed to parse field [id] of type [long] in document with id 'df186dec-5e2d-483e-ae81-d313d7086592'.
    # Preview of field's value: 'I'", 'caused_by': {'type': 'illegal_argument_exception', 'reason':
    # 'For input string: "I"'}}, 'data': {'id': 'I', 'data_value': 2}}}])
    wr.opensearch.index_df(client=opensearch_client, df=SECOND_INSERT, index=table_name)
    opensearch_client.close()
```

**Comment by AssafMentzer** [comment]
@snikolakis thank you for the enhancement suggestion.
Can you please elaborate on RDS->Redshift CDC? where do you see this in the code?
If we move forward with this enhancement to OpenSearch we'd like to provide a consistent experience.

**Comment by snikolakis** [comment]
Thank you for your response @AssafMentzer . I cannot really respond to where this exists inside the data-wrangler code, however I can describe my use case and how this works in case it helps you better understand. Suppose we are performing data migration between a RDS DB and Redshift and we need logical replication enabled in order to keep "listening" for changes and migrate them, as well, to our Redshift cluster.

In my use case, I need to perform some transformations in a AWS Lambda Function before copying the data to Redshift. So let's say in the full load I am having this file:

```python
1,Full-load,"{full,load}",2022-04-21 12:18:00.000000,2022-04-21 12:18:00.000000
``` 

I send this file to a S3 bucket, read it with data-wrangler:

```python
chunks = wr.s3.read_csv(
    path=input_file, names=["id", "name", "keys", "created_at", "updated_at"], chunksize=1000
)
```
Then, I transform the chunk changing `{full, load}` array ("keys" column) to two different rows each containing one item of the list and then copy the `DataFrame` to Redshift:

```python
wr.redshift.copy(
    df=df,
    path=s3_path,
    con=redshift_conn,
    table="table",
    schema="public",
    iam_role=arn::..........,
    primary_keys=["id"],
)
``` 
And it correctly creates a table with two rows in Redshift:

```python
1,Full-load,2022-04-21 12:18:00.000000,2022-04-21 12:18:00.000000,full
1,Full-load,2022-04-21 12:18:00.000000,2022-04-21 12:18:00.000000,load
```
Afterwards, I am performing the same operation for a file produced again by AWS DMS, but now the file is created because of CDC, which means that an operation code is also inserted in the beginning of the .csv row, e.g.:

```python
I,2,Test,"{Test,test}",2022-04-21 12:19:00.000000,2022-04-21 12:19:00.000000
```

By performing the same operation it still adds two rows to the Redshift table, ignoring the operation code "I":

```python
1,Full-load,2022-04-21 12:18:00.000000,2022-04-21 12:18:00.000000,full
1,Full-load,2022-04-21 12:18:00.000000,2022-04-21 12:18:00.000000,load
2,Test,2022-04-21 12:19:00.000000,2022-04-21 12:19:00.000000,Test
2,Test,2022-04-21 12:19:00.000000,2022-04-21 12:19:00.000000,test
```

This does not work with "U" operations, leading to new rows insertions though. However, when trying to perform data migration from RDS to Opensearch, the "I" operation code breaks the insertion to the Opensearch step and thus, cannot perform CDC with RDS and Opensearch.

It feels weird that when migrating data to Redshift it seems to ignore the operation code (I have personally only used Inserts and Updates) while not the same happens for Opensearch.

I hope this helps clarifying a bit your question? From my understanding and my latest experiments I gather that data-wrangler does not handle operation codes and it is the responsibility of the engineer to do so. But, maybe, could the data-wrangler actually handle this?

**Comment by kukushking** [comment]
Data Wrangler does not handle change data capture in any of its services at the moment. 
To be honest, not quite sure why "I" column is ignored in your case, perhaps because it's not part of the schema and the default behaviour is to ignore the unknown fields. 
You should be able to handle updates/deletes by specifying `update`/`delete` operation (that goes in the doc_type field I think) when indexing.
