### ISSUE TITLE
Lambda times out reading JSON data from S3 using AWS wrangler

### ISSUE THREAD

**Issue by Jeni-P** [awslabs/aws-data-wrangler#1286]
Lambda function scans few partitions in S3 and has to read about 40-50 files in total with no more than couple thousand records. I have configured the Lambda function with about 1GB memory and 5 minutes time out. Lambda execution times out while reading data from S3 **using wrangler**. I even tried reading data in chunks using chunksize parameter in read_json function but still no luck. By seeing lambda monitoring metrics, this does not seem to be memory issue (as usage is around 250-300 MBs for most executions) but compute issue. Any suggestion to resolve this compute issue will be much appreciated.

**Code:**
```
        df_existing_data = pd.DataFrame()
        for partition in s3_partitions_list:
            bucket_filter_prefix = f"{s3_dir}/{partition}/"
            path_prefix = f"{s3_path}/{partition}/"
            for obj in bucket.objects.filter(Prefix=bucket_filter_prefix):
                temp_df = wr.s3.read_json(path=path_prefix)
                df_existing_data = df_existing_data.append(temp_df)
```

**Raw data in JSON format:**
```
{
 "key1": {"0": value1, "1": value2},
 "key2": {"0": value1, "1": value2}
}
```

**Note:** When I use **boto3**, I do not face this issue. Lambda execution completes smoothly.

Using wrangler version 2.14.0

**Comment by AdrianoNicolucci** [comment]
I'm having a similar issue. Any suggestions on how to improve reading performance from S3 using aws data wranger?

**Comment by jaidisido** [comment]
Hi folks,

I am slightly confused by these lines:
```
            for obj in bucket.objects.filter(Prefix=bucket_filter_prefix):
                temp_df = wr.s3.read_json(path=path_prefix)
```
It's looping over every object in a partition and then reading all the objects in the partition into a dataframe? So if say a partition has 4 objects, it would create 4 dataframes which would each contain ALL objects in that partition?

**Comment by Jeni-P** [comment]
Ah yes! Thank you.
**Modified code:**
        df_existing_data = pd.DataFrame()
        for partition in s3_partitions_list:
            bucket_filter_prefix = f"{dest_s3_log_dir}/{partition}/"
            for obj in bucket.objects.filter(Prefix=bucket_filter_prefix):
                obj_uri = f"s3://{obj.bucket_name}/{obj.key}"
                temp_df = wr.s3.read_json(path=obj_uri)
                df_existing_data = df_existing_data.append(temp_df)

**Comment by jaidisido** [comment]
Glad it helped, I am closing the issue. As a side note, your code can further be optimised as the loop is completely unnecessary. You could simply run:
```
objs = bucket.objects.filter(Prefix=bucket_filter_prefix)
df = wr.s3.read_json(path=objs)
```
or simply:
```
df = wr.s3.read_json(path=f"{s3_path}/{partition}/")
```
without the need for a loop as the method accepts an S3 prefix or list of objects anyways.
