### ISSUE TITLE
Pip package too big for AWS Lambda functions

### ISSUE THREAD

**Issue by cdelamocepsa** [awslabs/aws-data-wrangler#1289]
When I try to install Data Wrangler in a lambda function from Pip, the package is too big for the lambda package size limits (50 mb zipped, 250 mb unzipped). If, for example, I try to install the [Lambda Powertools](https://github.com/awslabs/aws-lambda-powertools-python) package and AWS Data Wrangler, I'm getting a 67 MB zipped package, 263 MB unzipped. I'm zipping the package via serverless with the **slim** option set to true.

Inspecting the package, I see that some packages that are already on lambda are being installed, such as botocore, boto3. Maybe one option to lighten the package could be releasing a version optimized for Lambda that does not include this packages.

Thank you!

**Comment by jaidisido** [comment]
There is no need for the user to install the library in Lambda as it has already been packaged and made available. See the installation docs for available options: https://aws-data-wrangler.readthedocs.io/en/latest/install.html#aws-lambda-layer

**Comment by corte** [comment]
Doesn't this problem still exist when using the lambda layer?
I have in my requirements.txt file only `aws-lambda-powertools` and I'm using the lambda layer `arn:aws:lambda:eu-west-1:336392948345:layer:AWSSDKPandas-Python37:1` 
But still get the error:
```Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 331886024 bytes```

**Comment by malachi-constant** [comment]
@corte I was able to use the both the layers together in a single function. Have you given that a try?
<img width="1615" alt="Screen Shot 2022-11-29 at 10 03 40 AM" src="https://user-images.githubusercontent.com/6465221/204609772-4dcedd97-b412-40ec-b05e-8866e77a25a3.png">
