### ISSUE TITLE
wr.timestream.query is very slow due to large number of pagination requests

### ISSUE THREAD

**Issue by NakedKoala** [awslabs/aws-data-wrangler#1308]
my call to query api 

```
wr.timestream.query(query_str)

```
took 50 seconds to return about a dataframe of size 6MB containing 80K records.

I can see that a majority of the 50 seconds is taken up by dispatching a large number of paginate request one after another.

I have tried to change the pagination config from default value below. 

```
{ "MaxItems": 10, "PageSize": 10, "StartingToken": "…"}
```
But I am unable to work out what value should "StartingToken" be. 

I tried to set "MaxItems" = 100,000 and "PageSize" = 1000 without specifying "StartingToken", but only 20K records get returned and the entire call still took close to 40 seconds.

Question:

How should I make large query faster by i) correctly increase page size or ii) parallelize request for different pages ?

**Comment by NakedKoala** [comment]
@kukushking 

my usecase ( some global analytics ) can't work with partial result.

Looks like the underlying service timestream is not suitable for this query pattern ( where i need to query hundreds of MB's worth of data quickly )

I am considering periodically coping raw data from timestream to some other AWS data store service which supports fast & efficient dumping of large amount of data.  For this, do you have any suggestion ? 

The dumpest idea would be just to pull raw data from timestream and dump it onto csv and put it on S3.

**Comment by kukushking** [comment]
@NakedKoala If you can't work with partial results try to retrieve by page and then `pd.concat` the data. Hundreds of MBs should still be OK with API, that is only my hyphothesis regarding the limits (also It's row size that is limited to 1MB, not the entire response size)
