### ISSUE TITLE
Redshift API. Pass column names to not have issues with column orders between destination and staging tables when doing UPSERT operation

### ISSUE THREAD

**Issue by IldarAlmakaev** [awslabs/aws-data-wrangler#1314]
**Is your idea related to a problem? Please describe.**
If a table definition is changed(e.g. add/drop columns) then column orders between a destination and a staging tables in Redshift will be different. It might cause an incompatible schema error when the awswrangler is copying parquet files from S3 to Redshift. 
AFAICS, the problem is in awswrangler’s code for upsert operation logic in **__upsert_** method [here](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/redshift.py#L202):

`sql = f"INSERT INTO {schema}.{table} SELECT * FROM {temp_table}"`

AYCS, there is a `*` sign in the SELECT clause instead of exact column names. So if we modify add or delete a column, then number of columns between {schema}.{table} and {temp_table} differs. It causes the aforementioned error.

**Describe the solution you'd like**
As an option, we could just pass the column names and use them in that SQL query. For example,
`sql = f"INSERT INTO {schema}.{table} ({column_names}) SELECT {column_names} FROM {temp_table}"`

where the column_names parameter is a comma-separated string with column names

**Comment by IldarAlmakaev** [comment]
Ther PR with changes is [here](https://github.com/awslabs/aws-data-wrangler/pull/1317). Just need to fix tests and rebuild

**Comment by jaidisido** [comment]
Looks great, thanks for the contribution!
