### ISSUE TITLE
describe_objects runs slow compared to list_objects or equivalent boto3 request.

### ISSUE THREAD

**Issue by davidparks21** [awslabs/aws-data-wrangler#1326]
### Describe the bug

`awswrangler.s3.describe_objects(S3PATH)` is taking 10+ minutes to run (even with threads, though a little better) when there are 1000+ files in `S3PATH`. 

Both of these commands run fast:

```
awswrangler.s3.list_objects(S3PATH)

boto3.resource('s3').Bucket(BUCKET).meta.client.list_objects(Bucket=BUCKET, Prefix=KEYPREFIX)
```

### How to Reproduce

```
s3wrangler.describe_objects(S3PATH)   # where S3PATH is an S3 prefix with 1000+ files.
```

### Expected behavior

Expected similar performance to `boto3`.

### Your project

https://github.com/braingeneers/braingeneerspy/

### OS

Linux

### Python version

3.8.10

### AWS DataWrangler version

2.14.0

**Comment by jaidisido** [comment]
I am not sure why you think the two methods (list_objects and describe_objects) are comparable here?

`wr.s3.describe_objects` does not only list the objects in the S3 prefix, but also makes a HEAD call on __each__ one of them. S3:Head is an expensive operation because it collects far more information than list object, including ContentLength, DeleteMarker, ContentType...

A fairer comparison would be to contrast:
```
wr.s3.describe_objects
```
to
```
import boto3

bucket = "my-bucket"

bucket_resource = boto3.resource('s3').Bucket(bucket)
objs = bucket_resource.meta.client.list_objects(Bucket=bucket)["Contents"]

for obj in objs:
    print(
        bucket_resource.meta.client.head_object(Bucket=bucket, Key=obj["Key"])
    )
```
at which point the performance would be similar

**Comment by davidparks21** [comment]
I agree that it's a reasonable expectation that `describe_objects` be slower due to individual `head_object` requests. Solving the problem by making `describe_objects` as fast as `list_objects` is probably not a reasonable solution, and I wasn't clear in my description that I wasn't proposing that.

Rather, I think the more simple solution is to include more of the information available with `list_objects` or at least give the users an option to get more of that information. In the current state when `list_objects` is called it returns only string object names, which throws away information that is very much needed (modified dates in particular for my use case). Thus to get that information from `awswrangler` users are forced to use `describe_objects` which then imposes an unreasonable performance penalty. The only reasonable solution is to abandon `awswrangler` and fall back to `boto3`, which defeats the purpose of having `awswrangler` in the first place. 

It's clear that `list_objects` _can_ include additional information such as modified date, for a single-query cost, and there are clear use cases that would benefit from this. Therefore, my suggestion is that `list_objects` return this information. I'd suggest perhaps adding a parameter to `list_objects` to `return_details=True|False` and default it to False. If `True` then a second return value could be provided with additional detail available in the single query. This way backwards compatibility is maintained.

This would make `awswrangler` match `awscli` output, where users are commonly accustom to seeing an `ls` operation provide date, object size, and key.
