### ISSUE TITLE
AttributeError: 'Index' object has no attribute 'head' - Regression in 2.15.*

### ISSUE THREAD

**Issue by mwoods-familiaris** [awslabs/aws-data-wrangler#1327]
### Describe the bug

Regression of #1188 in awswrangler 2.15.*

`wr.s3.to_parquet` fails when writing a `DataFrame` with an an ExtensionDType index resulting in error

```
AttributeError: 'Index' object has no attribute 'head'
```

Specifically, the failure happens when using `pandas==1.4.*` and `awswrangler==2.15.*`. This behavior is consistent on both `pyarrow==5.0.0` and `pyarrow==7.0.0`. Appears to be a regression in the 2.15.0 release, as works fine when `awswrangler==2.14.*`

### How to Reproduce

```python
import pandas as pd
import awswrangler as wr


df = pd.DataFrame(
    {"col1": [1, 2, 3], "col2": [1, 2, 3]}, dtype=pd.Int64Dtype()
).set_index("col1")

wr.s3.to_parquet(
    df,
    path="s3://bucket/tmp.parquet",
    index=True,
    dataset=False,
)
# throws error
```

### Expected behavior

Successful write of parquet file to S3 location

### OS

Linux / Debian 10.12

### Python version

3.9

### AWS DataWrangler version

2.15.0, 2.15.1

### Additional context

Pandas 1.4.2

**Comment by kukushking** [comment]
There's all sorts of strange issues when using extension types in indexes in pandas `1.4.*` i.e. [this](https://github.com/pandas-dev/pandas/issues/46507) as well. 

Let's see if above fix helps with this particular case & doesn't break anything else

**Comment by updiversity** [comment]
Hi,

it looks like it continues to fail in the case the index has no name.

````
import pandas as pd
import awswrangler as wr

df = pd.DataFrame(
    {"col1": [1, 2, 3], "col2": [1, 2, 3]}, dtype=pd.Int64Dtype()
).set_index("col1")

df.index.name = None

wr.s3.to_parquet(
    df,
    path="s3://bucket/tmp.parquet",
    index=True,
    dataset=False,
)

# throws error
```

This is a common case when dealing with df generated with user-functions.
