### ISSUE TITLE
pyarrow is limit to <7.1.0 and >=2.0.0, if we want to use pyarrow==8.0.0

### ISSUE THREAD

**Issue by bingwork** [awslabs/aws-data-wrangler#1328]
### Describe the bug

aws-data-wrangler is a great package, we want to use pyarrow==8.0.0, but now aws-data-wrangler limits pyarrow between <7.1.0 and >=2.0.0. So is there any reason or can it update to pyarrow==8.0.0?

### How to Reproduce

pip install pyarrow==8.0.0
pip install awswrangler==2.15.0

it will cause the error below:
The conflict is caused by:
    The user requested pyarrow==8.0.0
    awswrangler 2.15.0 depends on pyarrow<7.1.0 and >=2.0.0

### OS

Mac

### Python version

3.8.12

### AWS DataWrangler version

2.15.0

**Comment by jaidisido** [comment]
Glad to hear you enjoy the package @bingwork.
Within wrangler, pyarrow is pinned to the specific major versions that we have tested. Pyarrow 8 was released less than 7 days ago. In our next release of the library, we will test this new pyarrow version and pin the dependency to <=8.0.

In the meantime, you can always override/force the install of a package in pip with the `--no-deps` argument:
```
pip install awswrangler
pip install pyarrow==8.0.0 --no-deps
```

**Comment by bingwork** [comment]
@jaidisido thanks for your detailed reply. I didn't find a requirement.txt in the project, so how I can make sure you "pin the dependency to <=8.0"?

**Comment by bingwork** [comment]
I find the PR in https://github.com/awslabs/aws-data-wrangler/pull/1321/commits/343a464d50156f4bff5c0984d094729cb091e3e5 thanks.
