### ISSUE TITLE
head_object_with_retry removed?

### ISSUE THREAD

**Issue by JPFrancoia** [awslabs/aws-data-wrangler#133]
Hi,

Is it me or the `awswrangler.s3.head_object_with_retry` was removed in 0.3.1 ? Is there any reason for this?

It's breaking some of my scripts.

Cheers

**Comment by igorborgest** [comment]
We just converted it to an internal method with the the underscore as prefix:

*" _head_object_with_retry()"*

But it was a mistake, we will convert it back to public in the next release on the weekend.

In the meanwhile the recommendation is to keep using the version 0.3.0.

**Comment by JPFrancoia** [comment]
Hi @igorborgest ,

Ok no problem, thank you for commenting this quickly. I'll pin to 0.3.0 for now.

Thanks

**Comment by igorborgest** [comment]
@JPFrancoia fixed. Will be in the next release!
