### ISSUE TITLE
[Support Data Wrangler]: Infomach

### ISSUE THREAD

**Issue by Alcefilho** [awslabs/aws-data-wrangler#1330]
Thank you for letting us use your organization's name on the Data Wrangler read.me page and letting other customers know that you support the project!  If you would like us to also display your organization's logo. please raise a pull request to provide an image file for the logo.

Please add any files to *docs/source/_static/*

Organization Name: Infomach
Your Name: Alcebiades Filho
Your Position: Data Cientist
I have included a logo: n

*By raising a Support Data Wrangler issue (and related pull request), you are granting AWS permission to use your company’s name (and logo) for the limited purpose described here and you are confirming that you have authority to grant such permission.*

**Comment by jaidisido** [comment]
Added to the readme, thank you for the contribution
