### ISSUE TITLE
Accept a PartitionStrategy for Neptune property graph loading

### ISSUE THREAD

**Issue by laithalsaadoon** [awslabs/aws-data-wrangler#1348]
**Is your idea related to a problem? Please describe.**
In development, I would like to have logically separate property graphs so I can use a single AWS Neptune cluster for multiple development flows/features/tests. `neptune.to_property_graph` could have a parameter to support [PartitionStrategy](https://tinkerpop.apache.org/docs/current/reference/#partitionstrategy).

**Describe the solution you'd like**
A clear and concise description of what you are expecting.

Updating neptune.to_property_graph to accept and use an instance of `PartitionStrategy`, cascading it to `_set_properties`. It would be worth also considering enhancing the `execute_gremlin` method.

https://github.com/apache/tinkerpop/blob/11502fb5bd0eb6a7e686c9433da3559718954348/gremlin-python/src/main/python/gremlin_python/process/strategies.py#L60
https://github.com/awslabs/aws-data-wrangler/blob/b3c56768e6ba297338217e0b36f30a02c4ca25a9/awswrangler/neptune/neptune.py#L310

**I am willing to contribute to this enhancement 👋 **

**Comment by jaidisido** [comment]
Ping @bechbd

**Comment by bechbd** [comment]
@laithalsaadoon Do you have a proposed way that we would want to implement this from the client?  I am not sure I would want to explicitly expose the PartitionStrategy object out to the end user.

**Comment by laithalsaadoon** [comment]
> @laithalsaadoon Do you have a proposed way that we would want to implement this from the client? I am not sure I would want to explicitly expose the PartitionStrategy object out to the end user.

Not exactly sure how it would be implemented from the client, since it seems the traversal is instantiated later. I'm happy to take a stab at it, but wanted to make sure it was something that was applicable aws wrangler from a vision point-of-view.
