### ISSUE TITLE
mypy version: 0.960 errors 

### ISSUE THREAD

**Issue by malachi-constant** [awslabs/aws-data-wrangler#1371]
### Describe the bug

New version of `mypy:0.960` throws the following error on 2 year old code: 

```
awswrangler/s3/_read.py:96: error: Redundant cast to "str"
```

It is possible this can be safely removed, but futher investigation should be performed to evaluate any impact of removing this cast.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

Static checks Github Action or running `./validate.sh` with mypy version 0.960 will produce the above error.

### OS

Mac

### Python version

3.8.13

### AWS DataWrangler version

2.15.1

**Comment by kukushking** [comment]
Mypy's `cast()` returns the value [unchanged](https://docs.python.org/3/library/typing.html#typing.cast) so it should not have any runtime impact. Most likely this was added because `path_root: Optional[str]` in the function args and it would complain about unhandled `None` case
