### ISSUE TITLE
when use read_sql_query to get data if it exist special character "£"

### ISSUE THREAD

**Issue by oceanchow** [awslabs/aws-data-wrangler#1391]
Hi guys,
Thanks for your hard work to let this lib easily to use. 
here is my question
when I use a 3rd package using pyathena, it works and return right data, while it can't work when I use below codes

> wr.athena.read_sql_query(sql, database=database, use_threads=True, ctas_approach=False)

after search settings in AWSDATAWrangler about encoding, unfortunately, nothing can solve my problem, could you please help me with it? Thanks.

**Comment by jaidisido** [comment]
When setting `ctas_approach=False`, a [regular query](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) against athena is started and the results are stored as CSV in S3 before being read.

Special characters have caused [issues](https://github.com/awslabs/aws-data-wrangler/issues/1156) in the past in a CSV, but a fix was pushed in https://github.com/awslabs/aws-data-wrangler/pull/1257 waiting for release.

I suggest you either:
- Test with `ctas_approach=True` or `unload_approach=True` to read the results as parquet instead
- Test the fix from the PR:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```

**Comment by oceanchow** [comment]
> 

Thanks Jaidisido, I will make some tests accordingly.

**Comment by oceanchow** [comment]
seems option1 don't work for me:(, but option2 works. 
Hope you guys can publish a new version soon. Thanks @jaidisido

**Comment by cotrariello84** [comment]
has the bug been fixed?

**Comment by malachi-constant** [comment]
@cotrariello84 Yes this was published in release [`2.16.0`](https://github.com/aws/aws-sdk-pandas/releases/tag/2.16.0) and should not be an issue in `awswrangler>=2.16.0`

**Comment by cotrariello84** [comment]
Hi @malachi-constant I still have the bug in version 2.17.0. I had to use pyathena to solve it. but I 'd like to use wrangler.

**Comment by malachi-constant** [comment]
> Hi @malachi-constant I still have the bug in version 2.17.0. I had to use pyathena to solve it. but I 'd like to use wrangler.

See [comment](https://github.com/aws/aws-sdk-pandas/issues/317#issuecomment-1308971639)
