### ISSUE TITLE
wr.timestream.query raises ValueError("No objects to concatenate") for valid query with no results

### ISSUE THREAD

**Issue by tsaluszewski** [awslabs/aws-data-wrangler#1394]
### Describe the bug

`wr.timestream.query` raises `ValueError("No objects to concatenate")` for valid query with no results.

`
  File "/home/tsaluszewski/miniconda3/envs/semioticlabs-dev/lib/python3.8/site-packages/awswrangler/timestream.py", line 268, in query
    return pd.concat(result_iterator, ignore_index=True)
  File "/home/tsaluszewski/miniconda3/envs/semioticlabs-dev/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/tsaluszewski/miniconda3/envs/semioticlabs-dev/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/home/tsaluszewski/miniconda3/envs/semioticlabs-dev/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
`

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

I had to implement the following workaround for `wr.timestream` in order to handle the issue and return `None` instead of raising exception for empty result set.

Below is the test and the wrapper showing the bug:
```
class TimeStreamReader:
    """Generic TimeStream reader based on AWS Wrangler implementation"""

    _session: boto3.Session
    _client = wr.timestream

    def __init__(self, session: boto3.Session = None):
        self._session = session if session is not None else boto3.Session()

    def query(self, sql: str) -> Optional[pd.DataFrame]:
        """
        Queries AWS Timestream using textual SQL statement.
        https://docs.aws.amazon.com/timestream/latest/developerguide/reference.html

        Parameters:
            sql: AWS Timestream SQL syntax
        Returns:
            pandas DataFrame or None if no results returned
        """
        result = None
        try:
            result = self._client.query(sql, chunked=False, boto3_session=self._session)
        except ValueError as err:
            # AWS Wrangler bug, caused by
            # return pd.concat(result_iterator, ignore_index=True)
            if str(err) != "No objects to concatenate":
                raise

        return result
```

```
    def test_query_with_no_records_should_return_none(self) -> None:
        non_existing_dimension = "xyz"
        sql = """select * 
        from "db"."table" 
        where dimension = '{0}'""".format(
            non_existing_dimension
        )

        # Act
        df = self.target.query(sql)

        # Assert
        self.assertIsNone(df)
```

### Expected behavior

Instead of throwing an error for empty result set the `wr.timestream.query` should return `None`

### OS

Linux - Ubuntu 22.04 LTS

### Python version

3.8

### AWS DataWrangler version

2.14.0

**Comment by kukushking** [comment]
Thanks, would you be ok with an empty dataframe?

**Comment by informatica92** [comment]
> Thanks, would an empty dataframe work for you?

I think that it would be even better

**Comment by jdc891010** [comment]
I see quite a few failed builds on the PR, and I am running 2.16.1, with the issues stated above, so I am assuming that there are still a few things to get in order before an updated release?
