### ISSUE TITLE
wr.timestream.query should allow to return pure list of python objects instead of being limited to pandas DataFrame

### ISSUE THREAD

**Issue by tsaluszewski** [awslabs/aws-data-wrangler#1395]
**Is your idea related to a problem? Please describe.**
We do operate on our custom domain objects (mainly data classes) between different layers / lambdas in the application. 
We are using `wr.timestream.query` to retrieve data from AWS Timestream, but as it returns pandas DataFrame we have to deserialize it back to python objects. It unnecessary takes up more memory than needed and is inefficient. For the same reason we've implemented our custom `write_records` method and not using AWS Wrangler implementation as it is 10x faster and less memory intensive ;) 

**Describe the solution you'd like**
Consider parametrizing `wr.timestream.query` , so it can return python list of objects instead of being constraint to only pandas DataFrame. The new signature can look like follows:

`
def query(
    sql: str,
    chunked: bool = False,
    as_data_frame: bool: False,
    pagination_config: Optional[Dict[str, Any]] = None,
    boto3_session: Optional[boto3.Session] = None,
) -> Union[pd.DataFrame, Iterator[pd.DataFrame], List[List[Any]], Iterator[List[Any]] ]:
`

**Comment by jaidisido** [comment]
Hi @tsaluszewski, thank you for the suggestion, however as the name implies, the library is about "Pandas on AWS". The vast majority of the API calls start or end with a Pandas dataframe, it wouldn't make sense to have exceptions for some of them. Glad you managed to develop a faster implementation, don't hesitate to submit a PR if you feel it would be beneficial. Cheers

**Comment by kukushking** [comment]
In terms of optimisation every result page is separately [converted](https://github.com/awslabs/aws-data-wrangler/blob/f2d9299011fd3df66432d53760d363a5b2eec814/awswrangler/timestream.py#L164) to a DataFrame and then concatenated so there is definitely potential for optimisation there

I do agree with @jaidisido though this library is an integration between Pandas and AWS and we would not want to change that, but we can definitely look into optimising the code
