### ISSUE TITLE
Support for export of Aurora PostgreSQL table data as CSV files on S3

### ISSUE THREAD

**Issue by ankurshri** [awslabs/aws-data-wrangler#140]
Hi,
We work on Aurora PostgeSQL.
Are you planning to release support for Amazon Aurora table export as CSV files on S3?

**Comment by igorborgest** [comment]
Thanks for contributing @ankurshri.

We will address that on version 1.0.0!

**Comment by igorborgest** [comment]
This feature request already is open for a while but we didn't receive any PR or had time to work on. We will close it until we had more concrete plains to evolve it.
