### ISSUE TITLE
pq_file.schema.names(): TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by robert-schmidtke** [awslabs/aws-data-wrangler#1411]
### Describe the bug

When using `validate_schema=True` to read parquet files, [PyArrow Schema.names](https://arrow.apache.org/docs/python/generated/pyarrow.Schema.html#pyarrow.Schema.names) is called, even though it is an attribute: https://github.com/awslabs/aws-data-wrangler/blob/2.16.0/awswrangler/s3/_read_parquet.py#L486

This was introduced with the most recent release.

### How to Reproduce

Call `wr.s3.read_parquet` with `validate_schema=True`.

### OS

Ubuntu 20.04.4 LTS

### Python version

3.9.10

### AWS DataWrangler version

2.16.0

**Comment by malachi-constant** [comment]
@robert-schmidtke Appreciate you spotting this
