### ISSUE TITLE
Timestream endpoint url not present 

### ISSUE THREAD

**Issue by ben-w1** [awslabs/aws-data-wrangler#1414]
We are using wrangler in a lambda within a vpc to communicate with timestream. When trying to connect to timestream using vpc  endpoints we are unable to connect due to not being able to set the endpoint url for timestream. 

We would like to request enabling timestream-write and timestream-query url endpoints so wrangler can be used to connect to timestream using vpc endpoints as mentioned in this aws blog: 
https://aws.amazon.com/blogs/database/use-vpc-endpoints-with-amazon-timestream/

**Comment by malachi-constant** [comment]
Hi @ben-w1 thanks for bringing this to our attention. Personally, I'm in agreement that this is a necessary enhancement and we will get this on the roadmap.
