### ISSUE TITLE
Add filename argument for Pandas.to_parquet()

### ISSUE THREAD

**Issue by dwbelliston** [awslabs/aws-data-wrangler#142]
Feature Request: Add filename argument for Pandas.to_parquet().

This was done for to_csv here: https://github.com/awslabs/aws-data-wrangler/pull/139

Could we get to_parquet too?

File location here:
https://github.com/awslabs/aws-data-wrangler/blob/19aaff97e1952c04c60915b7d065690fb4e04a18/awswrangler/pandas.py#L936

**Comment by igorborgest** [comment]
@dwbelliston thanks! We will put it in the release `1.0.0`!

**Comment by dwbelliston** [comment]
Thank you @igorborgest - looking forward to that release 🥳

**Comment by igorborgest** [comment]
Hi! We will release AWS Data Wrangler 1.0.0 on `April 10` and we are collecting as much feedback as possible.

This issue should be resolved with this release. So, please test it if possible, and any feedback about the docs, the library or this specific functionality will be very welcome. 

- Install: `pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev-1.0.0`
- Docs: https://aws-data-wrangler.readthedocs.io/en/dev-1.0.0/
- Code: https://github.com/awslabs/aws-data-wrangler/tree/dev-1.0.0

**Comment by dwbelliston** [comment]
Yay! 🎉

Tested it out and worked great. thanks.
