### ISSUE TITLE
All the read the docs link seem to not work

### ISSUE THREAD

**Issue by nadeem-lalani** [awslabs/aws-data-wrangler#1425]
### Describe the bug

All the read links on the page , https://github.com/awslabs/aws-data-wrangler seems to be browken, 
example: https://aws-data-wrangler.readthedocs.io/en/2.16.1/what.html

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Navigate to the aws data wrangler github page  https://github.com/awslabs/aws-data-wrangler 
Click on any read the docs links, for example: https://aws-data-wrangler.readthedocs.io/en/2.16.1/what.html

### OS

win 10

### Python version

3

### AWS DataWrangler version

main

**Comment by kukushking** [comment]
Hi @nadeem-lalani thanks for raising this - 2.16.1 release is in progress, the links should be working as soon as we publish the release on GitHub. Meanwhile please use /stable /latest or /2.16.0

**Comment by nadeem-lalani** [comment]
got it thanks !!!

**Comment by malachi-constant** [comment]
Links now working for `2.16.1`
