### ISSUE TITLE
Cannot import awsrangler on Glue docker

### ISSUE THREAD

**Issue by Menniti** [awslabs/aws-data-wrangler#1428]
Hello,

I have installed the awsrangler on Glue Docker
With python 3.7.10
But I cannot import the conf for some reason. But I do have credentials setup there
![Screenshot from 2022-07-01 18-10-36](https://user-images.githubusercontent.com/15658494/176968722-08c167d6-654b-4b8a-bf61-1887b6b2c510.png)
![canvas](https://user-images.githubusercontent.com/15658494/176968741-8a72e09c-8f0f-4bf4-aa83-2dd3d509e8f4.png)

Thanks

Docker command to setup the Glue Enviroment in case someone wants to replicate
`docker run -it -v ~/.aws:/home/glue_user/.aws -v $JUPYTER_WORKSPACE_LOCATION:/home/glue_user/workspace/jupyter_workspace/ -e AWS_PROFILE=$PROFILE_NAME -e chmod -R 777 directory DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 -p 8998:8998 -p 8888:8888 --name glue_jupyter_lab amazon/aws-glue-libs:glue_libs_3.0.0_image_01 /home/glue_user/jupyter/jupyter_start.sh `

**Comment by Menniti** [comment]
@malachi-constant may you could help me with 
thanks

**Comment by jaidisido** [comment]
By default, boto3 will check the `~/.aws/config` location (see [here](https://stackoverflow.com/a/60495453/8178963)). Could you check what is the value of `AWS_CONFIG_FILE` environment variable within the docker image? If it does not match `/home/glue_user/` you could force it to be that value. Sharing a snippet of your `~/.aws/config` would also be helpful

**Comment by Menniti** [comment]
Obs: I have retested and the error remains the same

**Comment by Menniti** [comment]
Hey @jaidisido 

I`ve found the issue, Thanks
