### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by qemtek** [awslabs/aws-data-wrangler#143]
Hi, after installing the package using Python 3.6 I get the following error when trying to import the package: 
ImportError: numpy.core.multiarray failed to import

**Comment by igorborgest** [comment]
Hi @qemtek, could give us more details?

It was Installed through Pip, Conda, Lambda Layer or Glue wheel file?
Which OS?

Thanks

**Comment by igorborgest** [comment]
Closing by inactivity.
