### ISSUE TITLE
 wr.dynamodb.put_items : All items need to contain the required keys for the table.

### ISSUE THREAD

**Issue by khanvaws** [awslabs/aws-data-wrangler#1436]
### Describe the bug

When i am try to insert records into Dynamodb using wrangler its given error and same is working in boto3 without any issue .
I am using AWS lambda python 9 and wrangler layer 9 

**Table details :**
Partition key
pk (String)
Sort key
sk (String)
Capacity mode
On-demand

**Code**

 wr.dynamodb.put_items(
    items={'pk': '35','sk':  'aws'},
    table_name='TestTbl'
    )

**Error** 👍 

           "errorMessage": "All items need to contain the required keys for the table.",
           "  errorType": "InvalidArgumentValue",
           "requestId": "53daddbf-7253-4e79-8af6-ab41cbd8495e",
          "stackTrace": [
          "  File \"/var/task/lambda_function.py\", line 35, in lambda_handler\n    wr.dynamodb.put_items(\n",
          "  File \"/opt/python/awswrangler/_config.py\", line 450, in wrapper\n    return function(**args)\n",

# This code is working without issue and insert records into dynamodb table 
s3_client = boto3.client('s3')
lambda_client = boto3.client('lambda')
table = dynamodb.Table("TestTbl")
 table.put_item(Item= {'pk': '34','sk':  'aws'})

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Should  insert records into dynamodb table 

### OS

aws lambda

### Python version

3.9

### AWS DataWrangler version

3.9

**Comment by jaidisido** [comment]
items in `wr.dynamodb.put_items` is expecting a list, not a dictionary

**Comment by khanvaws** [comment]
Thanks , After add List it start working 

           wr.dynamodb.put_items(
                   items=[{'pk': '35','sk': 'aws'}],
                   table_name='TestTbl'
             )
