### ISSUE TITLE
`wr.pandas.to_parquet()` overwrites existing S3 data when using different `path`

### ISSUE THREAD

**Issue by zacharylawrence** [awslabs/aws-data-wrangler#144]
Calling `wr.pandas.to_parquet()` with `path="s3://path/foo_unprocessed"` and then `path="s3://path/foo` causes the S3 bucket "foo_unprocessed" to be deleted.

If the 1st call instead writes to `path="s3://path/unprocessed_foo"` then the 2nd call with `path="s3://path/foo` will not overwrite the first.

I'm using the kwargs:
```
preserve_index=False,
mode="overwrite",
procs_cpu_bound=1,
procs_io_bound=1,
```

**Comment by igorborgest** [comment]
Thanks @zacharylawrence!

By now you should use a trailing slash in your path to avoid that.
Something like that:

`path="s3://path/foo_unprocessed/"` 
`path="s3://path/foo/"`

But of corse we can add some automatic protection against that inside the library, and we will do that on version `1.0.0`.

**Comment by zacharylawrence** [comment]
Got it! Thanks for the quick response and the consideration for a warning in version `1.0.0`.

Would you imagine that check living here?
https://github.com/awslabs/aws-data-wrangler/blob/380b8ff32fe575b2b48d669bc72da208dc34713a/awswrangler/pandas.py#L647-L665

Would you be open to a PR?

**Comment by igorborgest** [comment]
@zacharylawrence sure. A PR would be very welcome!

**Comment by igorborgest** [comment]
Hi! We will release AWS Data Wrangler 1.0.0 on `April 10` and we are collecting as much feedback as possible.

This issue should be resolved with this release. So, please test it if possible, and any feedback about the docs, the library or this specific functionality will be very welcome. 

- Install: `pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev-1.0.0`
- Docs: https://aws-data-wrangler.readthedocs.io/en/dev-1.0.0/
- Code: https://github.com/awslabs/aws-data-wrangler/tree/dev-1.0.0

**Comment by igorborgest** [comment]
Thank you for the contribution. Please, reopen the issue if it persists even after the version `1.0.0`.
