### ISSUE TITLE
Add use_column_names support for awswrangler.redshift.copy API

### ISSUE THREAD

**Issue by im-rathi** [awslabs/aws-data-wrangler#1442]
When i try to make use of awswrangler.redshift.copy API, the data which is getting inserted has wrong data in target columns., which is not expected.

I could find **'use_column_names'** argument in awswrangler.redshift.to_sql API, but i don't find it in awswrangler.redshift.copy API

it would be nice to have **'use_column_names'** in awswrangler.redshift.copy, so that the data gets inserted as expected or having list of column names to load source data fields into specific target columns.

Thanks

**Comment by kukushking** [comment]
Thanks @im-rathi, I linked the related PR
