### ISSUE TITLE
awswrangler.s3.copy_objects accept two different regions

### ISSUE THREAD

**Issue by viniciusmantegazine** [awslabs/aws-data-wrangler#1459]
I need to copy files from a source bucket on one region to another bucket on a different region.

Currently this function supports copying files to the same region, it would be interesting to have the parameter of source and target bucket.

E.g.: new parameters, boto3_session_source and boto3_session_target

**Comment by jaidisido** [comment]
I am not sure what makes you think that the method is specific to a given region or account. There is no need for two separate boto3 sessions. As long as the credentials you are using have `GetObject` permissions on the source bucket and `PutObject` on the destination, the call should succeed not matter the region or the account. An even more detailed explanation is available [here](https://stackoverflow.com/questions/56380673/how-to-copy-files-between-s3-buckets-in-2-different-accounts-using-boto3)
