### ISSUE TITLE
redshift serverless support

### ISSUE THREAD

**Issue by karim-soufi** [awslabs/aws-data-wrangler#1463]
with the general release of redshift serverless comes new functionalities that were not in classic redshift (e.g. workgroup)

will the next release support redshift serverless ?

**Comment by jaidisido** [comment]
Fair ask, I suggest we simply enable the user to pass any number of arguments to the [redshift_connector.connect](https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/__init__.py#L86) method, which would include `is_serverless`

**Comment by jaidisido** [comment]
Working on a PR, but in the meantime, you can already do this by creating your own connection instead of connecting via awswrangler:
```
import redshift_connector

# Connects to Redshift cluster using IAM credentials from default profile defined in ~/.aws/credentials
conn: redshift_connector.Connection = redshift_connector.connect(
    iam=True,
    database='',
    db_user='',
    password='',
    user='',
    cluster_identifier='',
    profile='default',
    is_serverless=True,
    serverless_acct_id='',
    serverless_work_group='',
 )
```
then use the connection in any wr.redshift method
