### ISSUE TITLE
Multiple MFA prompts w/ Active Session

### ISSUE THREAD

**Issue by sapientderek** [awslabs/aws-data-wrangler#150]
When using a profile that assumes a role requiring MFA, there is a prompt for an MFA when creating a session and when using `wr.pandas.read_sql_athena()`. Every successive `read_sql_athena` query requires an MFA.

![image](https://user-images.githubusercontent.com/51373374/77478109-d36f7900-6df3-11ea-9e49-f1387f06d931.png)

**Comment by igorborgest** [comment]
Thanks for report @sapientderek! We will work on it!

**Comment by igorborgest** [comment]
Hi! We will release AWS Data Wrangler 1.0.0 on `April 10` and we are collecting as much feedback as possible.

This issue should be resolved with this release. So, please test it if possible, and any feedback about the docs, the library or this specific functionality will be very welcome. 

- Install: `pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev-1.0.0`
- Docs: https://aws-data-wrangler.readthedocs.io/en/dev-1.0.0/
- Code: https://github.com/awslabs/aws-data-wrangler/tree/dev-1.0.0

**Comment by sapientderek** [comment]
Thank you! The new version has some great improvements!
