### ISSUE TITLE
Athena read issues (blank parquet cols; csv delimiters)

### ISSUE THREAD

**Issue by mjh7** [awslabs/aws-data-wrangler#16]
Hi again, making progress... I'm successfully using awswrangler to write Glue tables along with associated parquet or csv files in S3 now. However, having issues reading this data back with Athena.

I like parquet and haven't had problems with delimiter characters, encoding etc. before beyond having to explicitly set a few columns dtypes using pandas df.astype({'col name':'str'}) before writing to avoid mixed-type columns erroring out.

When I download and open one of the awswrangler-produced parquet files and open in pandas on my local machine, everything looks fine. However when I query the Glue table using Athena I get all the headers and rows, but the majority (not all) of the column data appears blank. Any idea what's going on here - something with datatypes or encoding, perhaps? It is reading from the exact same parquet files...

To work around, I also tried session.pandas.to_csv. When I download one of these csv files and to my local machine, I noticed fields with commas in the content are enclosed in quotes (normally I use pipe delimiters but don't see an option). Athena doesn't handle this well (and from what I have read, this kind of thing is a general pain with Athena/Presto). Do you plan to implement a "sep" parameter for the session.pandas.to_csv() function, or do you have any suggestion for what I might specify in Athena to match the csv formatting currently output by awswrangler?

Thanks again!

**Comment by igorborgest** [comment]
Hey @mjh7!

I will close this issue by inactivity. Please, open a new one if you have more issues.

**Comment by mjesbar** [comment]
Hey! for you all land here due to this issue.
¡ Rename the Glue Schema with the original parquet headers.!

**Comment by asteriske** [comment]
@mjesbar That was very helpful, thank you!
