### ISSUE TITLE
Glue table column name sanitize issue.

### ISSUE THREAD

**Issue by nitin-kakkar** [awslabs/aws-data-wrangler#161]
After upgrading to 1.0.0 version, data from source having a column name with underscore - xyz_cd is getting converted to xyz__cd. Is this expected? Previously I was using version 0.0.9 and it was working fine. Could you please check.
I am using  wr.s3.to_parquet to create glue table

**Comment by igorborgest** [comment]
Hi @nitin-kakkar, thanks for open it!

It is not expected.

On version 1.0.0 we updated the sanitization logic, probably some bug was introduced. Please help me to understand better your issue, are you sure that the original name doesn’t have any uppercase letter? Something like “xyz_Cd” ?

**Comment by nitin-kakkar** [comment]
Hi Igor, thanks for the quick reply.You are right, there are upper case in original name. Also table name sanitization has same issue. 
example column XYZ_Cd
Table Name example abc_Stck_t

**Comment by igorborgest** [comment]
Hi @nitin-kakkar. We already addressed your issue in the commit/PR above. The fix will be available in the next minor release tomorrow.

Thank you for the contribution!

**Comment by nitin-kakkar** [comment]
Thanks!!! @igorborgest . Just wanted to confirm if table name issue is resolved as well

**Comment by igorborgest** [comment]
@nitin-kakkar Yes, it was, both are the some sanitisation algorithm behind the scenes. Even so I will also add some specific tests to cover the tables names too before the release.

**Comment by igorborgest** [comment]
@nitin-kakkar fix available on version [1.0.1](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.0.1). Thanks!
