### ISSUE TITLE
Ability to load CloudWatch Logs query into Pandas

### ISSUE THREAD

**Issue by CaseyBurnsSv** [awslabs/aws-data-wrangler#17]
It would be great to have the ability to load a pandas data frame from a CloudWatch Insights Query.

**Comment by igorborgest** [comment]
Hi @CaseyBurnsSv!

Sounds like a awesome plan, I will do that!

Thank you!

**Comment by igorborgest** [comment]
Hey @CaseyBurnsSv!

I'm happy to say that we already have the support for **CloudWatch Insights Query** in the [new 0.0.1 version](https://github.com/awslabs/aws-data-wrangler/releases/tag/0.0.1).

Now you can get a Pandas Dataframe with the result:

```py3
session = awswrangler.Session()

dataframe = session.pandas.read_log_query(
    log_group_names=[LOG_GROUP_NAME],
    query="fields @timestamp, @message | sort @timestamp desc | limit 5",
)
```

Or you also can get the raw result if you prefer:

```py3
session = awswrangler.Session()

results = session.cloudwatchlogs.query(
    log_group_names=[LOG_GROUP_NAME],
    query="fields @timestamp, @message | sort @timestamp desc | limit 5",
)
```

I hope you enjoy it!

**Comment by igorborgest** [comment]
Hi @CaseyBurnsSv,

I will close this issue by inactivity. Please, open a new one if you have more issues.

**Comment by CaseyBurnsSv** [comment]
Thanks @igorborgest
