### ISSUE TITLE
data wrangler tutorial link is broken on index.rst file

### ISSUE THREAD

**Issue by rmlove** [awslabs/aws-data-wrangler#171]
**Describe the bug**
The link to the AWS Data Wrangler tutorial is broken in the file index.rst. 

Current URL: https://github.com/awslabs/aws-data-wrangler/tree/latest/tutorials
Should be this URL: https://github.com/awslabs/aws-data-wrangler/tree/master/tutorials

**To Reproduce**
Click the link on https://aws-data-wrangler.readthedocs.io/   at the bottom of the page.

**Comment by igorborgest** [comment]
Thank you very much @rmlove!

I will fix it now!

**Comment by rmlove** [comment]
Thank you Igor.   BTW, I'm an AI/ML BDM in Dallas. roblov@amazon.com
