### ISSUE TITLE
No more data_types.extract_pyarrow_schema_from_pandas

### ISSUE THREAD

**Issue by JPFrancoia** [awslabs/aws-data-wrangler#181]
I noticed that in the API for version > 1.0, the module `data_types` disappeared. Which basically means it's not possible to get the schema of a dataframe with: `data_types.extract_pyarrow_schema_from_pandas`.

This function was quite handy, I normally call it to get the schema of a dataframe (often imported from csv), before calling `wr.glue.create_table`.

`wr.glue.create_table` is now called `wr.glue.create_csv_table`, and it has a parameter `columns_types` which is the schema of the dataframe (the format of the schema changed, and is now a Dict[str, str]). But I can't generate this schema anymore, which means my custom crawlers don't work anymore.

Of course I could get this schema with pyarrow, but I was wondering if it was intentional to remove this feature, and if it would be back at some point. Ideally a function that returns the schema in the format that `columns_types`expect would be great.

Cheers

**Comment by igorborgest** [comment]
Hi @JPFrancoia!

The [catalog.extract_athena_types](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.catalog.extract_athena_types.html#awswrangler.catalog.extract_athena_types) was developed to replace the old `data_types.extract_pyarrow_schema_from_pandas`.

You can extract the `columns_types` and the `partitions_types` from your DataFrame and then create your CSV table with them.

I just added a [new tutorial](https://github.com/awslabs/aws-data-wrangler/blob/master/tutorials/12%20-%20CSV%20Crawler.ipynb) to address this case. What you think?

**Comment by JPFrancoia** [comment]
Ah perfect, sorry I missed the function in the doc. The tutorial is exactly the workflow I use. Also, the `get_table_types` function is nice, it can be used to compare the schema of previous crawler runs to the schema of the new files being crawled. Useful to detect new incoming schemas.

Once again, thanks for your help!
