### ISSUE TITLE
No more wr.s3.copy_listed_objects

### ISSUE THREAD

**Issue by JPFrancoia** [awslabs/aws-data-wrangler#186]
Hi,

The s3 submodule used to have (in version 0.3.x) a `copy_listed_objects` function that could be used like this:

```python
wr.s3.copy_listed_objects(s3_objects, in_dir, out_dir)
```

Quite handy to copy processed files from one location to another, before registering them with the catalog, for example. I'm sure there are other use cases for this.

Did I miss an equivalent function in version 1.x ? Or this feature abandoned?

**Comment by igorborgest** [comment]
Thanks a lot @JPFrancoia.

I just added the `wr.s3.copy_objects()` and a [related tutorial](https://github.com/awslabs/aws-data-wrangler/blob/s3-copy/tutorials/13%20-%20Merging%20Datasets%20on%20S3.ipynb) (*Temporary link*).

Could you check and give us some feedback, please?

**Comment by igorborgest** [comment]
Available on version [`1.0.4`](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.0.4)
