### ISSUE TITLE
Support Append mode for Glue Create Parquet Table

### ISSUE THREAD

**Issue by deathrowe** [awslabs/aws-data-wrangler#188]
It would be great if the catalog.create_parquet_table() method would not try to delete the table if it exists.

I believe adding "append" as a value for the mode param would solve this. (unless I'm misunderstanding what mode means)

**Comment by igorborgest** [comment]
@deathrowe thanks! It makes sense.

Working on that!

**Comment by igorborgest** [comment]
Available on version [`1.0.4`](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.0.4)
