### ISSUE TITLE
EMR File System (EMRFS) Integration

### ISSUE THREAD

**Issue by DenysNunes** [awslabs/aws-data-wrangler#19]
Add synchronization feature when EMRFS metastore enabled, e.g. having parquet files created by EMR and trying deletion from S3 with AWS Lambda (or local boto app).

**Comment by igorborgest** [comment]
Great idea @DenysNunes ! Let's add an optional argument for the current **S3.delete_objects** method.

**Comment by igorborgest** [comment]
Not necessary anymore 🎉 

https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/
