### ISSUE TITLE
Environment variable 

### ISSUE THREAD

**Issue by anand086** [awslabs/aws-data-wrangler#190]
**Describe the bug**
I am reading few columns of parquet files stored in S3 with aws lambda using awswrangler.s3.read_parquet, column parameter. I want to use column as environment variable in lambda but it fails. Using the same as list in the code works.

**To Reproduce**
Python - 3.8
Wrangler version - awswrangler-layer-1.0.3-py3.8.zip

In the lambda code --
  cols = ["id", "last_updated"] --> Works well, no error

But, if I pass columns as environment variable it fails.
  cols = os.environ["COLUMNS"]

In the environment variable I have tried setting in 3 ways and all fails
1. ["id", "last_updated"]
2. "id", "last_updated"
3. ("id", "last_updated")

Response:
{
  "errorMessage": "\"None of [Index(['last_updated'], dtype='object')] are in the [columns]\"",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 146, in lambda_handler\n    df = read_parquet(s3_path=s3_files, columns=cols,\n",
    "  File \"/var/task/lambda_function.py\", line 90, in read_parquet\n    df[[\"last_updated\"]] = (df[[\"last_updated\"]] -\n",
    "  File \"/opt/python/pandas/core/frame.py\", line 2806, in __getitem__\n    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]\n",
    "  File \"/opt/python/pandas/core/indexing.py\", line 1552, in _get_listlike_indexer\n    self._validate_read_indexer(\n",
    "  File \"/opt/python/pandas/core/indexing.py\", line 1640, in _validate_read_indexer\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\n"
  ]
}

**Comment by igorborgest** [comment]
Hi @anand086!

Actually [`wr.s3.read_parquet()`](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.read_parquet.html#awswrangler.s3.read_parquet) expects the `columns` argument as a list of string (*List[str]*). But when you get your environment variable, you are probably receiving a string (within a stringfied list).

It is not directly related to AWS Data Wrangler. But maybe a simpler straightforward approach would be:

1 - Set your environment variable with pure columns names separated by commas:

`id,last_updated,other_column...`

2 - Split the received variable by comma:

`columns=os.environ["COLUMNS"].split(",")`

Let me know if it help you.

**Comment by anand086** [comment]
Thank you! Yes setting the environment variable with comma separated column name worked.
