### ISSUE TITLE
read parquet file in chunksize.

### ISSUE THREAD

**Issue by parasml** [awslabs/aws-data-wrangler#192]
Hi Team,

I need to roll up my parquet files on s3 on a daily basis. My max filesize after combining smaller files to bigger parquet file should not exceed 512 MB.
Please suggest if we have a provision to chunk files by using 'read_parquet'.

Thanks,
Prashan

**Comment by igorborgest** [comment]
Hi @parasml,

I'm not sure if I understood your use case. Did you see the `chunked` argument in the [`wr.s3.read_parquet()`](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.read_parquet.html#awswrangler.s3.read_parquet) function? It should solve your issue.

What you think about it?

**Comment by parasml** [comment]
Hi @igorborgest 
Thanks for the quick reply.

I am looking chunksize: int, parameter in 'read_parquet'.
as we do have in 'read_csv' and 'read_json'.

I guess 'chunked' parameter is a boolean which loads the file into smaller chunks. but can we specify the size also there?


My Ref: 
 https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/s3.py


Regards,
Prashan

**Comment by igorborgest** [comment]
Hi @parasml, you got it.

Unfortunately, by now, there is no way to iterate efficiently over parquet files line by line, so we can't set a fixed chunk size.

**Comment by parasml** [comment]
Hi @igorborgest 

No issues, I have two lines of code to it.

Thanks for all the help.

Thanks,
Prashan

**Comment by igorborgest** [comment]
Hi @parasml ,

After some experiments, today we decided to develop an option to the `chunked` option to accept `int` and return chunks with the desired number of rows.

We added this feature to all functions related to reading Parquet files:
- `wr.s3.read_parquet`
- `wr.s3.read_parquet_table`
- `wr.athena.read_sql_query`
- `wr.athena.read_sql_table`
- `wr.db.unload_redshift`

To install the related branch:
`pip install git+https://github.com/awslabs/aws-data-wrangler.git@parquet-chunked`

Please, could you test it and give us feedback?

**Comment by igorborgest** [comment]
Available on version [1.1.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.1.0)
