### ISSUE TITLE
Add support for KMS_KEY_ID on Redshift UNLOAD

### ISSUE THREAD

**Issue by jar-no1** [awslabs/aws-data-wrangler#197]
Redshift file unload supports defining KMS_KEY_ID for UNLOAD query. "Specifies the key ID for an AWS Key Management Service (AWS KMS) key to be used to encrypt data files on Amazon S3."
* https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html

Adding support for it in Wrangler command would enable encrypting the data e.g. into another account / other KMS key.
https://github.com/awslabs/aws-data-wrangler/blob/1.0.4/awswrangler/db.py#L1072-L1082

**Comment by igorborgest** [comment]
Hi @jar-no1 ! Thanks for the suggestion above!

I added `kms_key_id`, `max_file_size` and `region` to `wr.db.unload_redshift()` and `wr.db.unload_redshift_to_files()` on our [dev branch](https://github.com/awslabs/aws-data-wrangler/tree/dev).

Could you test it and give us feedback?

To install:
`pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev`

[Development docs](https://aws-data-wrangler.readthedocs.io/en/dev/api.html)

**Comment by igorborgest** [comment]
Available on version [1.1.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.1.0)
