### ISSUE TITLE
Request for catalog.update_table

### ISSUE THREAD

**Issue by keatmin** [awslabs/aws-data-wrangler#198]
**Is your feature request related to a problem? Please describe.**
When there's a change in schema, there's no way to update-table in Glue catalog and the current best option is just create a whole new table. If using manage access control via Lake Formation, removing the table would require a reassignment of table permission

**Describe the solution you'd like**
an update_table function that could update the catalog of the existing catalog, or a 
`if_exists: str = 'update'` in create_table or create_csv_table.

**Comment by igorborgest** [comment]
Thanks @keatmin! Great ideas!

I've just replaced all "delete table" operations from the _create_table() function by an "update table" approach as suggested.

In addition I also added the new `catalog_versioning` argument to allow table versioning on Glue catalog for `overwrite` operation.

**Comment by igorborgest** [comment]
Available on version [1.1.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.1.0)
