### ISSUE TITLE
Load to aurora postgresql table using rds-data api

### ISSUE THREAD

**Issue by nagacheruvu** [awslabs/aws-data-wrangler#207]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to load data from Athena/S3 query to DataFrame and load to RDS aurora database. main problem with accessing Aurora database from lambda functions is to create VPC end link & networking. which makes our use case of loading data to database very complicated.
if we can use rds-data part of boto3 library to load dataframe to aurora sql table that would be very easy.

**Describe the solution you'd like**
if we can use wr.copy_to_aurora_table(cluster_arn, db_credentials_secrets_store_arn,databasename,tablename) with cluster_arn & db_credentials_secrets_store_arn without host & user credentials.

**Comment by igorborgest** [comment]
This feature request already is open for a while but we didn't receive any PR or had time to work on. We will close it until we had more concrete plains to evolve it.
