### ISSUE TITLE
Accepting dict or list in paths param for s3.copy_objects to rename object when copying

### ISSUE THREAD

**Issue by keatmin** [awslabs/aws-data-wrangler#215]
**Is your idea related to a problem? Please describe.**
I can make a pr for this, but it would be great to have *paths* param in s3.copy_objects to accept dict to enable renaming when copying. Particularly useful if you are extracting snapshots of a table everyday and want to rename the name of the table snapshot when you are moving it

**Describe the solution you'd like**
s3.copy_objects(paths=Union[List[str], Dict[str, str]]) 
where {"filename_to_move_1": "filename_after_copying_1" , "filename_to_move_2": "filename_after_copying_2"}

**Comment by igorborgest** [comment]
@keatmin thanks again!!!

I've just added the `replace_filenames` argument to `wr.s3.copy_objects()` to address it.

Will be released soon on version `1.1.0`!

**Comment by igorborgest** [comment]
Available on version [1.1.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.1.0)
