### ISSUE TITLE
AttributeError: module 'awswrangler' has no attribute 'Session'

### ISSUE THREAD

**Issue by sdhong** [awslabs/aws-data-wrangler#217]
I am passing in this code:

import pandas as pd
import awswrangler as wr
import boto3

boto3_session = boto3.Session(aws_access_key_id="****", aws_secret_access_key="****",region_name="*")

wr_session = wr.Session(boto3_session=boto3_session)

but am receiving this error: "AttributeError: module 'awswrangler' has no attribute 'Session." I have installed the latest version of awswrangler and then also tried to uninstall and install previous versions, but I keep running into this same error. Any ideas on what's going on?

**Comment by igorborgest** [comment]
Hi @sdhong, seems that you are confusing the Wrangler's version. We had a breaking changes after version `1.0`.

Your code snippet is compatible with versions <1.0, so to keep using it please install `pip install awswrangler==0.3.2` por example.

If you would like to move to version >=1.0, please check our [docs](https://aws-data-wrangler.readthedocs.io/en/latest/). We also have a tutorial to cover this specific [Session handling](https://github.com/awslabs/aws-data-wrangler/blob/master/tutorials/02%20-%20Sessions.ipynb).

**Comment by sdhong** [comment]
Hi @igorborgest, thank you for this! I am using the newer version, but still having some issues connecting using boto3 creds. Is this how I would be using custom sessions:
wr.s3.to_parquet(
    df=df
    path=bucket_name,
    dataset=True,
    mode="overwrite",
    partition_cols=["col"],
    boto3_session=boto3.Session(aws_access_key_id="",aws_secret_access_key="", region_name="")
)

**Comment by sdhong** [comment]
Thank you @igorborgest. The custom session handling works for me.
