### ISSUE TITLE
Support for working with Arrow tables directly

### ISSUE THREAD

**Issue by nugend** [awslabs/aws-data-wrangler#223]
**Is your feature request related to a problem? Please describe.**
AWS Data Wrangler already uses the Apache Arrow project and the Arrow in-memory format for ingestion and retrieval of data from parquet. But there does not appear to be a way to have Arrow Table objects be the types returned by various functions.

The Arrow table type is already directly usable without conversion to Pandas dataframes through the use of libraries like vaex and RAPIDS. Using the project, which makes a copy from an in-memory Arrow table, to a Pandas dataframe, only to have to copy it back to an Arrow table is very memory intensive as well as processing intensive for certain column types.

**Describe the solution you'd like**
Anywhere that a pandas dataframe is accepted as an argument, provide an Arrow Table (or at least Arrow RecordBatch). Wherever a pandas dataframe is a result, make it possible to receive an Arrow Table instead.

**Comment by igorborgest** [comment]
Thanks for reaching out!

I agree that Arrow Tables are great, but we decided to keep the library focused on the Pandas interface.
