### ISSUE TITLE
Enable AutoScaling on EMR Cluster

### ISSUE THREAD

**Issue by OElesin** [awslabs/aws-data-wrangler#225]
I must commend the maintainers of this library. This has been very useful for adhoc analysis when launching an EMR cluster.

This is not a problem but an enhancement. Would it be possible to support EMR autoscaling within this library.  This would be a nice feature to have.

**Comment by igorborgest** [comment]
This feature request already is open for a while but we didn't receive any PR or had time to work on. We will close it until we had more concrete plains to evolve it.
