### ISSUE TITLE
Make old documentation more easily available

### ISSUE THREAD

**Issue by skoschik** [awslabs/aws-data-wrangler#227]
**Is your feature request related to a problem? Please describe.**
Unless I'm missing something obvious, I can't find the older documentation anywhere.  I am not ready to upgrade to 1.x yet, I will soon.  It would be nice to have easy access to the old docs.  

**Describe the solution you'd like**
Keep links to old docs in new documentation.

**Comment by igorborgest** [comment]
Thanks for reaching out @skoschik !

Now it is available [here](https://aws-data-wrangler.readthedocs.io/en/legacy/).

**Comment by skoschik** [comment]
Thank you!
