### ISSUE TITLE
Read Json

### ISSUE THREAD

**Issue by parasml** [awslabs/aws-data-wrangler#230]
Hi @igorborgest,

I am reading json from S3 in below code.
**dfJson = wr.s3.read_json(path=jsonFile)**

jsonFile is a json format file got from Glue. 

But with above code it is not able to read it, because it has square bracket at start and end of json. Do we have a builtin solution to this, please suggest.

Reagrads,
Prashan

**Comment by igorborgest** [comment]
Yes, there is an argument `orient`  inherited from [pandas.read_json()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html).

Probably for you case it will be: `orient="records"`.

**Comment by igorborgest** [comment]
Closing by inactivity.
