### ISSUE TITLE
Custom Parquet File Name Geneartion

### ISSUE THREAD

**Issue by parasml** [awslabs/aws-data-wrangler#242]
Hi @igorborgest 

Thanks for all the help and reply in past.
Sorry, I am back with one more question.

I am writing Parquet file with below code.
**parqueFile = wr.s3.to_parquet(
            df=df
            path=targetFolder
            dataset=True)**

It gives me a parquet file with name '8eaa0fefdb724f18bce4e16b8f1a66cd.snappy.parquet'
I guess it randomly generates the file name.
Do we have a provision where we can also add a timestamp with our generated file name or can give a our own file name? Please suggest.

Regards.
Prashan

**Comment by igorborgest** [comment]
Hi @parasml !

There is absolutely no problem on it, please keep interacting.

Unfortunately, it is only possible to set the filename if dataset=False. And you should use the path argument for that, passing the whole path with the desired filename.

**Comment by parasml** [comment]
> Hi @parasml !
> 
> There is absolutely no problem on it, please keep interacting.
> 
> Unfortunately, it is only possible to set the filename if dataset=False. And you should use the path argument for that, passing the whole path with the desired filename.

Got It!
Thanks @igorborgest

**Comment by chis86** [comment]
Hi, I'm exploring this package and really like it!  However for production, we lock down any object deletions.  So I still want to use the dataset=True functionality, however provide a default filename so the objects always get overwritten on the S3 partition location (but doesn't require the access level to delete all the objects in that path first).  I noticed there is a "filename_prefix" parameter, but if possible, it would be great to set a default filename to be used for all objects stored in those partitions, e.g. simple "data", and then data.snappy.parquet in each partition location would always be updated/overwritten, when setting mode='overwrite_partitions'.  The benefit here, is we can utilize s3 versioning of objects, so we can see the changes overtime.  I understand dynamically generating a unique file/object name is probably good for Athena query performance?  But I can see a use case where keeping the objects the same name, and simply overwriting to keep object version history would be beneficial for production systems.  Please let me know your thoughts?  Many thank, Craig.
