### ISSUE TITLE
PySpark support with koalas

### ISSUE THREAD

**Issue by webysther** [awslabs/aws-data-wrangler#247]
Integration with koalas maybe make possible to use pyspark without need to change much code:

https://github.com/databricks/koalas

**Comment by igorborgest** [comment]
Hey @webysther thanks a lot for reaching out!

Unfortunately we added some PySpark features in the [legacies pre-1.0.0 versions](https://aws-data-wrangler.readthedocs.io/en/legacy/). But we detected low community engagement on these features and high maintaining time along the way. So we decided to drop it before our first major release `1.0.0` to focus on Pandas.

Probably if we decide to create new PySpark features we will prefer to create a new project. In that case Koalas will be useful indeed!
