### ISSUE TITLE
Support Spark Dataframe

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#250]
Hi guys,

Data wrangler is great, but i think in big data scenarios support spark dataframe could be better then pandas, is there any plan to support this in a near feature?

Thank you!

**Comment by igorborgest** [comment]
Hi @rubenssoto, thanks for reaching out.

Unfortunately there isn't. We added some PySpark features in the [legacies pre-1.0.0 versions](https://aws-data-wrangler.readthedocs.io/en/legacy/). But we detected low community engagement on these features and high maintaining time along the way. So we decided to drop it before our first major release `1.0.0` to focus on Pandas.

**Comment by rubenssoto** [comment]
Thank you so much for your answer, in my environment we want to use Data Wrangler in EMR, pandas dataframe could be a performance killer with big dataframe? My question is because pandas do not parallelize the process in multinode environment, is that right?

Thank you so muco!

**Comment by igorborgest** [comment]
Hi @rubenssoto,

You are right, Pandas will not scale to the infinite, it will only be a good choice if your data fits in your machine's memory. If you really have a massive dataset that requires a cluster, I recommend to use PySpark or Dask to process your data and keep the Wrangler only as an auxiliar.

**Comment by melvinev** [comment]
+1 for Dask integration!
