### ISSUE TITLE
Refactor test cases for s3 related functions 

### ISSUE THREAD

**Issue by bryanyang0528** [awslabs/aws-data-wrangler#254]
**Is your idea related to a problem? Please describe.**
`s3` is a basic component of `aws-data-wrangler`. I would like to add test cases for functions in `s3`.

**Describe the solution you'd like**
1. Refactor the scope of mock s3. The scope of the `s3` is `module` now. This will let the results of test cases have dependencies between them, so I will modify the scope of mock s3 from `module` to `function` first.

2. Add Basic test cases for public functions.

3. I'm not sure I can mock every condition or scenario of those public functions. I'll try to to it.

**Comment by igorborgest** [comment]
Nice @bryanyang0528, for sure is a important topic.

> I'm not sure I can mock every condition or scenario of those public functions. I'll try to to it.

Probably you will not be able to mock functions on the S3 module related to the Glue Catalog service not yet supported on moto. But for sure we will be good covering as much as possible.

**Comment by bryanyang0528** [comment]
> Nice @bryanyang0528, for sure it is an important topic.
> 
> > I'm not sure I can mock every condition or scenario of those public functions. I'll try to to it.
> 
> Probably you will not be able to mock functions on the S3 module related to the Glue Catalog service not yet supported on moto. But for sure we will be good covering as much as possible.

Yes, that what I'm worried about too. I think I could mock external function calls to cover basic logic first. It's much simpler and could provide basic protection.

**Comment by igorborgest** [comment]
Changes released on version [1.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.3.0)

Thanks!
