### ISSUE TITLE
s3.to_parquet crashes when writing column with array dtype

### ISSUE THREAD

**Issue by buseynehannes** [awslabs/aws-data-wrangler#263]
When writing a dataframe with numpy array columns, the s3.to_parquet function crashes when trying to cast the columns

 - When specifying dtypes, specifying dtype 'array' for the column is allowed, which causes the column to be casted to list, which is an invalid pandas datatype
 - When not specifying dtypes, dtypes are queried from the table. The glue column had type `array<string>`, this was not an allowed dtype. When changing the column type to 'array', the same problem as above appeared

To reproduce:
 - use awswrangler version 1.2.0
 - create df with numpy array as column and try to write to parquet

This worked in awswrangler 0.3.0 by casting the column explicitly to `array<string>`. Did not work anymore after updating the library.

**Comment by igorborgest** [comment]
Thanks for reaching out @buseynehannes !

Fixed in the commit above and will be available soon in the version `1.3.0`.

**Comment by igorborgest** [comment]
Changes released on version [1.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.3.0)

Thanks!

**Comment by buseynehannes** [comment]
Thanks for the fix :+1:

**Comment by igorborgest** [comment]
Hi @buseynehannes !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
