### ISSUE TITLE
Read files from s3 and keep partitions at columns

### ISSUE THREAD

**Issue by dwbelliston** [awslabs/aws-data-wrangler#265]
Files have been saved to s3 with partitions in the name of the file.

```
bucket/prefix/initiative=123/file.json
bucket/prefix/initiative=456/file.json
```

As I see it now, when using 'read_json' from 'bucket/prefix' it does not include initiative with the valueas a column in the resulting dataframe. yyyy=, mm=, dd= are more common examples of this.

**Comment by patrick-muller** [comment]
I took a look at the code, and the read and write functions (for both json and csv files) are making calls to the pandas internal functions to_csv and to_json

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

Both functions doesn't support partitions.

I made a change in the code adding a parameter to create a new column in the data frame with the file name, for example

   id name  FileName
0   1  foo  s3://bucket/test/day=01/file1.json
1   2  boo  s3://bucket/test/day=01/file1.json
2   3  bar  s3://bucket/test/day=01/file2.json

Now I can work with my dataframe, and I can do a split in the FileName column, creating a new column only with the value needed, for example
df = wr.s3.read_json(path1)
df2 = df.FileName.str.split("s3://bucket/teste/day=")
print(df2)
0    [, 01/file1.json]
1    [, 01/file1.json]
2    [, 01/file2.json]


What do you thing about this approach @igorborgest  ?

**Comment by igorborgest** [comment]
Thanks @dwbelliston @patrick-muller 

I've evolved Patrick's snippets and added support for reading partitions as column in the [commit above](https://github.com/awslabs/aws-data-wrangler/commit/58f1eb9881d345056be9c21df08cd816f27af388) (Only on development branch by now).

Could you test it and give us feedback?

To install the development version run the command bellow:

```sh
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
```

Examples:

```py
df = wr.s3.read_json("s3://bucket/dir/", dataset=True)
df = wr.s3.read_csv("s3://bucket/dir/", dataset=True)
df = wr.s3.read_fwf("s3://bucket/dir/", dataset=True)
```

**Comment by igorborgest** [comment]
Changes released on version [1.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.4.0)

Thanks!

**Comment by dwbelliston** [comment]
Just tested, works great! Thanks for the effort to put that together.

**Comment by igorborgest** [comment]
Hi @dwbelliston !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
