### ISSUE TITLE
columns_comments in s3.to_csv will not work as expected 

### ISSUE THREAD

**Issue by bryanyang0528** [awslabs/aws-data-wrangler#268]
**Describe the bug**
The comment here https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/s3.py#L684
said that dataset=False will not be able to use with these arguments: database, table, description, parameters, and columns_comments. But `columns_comments` is not a `if else` statement in this part.

**To Reproduce**
When a user called  to_csv with `dataset=False` and `columns_comment={"foo": "bar"}`, this method can run normally without any exception.

**Comment by igorborgest** [comment]
Hey @bryanyang0528 thank you one more time!

P.S.

 I've just added *black* and *isort* checks in the statical check that runs on Github Actions (commit above).
So, make sure that you run this commands before any code:
```sh
cd testing/
./validations.sh
```

**Comment by bryanyang0528** [comment]
@igorborgest  No problem, thank you!

**Comment by igorborgest** [comment]
Changes released on version [1.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.4.0)

Thanks!
