### ISSUE TITLE
Provide public Lambda Layers

### ISSUE THREAD

**Issue by jesusch** [awslabs/aws-data-wrangler#270]
Hi folks!

Great job - Getting all those dependencies into a Lambda function caused me a lot of headache before I found this project!

It would be awesome if (during release process) you could also create public available Lambda Layer ARNs 
e.g.
arn:aws:lambda:{AWS_REGION}:{AWS_ACCOUNT_ID}:layer:awswrangler-py38-130:1

**Comment by igorborgest** [comment]
Hey @jesusch ! Thanks for reaching out.

Did you saw our [release page](https://github.com/awslabs/aws-data-wrangler/releases)? We always make available lambda layers ready-to-deploy for all python compatible python versions in each new release.

We also have [more detailed instructions in the docs](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#aws-lambda-layer).

Please, let me know if you are still having problems.

**Comment by igorborgest** [comment]
@jesusch 

![image](https://user-images.githubusercontent.com/2163472/83258505-c0c74680-a18c-11ea-8e81-ef344234b059.png)

**Comment by jesusch** [comment]
yes I know that current releases provide zip files
but they have to be manually (or some homebrew CI way) have to be uploaded to AWS Lambda Layers

I'm using a framework called serverless https://www.serverless.com/framework/docs/providers/aws/guide/layers/
This would support adding public available Layers via ARN
and it would be awesome to just use those references instead of uploading them

**Comment by spencervoorend** [comment]
+1 Would be convenient and grow exposure to the project.

**Comment by igorborgest** [comment]
Thanks for reaching out!

We decided to keep the library scope more focused in support the code base itself. Support public lambda layers would mean support some kind of infrastructure too.
