### ISSUE TITLE
Read Parquet Files (Modified Date)

### ISSUE THREAD

**Issue by parasml** [awslabs/aws-data-wrangler#274]
Hi,

I need to read paquet files from S3 bucket.
I can do it from wr.read_parquet. I need a filter of file modified date. 

I mean to read files from a particular modified date/time.

Please suggest if this is possible.

Regrads,
Prashan

**Comment by patrick-muller** [comment]
Hi,
What I understand from your question is: 
do you want to read only some files from a specific folder ?

For example:

File Name  | Last Modified
------------ | -------------
s3://bucket/folder1/file1.parquet | May 30, 2020 10:47:30 PM GMT+0200
s3://bucket/folder1/file1.parquet | May 01, 2020 10:47:30 PM GMT+0200
s3://bucket/folder1/file3.parquet | Nov 30, 2029 10:47:30 PM GMT+0200

And you wants to read only the file modified > 2020 ?

**Comment by parasml** [comment]
Hi Patrick.

-do you want to read only some files from a specific folder ? YES

Scenario: My bucket folder has billion of files, I need only of a particular date time files.

Hope this helps.

Thanks,
Prashan

**Comment by patrick-muller** [comment]
Hi @parasml 
I added a feature to filter the files by last modified date.

Could you test it, and give us some feedback?

To install the development branch:

pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev

You can run these commands as example:
from datetime import datetime
import pytz

begin = datetime.strptime("05/06/20 16:30", "%d/%m/%y %H:%M")
end = datetime.strptime("10/06/20 16:30", "%d/%m/%y %H:%M")

begin_utc = pytz.utc.localize(begin)
end_utc = pytz.utc.localize(end)

dfs = wr.s3.read_parquet(path="S3 PATH", lastModified_begin=begin_utc, lastModified_end=end_utc)

**Comment by igorborgest** [comment]
Awesome job @patrick-muller!
Released on version [1.6.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.6.0)!
