### ISSUE TITLE
reading parquet in chunks without permissions won't raise an error but will end the loop just reading first chunk

### ISSUE THREAD

**Issue by alvaropc** [awslabs/aws-data-wrangler#276]
**Describe the bug**
I am currently developing a lambda that read parquet files in chunks, I tested my code and it worked in local but when running inside a lambda I saw that the code worked BUT did not iterate, It only reads like the first chunk and it finishes the loop.

**To Reproduce**
I deployed a lambda with a role just giving s3:GetObject  permission to a given path path and s3:ListBucket to the bucket.

I am already testing which permissions should my lambda have to be able to do this read operation (and I will update this issue then) but it would be nice to have some additional documentation related to the permissions needed to run each method, sometimes it is not intuitive.

Thank you!

**Comment by alvaropc** [comment]
nevermind, I slept 5 hours and after 2 hours of watching at my code I saw an error.

Anyway, it would be nice to have the permissions needed next to the method.

Thank you so much for such an amazing tool!

**Comment by igorborgest** [comment]
Thanks for reach out @alvaropc 
Please, let us know any other issue.

**Comment by igorborgest** [comment]
Hi @alvaropc !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
