### ISSUE TITLE
Installing data wrangler package using whl file in python glue job fails

### ISSUE THREAD

**Issue by sarojdongol** [awslabs/aws-data-wrangler#281]
**Describe the bug**
I trying to use data wrangler in python glue job. Unfortunately, the installation fails with the following error.

ERROR: Could not build wheels for SQLAlchemy which use PEP 517 and cannot be installed directly

**To Reproduce**
1. Download data wrangler package awswrangler-1.4.0-py3-none-any.whl and upload to s3 bucket.
2. Add python glue job with extra files option pointing to s3 "whl" file bucket location.
3. Then run the job and in a few seconds, you will get the error.
 
Docs link:
https://docs.aws.amazon.com/glue/latest/dg/add-job-python.html

Is there any solution for this issue?

**Comment by igorborgest** [comment]
Thanks @sarojdongol !

Seems that Glue Python Shell can't run `SQLAlchemy>=1.3.14` on region `ap-southeast-2` (Asia Pacific (Sydney)) yet.

So I will go back and limit the SQLAlchemy to `>=1.3.10,<1.3.14` in Wrangler's requirements.

The fix will be released in the version `1.5.0`. I will be available in some hours.

**Comment by igorborgest** [comment]
Fix released on version [1.5.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.5.0)!

**Comment by igorborgest** [comment]
Hi @sarojdongol !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
