### ISSUE TITLE
wr.athena.read_sql_query in VPCed Python 3.8 Lambda doesn't get executed

### ISSUE THREAD

**Issue by dirkgomez** [awslabs/aws-data-wrangler#286]
I've discovered the problem when upgrading from Python 3.7 Lambda to Python 3.8 Lambda.

The lambda in question is in a VPC and wr.athena.read_sql_query doesn't execute the query, it basically stalls until the lambda gets cancelled out by AWS. There's no query shown in the Athena query history.

It used to work in Python 3.7 1.1.2, it doesn't work with Python 3.8 1.1.2 or 1.5.0

Here's how I invoke the query:

>     df = wr.athena.read_sql_query(sql=query, database=database, ctas_approach=False,)

**Comment by igorborgest** [comment]
Thanks for reach out @dirkgomez!

it looks like a network issue, are you sure that your subnet has access to the internet? If not will need to add an Athena endpoint in your VPC.

![image](https://user-images.githubusercontent.com/2163472/84650940-86291200-aedf-11ea-9909-0dae43e01472.png)

Please let me know if it works.

P.S. This python/layer/wrangler versions was tested under an VPC before the release, so I'm biased to believe that is something in your environment.

**Comment by dirkgomez** [comment]
Hi Igor,

you were right, it was caused by a changed security group on the VPC endpoint...we have big accounts alas.

Thanks a lot!

Dirk

**Comment by dirkgomez** [comment]
On second thought: a warning or an error message regarding a timeout would have been convenient. Or is that a shortcoming of the Boto3 library?

Here's how to reproduce it: create an Athena VPC endpoint, close down its security group, and run a query against Athena. It'll stall till the Lambda times out.

**Comment by igorborgest** [comment]
@dirkgomez By now Wrangler inherit the [default boto3 timeout of 60 seconds](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html).

**Comment by igorborgest** [comment]
Hi @dirkgomez !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
