### ISSUE TITLE
URGENT-Service not coming up with awswrangler

### ISSUE THREAD

**Issue by vagarwal77** [awslabs/aws-data-wrangler#302]
I am using Docker based deployment on AWS EKS clusters which works fine. The moment, i had added  awswrangler library into the requirement file, my service had stopped responding without showing any error. I had tried awswrangler version 1.5.0 and 1.6.1. The moment, i remove awswrangler from requirements.txt, every thing works fine. I am able to consistently reproduce this issue. 
My docker is using debian base along with Apache. My web server is based on Django and have attached the Docker file for reference. 
[Dockerfile.TXT](https://github.com/awslabs/aws-data-wrangler/files/4843467/Dockerfile.TXT). 

I just need this library to get metadata of parquet for below. If any other library can provide this information, i would be more than happy to move to some light weight library. 
import awswrangler as wr
columns_types, partitions_types = wr.s3.read_parquet_metadata(path='s3://data-processing-bucket-01/raw_9/test_goal/', dataset=True)

astroid==2.3.3
autopep8==1.4.4
awswrangler==1.6.1
Babel==2.8.0
boto3==1.14.10
botocore==1.17.10
cachetools==3.1.1
certifi==2019.9.11
chardet==3.0.4
Django==2.2.7
django-phonenumber-field==4.0.0
dpath==2.0.1
django-webpack-loader==0.6.0
djangorestframework==3.10.3
djangorestframework-jwt==1.11.0
docutils==0.15.2
google-api-core==1.14.3
google-auth==1.7.1
google-cloud-bigquery==1.22.0
google-cloud-core==1.0.3
google-resumable-media==0.5.0
googleapis-common-protos==1.6.0
idna==2.8
isort==4.3.21
jmespath==0.9.4
lazy-object-proxy==1.4.3
mccabe==0.6.1
mod-wsgi==4.6.8
newrelic==5.2.3.131
pep8==1.7.1
phonenumbers==8.12.0
protobuf==3.10.0
psycopg2-binary==2.8.4
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycodestyle==2.5.0
PyJWT==1.7.1
pylint==2.4.4
pylint-django==2.0.12
pylint-plugin-utils==0.6
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
rope==0.14.0
rsa==4.0
s3transfer==0.3.3
six==1.13.0
sqlparse==0.3.0
typed-ast==1.4.0
urllib3==1.25.7
wrapt==1.11.2
sqlvalidator==0.0.2
numpy==1.18.2
pandas==1.0.3

**Comment by igorborgest** [comment]
Hi @vagarwal77!

1. Are your EKS cluster running into a subnet w/o internet access? If yes, you need to configure s3 and glue endpoints in your VPC (Wrangler requires network access to this services, otherwise it will be stuck trying to reach them).

2. I'm not sure how was your test. Only adding wrangler in your requirements is enough to stop your service? Or does it only happen when you ALSO add the `read_parquet_metadata` code?

3. I'm not allowed to download your attached file. Could you paste the it directly here in the chat, please?

**Comment by vagarwal77** [comment]
Thanks for the response.
#1. Yes, EKS cluster subnet don’t have internet connectivity. If we need to whitelist the urls, which one we should (pypi.org)? Please suggest.
#2. It is happening without even calling - read_parquet_metadata
#3 File below –

FROM debian:latest

# install python3 and pip3 and apache
RUN apt-get -qq update && apt-get -qq install apt-utils -y
RUN apt-get -qq install apache2 libapache2-mod-wsgi-py3 -y
RUN apt-get -qq install python3 python3-pip -y

# install nodejs
RUN apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -qq install -y nodejs

# copy whole structure [preserve git versioning for debugging]
COPY . /django/app_ph_web

# change working dir to project dir
WORKDIR /django/app_ph_web

# add apache apxs workaround for mod-wsgi
RUN pip3 install mod-wsgi-httpd

# pip3 install all requirements
RUN pip3 install -r requirements.txt

# Node and Npm Configuration
RUN npm install
RUN npm run build
RUN npm audit fix

# change working dir to root
WORKDIR /

# apache specifc configrations
COPY wsgi_prod.conf /etc/apache2/conf-available/
COPY security.conf /etc/apache2/conf-available/
COPY default-ssl.conf /etc/apache2/sites-available/
COPY 000-default.conf /etc/apache2/sites-available/
COPY sslCert-_precisionhealth_ai.* /etc/ssl/certs/phai/certs/

# do apache configuration
RUN a2enmod lbmethod_byrequests
RUN a2enmod ssl
RUN a2enconf wsgi_prod
RUN a2ensite default-ssl
RUN apachectl configtest

# expose ports on docker/kubernetes
EXPOSE 80
EXPOSE 443

**Comment by igorborgest** [comment]
@vagarwal77 

Oh, does it happening during the image build?
If you are building this docker image inside the subnet w/o internet access you will need to open the access to pypi to download the package as you said.

**Comment by vagarwal77** [comment]
No. Image build process was fine as Jenkins have internet access

When running the image in the container also show “Running” status but it is not responding.
c3-dev-pe-dev1-c97ff6869-5hwf7               1/1     Running   0          5m6s    10.164.2.17    ip-10-164-2-175.ec2.internal   <none>           <none>

Can you please suggest which IP address or uls we need to whitelisted?

**Comment by igorborgest** [comment]
I'm not sure what is happening on your environment, but I can point that S3 VPC endpoint will be required to do what you want on this private subnet w/o internet access.

**Comment by vagarwal77** [comment]
I just logged into the container Pods deployed don EKS and was able to run the code manually successfully. Hence, we can rule out the issue with connectivity.

[cid:image001.png@01D64E48.BB4FCF70]

Only thing left is – whether awswrangler library can coexist with apache server? I don’t know how to trace but have a question –

I just need to read parquet files metadata which are in S3 without loading the file into the container. As awswrangler usage multiple library internally, can you point me if I can achieve the same with any other Python library? You also must be using some other library internally?

[cid:image002.png@01D64E48.BB4FCF70]

Any help would really be of great help!!!

Thanks
-Vivek

**Comment by igorborgest** [comment]
> I just logged into the container Pods deployed don EKS and was able to run the code manually successfully. Hence, we can rule out the issue with connectivity.

Good.

> Only thing left is – whether awswrangler library can coexist with apache server? I don’t know how to trace but have a question 

I can't see any reason to block apache server and awswrangler to coexist. I'm betting that there is something else going wrong into your environment... Maybe lack of resources?

> I just need to read parquet files metadata which are in S3 without loading the file into the container. As awswrangler usage multiple library internally, can you point me if I can achieve the same with any other Python library? You also must be using some other library internally?

Sure, we count on Apache Arrow (pyarrow) to extract this metadata w/o load the entire file. [Here is](https://github.com/awslabs/aws-data-wrangler/blob/df4c00cf9cec98e4023280688300b533e1e53cad/awswrangler/s3/_read.py#L333) the exactly line of code where we are doing it.

**Comment by koiker** [comment]
I think will be a good idea to add a new section in the README to talk about requirements.
There we can describe the requirements to install aws-data-wrangler and the requirements to execute and maybe add some scenarios of running aws-data-wrangler in a private-only network with VPC endpoints, NAT gateway, etc.
This can help customers to understand how work the package and troubleshoot if they have all requirements to run.

**Comment by igorborgest** [comment]
@vagarwal77 please reopen if you find more details about some issue in the library itself.

**Comment by vagarwal77** [comment]
I have trimmed down the code and now just importing pyarrow==0.17.1 and s3fs==0.4.2 and still having same issue.
Seems like, PyArrow usages Apache2 and my deployment docker also use apache2 hence, some library incompatibility....
Any Apache expert here to help? 
or any other way to get parquet schema without using PyArrow?
