### ISSUE TITLE
What is the different between get_parquet_partitions and get_csv_partitions?

### ISSUE THREAD

**Issue by bryanyang0528** [awslabs/aws-data-wrangler#305]
I saw that there are two functions called `get_csv_partitions` and `get_parquet_partitions` in `catalog.py`. and they both called `_get_partitions` for getting partitions and didn't do anything else in each method. For simplifying the usage of `get_parition`, is this a good idea to add a new method called `get_parition`?

**Comment by igorborgest** [comment]
Hi @bryanyang0528!

Yeah, simply `get_partitions` would be better, it stills segregated due historical reasons.
I don't think it a good idea remove the existing functions, even though with this redundancy.
But for sure would be great have this third generic function. I like it!

**Comment by bryanyang0528** [comment]
@igorborgest no problem. Would you mind assign this task to me? I'll commit the first version of this function in two days.

**Comment by igorborgest** [comment]
Thank @bryanyang0528!

Converting this issue into an `enhancement`. The plan is release it in the version `1.7.0` next week.

**Comment by igorborgest** [comment]
Released on version [1.6.3](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.6.3).
