### ISSUE TITLE
allow connect_args to be passed when creating an SQL engine from a glue connection

### ISSUE THREAD

**Issue by jasadams** [awslabs/aws-data-wrangler#309]
To increase the statement timeout on postgres, I need to pass arguments to sqlalchemy to allow queries to run for a longer time before timing out:
`engine = sqlalchemy.create_engine(pg_conn_string, connect_args={"options": "-c statement_timeout=900s"})`
It would be good to allow this option for for awswranger 
`engine = wr.catalog.get_engine(connection='rds-connection-name', connect_args={"options": "-c statement_timeout=900s"})`

also your docs are incorrect for the above statement, instead of `connection=` it reads `name=` in the example

**Comment by igorborgest** [comment]
Thank you @jasadams!

I've just implemented the enhancement in the commit above. The intention is to release it in the next version `1.7.0`.

Could you test our dev branch and check if it addresses your use case before the official release?

```
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
```

**Comment by jasadams** [comment]
I tested your new branch by executing
```shell
pip uninstall awswrangler
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
Successfully installed awswrangler-1.6.3
```

I then ran the following code
```python
import awswrangler as wr
import sqlalchemy

engine = wr.catalog.get_engine(connection='rds-db_name', connect_args={"options": "-c statement_timeout=900s"})
engine_2 = sqlalchemy.create_engine("postgresql+psycopg2://user:password@db.t2.small.rds.amazonaws.com:5432/db_name", connect_args={"options": "-c statement_timeout=900s"})

table_name = "game_result_history"
try:
    print("starting df_1")
    start_time = datetime.now()
    df_1 = wr.db.read_sql_table(table_name, engine)
    print(f"df_1 row count: {len(df_1.index)}")
except Exception as e:
    print(f"Error: {e}")
finally:
    print(f"df_1 query time: {(datetime.now() - start_time).seconds}s")

try:
    print("starting df_2")
    start_time = datetime.now()
    df_2 = wr.db.read_sql_table(table_name, engine_2)
    print(f"df_2 row count: {len(df_2.index)}")
except Exception as e:
    print(f"Error: {e}")
finally:
    print(f"df_2 query time: {(datetime.now() - start_time).seconds}s")
```
and got the following output
```shell
starting df_1
Error: (psycopg2.errors.QueryCanceled) canceling statement due to statement timeout

[SQL: SELECT * FROM game_result_history]
(Background on this error at: http://sqlalche.me/e/e3q8)
df_1 query time: 34s
starting df_2
df_2 row count: 1374715
df_2 query time: 174s
```
so it appears this does not work for my use case unless I am doing something wrong

**Comment by igorborgest** [comment]
@jasadams thanks a lot for your quick response and great test report.

I was able to find where was the problem and I also added a test case to cover your usage.

Do you mind to test it again?

**Comment by jasadams** [comment]
looks good
```
starting df_1
df_1 row count: 1374715
df_1 query time: 200s
starting df_2
df_2 row count: 1374715
df_2 query time: 199s
```

**Comment by igorborgest** [comment]
Hi @jasadams !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
