### ISSUE TITLE
Support for Async Redshift queries

### ISSUE THREAD

**Issue by dryst0** [awslabs/aws-data-wrangler#314]
**Is your feature request related to a problem? Please describe.**
We have created a bunch of APIs that makes use of an Async Web Framework, GraphQL, and AWS Redshift. We were having a particular problem about making our resolvers to execute in parallel because the underlying SQLAlchemy engine was based on psycopg2 which is a synchronous DB driver.

**Describe the solution you'd like**
An inclusion of Async DB driver/s (e.g. asyncpg)for AWS Redshift as an option when creating an engine.

**Comment by igorborgest** [comment]
We rely on the [official Redshift driver](https://github.com/aws/amazon-redshift-python-driver) to handle Redshift connections. And how it is not async, we will not support it.

Thanks!
