### ISSUE TITLE
Converting jsonLines file into parquet

### ISSUE THREAD

**Issue by edvorkin** [awslabs/aws-data-wrangler#319]
I am writing log files in jsonlines format into s3 bucket. I was able to load it into panda dataframe:
`df=wr.s3.read_json(path, lines=True)`
then if I save it back 
`wr.s3.to_parquet(
    df=df,
    path=path2,
    dataset=True,
    mode="append"
)`
I am receiving error 
`ArrowTypeError: Expected a bytes object, got a 'dict' object`

If I modify my code and do 
`for df in wr.s3.read_json(path, lines=True, chunksize=1):
     wr.s3.to_parquet(
     df=df,
     path=path2,
     dataset=True,
     mode="append"
)`

The code worked, but then I am getting one file for each log entry. This is very slow and not efficient. How can I read jsonlines file and write it to parquet?

**Comment by igorborgest** [comment]
Hi @edvorkin,

Seems that your JSON file has mixed data types for the same attribute name. Pandas will accept it using the `object` column that supports anything, but it will not fit on parquet files that requires real data types.

Could you check it please? 

Also, could you send a sample of your JSON file structure here in the chat (don't sent attachments)?

*P.S. Please, replace the atribute names, values and any other sensitive information, only the structure itself is relevant.*

**Comment by edvorkin** [comment]
Hi @igorborgest ,
Thanks for prompt reply. 
Here is one of the json structure:
`{
    "tags": [
        "cleaned"
    ],
    "sessionId": "c59-fbf8-4c5f-9e9d-0bd01ffe7d8c",
    "containerId": "ui-web-api-gateway-798895-v57vg",
    "message": "Response time before serialization: 0.060591ms",
    "traceId": "4167e1af-08d3-4158-89e3-availability",
    "program": "ui-web-api-gateway",
    "image.tag": "ui-web-api-gateway:1.1.0-0169-ac061d51",
    "type": "test_log",
    "clientId": "10857fb-4d3f-8c50-d506e5fa59e8",
    "associateId": "6f-830a-4c7f-b8a4-7d02d562f42d",
    "workstream": "ui",
    "image.name": "ui-web-api-gateway",
    "host_name": "ip-1056-7.ec2.internal",
    "image.version": "1.1.0-0169-ac061d51",
    "env": "test",
    "startTime": 1594673282574,
    "@timestamp": "2020-07-13T20:48:02.600Z",
    "path": "auth/check",
    "image.owner": "test",
    "level": "info",
    "spanId": "88771d5a-ff1b-4d50-b88b-6bb7410edaf7"
}`
I don't think I have a mixed data types.

**Comment by igorborgest** [comment]
@edvorkin I've just tested here against a JSON file with 10x your sample (One by line) and everything worked.

My code:

```py3
import awswrangler as wr

df = wr.s3.read_json(path=PATH, orient="record", lines=True)
wr.s3.to_parquet(df=df, path=PATH2, dataset=True, mode="append")
```

1 - Could you also try with `orient="record"`?
2 - Was my emulation correct?

**Comment by edvorkin** [comment]
@igorborgest after further inspection I discover that you are right, some fields with the same name have different data types. That how I got the exception. Thanks for your help.

**Comment by edvorkin** [comment]
is there I way to enforce some schema from the catalog and reject non-compliant records?

**Comment by igorborgest** [comment]
> is there I way to enforce some schema from the catalog and reject non-compliant records?

Yes there is, using the [`dtype`](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) argument:

*dtype (Dict[str, str], optional) – Dictionary of columns names and Athena/Glue types to be casted. Useful when you have columns with undetermined or mixed data types. (e.g. {‘col name’: ‘bigint’, ‘col2 name’: ‘int’})*
