### ISSUE TITLE
How is the lambda layer size achieved?

### ISSUE THREAD

**Issue by m1nde** [awslabs/aws-data-wrangler#320]
Hi! I was trying to get AWS wrangler to run inside my lambda, and I failed because of the size of its dependency tree. pyarrow, numpy and pandas are almost at 350MB unzipped, which is over the 250MB limit of lambda functions (including layers).

Then I saw that you are publishing pre-built zip files that we can upload as a Lambda layer, and they are only 42MB, and 150MB unzipped. How are you achieving this? Looking at the content of the zip file, I see that you managed to greatly reduce the footprint of pyarrow and numpy: 

<img width="388" alt="Screenshot 2020-07-14 at 10 30 32" src="https://user-images.githubusercontent.com/12549786/87404856-f8fcda00-c5be-11ea-8291-78ed749d2aa0.png">

Can someone explain to me how to do this, so I can use this trick in the future?

**Comment by monken** [comment]
The build pipeline can be found here https://github.com/awslabs/aws-data-wrangler/blob/master/building/lambda/build-lambda-layer.sh

**Comment by igorborgest** [comment]
Hi @m1nde thanks for reaching out!

@monken was directly to the point, we resolve everything in the referenced script.

We basically compile PyArrow from source removing several optional components to and leaving only what matters for Wrangler.

**Comment by igorborgest** [comment]
Hi @m1nde @monken !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .

**Comment by AlecVivian** [comment]
> Hi @m1nde @monken !
> 
> It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .

What ever happened to this link? I love this library and want to learn deployment best practices with it :)

**Comment by LeonLuttenberger** [comment]
Hey,

You can find the list [here](https://github.com/aws/aws-sdk-pandas#who-uses-aws-sdk-for-pandas).
