### ISSUE TITLE
support pyarrow 1.0

### ISSUE THREAD

**Issue by davidszotten** [awslabs/aws-data-wrangler#337]
[Pyarrow 1.0](https://arrow.apache.org/blog/2020/07/24/1.0.0-release/) is out. It would be nice to support it. (One of the changes i'm interested is the reduced size of the installed package, which for me has gone from 147Mb to 38Mb)

**Comment by igorborgest** [comment]
Thanks @davidszotten! For sure it will be a good improvement.

I've already added it to our development branch. Do you mind to test it?
The ideia is release it in the next version `1.7.0` this week.

```sh
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
```

**Comment by davidszotten** [comment]
thanks! seems to work for me (though i guess i have a fairly basic use-case at the moment)

**Comment by davidszotten** [comment]
maybe i'm just missing it, but is there a changelog anywhere where i can see what else is changing between versions?

**Comment by igorborgest** [comment]
@davidszotten thanks for test it.

Yep, we keep changes tracked in our [releases](https://github.com/awslabs/aws-data-wrangler/releases) page.

Btw, why are you worrying with PyArrow size? Do you know that we have pre-built lambda layers with it, right?

**Comment by davidszotten** [comment]
thanks. (though i guess that means i can't see changes for the next unreleased version, right?)

i'm using it from an app i run in docker

**Comment by igorborgest** [comment]
> i'm using it from an app i run in docker

I see.

> though i guess that means i can't see changes for the next unreleased version, right?

No, sorry. I will try to address this "roadmap visibility".

**Comment by igorborgest** [comment]
Released in [1.7.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.7.0)!

**Comment by davidszotten** [comment]
Thanks!

**Comment by igorborgest** [comment]
Hi @davidszotten  !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
