### ISSUE TITLE
Add table properties for athena create csv

### ISSUE THREAD

**Issue by kylepierce** [awslabs/aws-data-wrangler#338]
**Is your idea related to a problem? Please describe.**
I am trying to automate my athena table creation for multiple environments. CSV are loaded into s3 unedited. When I create the table with the UI it detects a header row. With this package it doesnt. 

**Describe the solution you'd like**
Add TBLPROPERTIES like `skip.header.line.count"="1` to create_csv_table

**Comment by igorborgest** [comment]
Hi @kylepierce, thank you for reach out.

Could you paste here the code snippet where you are trying do create it?

**Comment by kylepierce** [comment]
I dont see it in the [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_table) so maybe its not supported at the moment.

Ideally it would be a dict that can accept other table properties. (last line)

`wr.catalog.create_csv_table(
    database='lake',
    table='table',
    path='path',
    columns_types=data,
    compression='gzip',
    description='My own table!',
    parameters={'source': 'postgresql'},
    table_properties={'skip.header.line.count': "1"}
)`

**Comment by kylepierce** [comment]
data refrences a dict 

`{
    "name": "varchar(100)",	
    "clicks": "bigint",	
    "sum": "double"
}`

**Comment by igorborgest** [comment]
@kylepierce!

I've already added the `skip_header_line_count` as a new argument to our development branch. Do you mind to test it?
The ideia is release it in the next version `1.7.0` this week.

```sh
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
```

_P.S. For details see the [related commit](https://github.com/awslabs/aws-data-wrangler/issues/338).
P.P.S. For the documentation related to the development branch [see](https://aws-data-wrangler.readthedocs.io/en/dev/stubs/awswrangler.catalog.create_csv_table.html#awswrangler.catalog.create_csv_table).
P.P.P.S By now it only support the [LazySimpleSerDe](https://docs.aws.amazon.com/athena/latest/ug/lazy-simple-serde.html) (And not the [OpenCSVSerDe](https://docs.aws.amazon.com/athena/latest/ug/csv-serde.html)), so quoted values will work._

**Comment by kylepierce** [comment]
Wow thanks! Works as a test.

**Comment by kylepierce** [comment]
Looking at your P.P.P.S is there any way to specify which SerDe I want to use or because it is a csv I am locked into "LazySimpleSerDe"? 


I have a table that has every value quoted. I see that one of the parameters is "areColumnsQuoted" and that marked false as default. 


Maybe I am trying to use this package too much and should look at just using DDL creation directly.

**Comment by igorborgest** [comment]
Released in [1.7.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.7.0)!

**Comment by igorborgest** [comment]
@kylepierce about the OpenCSVSerDe support, if you still want it, could you please open a separated issue for that?

**Comment by igorborgest** [comment]
Hi @kylepierce !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
