### ISSUE TITLE
Getting error ResourceNumberLimitExceededException) when calling the UpdateTable operation: Number of TABLE_VERSION resources exceeds the limit 100000 per TABLE

### ISSUE THREAD

**Issue by edvorkin** [awslabs/aws-data-wrangler#342]
*P.S. Don't attach file. Please, prefer add code snippets directly in the message body.*
I have the following code:
`wr.s3.to_parquet(df=df, 
                path=destination_path, 
                dtype=types, 
                dataset=True, 
                database=DATABASE,
                table=TABLE,
                mode="append",
                catalog_versioning=False,
                partition_cols=['env','year','month','day','hour'])`
I am executing this on S3 event when data file created in s3.  At some point I got error "(ResourceNumberLimitExceededException) when calling the UpdateTable operation: Number of TABLE_VERSION resources exceeds the limit 100000 per TABLE" . Is there any way not to update table version? The table stay the same, only partitions are added with new data.

**Comment by igorborgest** [comment]
Hi @edvorkin! Are you using what version?

**Comment by edvorkin** [comment]
@igorborgest I am using `pip install awswrangler` without specifying any version. I see in the path it is awswrangler-1.7.0.dist-info.

**Comment by igorborgest** [comment]
Hi @edvorkin!

 I've just fixed it in the `dev` branch. Could you please test it before the official release?
The ideia is publish the fix in the version `1.8.0` this weekend.

```sh
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
```

**Comment by edvorkin** [comment]
Ok. Great I will test today.

**Comment by edvorkin** [comment]
@igorborgest tested. It does not throw the exception any more. Thanks

**Comment by igorborgest** [comment]
Thank you @edvorkin, it will be released on Sunday.

**Comment by igorborgest** [comment]
Hi @edvorkin !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .

**Comment by igorborgest** [comment]
Released on version [1.8.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.8.0).

**Comment by janpio** [comment]
For anyone else finding this issue years later:

This error message is related to a limit in AWS Glue called `Max table versions per table`. It doesn't seem to be documented anywhere, but fortunately is listed on the Service Quotas page and you can request an increase: https://us-east-1.console.aws.amazon.com/servicequotas/home/services/glue/quotas/L-071ABE08 It seems to be one of those quotas that can easily increased 10x in seconds 👍

**Comment by Gatsby-Lee** [comment]
@janpio thank you!!
