### ISSUE TITLE
Duplicated column error in S3.to_parquet using overwrite_partitions

### ISSUE THREAD

**Issue by larrylayne** [awslabs/aws-data-wrangler#355]
I am trying to update a parquet file in a lambda function using `s3.to_parquet`. The function creates the update file by appending a new Pandas dataframe with a Pandas dataframe created from the original parquet file. I am receiving the following error: `"errorMessage": "There is duplicated column names in your DataFrame` when I finally call `s3.to_parquet` on the appended dataframe. The original parquet file was also created with `s3.to_parquet`. 

The code that checks for duplicate columns in the `s3.to_parquet` function (`_utils.check_duplicated_columns`) produces an empty list when I run the same code on my dataframe manually prior to running the `s3.to_parquet` line. I am not certain why I am getting this error when I don't believe my code is producing duplicate columns. Do you have any ideas as to why this is the case? Thanks!

`wr.s3.to_parquet(df=parquet_df,
                            path=path,
                            dtype=dtype_dict,
                            compression='snappy',
                            dataset=True,
                            mode='overwrite_partitions',
                            partition_cols=['mls_name'])`

**Comment by igorborgest** [comment]
Hi @larrylayne, thanks for reach out!

You are in the right way troubleshooting it!
I think the only missing piece it that `s3.to_parquet()` [sanitises](https://github.com/awslabs/aws-data-wrangler/blob/e13319fd5fdfa31b1545a53acb6d0d38f1bdbd8e/awswrangler/s3/_write_parquet.py#L425) your DataFrame before the duplicated columns check.

This sanitisation is necessary to convert your columns names to `lower case/ snake case` and also remove special characters. It it a good practice enforced to make everything compatible with Amazon Athena and others engines.

My guess is that probably you have two columns with distinct names that became igual after the sanitisation.
e.g. `["ColA", "colA"] -> ["col_a", "col_a"]`.

Please, apply [this private function](https://github.com/awslabs/aws-data-wrangler/blob/e13319fd5fdfa31b1545a53acb6d0d38f1bdbd8e/awswrangler/s3/_write.py#L68) before the check if you would like to confirm it.

And if my guess is right, you will only need to rename your columns keeping in mind that it will be converted to lower case.

What do you think?

**Comment by larrylayne** [comment]
Yes, this was helpful. The function you linked still gave me an error that was hard to decipher without further digging, but it led me to `catalog._utils.sanitize_dataframe_columns_names`.  I found out that the issue was further upstream with my append. I forgot that the `to_parquet` function converts all columns to lowercase and I was trying to append the lower case columns with capitalized columns. This caused the duplicated columns that triggered the error when calling `to_parquet`. 

Thank you for your help!
