### ISSUE TITLE
SQL server support

### ISSUE THREAD

**Issue by gtossou** [awslabs/aws-data-wrangler#356]
**Get Sql server RDS connection and retrieve data**

I'm interested in aws data  wrangler for interacting with SQL Server RDS. Doo you plan to release methods for connection and data retrieval ?

**Comment by maxispeicher** [comment]
I will try to create a PR for this the next days 👍

**Comment by igorborgest** [comment]
Released on version [2.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.3.0) 🚀
