### ISSUE TITLE
partition_filter in read_parquet

### ISSUE THREAD

**Issue by parasml** [awslabs/aws-data-wrangler#357]
Hi Team,

I implemented the below code.

import awswrangler as wr
my_filter = lambda x: True if x["city"].startswith("new") else False
df = wr.s3.read_parquet(path, dataset=True, partition_filter=my_filter)

It gives me below error.
TypeError: read_parquet() got an unexpected keyword argument 'partition_filter'

Please suggest on this.

Regards,
Prashan

**Comment by igorborgest** [comment]
Closing by inactivity.
