### ISSUE TITLE
No longer works on AWS Glue Python shell job

### ISSUE THREAD

**Issue by mkwatson** [awslabs/aws-data-wrangler#361]
**Describe the bug**

Starting on 8/22/20, I started seeing the following exception when using aws-data-wrangler from a Python shell Glue job:

```
 File "/glue/lib/installation/awswrangler/__init__.py", line 10, in <module>
    from awswrangler import athena, catalog, cloudwatch, db, emr, exceptions, quicksight, s3, sts  # noqa
  File "/glue/lib/installation/awswrangler/athena/__init__.py", line 3, in <module>
    from awswrangler.athena._read import read_sql_query, read_sql_table  # noqa
  File "/glue/lib/installation/awswrangler/athena/_read.py", line 14, in <module>
    from awswrangler import _utils, catalog, exceptions, s3
  File "/glue/lib/installation/awswrangler/_utils.py", line 16, in <module>
    import s3fs  # type: ignore
  File "/glue/lib/installation/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/glue/lib/installation/s3fs/core.py", line 14, in <module>
    import aiobotocore
  File "/glue/lib/installation/aiobotocore/__init__.py", line 1, in <module>
    from .session import get_session, AioSession
  File "/glue/lib/installation/aiobotocore/session.py", line 11, in <module>
    from .credentials import create_credential_resolver, AioCredentials
  File "/glue/lib/installation/aiobotocore/credentials.py", line 15, in <module>
    from botocore.credentials import EnvProvider, Credentials, RefreshableCredentials, \
ImportError: cannot import name '_get_client_creator'
```

**To Reproduce**

Using `awswrangler-1.8.1-py3-none-any.whl`

```python
import awswrangler as wr
```

**Comment by igorborgest** [comment]
Hi @mkwatson, Thanks for reaching out!

This error seems to be related with the last major update on [s3fs](https://pypi.org/project/s3fs/#history) on 8/21/20 (one of Wrangler's dependencies).

But Wrangler [keeps all dependencies versions pinned](https://github.com/awslabs/aws-data-wrangler/blob/c6e4ff0746817ab38d4a26ac792e36281ff6cc08/requirements.txt#L10) on fixed versions and only allows micro updates related to bug fix and w/o breaking changes. And it extends to our Glue artefacts (whl/egg).

So if you are using `awswrangler-1.8.1-py3-none-any.whl` it should install `s3fs==0.4.2` and not `5.0.0` (The new version that you probably have there).

Just to double check we've run several tests here on Glue and we were not able to reproduce your issue.

- Do you have others dependencies that relies on `s3fs`?
- Could you check your logs on Glue to see what version of `s3fs` are being installed?

It should be something like:


> Successfully installed SQLAlchemy-1.3.19 awswrangler-1.8.1 boto3-1.14.48 botocore-1.17.48 docutils-0.15.2 fsspec-0.8.0 jmespath-0.10.0 numpy-1.19.1 packaging-20.4 pandas-1.1.1 psycopg2-binary-2.8.5 pyarrow-1.0.1 pymysql-0.10.0 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 **s3fs-0.4.2** s3transfer-0.3.3 six-1.15.0 sqlalchemy-redshift-0.8.1 urllib3-1.25.10

**Comment by mkwatson** [comment]
@igorborgest thanks for addressing this so quickly. My library that uses datawrangler, in fact, did have an unpinned version of s3fs listed under install_requires. I resolved that and all seems to be working now! Thanks so much!
