### ISSUE TITLE
'S3' object has no attribute '__aenter__'

### ISSUE THREAD

**Issue by chrisrana** [awslabs/aws-data-wrangler#368]
**Describe the bug**
I have docker application with FROM python:3.7-slim
python version 3.6
I am running aws batch job to write parquet file

> import awswrangler as wr
> wr.s3.to_parquet(
>                 partition_cols=partition_col,
>                 df=df,
>                 path=s3_write_path,
>                 dataset=True
>             )
> 

**To Reproduce**
Steps to reproduce the behavior. Also add details about Python and Wrangler's version and how the library was installed.

*P.S. Don't attach file. Please, prefer add code snippets directly in the message body.*

**Comment by igorborgest** [comment]
Hi @chrisrana ,

This error seems to be related with the last major update on [s3fs](https://pypi.org/project/s3fs/#history) on 8/21/20 (one of Wrangler's dependencies).

Wrangler [keeps all dependencies versions pinned](https://github.com/awslabs/aws-data-wrangler/blob/c6e4ff0746817ab38d4a26ac792e36281ff6cc08/requirements.txt#L10) on fixed versions and only allows micro updates related to bug fix and w/o breaking changes.

So it must install `s3fs==0.4.2` and not `5.0.0` (The new version that you probably have there).

- Could you check which `s3fs` version are being installed?
- Do you have others dependencies that relies on `s3fs`? Are they with pinned versions?

**Comment by chrisrana** [comment]
Should I try older version ? let me me know stable version 

I am doing this in my docker container.
pip install awswrangler==1.8.1 
I see version as s3fs-0.4.2-py3-none-any.whl

pip install awswrangler==1.8.1 -t . 

Collecting awswrangler==1.8.1
  Using cached https://files.pythonhosted.org/packages/b7/1c/c76487c0dd3fe6e81aecc7ed8f6c06f9675424f85b3d1cca66a629f4689e/awswrangler-1.8.1-py3-none-any.whl
Collecting s3fs==0.4.2
  Using cached https://files.pythonhosted.org/packages/b8/e4/b8fc59248399d2482b39340ec9be4bb2493846ac23641b43115a7e5cd675/s3fs-0.4.2-py3-none-any.whl
Collecting pyarrow~=1.0.0
  Downloading https://files.pythonhosted.org/packages/00/f4/bb3c40a80539c444871cf4f63e3c5d6fdeb9a25025ff525a2ccf6ffda059/pyarrow-1.0.1-cp36-cp36m-win_amd64.whl (10.5MB)
Collecting pymysql<0.11.0,>=0.9.0
  Using cached https://files.pythonhosted.org/packages/2c/57/af502e0e113f139b3f3add4f1efba899a730a365d2264d476e85b9591da5/PyMySQL-0.10.0-py2.py3-none-any.whl
Collecting botocore<2.0.0,>=1.15.49
  Downloading https://files.pythonhosted.org/packages/49/d7/8a7f3cf2fe32e9d33f0cb8548c3e83d68bc453b714850ee03d2606be5370/botocore-1.17.50-py2.py3-none-any.whl (6.6MB)
Collecting pandas<1.2.0,>=1.0.0
  Downloading https://files.pythonhosted.org/packages/73/0f/8757a2da3538a5f5c2bb6764056f08940146bb70ab40dff836aa46e8d7bf/pandas-1.1.1-cp36-cp36m-win_amd64.whl (9.4MB)
Collecting SQLAlchemy~=1.3.10
  Downloading https://files.pythonhosted.org/packages/da/15/84911003b3babe87193a2654ba561317a50951190d5626df7f7f141fe0f7/SQLAlchemy-1.3.19-cp36-cp36m-win_amd64.whl (1.2MB)
Collecting sqlalchemy-redshift<0.9.0,>=0.7.0
  Using cached https://files.pythonhosted.org/packages/34/51/13b5422cfc08bee0d2aee1bb782fbc13e94fb204022838f371e513aa20dc/sqlalchemy_redshift-0.8.1-py2.py3-none-any.whl
Collecting psycopg2-binary~=2.8.0
  Using cached https://files.pythonhosted.org/packages/6f/5d/9e69ffac34f791d5b69d9f351e042544ccdfdbbce38802c4e66b2cdf9105/psycopg2_binary-2.8.5-cp36-cp36m-win_amd64.whl
Collecting numpy<1.20.0,>=1.18.0
  Using cached https://files.pythonhosted.org/packages/05/1d/d7b100264346a8722325987f10061b66d3c560bfb292f2c0254736e7531e/numpy-1.19.1-cp36-cp36m-win_amd64.whl

**Comment by igorborgest** [comment]
The version `1.8.1` is stable. Are you sure that you don't have other libraries that also install `s3fs`?
Btw, could you paste here a more detailed traceback from your error please?

**Comment by chrisrana** [comment]
@igorborgest you are right...it somehow mixed up with s3fs 5.0.0....There was one more pip install happening for s3fs separately ..
Now I removed the dependency, i get passed the issue but aws batch is getting stuck in below line  and is not moving...
This issue is resolved i facing wr.s3.to_parquet(
                partition_cols=partition_col,
                df=df,
                path=s3_write_path,
                dataset=True
            )
any pointer on this will be helpful....is s3fs behave differently while calling from batch job i.e docker container...
same code works fine in lambda.

**Comment by igorborgest** [comment]
We have several use cases running on docker and also AWS Batch.

My **guess** is that you probably have a networking issue.
Are your instances running on private/isolated subnets? If you are running w/o internet access you will need to setup a S3 Endpoint in your VPC.
