### ISSUE TITLE
wr.s3.to_parquet to support more 'mode' other than append , overwrite, overwrite_partitions

### ISSUE THREAD

**Issue by xxsacxx** [awslabs/aws-data-wrangler#369]
**Is your idea related to a problem? Please describe.**
We have a batch process to sync operational data to s3 which runs daily and put data(.csv) in raw bucket 
for example : for partners data it is like : `raw/partners/landing/2020-08-29.csv` which after all preprocessing goes to staging bucket(converted into parquet and partitioned on year-month-partner) . I am using wr.s3.to_parquet for that
 ```
wr.s3.to_parquet(df = data, 
             path = self.staging_path, 
            dataset=True,
             partition_cols=["year","month","partner"],
             boto3_session = self.session,
             index=False,
            regular_partitions=True,
            mode='overwrite_partitions',
            database='staging',
            table='partners',
            );
```
where data looks like : 
```
year | month | partner | emp_id | created_at|........|
-- | -- | -- | -- | --
2019 | 1 | xxx | 123 | 2020-08-20....
2020 | 2 | yyy | 234 | 2020-08-20....
2020 | 3 | zzz | 345 | 2020-08-20....
```
Now the problem with this is if any old_files collides with the new data I have to remove old file's duplicated data in raw bucket and make changes in the partitions of the staging bucket but any  'mode' at best will remove all the files in month instead of just removing the particular date file. For example :
`raw/partners/landing/` :  _has 3 csv files created on 1,2,3 dates respectively now when 4th day new file comes there are few duplicates exist in 1,2 file which is deduplicated and replaced now when the partioning-parquet scripts runs for them 

`staging/partners/year=2020/month=8` it will replace whole month=8 data instead of just replacing respective 1,2 files.
The solution to this I am able to figure out is to have `partner-year-month-day` partition columns but as most of the  queries  needs granularity till month avoid 'day'   partitions but I feel this is not an optimal solution.So , open for suggestion.

**Describe the solution you'd like**
If there is some way where we have control of till what stage we can delete the files so like in this case instead of deleting whole month's data just delete that particular data or something similar.

*P.S. Don't attach file. Please, prefer add code snippets directly in the message body.*

**Comment by igorborgest** [comment]
Hi @xxsacxx, thanks for reaching out!

Unfortunately I can't think in a good way to solve it with new `mode`. (New ideas are welcome!)

But we often solve it using the existing `modes` and changing the architecture/strategy a little bit.

**E.g.**

Decouple the updatable layer from the query layer.

* Keep files partitioned by the most granular updatable level in an intermediate layer. (**partner-year-month-day** in your case.)
* Create a new ETL to consolidate the previous layer into a new one less fragment for queries (**partner-year-month** in your case).
  This new logic can be created based in several different approaches like:

  - Overwrite in the final layer only the last months that could be updated. (Depends on the source behaviour)
  - Recreate the final layer entire from scratch everyday. (Don't need to be done all at once, you can do it batching month-by-month for example.)
  - List only the files that was recent created in the updatable layer to get all days and months that must be overwrite (`overwrite_partitions`) in the final layer. *P.S. The filter of new files could be done through using the `argument last_modified_begin` in `wr.s3.list_objects`.*
