### ISSUE TITLE
Ability to query redshift into dataframe

### ISSUE THREAD

**Issue by robertaves** [awslabs/aws-data-wrangler#37]
i have a use case where querying redshift into a dataframe would be a good addition. Any ideas if this is possible?

**Comment by igorborgest** [comment]
Hey @robertaves, this is one of the most wanted features!

We are waiting for the "UNLOAD to Parquet" feature release on the Redshift service.
Of course we can do with CSV or JDBC, but we would like to wait for Parquet that will be the best approach.

**Comment by robertaves** [comment]
looks to be available now..

https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html

**Comment by igorborgest** [comment]
Hi @robertaves, you are right!

And I'm already working on that, take a look in the snippet of code that I [committed yesterday](https://github.com/awslabs/aws-data-wrangler/commit/9903c9e3f60ad32c5e044d394e8d109556697379)!

Of course that stills a lot of work to do, so I will keep working on it.

**Comment by igorborgest** [comment]
Available on version >= 0.1.0
