### ISSUE TITLE
Listing data files on s3

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#374]
Hi, 

The project has a lot of features on s3, but I missed an option to list files on s3. For example I want to list every file in a specific path and get a list of only parquet files, or only csv files for example. Because I will read the data with spark.

Thank you

**Comment by igorborgest** [comment]
Hi @rubenssoto, thanks for reaching out!

You can use the [wr.s3.list_objects()](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.list_objects.html) function with `suffix=".parquet"` or simply pass your path with wild card (e.g. `path="s3://bucket/dir/*.parquet"`)

_P.S. All Wrangler's path arguments accepts Unix shell-style wildcards in the path argument. * (matches everything), ? (matches any single character), [seq] (matches any character in seq), [!seq] (matches any character not in seq)._

**Comment by rubenssoto** [comment]
> Hi @rubenssoto, thanks for reaching out!
> 
> You can use the [wr.s3.list_objects()](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.list_objects.html) function with `suffix=".parquet"` or simply pass your path with wild card (e.g. `path="s3://bucket/dir/*.parquet"`)
> 
> _P.S. All Wrangler's path arguments accepts Unix shell-style wildcards in the path argument. * (matches everything), ? (matches any single character), [seq] (matches any character in seq), [!seq] (matches any character not in seq)._

Great, thank you :)
