### ISSUE TITLE
Change in way read_glue_table addresses tables

### ISSUE THREAD

**Issue by gkennos** [awslabs/aws-data-wrangler#375]
**Describe the bug**
Previously, I have used the following code without issue:

```
item_ids = wr.s3.read_parquet(path=f'{processed_data_bucket}/distinct_path')
keys = list(wr.s3.read_parquet_table(database=gluedatabase, table='path_tokens').itemid.unique())
```

Now when I try to run the same code, I can see there has been some changes in the way that awswrangler refers to parquet file locations, as I now get:

```
item_ids = wr.s3.read_parquet(path=f'{processed_data_bucket}/distinct_path')
...
InvalidArgumentValue: '<redacted s3 path that does not start with s3://>/distinct_path' is not a valid path. It MUST start with 's3://'
```

which can obviously be fixed by changing the specified path, however I am not sure how to resolve the read_parquet_table issue:

```
keys = list(wr.s3.read_parquet_table(database=gluedatabase, table='path_tokens').itemid.unique())
...
InvalidArgumentValue: '<redacted s3 path that does not start with s3://>/path_tokens' is not a valid path. It MUST start with 's3://'
```

digging into the call to read_parquet_table, I see that the location is resolved via 
```
res = client_glue.get_table(DatabaseName=gluedatabase, Name="path_tokens")
res['Table']['StorageDescriptor']['Location']

>> <same path from above that does not include s3://>
```
Because of this, I figured it must have been a configuration issue in the data catalogue, but I checked and all the tables have the full location path specified including s3, as does the database, so I cannot see how to work around this issue

wr.__version__ = 1.9.0
boto3.__version__ = 1.14.53

**Comment by igorborgest** [comment]
Hi @gkennos, thanks for reporting that.

Could you please double check if the target table really has the **Location** parameter following the pattern `s3://my-bucket/anything/` ?

![image](https://user-images.githubusercontent.com/2163472/91988275-74e4ea00-ed05-11ea-9018-8bab0985c568.png)

I've just tried to reproduce your issue with wrangler `1.9.0` and boto3 `1.14.53` but everything works correctly here.

```py3
import awswrangler as wr
import pandas as pd

PATH = f"s3://BUCKET_NAME_PLACEHOLDER/test/"

# Mocking
df = pd.DataFrame({"itemid": [1, 2, 2]})
wr.s3.to_parquet(df, PATH, dataset=True, database="default", table="my_table", mode="overwrite")

# Trying to replicate
keys = list(wr.s3.read_parquet_table(database="default", table="my_table").itemid.unique())

# Verifying
assert keys == [1, 2]
```

**Comment by gkennos** [comment]
![Screen Shot 2020-09-02 at 11 26 24 pm](https://user-images.githubusercontent.com/12161195/91989427-dba0ec80-ed73-11ea-868e-37d7c51141ad.png)

Looks correct to me?

**Comment by gkennos** [comment]
I also tried dropping the table and re-running the crawler to pick it up from s3 just in case, but it didn't change anything

**Comment by igorborgest** [comment]
Thanks @gkennos

1. If you click in this link, will it point for your parquet files?
2. What crawler are you referring? The Glue Crawler?
3. Could you also try to run the code snippet that I sent above in your environment?

**Comment by igorborgest** [comment]
Also

4. Could try to read these files directly from s3 skipping the catalog?

```py3
keys = list(wr.s3.read_parquet(path="S3-LOCATION", dataset=True).itemid.unique())
```

*P.S. You can add the snippet bellow to enable the internal logging*

```py3
import logging

logging.basicConfig(level=logging.INFO, format="[%(asctime)s][%(name)s][%(funcName)s] %(message)s")
logging.getLogger("awswrangler").setLevel(logging.DEBUG)
```

**Comment by gkennos** [comment]
1. yes clicking the link takes me to the files
2. yes, the glue crawler - since that was how I added it to the data catalogue, I figured re-running it may fix whatever config is in error
3. your code snip works in my env
4. I am able to load the files directly, but there are a *lot* of places where I use read_parquet_table on this data source, so it would be much better to update my config if I can work out what has changed - this code was working on these same tables last time it was run - I have not changed anything except it is running in sagemaker and I did not fix the awswrangler version, so the version of the library has obviously changed (now that I look, it seems wrangler 1.9 is only a couple of days old)

**Comment by igorborgest** [comment]
> I figured re-running it may fix whatever config is in error

So now everything is right?

**Comment by igorborgest** [comment]
If you want, you also could store the metadata programatically through AWS Data Wrangler skipping the Glue Crawler.

```py
wr.s3.store_parquet_metadata(
    path="...",
    database="...",
    table="...",  # Give other name here just for the sake of this test
    dataset=True,
)
```

It will scan your parquet schemas on S3 and will create the related table on Glue Catalog. It is faster and cheaper than run the Glue Crawler manually.

**Comment by igorborgest** [comment]
Maybe the better way to troubleshot what is going on is enabling the internal logs.

You just need to add the snippet bellow in the beginning of your code:

```py3
import logging
logging.basicConfig(level=logging.INFO, format="[%(asctime)s][%(name)s][%(funcName)s] %(message)s")
logging.getLogger("awswrangler").setLevel(logging.DEBUG)
```

**Comment by gkennos** [comment]
OK I'm still unsure what was wrong with my metadata, because it looks identical in the console to me, but thank you for that - updating it programmatically has resolved it - I really appreciate the timely assistance

```python
table_list = wr.s3.list_objects(f's3://{processed_data_bucket}')
table_list_for_updating = list(set([t.split(processed_data_bucket)[1].split('/')[1] for t in table_list]))
for t in table_list_for_updating:
    wr.s3.store_parquet_metadata(
        path=f's3://{processed_data_bucket}/{t}',
        database=gluedatabase,
        table=t,  
        dataset=True,
    )
```

(FWIW, the exception happened before any logging statements were made, which is why I didn't mention above, but I did add the logging snip as well)

**Comment by igorborgest** [comment]
Yes, it also weird for me, I have no idea what happened with your metadata...

This `wr.s3.store_parquet_metadata()` is quite useful, you can explore more in the [API documentation](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.store_parquet_metadata.html) or in the [related tutorial](https://github.com/awslabs/aws-data-wrangler/blob/master/tutorials/010%20-%20Parquet%20Crawler.ipynb).

Let us know any other issue/feedback.

**Comment by igorborgest** [comment]
A last tip about:

```py3
table_list = wr.s3.list_objects(f's3://{processed_data_bucket}')
table_list_for_updating = list(set([t.split(processed_data_bucket)[1].split('/')[1] for t in table_list]))
```

It can be done using [`wr.s3.list_directories()`](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.list_directories.html) - It is faster cause will not fetch all filenames to the client side.
