### ISSUE TITLE
How do I read a partitioned Parquet file on S3 from pandas?

### ISSUE THREAD

**Issue by rjurney** [awslabs/aws-data-wrangler#386]
I have data partitioned on S3 in the following way:

```
s3://mybucket/stock_bars_1min/ticker_agg/year=2018/2018.pq
s3://mybucket/stock_bars_1min/ticker_agg/year=2019/2019.pq
s3://mybucket/stock_bars_1min/ticker_agg/year=2020/2020.pq
```

How do I use this library to read this partitioned Parquet folder into Pandas DataFrame such that it will filter the data to 2020 if those are the only partitions I access/filter to in my DataFrame?

I read the documentation but I don't see an actual usage, just API docs.

**Comment by igorborgest** [comment]
Hi @rjurney, thanks for reaching out.

```py3
wr.s3.read_parquet(
    path=path,
    dataset=True,
    partition_filter=lambda x: x["year"] == "2020"
)
```

Ref: [Tutorial](https://github.com/awslabs/aws-data-wrangler/blob/master/tutorials/023%20-%20Flexible%20Partitions%20Filter.ipynb)

**Comment by igorborgest** [comment]
Closing by inactivity.

**Comment by AdrianoNicolucci** [comment]
What about returning returning results from **multiple** partitions?

For example, using the example above, I would like results from multiple partitions:

s3://mybucket/stock_bars_1min/ticker_agg/year=2018/2018.pq
s3://mybucket/stock_bars_1min/ticker_agg/year=2019/2019.pq
s3://mybucket/stock_bars_1min/ticker_agg/year=2020/2020.pq

when passing in the partition filter = `partition_query= lambda x: x["year"] in ['2018', '2019']`,
I only get one of the partition's data being returned. what am I missing here?
