### ISSUE TITLE
Athena query on a specific "Catalog id"

### ISSUE THREAD

**Issue by sl-antoinelaborde** [awslabs/aws-data-wrangler#392]
It is not possible to specify the catalog id in the `read_sql_query` function. I would like to be able to request a specific catalog id on Athena.

boto3 takes into account the catalog id parameter in the "QueryExecutionContext" argument since at least version 1.14.58 ([here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html)).

A solution could be to add this in the  athena._utils._start_query_execution [here](https://github.com/awslabs/aws-data-wrangler/blob/6ee5bfebd8144de194292c4530f14babfce098c8/awswrangler/athena/_utils.py#L82), something like:
```
    # database
    if database is not None:
        args["QueryExecutionContext"] = {"Database": database, "Catalog": catalog_name}
```
and have the catalog id parameter available from `read_sql_query`.

**Comment by igorborgest** [comment]
Thanks @sl-antoinelaborde, we will address it in our next minor release (`1.10.0`)!

**Comment by igorborgest** [comment]
Released on version [1.9.4](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.9.4)

**Comment by Xiangyu-C** [comment]
@igorborgest I just tested the 1.9.4 release and tried wr.athena.read_sql_query (just simple select statement) on a data catalog in a different account and got the following errors:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\athena\_read.py", line 495, in _resolve_query_without_cache
    boto3_session=boto3_session,
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\athena\_read.py", line 378, in _resolve_query_without_cache_ctas
    raise ex
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\athena\_read.py", line 366, in _resolve_query_without_cache_ctas
    boto3_session=boto3_session,
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\athena\_utils.py", line 94, in _start_query_execution
    response: Dict[str, Any] = client_athena.start_query_execution(**args)
  File "C:\Program Files\Python37\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\botocore\client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: This operation is currently not supported for external catalogs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\_config.py", line 263, in wrapper
    return function(**args)
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\athena\_read.py", line 725, in read_sql_query
    boto3_session=session,
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\athena\_read.py", line 498, in _resolve_query_without_cache
    catalog.delete_table_if_exists(database=database, table=name, boto3_session=boto3_session)
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\_config.py", line 263, in wrapper
    return function(**args)
  File "C:\Program Files\Python37\lib\site-packages\awswrangler\catalog\_delete.py", line 80, in delete_table_if_exists
    client_glue.delete_table(**_catalog_id(DatabaseName=database, Name=table, catalog_id=catalog_id))
  File "C:\Program Files\Python37\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\botocore\client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the DeleteTable operation: User: arn:aws:sts::123456789012:assumed-role/*****/** (sorry I am not supposed to show my actual company aws role and account #) is not authorized to perform: glue:DeleteTable on resource: arn:aws:glue:us-east-1:123456789012:catalog with an explicit deny

I think this exposed two problems:
1. wr can't do start_query_execution on data catalog in a different account even though the role has full access, whereas boto3 athena client is able to run this query (using QueryExecutionContext={'Database': database, 'Catalog': catalog} param)
2. Why does read_sql_query require delete table access in glue? (I assume the default ctas_approach is True).

**Comment by igorborgest** [comment]
## Wrangler has two ways to run queries on Athena and fetch the result as a DataFrame:

### ctas_approach=True (Default)

Wraps the query with a CTAS and then reads the table data as parquet directly from s3.

PROS:

- Faster for mid and big result sizes.
- Can handle some levels of nested types.

CONS:

- Requires create/delete table permissions on Glue.
- Does not support timestamp with time zone
- Does not support columns with repeated names.
- Does not support columns with undefined data types.
- A temporary table will be created and then deleted immediately.

### ctas_approach=False

Does a regular query on Athena and parse the regular CSV result on s3.

PROS:

- Faster for small result sizes (less latency).
- Does not require create/delete table permissions on Glue
- Supports timestamp with time zone.

CONS:

- Slower (But stills faster than other libraries that uses the regular Athena API)
- Does not handle nested types at all.

[Reference](https://github.com/awslabs/aws-data-wrangler/blob/master/tutorials/006%20-%20Amazon%20Athena.ipynb)

**Comment by igorborgest** [comment]
@Xiangyu-C thanks for testing.

> StartQueryExecution operation: This operation is currently not supported for external catalogs.

> is not authorized to perform: glue:DeleteTable on resource

I think both nested exceptions was caused due the CTAS nature of `ctas_approach=True`. Could you test with `ctas_approach=False`, please?

**Comment by Xiangyu-C** [comment]
@igorborgest  Thanks for the clarification. It worked after explicitly setting ctas_approach=False. Sorry about the confusion.

**Comment by igorborgest** [comment]
Actually this was a pretty useful comment. We MUST update our documentation and also improve our exception message to clarify this new `ctas_approach=True` limitation.

Thank you @Xiangyu-C !
