### ISSUE TITLE
Support for S3 Access Points

### ISSUE THREAD

**Issue by rodalarcon** [awslabs/aws-data-wrangler#393]
Some organizations have multiple Data Lake domains across AWS accounts, for which they need to grant access to different departments (Finance, HR, etc.). This was one of the use cases for which AWS created S3 Access Points, in order to securely share datasets. However, when it comes to building ETLs supported by AWS Data Wrangler, all methods related to S3 only accept an S3 path in the form "s3://bucket/path/".

**Describe the solution you'd like**
I'd like to be able to provide S3 Access Points instead of S3 buckets in the S3 methods. Currently, all low level S3 APIs that 
have a Bucket field (such as GetObject) allow the requester to input either a Bucket name or the ARN of an S3 Access Point (https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestParameters). Hence it should be a matter of redesigning the parsing capabilities on AWS Data Wrangler to accept such format, and shouldn't require a change in the underlying Boto3 calls.

**Comment by igorborgest** [comment]
Thanks @rodalarcon, great suggestion! We will address it in our next minor release (`1.10.0`)!

**Comment by rodalarcon** [comment]
Thanks @igorborgest. It'd be great to allow the same S3URI pattern that is already allowed in AWS CLI:

s3://arn:aws:s3:us-west-2:123456789012:accesspoint/myaccesspoint/mykey

Ref: https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html#examples

**Comment by igorborgest** [comment]
Released on version [2.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.3.0) 🚀
