### ISSUE TITLE
Migration question:  "procs_cpu_bound" for "to_parquet()" equivalent in 1.x

### ISSUE THREAD

**Issue by skoschik** [awslabs/aws-data-wrangler#395]
In version 0.2.5, have been using  `to_parquet(procs_cpu_bound=1, ...)` to append to a partitioned table.

It looks like `use_threads` is the replacement `procs_cpu_bound`.   Do I also need to specify concurrent_partitioning to keep same behaviour as procs_cpu_bound=1 when writing to a partitioned table? 

My thinking is this will do the same thing as `procs_cpu_bound=1` but would be great to have confirmation as well.
`to_parquet(use_threads=False, concurrent_partitioning=False, ...)`    

Thanks, great library.

**Comment by igorborgest** [comment]
Hi @skoschik! Thanks for reaching out!

The arguments used in version `>1.0.0` have no exact equivalents in the legacy version. So let me briefly explain only the new arguments you will have.

Now Wrangler doesn't have the number of files per partitions tied to the number of threads anymore, so you can use `use_threads=True` without worrying about increase your dataset fragmentation. The default behaviour will always be 1 files per partition.

-  `use_threads`: Wrangler will use multithreading whenever it is possible, it will speed up the execution though it also increase the memory usage. No relation w/ the number of files created.
-  `concurrent_partitioning`: Wrangler will add an extra level of concurrency for the multithreaded approach and will push several partitions at the same time to s3. It will increase the memory consumption even more. Check out the related [tutorial](https://github.com/awslabs/aws-data-wrangler/blob/master/tutorials/022%20-%20Writing%20Partitions%20Concurrently.ipynb).
- `max_rows_by_file` Now by default Wrangler will write only 1 files per partition, but if you want to split the dataframe in many files you can use this argument.

Does it makes sense for you?

**Comment by skoschik** [comment]
Thank you for the prompt response.  That answers my question.
