### ISSUE TITLE
s3.to_parquet does not take the catalog id into account for partition creation

### ISSUE THREAD

**Issue by sl-antoinelaborde** [awslabs/aws-data-wrangler#399]
**Bug description**
When using _s3.to_parquet_ with partitions columns and a specific catalog_id, **the partition is not created on the Glue catalog**.

Adding the parameter _catalog_id_ in the call of  [_catalog.add_parquet_partitions_](https://github.com/awslabs/aws-data-wrangler/blob/eb770c8ebe1bfdd9f979f38639396156280fe398/awswrangler/s3/_write_parquet.py#L563) solved the issue.

**Comment by igorborgest** [comment]
Fix released on version [1.9.4](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.9.4)
