### ISSUE TITLE
db.copy_files_to_redshift not convert Athena TINYINT 

### ISSUE THREAD

**Issue by tuannguyen0901** [awslabs/aws-data-wrangler#400]
Using copy_files_to_redshift does not convert Athena TINYINT to appropriate data type

CREATE TABLE IF NOT EXISTS clean_data.fact_Data
  WITH (format='PARQUET',
        parquet_compression='SNAPPY',
        partitioned_by = ARRAY['environmentid']
        ) 
  AS
  select 
        cast (environmentid as TINYINT  ) as environmentid

**Comment by igorborgest** [comment]
Fix released on version [1.9.4](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.9.4)
