### ISSUE TITLE
Typo in examples

### ISSUE THREAD

**Issue by sapientderek** [awslabs/aws-data-wrangler#404]
**Describe the bug**

In API reference for awswrangler.catalog.does_table_exist and awswrangler.catalog.delete_table_if_exists (found at https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.catalog.does_table_exist.html#awswrangler.catalog.does_table_exist and https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.catalog.delete_database.html#awswrangler.catalog.delete_database)

the example in does_table_exist reads:
```
import awswrangler as wr
wr.catalog.does_table_exist(database='default', name='my_table')
```
when it should be:
```
import awswrangler as wr
wr.catalog.does_table_exist(database='default', table='my_table')
```
where `name` should be `table`

similar in delete_table_if_exists. I checked a handful but not all examples and just saw those two.

**Comment by igorborgest** [comment]
Fix released on version [1.9.4](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.9.4)
