### ISSUE TITLE
read_sql_query with ctas_approach=False requires create/delete table permissions on Glue

### ISSUE THREAD

**Issue by paulnim-worldremit** [awslabs/aws-data-wrangler#407]
**Describe the bug**
The latest docs for read_sql_query say using ctas_approach=False [does not require create/delete table permissions](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.athena.read_sql_query.html?highlight=delete#awswrangler.athena.read_sql_query) on Glue. But in version 1.9.3 of awswrangler, this does not appear to be the case.

**To Reproduce**
Install awswrangler 1.9.3 with `pip install awswrangler`

Run the following with a role that does not have `glue:CreateTable` permission
```python
import awswrangler as wr

wr.athena.read_sql_query(
     sql=sql,
     database=database,
      s3_output="s3://bucket",
      ctas_approach=False,
)
```
The following exception is raised.
```
Traceback (most recent call last):
...
  File {/path/to/my_script.py}, line 103, in query_athena
    ctas_approach=False,
  File "/usr/local/lib/python3.6/dist-packages/awswrangler/_config.py", line 263, in wrapper
    return function(**args)
  File "/usr/local/lib/python3.6/dist-packages/awswrangler/athena/_read.py", line 714, in read_sql_query
    boto3_session=session,
  File "/usr/local/lib/python3.6/dist-packages/awswrangler/athena/_read.py", line 505, in _resolve_query_without_cache
    boto3_session=boto3_session,
  File "/usr/local/lib/python3.6/dist-packages/awswrangler/athena/_read.py", line 435, in _resolve_query_without_cache_regular
    query_execution_id=query_id, boto3_session=boto3_session, categories=categories,
  File "/usr/local/lib/python3.6/dist-packages/awswrangler/athena/_utils.py", line 169, in _get_query_metadata
    _query_execution_payload = wait_query(query_execution_id=query_execution_id, boto3_session=boto3_session)
  File "/usr/local/lib/python3.6/dist-packages/awswrangler/athena/_utils.py", line 647, in wait_query
    raise exceptions.QueryFailed(response["QueryExecution"]["Status"].get("StateChangeReason"))
```

```
awswrangler.exceptions.QueryFailed: Insufficient permissions to execute the query. Error creating table : table_name in database : database due to : User: MyAwsRolw is not authorized to perform: glue:CreateTable on resource: catalog . You may need to manually clean the data at location s3_path before retrying. Athena will not delete data in your account.
```

**Comment by igorborgest** [comment]
Hi @paulnim-worldremit, thanks for reporting it.

What kind of SQL are you running? SELECT statements?

**Comment by paulnim-worldremit** [comment]
@igorborgest thank you for the fast response.

Yeah, I am running SELECT statements. In fact, this does not happen when I run CREATE or DROP statements.

**Comment by igorborgest** [comment]
No problems @paulnim-worldremit!

Please take a look in [these](https://github.com/awslabs/aws-data-wrangler/issues/299#issuecomment-649725860) instructions, I think it will help you.

**Comment by igorborgest** [comment]
It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
