### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by kuldeepsingh0694** [awslabs/aws-data-wrangler#428]
Hey Im trying to get started with the module but i cant get pass the import statement, PFB the error im getting 

TypeError                                 Traceback (most recent call last)
<ipython-input-35-80ffa1355302> in <module>
----> 1 import awswrangler as wr
      2 # import pandas as pd
      3 # wr.s3.to_parquet(
      4 #     df=df,
      5 #     path='s3://quarkbia/quark_new.parquet.gz',

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\__init__.py in <module>
      8 import logging as _logging
      9 
---> 10 from awswrangler import athena, catalog, cloudwatch, db, emr, exceptions, quicksight, s3, sts  # noqa
     11 from awswrangler.__metadata__ import __description__, __license__, __title__, __version__  # noqa
     12 from awswrangler._config import config  # noqa

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\athena\__init__.py in <module>
      1 """Amazon Athena Module."""
      2 
----> 3 from awswrangler.athena._read import read_sql_query, read_sql_table  # noqa
      4 from awswrangler.athena._utils import (  # noqa
      5     create_athena_bucket,

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\athena\_read.py in <module>
     12 import pandas as pd
     13 
---> 14 from awswrangler import _utils, catalog, exceptions, s3
     15 from awswrangler._config import apply_configs
     16 from awswrangler.athena._utils import (

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\catalog\__init__.py in <module>
      1 """Amazon Glue Catalog Module."""
      2 
----> 3 from awswrangler.catalog._add import add_csv_partitions, add_parquet_partitions  # noqa
      4 from awswrangler.catalog._create import (  # noqa
      5     _create_csv_table,

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\catalog\_add.py in <module>
      9 from awswrangler._config import apply_configs
     10 from awswrangler.catalog._definitions import _csv_partition_definition, _parquet_partition_definition
---> 11 from awswrangler.catalog._utils import _catalog_id, sanitize_table_name
     12 
     13 _logger: logging.Logger = logging.getLogger(__name__)

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\catalog\_utils.py in <module>
      8 import pandas as pd
      9 
---> 10 from awswrangler import _data_types, _utils, exceptions
     11 from awswrangler._config import apply_configs
     12 

~\AppData\Roaming\Python\Python37\site-packages\awswrangler\_data_types.py in <module>
     12 import pyarrow.parquet
     13 import sqlalchemy
---> 14 import sqlalchemy.dialects.mysql
     15 import sqlalchemy.dialects.postgresql
     16 import sqlalchemy_redshift.dialect

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sqlalchemy\dialects\mysql\__init__.py in <module>
     49 from .base import VARCHAR
     50 from .base import YEAR
---> 51 from .dml import Insert
     52 from .dml import insert
     53 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sqlalchemy\dialects\mysql\dml.py in <module>
    113 
    114 insert = public_factory(
--> 115     Insert, ".dialects.mysql.insert", ".dialects.mysql.Insert"
    116 )
    117 

TypeError: public_factory() takes 2 positional arguments but 3 were given

**Comment by igorborgest** [comment]
Seems some conflict with dependencies

- Could send the output of `pip freeze`?
- Where are you installing? SageMaker? MacOS? AWS Lambda? AWS Glue Job?
- Do you mind to test it in a complete empty virtual environment?
`python -m venv venv && source venv/bin/activate && pip install awswrangler && python -c "import awswrangler as wr;print(wr.__version__)"`

**Comment by kuldeepsingh0694** [comment]
Here is the Pip freeze -

2to3==1.0
3to2==1.1.1
adal==1.2.2
agate==1.6.1
agate-dbf==0.2.1
agate-excel==0.2.3
agate-sql==0.5.4
alabaster==0.7.12
altgraph==0.16.1
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
aplus==0.11.0
arrow==0.15.5
asgiref==3.2.3
asn1crypto @ file:///home/conda/feedstock_root/build_artifacts/asn1crypto_1595949944546/work
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.1.0
aurora-data-api==0.2.0
autograd==1.3
autograd-gamma==0.4.1
awscli==1.16.264
awswrangler==1.9.6
azure-common==1.1.25
azure-core==1.7.0
azure-storage-blob==12.3.2
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.7
beautifulsoup4==4.7.1
bitarray==0.9.3
bkcharts==0.2
bleach==3.1.0
blis==0.4.1
bokeh==1.2.0
boto==2.49.0
boto3==1.15.17
botocore==1.18.17
Bottleneck==1.2.1
bqplot==0.12.17
branca==0.4.1
cachetools==4.1.1
catalogue==1.0.0
certifi==2020.6.20
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.1
clyent==1.2.2
colorama==0.4.1
colorlover==0.3.0
comtypes==1.1.7
conda==4.7.10
conda-build==3.18.8
conda-package-handling==1.3.11
conda-verify==3.4.2
contextlib2==0.5.5
cryptography==2.7
csvkit==1.0.4
cufflinks==0.17.3
cx-Oracle==7.2.3
cycler==0.10.0
cymem==2.0.3
Cython==0.29.12
cytoolz==0.10.0
dask==2.27.0
dbfread==2.0.7
decorator==4.4.0
defusedxml==0.6.0
distributed==2.1.0
Django==3.0.3
docutils==0.14
email==6.0.0a1
en-core-web-sm==2.3.1
entrypoints==0.3
et-xmlfile==1.0.1
extract-msg==0.23.3
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
flatten-json==0.1.7
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1602700749102/work
future==0.17.1
get==2019.4.13
gevent==1.4.0
gitdb2==2.0.6
githubcommit==0.1.0
GitPython==3.0.5
glob2==0.7
GoogleNews==1.3.6
greenlet==0.4.15
h5py==2.9.0
heapdict==1.0.0
herepy==2.1.1
html5lib==1.0.1
http-hmac-python==2.4.0
idna==2.8
imageio==2.5.0
imagesize==1.1.0
IMAPClient==2.1.0
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1602263269022/work
ipydatawidgets==4.1.0
ipykernel==5.1.1
ipyleaflet==0.13.3
ipympl==0.5.8
ipython==7.6.1
ipython-genutils==0.2.0
ipyvolume==0.5.2
ipyvue==1.4.0
ipyvuetify==1.5.1
ipywebrtc==0.5.0
ipywidgets==7.5.0
isodate==0.6.0
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.13.3
Jinja2==2.10.1
jmespath==0.9.4
joblib==0.13.2
json-logging==1.0.5
json2table==1.1.5
json5==0.8.4
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1602551949684/work
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.5.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.0.2
jupyterlab-server==1.0.0
jupyterthemes==0.20.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
leather==0.3.3
lesscpy==0.14.0
libarchive-c==2.8
lifelines==0.22.9
llvmlite==0.29.0
locket==0.2.0
lxml==4.3.4
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mo-dots==3.22.19344
mo-future==3.17.19324
mo-logs==3.21.19344
mock==3.0.5
more-itertools==7.0.0
mpmath==1.1.0
msgpack==0.6.1
msrest==0.6.17
multipledispatch==0.6.0
murmurhash==1.0.2
navigator-updater==0.2.1
nbconvert==5.5.0
nbformat==4.4.0
nbresuse==0.3.6
nest-asyncio==1.4.0
networkx==2.3
newsapi==0.1.1
newsapi-python==0.2.6
ngboost==0.1.3
nltk==3.4.4
nose==1.3.7
notebook==6.0.0
ntlm-auth @ file:///home/conda/feedstock_root/build_artifacts/ntlm-auth_1592313846293/work
numba==0.44.1
numexpr==2.6.9
numpy==1.18.5
numpydoc==0.9.1
O365==2.0.7
oauthlib==3.1.0
Office365-REST-Python-Client==2.2.1.1
olefile==0.46
onedrivesdk==1.1.8
openpyxl==2.6.2
oscrypto==1.2.0
packaging==19.0
pandas==1.1.3
pandocfilters==1.4.2
paramiko==2.7.1
parsedatetime==2.4
parso==0.5.0
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.4
patsy==0.5.1
pefile==2019.4.18
pep8==1.7.1
pickleshare==0.7.5
Pillow==6.1.0
pkginfo==1.5.0.1
plac==1.1.3
plotly==4.10.0
pluggy==0.12.0
ply==3.11
post==2019.4.13
preshed==3.0.2
progressbar2==3.53.1
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.11.2
psutil==5.6.3
psycopg2==2.8.3
psycopg2-binary==2.8.3
public==2019.4.13
py==1.8.0
pyAesCrypt==0.4.3
pyarrow==1.0.1
pyasn1==0.4.7
PyAthena==1.11.0
pybase64==1.0.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycryptodomex==3.9.8
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
PyInstaller==3.5
PyJWT==1.7.1
pylint==2.3.1
pymongo==3.10.1
PyMySQL==0.9.3
PyNaCl==1.4.0
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyreadline==2.1
pyrsistent==0.14.11
PySocks==1.7.0
pystream-protobuf==1.5.1
pytest==5.0.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.8.0
python-slugify==3.0.4
python-utils==2.4.0
pythonping==1.0.8
pythreejs==2.2.0
pytimeparse==1.1.8
pytz==2019.1
PyWavelets==1.0.3
pywin32==223
pywin32-ctypes==0.2.0
pywinpty==0.5.5
PyYAML==5.1.1
pyzmq==18.0.0
qgrid==1.3.1
QtAwesome==0.5.7
qtconsole==4.5.1
QtPy==1.8.0
query-string==2019.4.13
read-protobuf==0.1.1
request==2019.4.13
requests==2.22.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retrying==1.3.3
reverse-geocode==1.4
rope==0.14.0
rsa==3.4.2
ruamel-yaml==0.15.46
s3fs==0.4.2
s3parq==2.1.10
s3transfer==0.3.3
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
secure-smtplib==0.1.1
Send2Trash==1.5.0
sharepoint==0.4.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
smmap2==2.0.5
snowballstemmer==1.9.0
snowflake-connector-python==2.2.9
snowflake-sqlalchemy==1.2.3
snowflake-tools==0.0.2
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.8
spacy==2.3.2
Sphinx==2.1.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.1
SQLAlchemy==1.3.13
sqlalchemy-aurora-data-api==0.2.0
sqlalchemy-redshift==0.7.5
sqlparse==0.3.0
srsly==1.0.2
statsmodels==0.10.0
stringcase==1.2.0
sympy==1.4
tables==3.5.2
tabulate==0.8.7
tblib==1.4.0
tenacity==6.2.0
terminado==0.8.2
testpath==0.4.2
text-unidecode==1.3
thinc==7.4.1
toolz==0.10.0
tornado==6.0.3
tqdm==4.48.0
traitlets==4.3.2
traittypes==0.2.1
tzlocal==1.5.1
unicodecsv==0.14.1
urllib3==1.24.2
vaex==3.0.0
vaex-arrow==0.5.1
vaex-astro==0.7.0
vaex-core==2.0.3
vaex-hdf5==0.6.0
vaex-jupyter==0.5.2
vaex-ml==0.9.0
vaex-server==0.3.1
vaex-viz==0.4.0
wasabi==0.7.1
wcwidth==0.1.7
webencodings==0.5.1
webexteamsbot==0.1.3.0
webexteamssdk==1.2
Werkzeug==0.15.4
wget==3.2
widgetsnbextension==3.5.0
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xarray==0.16.1
xlrd==1.2.0
xlsx2csv==0.7.6
XlsxWriter==1.1.8
xlwings==0.15.8
xlwt==1.3.0
zict==1.0.0
zipp==0.5.1

**Comment by kuldeepsingh0694** [comment]
here is the pip freeze -
[New Text Document (5).txt](https://github.com/awslabs/aws-data-wrangler/files/5391624/New.Text.Document.5.txt)

Im installing it on my local windows system and its working fine in the new virtual environment.

Cant figure out exactly whats dependency are causing the issue

**Comment by igorborgest** [comment]
My guess is that is some conflict with `sqlalchemy-aurora-data-api==0.2.0`, but I'm not sure.
