### ISSUE TITLE
Params in athena sql query construction

### ISSUE THREAD

**Issue by imanebosch** [awslabs/aws-data-wrangler#432]
Is there a way to parametrize the query in `awswrangler.athena.read_sql_query()`, just as `pandas.read_sql()` has parameter `params`. If not may be it is a nice feature to consider isn't it?

**Comment by igorborgest** [comment]
It doesn't support params by now... Lets convert this to an `enhancement`!

**Comment by igorborgest** [comment]
Released on version [2.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.3.0) 🚀
