### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [awslabs/aws-data-wrangler#440]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://aws-data-wrangler.readthedocs.io/en/legacy/

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by igorborgest** [comment]
Thank you @MrCull !
