### ISSUE TITLE
Possible to set up Athena bucketing using wr.s3.to_parquet() and wr.s3.to_csv()?

### ISSUE THREAD

**Issue by eric-valente** [awslabs/aws-data-wrangler#443]
I've read that bucketing is a good way to improve performance on Athena tables, using the command here:
![image](https://user-images.githubusercontent.com/35536427/98290963-4088e680-1f5f-11eb-94a7-7ecd358759c2.png)

Is it possible to implement this with awswrangler in either wr.s3.to_parquet or wr.s3.store_parquet_metadata?

Thanks and love the package!

**Comment by igorborgest** [comment]
Oh this is a good one! Let's add a feature request tag.

Thanks!

**Comment by maxispeicher** [comment]
I will try to include this one. However after having a first look, I don't think including it in `store_parquet_metadata` is possible, as the columns by which bucketing is applied cannot be retrieved from the S3 path (in contrast to partitioning).

But for creating csv and parquet tables and files it should work just fine 👍

**Comment by maxispeicher** [comment]
After having a deeper look, I think this is really hard to include/implement. This is because the placement of values into different buckets, a hash value of the columns by which the bucketing is done is calculated and this hash function is not available (at least from what I've seen).
Additionally Athena also only supports bucketing during the creation of a table but is also not able to insert into a bucketed table afterwards (https://docs.aws.amazon.com/athena/latest/ug/insert-into.html).

It seems to be that because of that bucketing could only be done for the creation of tables, e.g. `awswrangler.catalog.create_parquet_table`, but I don't think that is very benefitial by itself.

@igorborgest What do you think about this?

**Comment by igorborgest** [comment]
I _think_ Hive's hash functions are the standard. I did a test here and I can confirm that at least for integer columns it is true (`bucket_id = value % num_buckets`).

Looking better at their implementation I'm not sure if it will worth to develop this feature, it will demand a considerable amount of work. Maybe just start with initial support only for integer and string types? What do you think @maxispeicher ?

References:
- [Concise explanation](https://stackoverflow.com/a/46772930/4162047)
- [Hive docs](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL+BucketedTables)
- [Hive source](https://github.com/apache/hive/blob/e60744d017ef79f1b17f474c0b969d4ca5592462/serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorUtils.java#L491)

p.s. If we decide to move forward here I can double check internally about the functions.

**Comment by maxispeicher** [comment]
If this functionality is limited (at first) to some datatypes like `int`, `str` and `bool` I think this should be doable. However it still needs a "duplicate" of the hive hashing, which at least in my opinion is still at least a little bit hacky (and could maybe even change).

@igorborgest If you think this feature is still beneficial, I can try to give it a shot and see if the results are as expected.

**Comment by maxispeicher** [comment]
I've tried to implement a first draft of the bucketing mechanism (see the PR above), which can be used as a starting point. It is still missing some tests and documentation but from a "feature-view" it should be usable. The new functions in `aws-data-wrangler/tests/test_athena.py` probably show best how the bucketing could work in this implementation.

If you find the time can you maybe have a look what you think about this approach @igorborgest @eric-valente. Thanks :)

**Comment by igorborgest** [comment]
Released on version [2.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.4.0).
