### ISSUE TITLE
wr.s3.store_parquet_metadata reading category dtype as null string

### ISSUE THREAD

**Issue by melvinev** [awslabs/aws-data-wrangler#447]
Hi - wr.s3.store_parquet_metadata is not correctly converting a category column to string.  

The parquet files have this column ticker as a category:
![image](https://user-images.githubusercontent.com/35536427/98743984-cd6bdf80-2365-11eb-86b9-92b5980a1107.png)

The Glue table that gets written using wr.s3.store_parquet_metadata writes correctly, but the 'ticker' field gets converted to string and is null.  
![image](https://user-images.githubusercontent.com/35536427/98744102-fe4c1480-2365-11eb-9814-19434984d614.png)

I tried setting dtype={'ticker':'string'} but still null.  Any thoughts?

**Comment by igorborgest** [comment]
Hi @melvinev how can you see that this column has this "category[know]" type in the parquet file? And how this parquet file was written?

**Comment by melvinev** [comment]
Hi @igorborgest I'm using dd.read_parquet() (Dask).

Dummy example (change the S3 path):

```dd.read_csv('https://perso.telecom-paristech.fr/eagan/class/igr204/data/cars.csv', delimiter=';')\
    .to_parquet(f"s3://bucket/cartest", engine="pyarrow", write_index=False, compression="snappy", partition_on=['Car'])

wr.s3.store_parquet_metadata(
    path='s3://bucket/cartest',
    database="database",
    table="cartest",
    dataset=True,
    mode="overwrite",
    compression="snappy",
    use_threads=True
)
```
![image](https://user-images.githubusercontent.com/35536427/98842832-fa200580-23fe-11eb-8986-442a88d34845.png)

**Comment by melvinev** [comment]
Confirmed that by looking at a single parquet file, the 'Car' column is not in there, yet wr is adding it as a second colum:
![image](https://user-images.githubusercontent.com/35536427/98843865-618a8500-2400-11eb-9f19-5fc539e2ab58.png)

![image](https://user-images.githubusercontent.com/35536427/98843941-79fa9f80-2400-11eb-8813-7770930a8033.png)

**Comment by melvinev** [comment]
And when I read the full parquet folder, Pandas correctly creates a column for Car derived from the folder partitions:
![image](https://user-images.githubusercontent.com/35536427/98844124-bcbc7780-2400-11eb-8405-d2736a57622c.png)

**Comment by igorborgest** [comment]
@melvinev thanks for more details, we will investigate it.

One last question, are you sure that you don't have this column materialized in some file?

You can run this snippet to check:

```py
wr.s3.read_parquet(
    path="...",
    dataset=True,
    validate_schema=True
)
```

It will throw an exception if there is some mismatching schema in your files.

**Comment by melvinev** [comment]
Hi @igorborgest really appreciate you looking into this!

The schema does not pass - do you think it has to do w/ how Dask is writing the parquet partitions? Any thoughts here? 
![image](https://user-images.githubusercontent.com/35536427/98955591-ec788780-24b3-11eb-8181-1065d6d0faed.png)

**Comment by melvinev** [comment]
Okay so I tried deleting the _metadata file that Dask creates and it works now... I can tell Dask to not write the metadata file, but do you know why this is happening?  

![image](https://user-images.githubusercontent.com/35536427/98956385-d0c1b100-24b4-11eb-921f-7a2dee9f70dc.png)

**Comment by melvinev** [comment]
The wr.s3.store_parquet_metadata takes a very long time to run with not a ton of files - is the metadata file supposed to help speed this up given it knows the parquet structure?

**Comment by melvinev** [comment]
Also I deleted the "_common_metadata" file and reran and it was successful so maybe these 2 metadata files together are causing the problem?

![image](https://user-images.githubusercontent.com/35536427/98957893-8e996f00-24b6-11eb-9ee4-13d5434abe9b.png)

**Comment by igorborgest** [comment]
Wrangler will ignore this metadata file.

Are you sure this issue has some relation with this metadata file? It seems that you had files mixed from two different "writes" and with different schemas. Maybe just the clean up would solved it.

About the `wr.s3.store_parquet_metadata()` speed.

- How much files do you have?
- How much time it takes?
- Are you running from inside AWS?

By default this function will check the footer of all your files, so it is I/O intense. If you are running it from a high latency environment (e.g. distant s3 region) is expected that it will take some time.

In addition to that we also have the `sampling` argument. So if you have a uniform schema you can pass `sampling=0.1` to scan only 10% of the files for example.

**Comment by melvinev** [comment]
@igorborgest yeah I tested the metadata a few times and deleting it makes it work... I'll try again. 

re: speed:
- 400 partition folders with 1 partition file of about 10mb in each
- Never finishes, > 10 minutes and I cancel
- yes in AWS running in same region as the S3 bucket (us east 1)

Does it help to prepopulate the names of the files like this? 
path = ['s3://' + s for s in s3fs.S3FileSystem().glob('s3://bucket/partitions)]

**Comment by melvinev** [comment]
When I use s3.store_parquet_metadata with dataset=True on a folder of parquet files (non partitioned) its very quick.

**Comment by melvinev** [comment]
I think the original issue stands, if delete the "common_metadata" file it actually works properly and finishes in 1.5 minutes and does not have duplicates.

![image](https://user-images.githubusercontent.com/35536427/98991066-2bbccd80-24e0-11eb-9ac6-a2fe698bbdd5.png)

I get this I leave both meta data files in:

HIVE_INVALID_METADATA: Hive metadata for table cartest is invalid: Table descriptor contains duplicate columns

**Comment by melvinev** [comment]
Adding **write_metadata_file=False,** fixes it, so it's either something weird with how Dask writes metadata files or AWS Wrangler reads them:

.to_parquet(f"s3://bucket/cartest", engine="pyarrow", write_index=False, write_metadata_file=False, compression="snappy", partition_on=['Car']

**Comment by igorborgest** [comment]
So if the problem is this metadata file, you can use the `path_suffix=["parquet"]` OR `path_ignore_suffix=["_medadata"]` arguments to ignore it.

This way you can keep using these files to read with Dask.

**Comment by melvinev** [comment]
Ah clever... thank you! Beats deleting the files.

**Comment by melvinev** [comment]
Thanks again @igorborgest

**Comment by igorborgest** [comment]
Also, it is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want.
