### ISSUE TITLE
Support Dynamodb?

### ISSUE THREAD

**Issue by dwbelliston** [awslabs/aws-data-wrangler#448]
**Is your feature request related to a problem? Please describe.**
Interested if Dynamodb support is on the roadmap?

**Describe the solution you'd like**
Write csv/json to dynamodb table

**Comment by maxispeicher** [comment]
I will try to have a look at this 👍

**Comment by maxispeicher** [comment]
I've added a first draft for the implementation. 
@dwbelliston Can you have a look if this what you have in mind?

**Comment by igorborgest** [comment]
Released on version [2.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.3.0) 🚀
