### ISSUE TITLE
add/delete column

### ISSUE THREAD

**Issue by bryanyang0528** [awslabs/aws-data-wrangler#451]
**Is your feature request related to a problem? Please describe.**
Add/ delete a column using Glue.

**Describe the solution you'd like**
Wraping `update_table` of glue as two functions add_column and delete_column to manipulate Glue.
(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.update_table)

**Comment by igorborgest** [comment]
Released on version [1.10.1](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.10.1)
