### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by orenmazor** [awslabs/aws-data-wrangler#454]
**Is your idea related to a problem? Please describe.**
I'm wondering what the roadmap is for python 3.9 support?

**Comment by igorborgest** [comment]
Thanks for reaching out @orenmazor !

By now we are blocked by PyArrow.
They already are working on that: https://github.com/apache/arrow/pull/8386

**Comment by igorborgest** [comment]
Released on version [2.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.4.0).
