### ISSUE TITLE
Support another DBs using Glue Connection

### ISSUE THREAD

**Issue by nefkor** [awslabs/aws-data-wrangler#455]
**Is your idea related to a problem? Please describe.**
I am trying to use Glue jobs to extract data from custom (non-supported natively) db by providing the jdbc jar and classpath. But I am disappointed on the Glue configuration and performance

**Describe the solution you'd like**
Ideally I would be able to call the read db method, and for custom db, pass the classpath already loaded in context. This is necessary for me to connect to DB2 sources

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by igorborgest** [comment]
We've just released support to [SQLServer](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.3.0). And the project has no intention to cover more database than those that already are supported.

Pandas + SQLAlchemy can be used as alternative to connect to others databases.
