### ISSUE TITLE
wr.s3.to_parquet writing null fields like double

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#457]
Hello,

I don't know if is a data wrangler problem or pandas. I'm reading data with pandas read_csv and writing to s3 using
wr.s3.to_parquet, all my null fields are created with Double types. When the field is not null the type is string, so, spark have problems to read this parquet files with type differences.

Could you help me? Thank you

**Comment by igorborgest** [comment]
Hi @rubenssoto , thanks for reaching out.

Actually `wr.s3.to_parquet()` will never mix different types in a single column. What probably is happening in your case is:

* CSV doesn't have hard schemas or real data types, in the end, all columns are just text there.
When you read this CSV files with, Pandas will try to _**infer**_ the columns types, and it is error prone.
* Pandas can infer different schema for the same "CSV pattern" according to the values in each file.
* The `wr.s3.to_parquet()` just move forward and write a parquet file following the data types in your DataFrame (Inherited from the CSV inference).

e.g.

### Batch 1

* CSV:

col_a,col_b
foo,boo
bar,xoo

* Pandas DataFrame from `read_csv()`

col_a: object (string)
col_b: object (string)

### Batch 2

* CSV:

col_a,col_b
,boo
,xoo

* Pandas DataFrame from `read_csv()`

col_a: float64 (double)
col_b: object (string)

**Comment by igorborgest** [comment]
You have some alternative to deal with this situation:

* Use the `read_csv()` `dtype` argument to ensure the right data type during the read.
* Use the `to_parquet()` `dtype` argument to ensure the right data type during the read.
* Cast the correct data types by yourself between the read and the write.
* Use the `to_parquet()` `database` and `table` arguments to store the metadata (schema) on Glue Catalog, it you ensure the conversion to the right data types automatically. (My favorite)

**Comment by igorborgest** [comment]
closing by inactivity
