### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by danielwo** [awslabs/aws-data-wrangler#462]
Looks like a copy + paste error: I think this line should be something like `SQL query.`
https://github.com/awslabs/aws-data-wrangler/blob/f6934763bd873a345e24a24c7e1d188c96dc10c1/awswrangler/db.py#L388-L389

**Comment by igorborgest** [comment]
Released on version [1.10.1](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.10.1)
