### ISSUE TITLE
Simplify some internals, since S3 became strongly consistent

### ISSUE THREAD

**Issue by pmleveque** [awslabs/aws-data-wrangler#464]
**Is your idea related to a problem? Please describe.**
As far as I remember, there were some protections against s3 eventual consistency. They are no longer needed.

https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency

**Describe the solution you'd like**
Simply some internals.

for instance:
https://github.com/awslabs/aws-data-wrangler/blob/dfad32e19b45439b54c26491325bfe183455954c/awswrangler/emr.py#L535

**Comment by igorborgest** [comment]
Released on version [2.0.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.0.0)
