### ISSUE TITLE
Copy Objects From Different Buckets

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#471]
Hello,

We are trying to use this feature
https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.copy_objects.html#awswrangler.s3.copy_objects

but are different buckets in different accounts, so we have to use different sessions for each bucket, is it possible?

thank you

**Comment by igorborgest** [comment]
No, it is not possible because theses copies are not in the client side, and we do it with API calls that rely in a single session. You probably should update your bucket policy in the target to allow the first role to put object there.
