### ISSUE TITLE
Pip install causing infinite loop on centos

### ISSUE THREAD

**Issue by rpmchale** [awslabs/aws-data-wrangler#473]
**Describe the bug**
When I run a pip install awswrangler==2.0.0 on centos, I get into (assumed) infinite loop. I have attached the pip output that executed prior to killing the command.

**To Reproduce**
On CentOS, run `pip install --upgrade awswrangler`
[pip_output.txt](https://github.com/awslabs/aws-data-wrangler/files/5676630/pip_output.txt)

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by igorborgest** [comment]
Which is you python and pip versions? Is pip updated? Did you try creating a fresh and clean virtual environment?

**Comment by rpmchale** [comment]
I was using a fresh environment. I developed on a windows machine without issue, but my build environment is CentOS which is ephemeral so each build is clean. 

Python version:
Python 3.6.9

Pip version:
pip 20.3

**Comment by igorborgest** [comment]
Thanks @rpmchale 

Just for troubleshooting purpose, could you try to install `pymysql` directly? 

`pip install pymysql`

**Comment by rpmchale** [comment]
Ran without issue

Collecting pymysql
  Downloading https://company.com/artifactory/api/pypi/vpypi-eval/packages/packages/1a/ea/dd9c81e2d85efd03cfbf808736dd055bd9ea1a78aea9968888b1055c3263/PyMySQL-0.10.1-py2.py3-none-any.whl (47 kB)
     |################################| 47 kB 1.0 MB/s
Installing collected packages: pymysql
Successfully installed pymysql-0.10.1

**Comment by igorborgest** [comment]
Hi @rpmchale. We've just released the `2.3.0` version with support for `pymysql` version `1.0.*`. Could you test it in your scenario, please?

**Comment by igorborgest** [comment]
Closing by inactivity.
