### ISSUE TITLE
Catalog add_column documentation error

### ISSUE THREAD

**Issue by lucasasmith** [awslabs/aws-data-wrangler#476]
I believe this should be `Add a column in a AWS Glue Catalog table.`

https://github.com/awslabs/aws-data-wrangler/blob/2a3afb027a00ce5ee0bd58d64a014c25383bd851/awswrangler/catalog/_add.py#L177-L179

**Comment by lucasasmith** [comment]
Sorry, didn’t mean for the bug label to be applied.

**Comment by igorborgest** [comment]
Hey @lucasasmith , thanks for reporting it!

Fixed in the commit above.
