### ISSUE TITLE
Pattern for athena caching

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#479]
Hello,

The athena cache feature is great, so I'm trying to found some patterns to this. For our data scientist is fine because they use notebooks so working with data wrangler is very easy.
Do you know some pattern to use of other types of users? For example, to use data wrangler with most of my users I have do put data wrangler in the middle of sql client and athena.

For know we use https://redash.io/ for sql client

**Comment by popeyesadley** [comment]
Only if you were going to put it in stall

**Comment by igorborgest** [comment]
I don't know Redash internals enough to say much, but you will need some kind of Python layer to use our cache.
