### ISSUE TITLE
Terraform installation

### ISSUE THREAD

**Issue by rsradulescu** [awslabs/aws-data-wrangler#486]
Hello!
Could you tell me how to install the data wrangler in terraform?

**Comment by igorborgest** [comment]
We can just [use Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) to deploy our [Lambda Layer](https://aws-data-wrangler.readthedocs.io/en/stable/install.html#aws-lambda-layer).
