### ISSUE TITLE
CSV (S3) -> Pandas (One shot or Batching) : Thousand Seperator

### ISSUE THREAD

**Issue by BellyTheMagnificent** [awslabs/aws-data-wrangler#50]
Suggest to include thousands and decimal from pandas.read_csv()

**Comment by igorborgest** [comment]
Hey @BellyTheMagnificent, thank you for one more contribution!

This request already is [done](https://github.com/awslabs/aws-data-wrangler/commit/f24ab963387cd73bd7cf52175a243b2e64593973) and will be in the version 0.0.12 that will be released later tonight!
