### ISSUE TITLE
Upload/download files

### ISSUE THREAD

**Issue by danielwo** [awslabs/aws-data-wrangler#506]
**Is your feature request related to a problem? Please describe.**
I am frustrated when having to use a different syntax to upload/download files with boto3 compared to AWS Data Wrangler. For example, with boto3, I must create a client or resource and specify a bucket and key, but with AWS Data Wrangler, I can use 's3://path/to/my/file'. There is already functionality in AWS Data Wrangler to copy, delete, list, and read/write specific formats with S3 -- I would like a unified interface which lets me bypass having to use boto3.

**Describe the solution you'd like**
Add functions under the `s3` namespace which allows uploading/downloading files using an s3 path such as 's3://bucket/my/file'. There should be ways to work with objects on disk and potentially in memory. Also need to consider encryption.

**Comment by igorborgest** [comment]
Released on version [2.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.4.0).
