### ISSUE TITLE
s3.to_parquet() - Changes columns names from DataFrame.  Adds an '_'

### ISSUE THREAD

**Issue by AndoKalrisian** [awslabs/aws-data-wrangler#515]
I have a dataframe with many columns with the names like 's1502_c02_014e', 's1502_c02_015e' etc.  When I use s3.to_parquet() to put the table on S3, I get the following column names: 's1502_c02_014_e', s1502_c02_014_e'.  awswrangler is adding and an underscore before the last letter.  

This is the code I am using:
`wr.s3.to_parquet(
                df=df_demo,
                dataset=True,
                path='s3://mybucket/raw/usa_acs5_2018/',
                database='raw',
                table='usa_acs5_2018',
                partition_cols=['state'],
                sanitize_columns=False,
            )`

I've also tried without the 'sanitize_columns' variable and found no difference in the result.  Another interesting discovery is that you this function also changes the dataframe's column names after running it.  You can easily test by checking the dataframe ('df_demo' in my case) before and after.

**Comment by maxispeicher** [comment]
Which version of awswrangler are you using? I've tried to reproduce the issue with the following code:
```python
import awswrangler as wr
import pandas as pd

df = pd.DataFrame({"s1502_c02_014e": [1, 2, 3], "s1502_c02_015e": [4, 5, 6], "state": ["DE", "US", "NL"]})
s3_path = "s3://my-bucket/col_test"
print(df.columns)
wr.s3.to_parquet(
    df=df,
    path=s3_path,
    dataset=True,
    database="mydatabase",
    table="col_test",
    partition_cols=["state"]
)

df_loaded = wr.s3.read_parquet(path=s3_path)
print(df_loaded.columns)
```

The output of this snippet (in my case) is:
```
Index(['s1502_c02_014e', 's1502_c02_015e', 'state'], dtype='object')
Index(['s1502_c02_014e', 's1502_c02_015e'], dtype='object')
```

**Comment by igorborgest** [comment]
We have some mechanisms to enforce compatibility with Amazon Athena and others engines. ([Reference](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html))

> If `database` and `table` arguments are passed, the table name and all column names will be automatically sanitized using `wr.catalog.sanitize_table_name()` and `wr.catalog.sanitize_column_name()`.

So my guess is: You probably has _camelCase_ columns names that are being converted to _snake_case_. (p.s. Underscore is the only special character accepted).

**Comment by AndoKalrisian** [comment]
> We have some mechanisms to enforce compatibility with Amazon Athena and others engines. ([Reference](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html))
> 
> > If `database` and `table` arguments are passed, the table name and all column names will be automatically sanitized using `wr.catalog.sanitize_table_name()` and `wr.catalog.sanitize_column_name()`.
> 
> So my guess is: You probably has _camelCase_ columns names that are being converted to _snake_case_. (p.s. Underscore is the only special character accepted).

Ah ok, that makes sense the columns have capitalized letters.  So 'S1502_C02_014E' gets converted to 's1502_c02_014_e'.  Thanks for your quick response.  I'll close this issue.
