### ISSUE TITLE
Support for running docker on EKS

### ISSUE THREAD

**Issue by kaushikCanada** [awslabs/aws-data-wrangler#518]
Just like you support running docker on EMR, this could also be another option. Please add support for this so we can do the etl on EKS too. thanks for your great work!

**Comment by benalta** [comment]
Hi Kaushik, Thank you for this one. Did you consider to run your ETL with Glue?
Are u running EMR on EKS? https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks.html

**Comment by kaushikCanada** [comment]
Thanks for your email. I want to use more python libraries than glue
allows. Hence the need for docker.

**Comment by kaushikCanada** [comment]
Plus i want to run spark on k8s

**Comment by benalta** [comment]
can you drop me an email to benaltar@amazon.com? would like to learn more.There is a way to run with Glue custom Python Library. Happy to connect

**Comment by igorborgest** [comment]
@kaushikCanada thanks for reaching out.

To run AWS Data Wrangler on Kubernetes is just a matter to add `pip install awswrangler` into your Dockerfile. I can't see a better way to arrange it.
