### ISSUE TITLE
Very long run time for uploading a dataframe to redshift (didnt complete)

### ISSUE THREAD

**Issue by qemtek** [awslabs/aws-data-wrangler#522]
Hi, I'm trying to upload a DataFrame to Redshift (around 140K rows, 10 columns). I first tried using the wr.redshift.to_sql function, then the wr.redshift.copy function after reading more of the docs. Both times I tried this, it was running for hours before I canceled. Is this normal behaviour? I'm sure I was able to upload much more data than this relatively quickly using the pandas sql functions.

**Comment by igorborgest** [comment]
Hi @qemtek , 

The `we.redshift.to_sql()` is supposed to be used for small data indeed. But the `wr.redshift.copy()` has a high throughput, far away faster than any other method for mid/big datasets. Check out our [tutorial](https://github.com/awslabs/aws-data-wrangler/blob/main/tutorials/008%20-%20Redshift%20-%20Copy%20%26%20Unload.ipynb) for example, we are loading ~4MM rows in ~20 seconds into a small cluster (2 nodes).

It's hard to say what is wrong in your case, but I would start investigating for network issues or bottlenecks.
Are you sure you have your security group open for your application?
Did you tested with a smaller dataframe just to check if your are really able to reach out to the cluster?

**Comment by igorborgest** [comment]
close due inactivity.
