### ISSUE TITLE
New `pandas==1.2.1` not supported

### ISSUE THREAD

**Issue by gvermillion** [awslabs/aws-data-wrangler#525]
**Describe the bug**
As of 20 Jan 2021, there is a new version of `pandas`. Right now, `awswrangler` requires `pandas>=1.1.0,<=1.2.0`. Can this be adjusted to include the newest release?

**Comment by igorborgest** [comment]
Thanks @gvermillion! We will do it for sure!

**Comment by gvermillion** [comment]
Thank you, sir!

**Comment by igorborgest** [comment]
Released on version [2.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.4.0).
