### ISSUE TITLE
Redshift copy() varchar length bug

### ISSUE THREAD

**Issue by data-bot-st** [awslabs/aws-data-wrangler#529]
**Describe the bug**

I'm getting a column length error when writing a dataframe to redshift via copy method. 

```
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'Spectrum Scan Error', 'D': '\n  -----------------------------------------------\n  error:  Spectrum Scan Error\n  code:      15001\n  context:   The length of the data column display_name is longer than the length defined in the table. Table: 256, Data: 320, File name: https://{...}20fee7fe7_0.snappy.parquet?&amp;X-Amz\n  query:     71875904\n  location:  dory_util.cpp:945\n  process:   fetchtask_thread [pid=19465]\n  -----------------------------------------------\n', 'F': '/home/ec2-user/padb/src/sys/xen_execute.cpp', 'L': '9226', 'R': 'pg_throw'}

```

In my code, I'm dynamically setting the column_length with a method like this.

```
column_length =  df['display_name'].str.len().max() + 1
```

In this particular case, this column / series of the DF is returning 218. The error says that column length is 320. 

Under the hood, the copy() method is encoding the str column - which is reasonable but I had to dig under the surface to figure out why I was seeing this issue. 

**To Reproduce**
Steps to reproduce the behavior. Also add details about Python and Wrangler's version and how the library was installed.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by njdanielsen** [comment]
I was able to pin point where this unexpected behavior pops ups.

```
assert selected_df['display_name'].str.len().max() == 218.0

transformed = wr._data_types._cast_pandas_column(selected_df, 'display_name', 'string', 'bytes')

assert transformed['display_name'].str.len().max() == 320.0

```

**Comment by njdanielsen** [comment]
One suggestion for the API is to have an auto_columns_length setting. For determining column lengths on my ETL jobs, I have the below ugly function that essentially does that.  Unfortunately this bug / edge isn't accounted for in this.

```

def get_col_len(series):
    try:
        col_len_plus_one = series.str.len().max() + 1
    except:
        return 256
    if pd.isnull(col_len_plus_one):
        return 256
    return int(max(col_len_plus_one, 256))


def get_varchar_lengths(df):

    varchar_lengths = {}

    for column in df.columns:
        try:
            series = df[column]

            col_len = get_col_len(series)
            if col_len > 256:
                varchar_lengths[column] = col_len
        except Exception as ex:
            logger.error(ex)
            traceback.print_exc()


    return varchar_lengths
```

**Comment by njdanielsen** [comment]
Again super helpful project here!  Has saved me so much time in writing something of lesser quality myself! Thank you!

**Comment by igorborgest** [comment]
Hi @njdanielsen, Thanks for reaching outtoo us  again!

I don't think we have something wrong with the current implementation. The point is that some characters (the special ones) with demand more than 1 byte to be represented. So probably the best way to measure what you want would be:

```py3
df["COLUMN_NAME"].str.encode(encoding="utf-8").apply(len)
```

I think your two functions are quite useful and the `auto_columns_length` a terrific idea. We could start just adding these two functions adapted in our code base and making it available for everybody and then in a second step we can incorporate it into the `copy` fucntion through the `auto_columns_length` argument.

What do you think? Could you open a pull request adding your two functions in our library?

**Comment by igorborgest** [comment]
Closing due the lack of interactions.

**Comment by singhksandeep25** [comment]
Recreating the column in redshift using varchar(max) as column type will solve the issue
