### ISSUE TITLE
Question about Redshift copy_from_files

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#530]
Hello,

Im trying redshift copy_from_files method, using mode upsert, my question is when you delete data and insert again to the destination table, do you do inside a transaction??

Thank you

**Comment by rubenssoto** [comment]
@igorborgest Could you help me with this please?

**Comment by igorborgest** [comment]
Hi @rubenssoto!

Yes, it runs inside a transaction to avoid racing condition with other processes and also to be able to rollback to the original state in case of failure (rollback).

[Reference source code](https://github.com/awslabs/aws-data-wrangler/blob/0fdf395c371bc09a1bf9a83df85d664d23d6af1d/awswrangler/redshift.py#L1156)
