### ISSUE TITLE
pyarrow updated to 3.0.0, awswrangler requires 2.0.0

### ISSUE THREAD

**Issue by gdbassett** [awslabs/aws-data-wrangler#531]
**Describe the bug**
pyarrow was just updated to 3.0.0 but awsrangler requires 2.0.0.  Hopefully a simple dependency fix.

**To Reproduce**
`pip install pyarrow awswrangler`

**Comment by igorborgest** [comment]
Thanks for reporting that @gdbassett. We will release it next week.

**Comment by igorborgest** [comment]
Released on version [2.4.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.4.0).
