### ISSUE TITLE
endpoint_url

### ISSUE THREAD

**Issue by patrick-muller** [awslabs/aws-data-wrangler#538]
**Describe the solution you'd like**
As suggested by Abdel Jaidi ,
When we define a connection to Glue, Athena etc, we need to add a feature to specify the URL for Athena.
For example:

athena_endpoint_url
lakeformation_endpoint_url

**Comment by maxispeicher** [comment]
You should just be able to set the URL in the `awswrangler.config`. Example for athena:
```python
import awswrangler as wr

wr.config.athena_endpoint_url = "my_athena_url"
```

It is also possible to set the URL through environment variables. You can check the global configuration tutorial for more information: https://github.com/awslabs/aws-data-wrangler/blob/main/tutorials/021%20-%20Global%20Configurations.ipynb

**Comment by igorborgest** [comment]
Exactly, it was address on issue #418 .

Thanks @patrick-muller and @maxispeicher !

**Comment by igorborgest** [comment]
p.s. @jaidisido is working on something specific to lakeformation that was not supported yet. Butbesides this one I think we already are well covered for most of the popular services related to our features.

**Comment by jaidisido** [comment]
Yes [Athena](https://github.com/awslabs/aws-data-wrangler/blob/54a266c860a1a9a6d4ec31aaaf6f22ccf92c1b5c/awswrangler/_config.py#L38) is already covered and Lake Formation will be in my PR
