### ISSUE TITLE
read athena sql result to pyspark dataframe

### ISSUE THREAD

**Issue by chanansh** [awslabs/aws-data-wrangler#542]
**Is your idea related to a problem? Please describe.**
today the api returns pandas data frame `read_sql_query` or just keep the data somewhere in parquet format `start_query_execution`.  One would want to read this data into a Spark data frame object as many times Athena is much faster than spark but you would like to feed the first query into a spark ml pipeline or further analytics which cannot be done in Athena. 

**Describe the solution you'd like**
`spark_data_frame = read_sql_query(sql, return_spark=True, spark_session=spark)`

e..g like:
```python
def _query(self, sql):
    if self.return_pandas:  # assume this is small so use ctas = False
        # see https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html
        # use engine_params{'ctas_approach'} to override.
        ctas_apprach = self.engine_params.get('ctas_approach', False)
        return awswrangler.athena.read_sql_query(sql=sql, database=self.database, ctas_approach=ctas_apprach)
    else:  # assume this is a big table
        ctas_apprach = self.engine_params.get('ctas_approach', True)  # assume this is large, use parquet
        query_id = awswrangler.athena.start_query_execution(sql=sql, database=self.database)
        awswrangler.athena.wait_query(query_execution_id=query_id)
        query_meta = awswrangler.athena.get_query_execution(query_execution_id=query_id)
        result_path = query_meta['ResultConfiguration']['OutputLocation']
        if self.spark is None:
            self.spark = get_spark() # dynamically get spark session if missing
        return self.spark.read.parquet(result_path)
```

**Comment by mattiamatrix** [comment]
Why don't you just use `spark.createDataFrame()`?

**Comment by igorborgest** [comment]
`spark.createDataFrame()` is a good alternative, but he would read BIG results faster using Spark directly than using Pandas and then converting to Spark.

It makes sense indeed. However we decided not to directly support Spark since version 1.0. This required a lot of effort to maintain testing and distribution. And since the adoption of the Pandas community has always been much greater for Wrangler, we prefer to focus our energy on that.

**Comment by igorborgest** [comment]
@chanansh thanks for reaching out to us! Feel free to submit other ideas.
