### ISSUE TITLE
include column names into the insert when use to_sql 

### ISSUE THREAD

**Issue by yyie** [awslabs/aws-data-wrangler#545]
Hi, I found that if you have an existing table and want to append a dataset using "to_sql" without including the primary key, the INSERT fails. This is because the name of the columns is not included in the generated INSERT.

The INSERT used in this moment has this fomr

`sql: str = f"INSERT INTO {table_identifier} VALUES ({placeholders})"`

It should be something like 

`sql: str = f"INSERT INTO {table_identifier} ({column_names}) VALUES ({placeholders})"`

**Comment by maxispeicher** [comment]
I've tried to provide a fix for the scenario that you've mentioned. Could you test if it works for you this way?

```
pip uninstall awswrangler -y
pip install git+https://github.com/maxispeicher/aws-data-wrangler.git@to_sql_use_column_names
```

```python
import awswrangler as wr
...
wr.postgresql.to_sql(..., use_column_names=True)
```
