### ISSUE TITLE
Meet No module named 'Cython' while install in AWS EMR with pip

### ISSUE THREAD

**Issue by dragonH** [awslabs/aws-data-wrangler#546]
**Describe the bug**

Meeting Error "No module named 'Cython'"

while installing awswrangler with pip(pip3) in EMR

i think there's something wrong with the newest version

cause previous is ok

![image](https://user-images.githubusercontent.com/18332044/106845118-33f26680-66e5-11eb-8a13-28d675e5c1ce.png)

**To Reproduce**

Use pip(pip3) to install awswrangler in AWS EMR

```
pip install awswrangler
```

**Comment by hwangji** [comment]
Same thing happening with Glue ETL Jobs using --additional-python-modules, likely from introducing C libraries.

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html

**Comment by igorborgest** [comment]
Hi @dragonH @hwangji , thanks for reporting it.

**For platforms without PyArrow 3 support (e.g. [EMR](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#emr-cluster)):**

`pip install pyarrow==2 awswrangler`

Or specifically for [Glue PySpark Job](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#aws-glue-pyspark-jobs):

- **Key:** `--additional-python-modules`
   **Value:** `pyarrow==2,awswrangler`

**Comment by igorborgest** [comment]
P.S. Also consider to freeze the Wrangler version for productive environments (e.g. `awswrangler==2.3.0`)

**Comment by dragonH** [comment]
> P.S. Also consider to freeze the Wrangler version for productive environments (e.g. `awswrangler==2.3.0`)

yes

this is what I did to overcome the issue

thanks @igorborgest 😊

**Comment by DarkxNess** [comment]
> P.S. Also consider to freeze the Wrangler version for production environments (e.g. `awswrangler==2.3.0`)

This is the solution!!

**Comment by brifordwylie** [comment]
To anyone coming to this issue in late July 2021... there's an issue with awsrangler==2.10.0... you get a cython version error if you try to use it in an AWS Glue Job.. so use this

Key: `--additional-python-modules`
Value: `pyarrow==2,awswrangler==2.9.0`
