### ISSUE TITLE
Provide rendered static HTML page of notebooks

### ISSUE THREAD

**Issue by impredicative** [awslabs/aws-data-wrangler#551]
**Is your feature request related to a problem? Please describe.**

The various notebooks on GitHub very often don't seem to render. I am unable to see them. The following error is shown instead:

> Sorry, something went wrong. Reload?

**Describe the solution you'd like**

As a more reliable alternative, publish and provide a static HTML rendered webpage of each notebook along with your documentation. Eliminate the dependency on GitHub rendering the notebooks.

**Comment by igorborgest** [comment]
Released on version [2.5.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.5.0)!
