### ISSUE TITLE
Unable to connect to mysql using ssl

### ISSUE THREAD

**Issue by mshober** [awslabs/aws-data-wrangler#554]
I discovered that connections to mysql fail when using a database user that requires ssl, even if the connection info in Glue specifies that ssl is required and supplies a relevant certificate. 

The expected behavior would be for wrangler to pass any ssl properties from the Glue connection to pymsql when establishing the connection, but that does not appear to be happening.

**To Reproduce** (Using environment from cloudformation)
```python
# Connect using master user which by default doesn't require ssl
con = wr.mysql.connect("aws-data-wrangler-mysql")
assert con.ssl is False

# Require SSL and attempt to reconnect
con.cursor().execute("ALTER USER 'test'@'%' REQUIRE SSL")
con = wr.mysql.connect("aws-data-wrangler-mysql")  # fails
```
_Error Output_:

    pymysql.err.OperationalError: (1045, "Access denied for user 'test'@'<ip-address>' (using password: YES)")

_awswrangler_: 2.4.0

**Comment by kukushking** [comment]
I raised a [PR](https://github.com/PyMySQL/PyMySQL/pull/980) with `PyMySQL` to support passing the CA cert via `cadata` (I'd hate it if the library I was using was creating temp files with downloaded certs). Once it's merged, should be an easy fix to fetch the cert from Glue and pass it over to MySQL.

**Comment by kukushking** [comment]
@mshober Hi Matt, FYI the fix was merged and should be included in next release. Meanwhile, you can test it by installing development version of the wrangler:

```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```

**Comment by jaidisido** [comment]
Now covered in [2.8.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.8.0).
