### ISSUE TITLE
Multiple LIMIT statements in postgres SQL query

### ISSUE THREAD

**Issue by Dhruv-Shah913** [awslabs/aws-data-wrangler#555]
When try to use the make a postgres sql query through aws wrangler like this:
```
df = wr.postgresql.read_sql_query(
sql= "(SELECT * FROM LJIFMXTTLP LIMIT 10) LIMIT 250",
con=conn)
```

 I get the error: 
{'S': 'ERROR', 'V': 'ERROR', 'C': '42601', 'M': 'multiple LIMIT clauses not allowed', 'P': '43', 'F': 'gram.y', 'L': '15889', 'R': 'insertSelectOptions'}.

I know having 2 LIMIT clauses in a row may look a bit silly, but I need it for a specific application. Essentially, the bracketed portion of the above query can change, but I need to ensure that at most 250 rows are retrieved, regardless of what the bracketed query is. Is there any workaround for this using awswranger? 

I am using aws wrangler version 2.4.0 on python3.7

**Comment by maxispeicher** [comment]
Could you just combine two `SELECT`?
```sql
SELECT * FROM (SELECT * FROM LJIFMXTTLP LIMIT 10) as subset LIMIT 250;
```
