### ISSUE TITLE
Installing on ARM Instances

### ISSUE THREAD

**Issue by reneincer** [awslabs/aws-data-wrangler#557]
Hi there, 

I have problems installing AWS Data Wrangler on ARM instances, because PyArrow is not properly installed. Do you have in your roadmap this update? I have searched for this problem and I realized that there is not a pip package for arm. Do you know how can I install it?

Thanks!

**Comment by cojmcc** [comment]
Same issue here. Specifically when trying to install on a Graviton2 (m6g) class of instance.

**Comment by maxispeicher** [comment]
You could maybe try installing `pyarrow` first with the steps that are given in this gist: https://gist.github.com/eladroz/b9437249a76de2b394d54e646d53ec5e.

**Comment by cojmcc** [comment]
PyArrow 4.0.0 is out now with aarch64 wheel support which seems to resolve the issue as I'm now able to install it on a Graviton2 instance. AWS Data Wrangler forces <3.1.0 however, so it will need to be updated to support the new version. Unfortunately I'm quite unskilled in how to make the necessary changes to do them so any help is much appreciated.

Arrow issue for reference https://github.com/apache/arrow/pull/9285

**Comment by maxispeicher** [comment]
@cojmcc You basically just need to adapt the version in the `requirements.txt` file. You can have a look in the linked PR 🙂

**Comment by jaidisido** [comment]
Thank you @cojmcc. As suggested, upgrading to Arrow 4.0.0 seems to have fixed the issue. I have tested on an ARM EC2 instance and was able to install and load the library. To test it:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
until it's included in the next release.

**Comment by cojmcc** [comment]
Thanks @maxispeicher & @jaidisido for the quick action on this! I was able to get this working successfully on my EMR Graviton based cluster without any issue.
