### ISSUE TITLE
enable upload download of object via aws-data-wrangler s3 api

### ISSUE THREAD

**Issue by chanansh** [awslabs/aws-data-wrangler#563]
**Is your feature request related to a problem? Please describe.**
As a Data Scientist, I would like to upload and download objects to and from s3 with the awswrangler API instead of using s3fs or others.

**Describe the solution you'd like**
```
from awswrangler import s3
s3.copy_objects('/tmp/model.binary', 's3://bucket/models/')
s3.copy_objects('s3://bucket/models/', '/tmp/model2.binary')
```

**Comment by maxispeicher** [comment]
You can use `s3.download()` and `s3.upload()` for down- and uploading files.

Download: https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.s3.download.html#awswrangler.s3.download
Upload: https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.s3.upload.html#awswrangler.s3.upload

**Comment by chanansh** [comment]
https://aws-data-wrangler.readthedocs.io/en/stable/api.html does not appear to show this API. oh it's 2.3

**Comment by mattiamatrix** [comment]
Linked to this topic, I think it would be interesting to also have a function that does not force you to store the object downloaded but instead returns a buffer or a byte array. 

It would be useful when the file is not supported by Pandas. Like with images.

**Comment by danielwo** [comment]
You can do this, as it accepts a file-like object in binary mode (this includes a bytearray)

For example:
```
bucket = "mybucket"
path = f"s3://{bucket}/img/myplot.png"
img_stream = io.BytesIO()
wr.s3.download(path=path, local_file=img_stream)
img = PIL.Image.open(img_stream)
```

**Comment by mattiamatrix** [comment]
Amazing, thank you @danielwo!
