### ISSUE TITLE
pandas.to_parquet writes out parquet files with data types not supported by athena/glue

### ISSUE THREAD

**Issue by jasonamyers** [awslabs/aws-data-wrangler#57]
session.pandas.to_parquet writes out parquet files with data types not support by athena/glue, which results in things like `HIVE_BAD_DATA: Field primary_key's type INT64 in parquet is incompatible with type string defined in table schema`

**Comment by igorborgest** [comment]
Hi @jasonamyers! Thanks for open this.

Do you have more context? I would like to reproduce your issue here in my environment.

**Comment by jasonamyers** [comment]
I'll make a good test case and post it back.

**Comment by igorborgest** [comment]
@jasonamyers thank you very much!

**Comment by jasonamyers** [comment]
I've been able to declare better types in my dataframe and get those to go all the way through to athena properly, so I'm going to close this issue for now.  I just expected that this would take care of that for me, which wasn't a good expectation on my part. Thank you for this library!
