### ISSUE TITLE
Use bump2version for changing version numbers

### ISSUE THREAD

**Issue by maxispeicher** [awslabs/aws-data-wrangler#573]
**Is your idea related to a problem? Please describe.**
Right now there are multiple instances of the current version in all kinds of files and places (README, docstrings, etc.). When preparing a new release all these version numbers need to be changed.

**Describe the solution you'd like**
Add `bump2version` with a correct configuration which will update all version numbers.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by igorborgest** [comment]
Released on version [2.5.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.5.0)!
