### ISSUE TITLE
Be able to configure ctas temporary database name in athena.read_sql_query

### ISSUE THREAD

**Issue by dimapod** [awslabs/aws-data-wrangler#576]
**Problem:**
In `Athena.read_sql_query()` when using `ctas_approach` the temporary table will be created in the **context** database. The problem is that sometimes it is not possible, as the write access to this database is restricted (in our case we have datalake read-only databases for example). 

**Enhancement idea:**
It might be interesting to pass the additional attibute `ctas_temp_database_name` to be able to specify the temporary database (like it is already done for temporary table name).

What do you think?

**Comment by Reeska** [comment]
Hi,

I'm interested by this enhancement too, and I think it could be interesting to set those properties (`ctas_temp_database_name` and `ctas_temp_table`) through environment variables.

What do you think ?

**Comment by jaidisido** [comment]
Covered in release [2.6.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.6.0)
