### ISSUE TITLE
Decimal DataType in Athena is not Supported

### ISSUE THREAD

**Issue by hhsurap** [awslabs/aws-data-wrangler#58]
Athena has a table with datatype decimal (13,4)
Out of the box aws wrangler library is not supporting this.
raise UnsupportedType(f"Unsupported Athena type: {dtype}")
awswrangler.exceptions.UnsupportedType: Unsupported Athena type: decimal

**Comment by danielcarletti** [comment]
I would add that Redshift is also missing DECIMAL and NUMERIC types.
Trying to use cast_columns with types DECIMAL and NUMERIC fails:
`Unsupported Redshift type: DECIMAL`

**Comment by igorborgest** [comment]
Hi @hhsurap and @danielcarletti!

Happy to say we already have decimal support implemented, will be released in the next release tomorrow.

Thanks!
