### ISSUE TITLE
wr.s3.read_parquet() unexpected type casting to pandas dtypes

### ISSUE THREAD

**Issue by jmahlik** [awslabs/aws-data-wrangler#580]
**Describe the bug**
Wrangler casts all data datatypes to the pandas nullable version with no option to disable this behavior.  [`pd.read_parquet()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html) has `use_nullable_dtypes` defaulted to False which disables this behavior. awswrangler has no such option.

This results in differences in datatypes when reading with pd/pyarrow vs. wrangler. It can cause issues for users relying on specific data types. Many modeling libraries rely on raw numpy arrays, so this could impact  users relying on the original dtypes.

[Specific loc](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_read_parquet.py#L260)

Willing to take on a PR to add the option if needed. Wondering if the default should be to not cast dtype?  Don't know if that would be considered a breaking change or a bug fix?

**To Reproduce**
Version: 2.4.0

```
import awswrangler as wr
import boto3
from moto import mock_s3
import numpy as np
import pandas as pd

# Setup
df_example = pd.DataFrame({"a": [0, 1, 1, 2]}, dtype=np.int8)

df_example.to_parquet("./np-data.parquet")
df = pd.read_parquet("./np-data.parquet")

with mock_s3():
    client = boto3.client("s3")
    client.create_bucket(Bucket="bucket")
    wr.s3.upload("./np-data.parquet", "s3://bucket/np-data.parquet")
    df_wr = wr.s3.read_parquet("s3://bucket/np-data.parquet")

# Note the differences
df["a"].dtype
df_wr["a"].dtype

# This is ok since it's np datatypes
np.nanstd(df["a"])

# Fails, is a pandas nullable dtype
np.nanstd(df_wr["a"])

# Same behavior with use_nullable_dtypes=True
df_bad = pd.read_parquet("./np-data.parquet", use_nullable_dtypes=True)
np.nanstd(df_bad["a"])
```

Outputs
```
In [61]: df["a"].dtype
Out[61]: dtype('int8')

In [62]: df_wr["a"].dtype
Out[62]: Int8Dtype()

In [64]: np.nanstd(df["a"])
Out[64]: 0.7071067811865476

In [65]: # Fails, is a pandas nullable dtype
In [66]: np.nanstd(df_wr["a"])
...
AttributeError: 'float' object has no attribute 'ndim'

In [69]: df_bad = pd.read_parquet("./np-data.parquet", use_nullable_dtypes=True)
In [70]: np.nanstd(df_bad["a"])
...
AttributeError: 'float' object has no attribute 'ndim'

```

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
@jmahlik thanks for flagging this. The reason why a casting `types_mapper` is used when converting from Arrow to Pandas is because without it the returned column type can be completely wrong in certain cases. For instance, if you were to run your same example adding a null value to the column:

`df_example = pd.DataFrame({"a": [0, 1, 1, 2, None]}, dtype=np.int8)`

then `df["a"].dtype` would return `float64` as a type which is incorrect.

That being said, I agree that a flag to disable the casting behaviour is a good idea. So we will add it in the next release (2.6.0)

**Comment by jmahlik** [comment]
> @jmahlik thanks for flagging this. The reason why a casting `types_mapper` is used when converting from Arrow to Pandas is because without it the returned column type can be completely wrong in certain cases. For instance, if you were to run your same example adding a null value to the column:
> 
> `df_example = pd.DataFrame({"a": [0, 1, 1, 2, None]}, dtype=np.int8)`
> 
> then `df["a"].dtype` would return `float64` as a type which is incorrect.
> 
> That being said, I agree that a flag to disable the casting behaviour is a good idea. So we will add it in the next release (2.6.0)

Makes sense. Thanks in advance for adding.

**Comment by jaidisido** [comment]
Covered in release [2.6.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.6.0)
