### ISSUE TITLE
Enforcement of to_parquet(sanitize_columns=True) break my dataset

### ISSUE THREAD

**Issue by pr0ximo** [awslabs/aws-data-wrangler#582]
I have a dataset that has two specific columns that are in my dataframe:
Engine_speed
EngineSpeed

I am trying to write a parquet file to a glue database table, and there is specific enforcement for sanitize_columns=True if any database parameters are passed.

Obviously this will cause duplicated columns with the removal of camel case and addition of underscores:
engine_speed
engine_speed
 
In my use case, I have users (picky engineers) who do not want these variable names changed for years of knowing what these variables mean from a physical standpoint.  I would really like to avoid making an identify column and going down that road.
 Is there a special reason why sanitize_columns=True must be enforced with database usage, or is it just a best practices thing?

**Comment by maxispeicher** [comment]
There is already an issue regarding the possibility to disable the `sanitize_columns` behavior: #533 
However it's part of the `3.0.0` Milestone / release, which will still take some time.
