### ISSUE TITLE
Error when writing to parquet for columns of struct type

### ISSUE THREAD

**Issue by luminita** [awslabs/aws-data-wrangler#585]
**Describe the bug**
I have a glue table including a column of type Array<struct<A:string, B:int>>. If I read the data in a data frame, and then try to write it again as parquet, all values of A and B gets null. 

**To Reproduce**
source_prefix = "source/dt=2021-01-01/" # here there is a parquet with a column of type Array<struct<A:string, B:int>>
destination_prefix = "destination/dt=2021-01-01/"
df = wr.s3.read_parquet(source_prefix, boto3_session=boto3_session, dataset=True, validate_schema=True)
dtype = wr.s3.read_parquet_metadata(source_prefix, boto3_session=boto3_session)[0]
wr.s3.to_parquet(df,
                         path=destination_prefix,
                         mode="overwrite_partitions",
                         dataset=True,
                         compression="snappy",
                         boto3_session=boto3_session,
                         max_rows_by_file=None,
                         dtype=dtype
                         )

--> In df I see the correct values of the column of type Array<struct> (with type object in pandas). However, all the values are set to null after writing to parquet destination.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
Hi @luminita, nested types are not always consistent and pandas don't support them natively. Wrangler makes a best effort to try to infer them through PyArrow but there are always edge cases. If you can share a minimal example we can look into it

**Comment by luminita** [comment]
Thanks for the quick reply.

To reproduce the error:
Below are two parquet files as created by AWS firehose. Place them at an s3 location such  as `s3://bucket_name/test/dest/dt=2021-01-07/`. Then run the following: 

```
session = boto3.Session(profile_name=your_profile, region_name="eu-north-1")
df = wr.s3.read_parquet("s3://bucket_name/test/dest/dt=2021-01-07/", boto3_session=session, dataset=True, validate_schema=True)
dtype = wr.s3.read_parquet_metadata("s3://bucket_name/test/dest/dt=2021-01-07/", boto3_session=session)[0]
wr.s3.to_parquet(df, path="s3://bucket_name/test/dest/dt=2021-01-08/", mode="overwrite_partitions",
                 dataset=True, compression="snappy", boto3_session=session, dtype=dtype)
df2 = wr.s3.read_parquet("s3://luminita-820918/test/dest/dt=2021-01-08/", boto3_session=session, dataset=True, validate_schema=True)
```

Now if you check the column onboardcountdetails in df and df2. While in df it looks like this: 
`[{'CarRef': 'A', 'OnboardCount': 10}, ...`

In df2 the fields are empty 
`[{'carref': None, 'onboardcount': None}, ...`

So the only thing I am doing is merging two parquet files in one, then read again the merged parquet. 

I am using awswrangler 2.3.0 and python 3.8.2
Let me know if you need additional information. 

Thanks




[Archive.zip](https://github.com/awslabs/aws-data-wrangler/files/6118479/Archive.zip)

**Comment by jaidisido** [comment]
Alright, got around testing this and you are right @luminita it's a bug on our end, thank you for raising it.

In short, it's caused by this [operation](https://github.com/awslabs/aws-data-wrangler/blob/cf99eafb7b0f6a0a46a1c29357e1ed5d5a5a4680/awswrangler/_data_types.py#L256) on the `dtype` supplied. The recursion call in the function coupled with the `lower` method is causing the return type to not match the original type.

I will raise a PR to fix this in the next release, in the meantime you can fix your issue by simply not passing the dtype:
```
wr.s3.to_parquet(df, path="s3://bucket_name/test/dest/dt=2021-01-08/", mode="overwrite_partitions",
                 dataset=True, compression="snappy", boto3_session=session)
```
not ideal, but will be corrected in the next version

**Comment by luminita** [comment]
Great that this got fixed! When will it be released? I really need to use dtype to get the data types right

**Comment by jaidisido** [comment]
It will be available in the next release 2.7.0. We cannot commit to a date but our releases are usually monthly.

In the meantime, you can also test it directly by installing wrangler based on the current main branch:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```

**Comment by jaidisido** [comment]
Covered in [2.7.0 release](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.7.0)

**Comment by adadouche** [comment]
Hi @jaidisido 
I came across a similar issue with a struct that include a decimal(6,3) field: 
                {
                    "Type": "struct<3h:decimal(6,3)>", 
                    "Name": "rain"
                }, 
The _split_struct function is going to split it using the comma, but it shouldn't.
It should instead use the ":" to determine how many fields are in there then if there is more than one, split using the ":" and ",".

How do you want to proceed on this? Shall I open a new issue?
