### ISSUE TITLE
s3.to_parquet overwrite changing the Glue table location

### ISSUE THREAD

**Issue by kamipatel** [awslabs/aws-data-wrangler#589]
Hello,
My use-case is store the dataframe in the S3 path by overwriting existing parquet files in the folder. So sure enough I used  mode="overwrite". Unfortunately this overwrite Glue table's Location as well which creates issues with my Athena queries. How do I prevent it from overwriting Glue Table location value? 
wr.s3.to_parquet(
    df=df,
    path="s3://app/log/todaydate",
    dataset=True,
    database="pi_database",
    table="pi_log_table",
    mode="overwrite"
)
My workaround is  to 
wr.s3.delete_objects("s3://app/log/todaydate")
and use Append. "Overwrite" seems to create issues as mentioned above.
Am I missing something? Is there a way I can avoid wr.s3.delete_objects("s3://app/log/todaydate")

**Comment by jaidisido** [comment]
Hi @kamipatel,

You don't have to pass a `database` and `table` when calling `dataset=True`. So this statement would be valid:
```
wr.s3.to_parquet(
    df=df,
    path="s3://app/log/todaydate",
    dataset=True,
    database="pi_database",
    table="pi_log_table",
    mode="overwrite"
)
```
at which point you are not interacting with the Glue catalog at all.
