### ISSUE TITLE
date type as partition key gets written as timestamp

### ISSUE THREAD

**Issue by chtorr** [awslabs/aws-data-wrangler#59]
Hi!  I'm trying to write out a partitioned parquet dataset using a date column with values like `YYYY-MM-DD` as the partition key.  However, the partition values in the s3 keys get written as `YYYY-MM-DD 00:00:00`.  The type is `date` in Glue, and Athena throws errors about invalid partition keys.  `date` types in non-partition columns do not appear to have any issues, though.

Here's a trivial example:

```python
import pandas as pd
import awswrangler
session = awswrangler.Session()

# create some dummy data
data = {
    'col1': [
        'val1',
        'val2',
    ],
    # date column to see valid dates
    'datecol': [
        '2019-11-09',
        '2019-11-08'
    ],
    # dates in partition column to see invalid date strings
    'partcol': [
        '2019-11-09',
        '2019-11-08'
    ]
}

df = pd.DataFrame(data)
# cast date columns to pandas datetime, similar to the result of read_csv() with parse_dates
df = df.astype({'datecol': 'datetime64', 'partcol': 'datetime64'})

# tell Athena what types you want
schema = {
    'col1': 'string',
    'datecol': 'date',
    'partcol': 'date',
}

session.pandas.to_parquet(
    dataframe=df,
    database="default",
    path="s3://some-bucket/some-path/",
    partition_cols=['datecol'],
    table="debug-date-partitions",
    mode="overwrite_partitions",
    cast_columns=schema
)
```

Thanks again for the great library!

**Comment by igorborgest** [comment]
Hey @chtorr, thank again to help us!

Today we are used to do that casting directly to datetime.date in pandas before the write:

```py3
df = pd.DataFrame({
    "col1": ["val1", "val2"],
    "datecol": ["2019-11-09", "2019-11-08"],
    'partcol': ["2019-11-09", "2019-11-08"]
})
df["datecol"] = pd.to_datetime(df.datecol).dt.date
df["partcol"] = pd.to_datetime(df.partcol).dt.date
awswrangler.Session().pandas.to_parquet(
    dataframe=df,
    database="...",
    path="s3://...",
    partition_cols=["datecol"],
    table="...",
    mode="..."
)
```

This will work fine!

But of course that your approach should also work, so I will fix that until the end of the day and release that in a new version!

**Comment by igorborgest** [comment]
Now with the new version 0.0.18 you can simple does:

```py3
df = pd.DataFrame({
    "col1": ["val1", "val2"],
    "datecol": ["2019-11-09", "2019-11-08"],
    'partcol': ["2019-11-09", "2019-11-08"]
})
awswrangler.Session().pandas.to_parquet(
    dataframe=df,
    database="...",
    path="s3://...",
    partition_cols=["datecol"],
    table="...",
    mode="...",
    cast_columns={
        "datecol": "date",
        "partcol": "date"
    }
)
```

**Comment by Samreay** [comment]
Looks like since this issue was raised, the cast_columns kwarg has been removed, but the same odd behaviour about date formatting in partitions is there.

Does anyone know how we should specify the schema using the current version of the code?

`wr.s3.to_parquet` doesn't seem to have any relevant kwargs.

**Comment by nowiczka** [comment]
The `cast_columns` property has been replaced by the `dtype` property, which appears to function similarly according to the [AWS Wrangler documentation](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html). However, when I ran my Glue job using the `dtype` property, it kept converting my column to a string. Finally, I resolved the issue by explicitly setting the date type in the Glue Table definition to date type... Hope it will help someone
