### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by kat-osad** [awslabs/aws-data-wrangler#593]
I am trying to install awswrangler into my pipenv environment and am seeing dependency incompatibilities:
<img width="594" alt="Screen Shot 2021-03-09 at 4 53 48 PM" src="https://user-images.githubusercontent.com/75644789/110543557-7948f000-80f8-11eb-8b06-0eda6c7ad485.png">

It seems that awswrangler requires:
- redshift-connector, which in turn requires botocore<1.20.0,>=1.19.8
- boto3, which requires botocore<1.21.0,>=1.20.24
There's no overlap between these versions and I can't find a way to get around this issue. 

For context, I am running python3.7 with pipenv version 2020.11.15 on MacOSX Catalina.

To reproduce the issue:
1. create a pipenv file with the following:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pandas = "*"
simplejson = "*"
numpy = "*"
awswrangler = "*"

[requires]
python_version = "3.7"
```

2. run `pipenv install`

**Comment by igorborgest** [comment]
Hi! Thanks for reaching out @kat-osad !

It seems to be a conflict in a underling dependency (`redshift_connector`) that had a micro upgrade 2 days ago.
We will reach out to redshift_connector team to fix it.

Meanwhile you can explicitly install the previous `redshift_connector` before install Wrangler to overcome it on `pipenv`.

```sh
pipenv install redshift_connector==2.0.874 awswrangler
```

**Comment by Brooke-white** [comment]
Hey @kat-osad ,

Thank you for identifying this issue, I am a maintainer for `redshift_connector`. We have released a new version of `redshift_connector==2.0.876` resolving the dependency issue. I have verified `pipenv install` can execute successfully given the pipenv file provided above.

**Comment by igorborgest** [comment]
I've also tested it here and everything seems fine.

Thank you very much @Brooke-white 🚀

**Comment by kat-osad** [comment]
thank you so much for the quick turnaround!
