### ISSUE TITLE
s3.to_parquet() support fixating parquet schema

### ISSUE THREAD

**Issue by rafaelmotaalves** [awslabs/aws-data-wrangler#594]
**Is your idea related to a problem? Please describe.**
When writing Parquet files to S3 I had some problems with the automatically inferred types. As a workaround, I converted the pandas Dataframe to a Pyarrow.Table passing a pyarrow.Schema, and used s3fs to write the Parquet file to S3. It would be nice to use the aws-data-wrangler s3.to_parquet() method to do this kind of operation.

**Describe the solution you'd like**
It would be nice to have an optional `schema`  parameter so that we could pass a Pyarrow.Schema instead of being inferred from the Pandas data frame types.

**Comment by maxispeicher** [comment]
Have you tried using the `dtype` arguemnt of `s3.to_parquet()`. It let's you define the desired datatype for certain columns, e.g. in your case the columns where the type inference fails. An example taken from the [documentation](https://aws-data-wrangler.readthedocs.io/en/2.5.0/stubs/awswrangler.s3.to_parquet.html):
```python
>>> import awswrangler as wr
>>> import pandas as pd
>>> wr.s3.to_parquet(
...     df=pd.DataFrame({
...         'col': [1, 2, 3],
...         'col2': ['A', 'A', 'B'],
...         'col3': [None, None, None]
...     }),
...     path='s3://bucket/prefix',
...     dataset=True,
...     database='default',  # Athena/Glue database
...     table='my_table'  # Athena/Glue table
...     dtype={'col3': 'date'}
... )
{
    'paths': ['s3://.../x.parquet'],
    'partitions_values: {}
}
```

**Comment by rafaelmotaalves** [comment]
Yes, I think this will solve the problem. From the documentation, I thought that this parameter would only set the types for the Athena/Glue schema. Thanks, @maxispeicher!
