### ISSUE TITLE
Encountered 403 forbidden error

### ISSUE THREAD

**Issue by esaeki** [awslabs/aws-data-wrangler#597]
Hello, 

I would like to import some data from AWS S3 to Lambda by using Athena and Data Wrangler. I wrote some codes to import data as follows, but encountered 403 forbidden error. In general, what is the cause of this issue? 

---
def lambda_handler(event, context):

    df = wr.athena.read_sql_query('''SELECT * FROM table_name WHERE ...''', database="sample_db")

**Comment by maxispeicher** [comment]
`403` indicates that some of the operations that `awswrangler` performs are forbidden or not allowed for the Lambda execution role. Have you checked if the role has the permissions needed for the query (e.g. `athena:*`, `s3` permissions for the bucket where the data is stored, ...).

If you could provide some more information about the permission error respectively the exact error message it would be easier to track down the exact issue 🙂.

**Comment by esaeki** [comment]
Thank you for your response. I am afraid I cannot provide detailed information because of the security reason, and will use pyathena instead of Datawrangler this time.
