### ISSUE TITLE
unable to cast partition column final Athena type

### ISSUE THREAD

**Issue by chtorr** [awslabs/aws-data-wrangler#60]
Hello!  I have need to cast the final Athena type of a partition column to `date`, however dropping the partition columns from the dataframe subgroup occurs before `cast_columns` is applied (here: https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/pandas.py#L762).  This has 2 effects:

1) I get a `ValueError: '<partition column name>' is not in list` if `cast_columns` includes the partition key(s).  The line that throws the exception is https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/pandas.py#L892

2) If I omit the partition column from `cast_columns` things work, but then I am unable to get the final desired Athena type to the bit that writes the glue table (https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/pandas.py#L674).

It would be great if the library could handle dropping the partition column names from `cast_columns` when casting the partition subgroups while ensuring the partition column types make it to the `self._session.glue.metadata_to_glue` call.

(Side note: trying a naive patch locally and trying it out leads to issue https://github.com/awslabs/aws-data-wrangler/issues/59 about `date` type formatting in partition keys)

Thanks!

**Comment by igorborgest** [comment]
@chtorr Yeah, I was able to replicate this behaviour here, working on the fix!

**Comment by igorborgest** [comment]
```py3
df = pd.DataFrame({
    "col1": ["val1", "val2"],
    "datecol": ["2019-11-09", "2019-11-08"],
    'partcol': ["2019-11-09", "2019-11-08"]
})
awswrangler.Session().pandas.to_parquet(
    dataframe=df,
    database="...",
    path="s3://...",
    partition_cols=["datecol"],
    table="...",
    mode="...",
    cast_columns={
        "datecol": "date",
        "partcol": "date"
    }
)
```
