### ISSUE TITLE
Reading Multiple Parquet Files by Folder Path

### ISSUE THREAD

**Issue by thufirtan** [awslabs/aws-data-wrangler#607]
I am trying to read multiple parquet files e.g. s3://bucket/2021/03/16/a.pq, s3://bucket/2021/03/16/b.pq, s3://bucket/2021/03/17/c.pq 

I am getting a ClientError: An error occurred (404) when calling the HeadObject operation: Not Found if I try to wr.s3.read_parquet(path=['s3://bucket/2021/03/16/', 's3://bucket/2021/03/17/']) It seems I would need to list the full path to each specific parquet file instead?

**Comment by jaidisido** [comment]
@thufirtan from the [docs](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet.html#awswrangler.s3.read_parquet), the `path` argument accepts either an S3 **prefix** (str: e.g. "s3://bucket/2021/03") or a list of S3 **objects** (list: e.g. ["s3://bucket/2021/03/16/a.pq", "s3://bucket/2021/03/16/b.pq", "s3://bucket/2021/03/17/c.pq"]). First option will return all objects under the prefix.

You can also take advantage of these optional arguments to further constraint your query:
- **path_suffix** (Union[str, List[str], None]) – Suffix or List of suffixes to be read (e.g. [“.gz.parquet”, “.snappy.parquet”]). If None, will try to read all files. (default)
- **partition_filter** (Optional[Callable[[Dict[str, str]], bool]]) – Callback Function filters to apply on PARTITION columns (PUSH-DOWN filter). This function MUST receive a single argument (Dict[str, str]) where keys are partitions names and values are partitions values. Partitions values will be always strings extracted from S3. This function MUST return a bool, True to read the partition or False to ignore it. Ignored if dataset=False. E.g lambda x: True if x["year"] == "2020" and x["month"] == "1" else False
