### ISSUE TITLE
Support for upserting to MySQL

### ISSUE THREAD

**Issue by senorkrabs** [awslabs/aws-data-wrangler#608]
**Is your feature request related to a problem? Please describe.**
For ETL jobs I would like the ability to upsert a Data Frame into an existing table, rather than overwriting or append. The mysql class doesn't have this option at the moment, as far as I can tell.

**Describe the solution you'd like**
- An optional parameter `upsert` when calling `to_sql`
- In researching, appending an `ON DUPLICATE KEY` statement to the SQL should allow for upserting in most situations

I'm planning to investigate and test this a bit and, if successful, will make a PR.

**Comment by mattboyd-aws** [comment]
Could you reassign to mattboyd-aws? That’s my work account, sorry for the confusion :)

**Comment by jaidisido** [comment]
Covered in [2.7.0 release](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.7.0)
