### ISSUE TITLE
Parameterized queries in Athena are not quoted properly

### ISSUE THREAD

**Issue by zdk123** [awslabs/aws-data-wrangler#609]
**Describe the bug**
According to the docs for [read_sql_query](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html), bind parameters are supported:

> params (Dict[str, any], optional) – Dict of parameters that will be used for constructing the SQL query. Only named parameters are supported. The dict needs to contain the information in the form {‘name’: ‘value’} and the SQL query needs to contain :name;.

However execution results in an error.

**To Reproduce**
Using the code example from the docs:
```py
df = wr.athena.read_sql_query(
    sql="SELECT * FROM my_table WHERE name=:name;",
    params={"name": "filtered_name"}
)
```

We can see from the Athena console that the query that was actually executed was:

```sql
SELECT * FROM my_table WHERE name=filtered_name
```

but we expected:
```sql
SELECT * FROM my_table WHERE name='filtered_name'
```

**Comment by maxispeicher** [comment]
You're right `awswrangler` does not consider datatypes of the table for the parameter insertion right now. If you know that `name` is a `varchar` column you can use:
```python
df = wr.athena.read_sql_query(
    sql="SELECT * FROM my_table WHERE name=:name;",
    params={"name": "'filtered_name'"}
)
```

**Comment by jaidisido** [comment]
I understand your point, but consider this use case:
```
wr.athena.read_sql_query(
    sql="SELECT * FROM my_table WHERE id=:id;",
    database="aws_data_wrangler",
    params={"id": "'1'"}
)
```
because the `id` column is an integer, the above would fail. It would mean that we would somehow need to infer the type of each column passed in the `params` argument before building the query which is too complex. Instead, the aim is just to help the user reconstruct the query exactly the same way they would define it in Athena.

That being said, I agree that the documentation should clearly state that closing single quotes are needed. So we will update it in the next release.

**Comment by zdk123** [comment]
Thanks for fast response. I'm happy for the updated documentation for now. However, relying on the user to enquote their own parameters is bad security (e.g. due to sql injection).

On the other hand, the pyathena library does have a[ PEP249-compliant query formatter](https://github.com/laughingman7743/PyAthena/blob/43954c24869b5071d4d478012debf188b215f511/pyathena/formatter.py#L152) which you might consider importing or cribbing.

My current workflow looks like this:
```py
from jinjasql import JinjaSql
from pyathena.formatter import DefaultParameterFormatter as PFormat
import awswrangler as wr

template="SELECT * FROM my_table WHERE name={{ name }}"
j = JinjaSql(param_style='pyformat')
query, bind_params = j.prepare_query(template, {"name": "filtered_name"})
f = PFormat()
query = f.format(query, bind_params)
athena_results_df = wr.athena.read_sql_query(sql=query, database=...)
```

**Comment by jaidisido** [comment]
Covered in [2.7.0 release](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.7.0)
