### ISSUE TITLE
Type error in postgresql's connect

### ISSUE THREAD

**Issue by jekozyra** [awslabs/aws-data-wrangler#611]
**Describe the bug**
The type signature for the `ssl_context` param [here](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/postgresql.py#L80) has the type signature `Optional[Dict[Any, Any]]`. The param is forwarded to pg8000, which [documents](https://github.com/tlocke/pg8000#functions) its `ssl_context` param as:

> None, meaning no SSL (the default)
> True, means use SSL with an ssl.SSContext created using ssl.create_default_context()
> An instance of ssl.SSContext which will be used to create the SSL connection.

(There is a typo in their documentation - "SSContext" actually refers to "SSLContext - they link to the right place.)

Therefore, the correct type signature for this param should be `Optional[Union[bool, SSLContext]]`.

**To Reproduce**
python version: 3.9.2
wrangler version: 2.4.0

To reproduce, create a connection and run mypy:

```
wr.postgresql.connect("db-name", ssl_context=ssl.SSLContext())
```

The error is:

`Argument "ssl_context" to "connect" has incompatible type "SSLContext"; expected "Optional[Dict[Any, Any]]"`

**Comment by jaidisido** [comment]
mypy did not seem to complain when using `Optional[Dict[Any, Any]]` within the `postgresql.connect` method definition. I have changed it to `Optional[Union[bool, SSLContext]]` as suggested anyways, thanks.
