### ISSUE TITLE
Support for ORC file

### ISSUE THREAD

**Issue by haizhouW** [awslabs/aws-data-wrangler#615]
Hello, 

Is there a plan to add support for ORC file?

https://github.com/awslabs/aws-data-wrangler/blob/4b9f27023057c359860669e44607c0825e08bf7b/building/lambda/build-lambda-layer.sh#L34

Thanks!

**Comment by jaidisido** [comment]
PyArrow's [support](https://arrow.apache.org/docs/python/api/formats.html) for ORC is still limited at the moment compared to other formats so we don't have it part of the roadmap at the moment

**Comment by goraj** [comment]
> PyArrow's [support](https://arrow.apache.org/docs/python/api/formats.html) for ORC is still limited at the moment compared to other formats so it's not part of the roadmap

@jaidisido: Curious what ORC functionality in particular are you missing in pyarrow? 
We use pyarrow + ORC/Athena in prod without any issues.
