### ISSUE TITLE
Control Parquet dataset file name

### ISSUE THREAD

**Issue by adarsh-chauhan** [awslabs/aws-data-wrangler#616]
I wanted to know how a file name is decided
```
 awswrangler.s3.to_parquet(
        df=data_frame,
        path=s3_path,
        dataset=True,
        s3_additional_kwargs={"ACL": "bucket-owner-full-control"},
    )

```

output file in AWS S3:
 `135a3c4ade8a438ebd0d29c28725596e.snappy.parquet` How is this name generated?

I want to control file name or rather have predictable name even if `dataset=True` so if my setup(ECS) receives redundant data (json) converted to dataframe, snappy parquet file in AWS S3 is simple overwritten

**Comment by jaidisido** [comment]
This is determined by the `path` argument. If the `s3_path` variable you supplied contains an S3 prefix (e.g. s3://bucket/prefix/) then the parquet file name(s) will be randomly generated. If on the other hand you supply a full S3 path (e.g. s3://bucket/prefix/myparquet-file.pq) then the supplied name will be used. You can find all of this in the [docs](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet).

**Comment by adarsh-chauhan** [comment]
@jaidisido 
that isnt the case, even you specify full path it gives random name to the file
```
awswrangler.s3.to_parquet(
...         df=dataframe,
...         path="s3://temp-dds-slack-alpha-userid-us-east-1/pre_fix/file.pq",
...         dataset=True,
...         s3_additional_kwargs={"ACL": "bucket-owner-full-control"},
...     )

{'paths': ['s3://temp-dds-slack-alpha-userid-us-east-1/pre_fix/file.pq/b7f44eddf8d24911b5855b2eb21bf781.snappy.parquet'], 'partitions_values': {}}

```
