### ISSUE TITLE
parquet dataset file name

### ISSUE THREAD

**Issue by adarsh-chauhan** [awslabs/aws-data-wrangler#617]
@jaidisido 
that isnt the case, even you specify full path it gives random name to the file
```
awswrangler.s3.to_parquet(
...         df=dataframe,
...         path="s3://temp-dds-slack-alpha-userid-us-east-1/pre_fix/file.pq",
...         dataset=True,
...         s3_additional_kwargs={"ACL": "bucket-owner-full-control"},
...     )

{'paths': ['s3://bucket/pre_fix/file.pq/b7f44eddf8d24911b5855b2eb21bf781.snappy.parquet'], 'partitions_values': {}}

```

_Originally posted by @adarsh-chauhan in https://github.com/awslabs/aws-data-wrangler/issues/616#issuecomment-806534690_

**Comment by jaidisido** [comment]
My bad I had not realized you had the `dataset=True` flag. In which case yes the filename is randomly generated ([here](https://github.com/awslabs/aws-data-wrangler/blob/d11ae04ced93c171de14b38983b19be076ba90d2/awswrangler/s3/_write_parquet.py#L158)) with no control over it. You would have to read back the content of the `path` s3 prefix in order to obtain the list of files ([wr.s3.list_objects](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.list_objects.html#awswrangler.s3.list_objects))

**Comment by adarsh-chauhan** [comment]
@jaidisido 
why is it this way, is it being done in this manner for any particular use case?
can we not have a way to get this user controlled/defined, may be one more optional parameter? 

Feature request!

**Comment by jaidisido** [comment]
By setting `dataset=True`, it's possible that more than one parquet file is created and a custom file name would not be enough to distinguish between them. A variable component in the name is therefore required. That being said we can prepend a filename prefix to the files which would give more deterministic control over them. I am working on a PR to do just that.

**Comment by adarsh-chauhan** [comment]
@jaidisido that still wont give the ability to predict file names.
i have two questions here.
1. what decides the file needs to be split into 2 or more, is it `max_rows_by_file` which. by default is saying dont split the files?
2. would it be naive to say just suffix multiple file in incrementing order of a. 3 or 4 digit number?
eg:
```
prefix001.pq
prefix002.pq
```

I am just trying to find a solution to. my use case described #616

**Comment by jaidisido** [comment]
There are numerous factors that would cause to split the files, `max_rows_by_file` is one of them but there is also whether the data is partitioned, bucketed... An incrementing counter would be too naive as you say. Write calls can be distributed across multiple threads making managing order complex.

I am tagging @igorborgest for a second opinion on this though

**Comment by adarsh-chauhan** [comment]
@jaidisido @igorborgest So if i dont use `dataset=True` then i can get around this problem, 
however then AWS Athena is **_not_** able to read the file is this expected?

**Comment by jaidisido** [comment]
With `dataset=False` no Glue table is created in the catalog so you would not be able to query in Athena

**Comment by jaidisido** [comment]
Covered in [2.7.0 release](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.7.0)

**Comment by rcyost** [comment]
Giving a custom name: 
```
bucket = 'equitybucket4'
path = f"s3://{bucket}/test.parquet"
wr.s3.to_parquet(
    df=df,
    path=path,
    # boto3_session=session,
    dataset=False,
    #mode="overwrite"
)
```
This successfully adds the file to s3 with the custom name. 

But it throws an error:
```
InvalidArgumentValue                      Traceback (most recent call last)
Input In [13], in <cell line: 34>()
     20 df = pd.DataFrame({
     21     "id": [1, 2],
     22     "value": ["foo", "boo"],
     23     "date": [date(2020, 1, 1), date(2020, 1, 2)]
     24 })
     26 wr.s3.to_parquet(
     27     df=df,
     28     path=path,
   (...)
     31     #mode="overwrite"
     32 )
---> 34 wr.s3.read_parquet(path, dataset=True)

File c:\Users\yosty\Envs\lobster\lib\site-packages\awswrangler\s3\_read_parquet.py:777, in read_parquet(path, path_root, path_suffix, path_ignore_suffix, version_id, ignore_empty, ignore_index, partition_filter, columns, validate_schema, chunked, dataset, categories, safe, map_types, use_threads, last_modified_begin, last_modified_end, boto3_session, s3_additional_kwargs, pyarrow_additional_kwargs)
    [769](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=768)     return _read_parquet_chunked(
    [770](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=769)         paths=paths,
    [771](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=770)         chunked=chunked,
   (...)
    [774](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=773)         **args,
    [775](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=774)     )
    [776](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=775) if len(paths) == 1:
--> [777](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read_parquet.py?line=776)     return _read_parquet(
...
---> [72](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read.py?line=71)     raise exceptions.InvalidArgumentValue(f"Object {path} is not under the root path ({path_root}).")
     [73](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read.py?line=72) path_wo_filename: str = path.rpartition("/")[0] + "/"
     [74](file:///c%3A/Users/yosty/Envs/lobster/lib/site-packages/awswrangler/s3/_read.py?line=73) path_wo_prefix: str = path_wo_filename.replace(f"{path_root}/", "")

InvalidArgumentValue: Object s3://equitybucket4/test.parquet is not under the root path (s3://equitybucket4/test.parquet/).
```
