### ISSUE TITLE
error writing parquet dataframe with only 1 row

### ISSUE THREAD

**Issue by chtorr** [awslabs/aws-data-wrangler#62]
Hello!  Thanks again for your quick fixes for my last couple of issues!

I'm having an odd problem where writing out a parquet dataframe fails if there's only 1 row.

In the below example, when one partition only has 1 row I get the error `ArrowTypeError: ('Did not pass numpy.dtype object', 'Conversion failed for column col1 with type Int64')`.

If you uncomment the additional row in the example below so that each partition has > 1 row the dataframe writes out fine.

I believe the issue is with this line https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/pandas.py#L896 .  For some reason slice notation with a single row isn't actually assigning the new `float64` casted dataframe.  I'm not entirely sure why that would be.

There also seems to be an interaction with `procs_cpu_bound`, when it's > 1 the 4 row partitioned dataframe throws the arrow type error when it didn't with `procs_cpu_bound=1`.

Let me know if I can provide any more info!

Thanks!

```python
import pandas as pd
import awswrangler

session = awswrangler.Session(procs_cpu_bound=1)

# create some dummy data
data = {
    'col1': [
        1,
        2,
        3,
        # 4,
    ],
    # date column to see valid dates
    'datecol': [
        '2019-11-09',
        '2019-11-09',
        '2019-11-08',
        # '2019-11-08',
    ],
    # dates in partition column to see invalid date strings
    'partcol': [
        '2019-11-09',
        '2019-11-09',
        '2019-11-08',
        # '2019-11-08',
    ]
}

df = pd.DataFrame(data)
# cast date columns to pandas datetime, similar to the result of read_csv() with parse_dates
df = df.astype({'datecol': 'datetime64', 'partcol': 'datetime64'})

# tell Athena what types you want
schema = {
    'col1': 'bigint',
    'datecol': 'date',
    'partcol': 'date',
}

session.pandas.to_parquet(
    dataframe=df,
    database="default",
    path="s3://...,
    partition_cols=['datecol'],
    table="r...",
    mode="overwrite_partitions",
    cast_columns=schema
)
```

**Comment by igorborgest** [comment]
Thanks again @chtorr !

Already fixed: https://github.com/awslabs/aws-data-wrangler/releases/tag/0.0.19
