### ISSUE TITLE
Oracle Database Support

### ISSUE THREAD

**Issue by senorkrabs** [awslabs/aws-data-wrangler#629]
**Is your feature request related to a problem? Please describe.**
awswrangler supports a variety of database engines - MySQL, Postgres, and MS SQL - but does not yet have support for Oracle. When building a data lake in an Enterprise, it is often the case that data needs to be extracted from Oracle databases and warehouses. In some cases, data may need to be written back to a table in an Oracle database as well.

**Describe the solution you'd like**
Add support for Oracle databases with functionality similar to the other supported database engines: `connect`, `read_sql_table`, `read_sql_query`, and `to_sql`

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by adamblvck** [comment]
I'm indeed looking for this feature too, however... I wonder how this will work out, knowing that Oracle Drivers addS about 70MB compressed, needs licensing, and the setup with drivers is an incredible hassle.

**Comment by jaidisido** [comment]
We are investigating the requirements for this in terms of:

- Licensing
- Size of the package
- Required drivers

and will revert back once we understand more

**Comment by rhanson32** [comment]
this is great news that this is WIP as this is something that would really come in handy for me... is there any update on where this feature is after April 30?

**Comment by AdrianoNicolucci** [comment]
Is there any update on Oracle Database Support? We have a use case to leverage oracle with aws data wrangler and would love to see this be implemented.

**Comment by djsaroka** [comment]
Are there any updates to this? I also would love to see this implemented and have many use cases for it.

**Comment by cnfait** [comment]
@djsaroka work is ongoing on this. It won't make it into the next release (2.15.0), but should be available in the one after that - barring any issues.

**Comment by harshalpatel555** [comment]
Please add the support for RDS oracle

**Comment by AdrianoNicolucci** [comment]
> Please add the support for RDS oracle

I'm not sure if you read the comments above but it is actively being worked on and looks like they are planning to release this feature soon.

**Comment by harshalpatel555** [comment]
Thanks for the update

**Comment by malachi-constant** [comment]
Keeping open.

**Comment by cnfait** [comment]
This took a while but Oracle support has now been merged in the main branch. It will be part of the next release scheduled this week.

When it does, please let us know if you encounter any issue or if it behaves like you would expect!
