### ISSUE TITLE
s3.merge_upsert_table deletes existing glue catalog table and doesn't write to existing partitions

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#636]
When you run the s3.merge_upsert_table  function on data that is partitioned, it does not write the upserts to the partitioned data and writes it to the root directly. Also, the glue catalog seems to be dropped and re-created which removes any column descriptions and partition a user may have defined. 

**To Reproduce**

aws data wrangler version = 2.6.0. Library was installed through pip.

1.Run S3.merge_upsert_table on data that is partitions and has column level metadata in the glue catalog table. 
2. You will see that the data is no longer written to the partitions and has column descriptions and partition has been removed. 
Steps to reproduce the behavior. Also add details about Python and Wrangler's version and how the library was installed.

**Comment by jaidisido** [comment]
Subject covered in this discussion [thread](https://github.com/awslabs/aws-data-wrangler/discussions/635)
