### ISSUE TITLE
add partition option to s3.merge_upsert_table so it can upsert to partitions and not read the entire table into memory

### ISSUE THREAD

**Issue by AdrianoNicolucci** [awslabs/aws-data-wrangler#637]
In version 2.6.0, s3.merge_upsert_table has to read the entire existing table into memory which can slow down performance. It would be nice if this method leveraged _partitions_ so it would only compare new records by  the partitions column. For example, if I want to upsert 20 records on a 1 million row dataset, this function will read in the entire existing 1 million records rather than only reading in a subset of the 1 million records which share the same partition. 

In version 2.6.0 this function will read from the existing partitions but when it upserts, it will not write back to the partitions.

**Comment by jaidisido** [comment]
Subject covered in this discussion [thread](https://github.com/awslabs/aws-data-wrangler/discussions/635)
