### ISSUE TITLE
Add column name to exception "Unsupported Pyarrow type" in  athena_types_from_pandas/pyarrow2athena

### ISSUE THREAD

**Issue by nmduarteus** [awslabs/aws-data-wrangler#639]
**Is your idea related to a problem? Please describe.**
While trying to convert pandas to athena types if `Unsupported Pyarrow type` is raised, there is no way of knowing what column is causing the exception.
While for `exceptions.UndetectedType` the column name is displayed, the same does not happen for `Unsupported Pyarrow type`.

Exception example:
`'Unsupported Pyarrow type: time64[us]'`

**Describe the solution you'd like**
It would be nice to have the name of the column that is causing the exception just like happens to the UndetectedType exception.

Exception example:
`'Column abc - Unsupported Pyarrow type: time64[us]'`

**Comment by jaidisido** [comment]
Covered in [2.7.0 release](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.7.0)
