### ISSUE TITLE
Chunked Parquet Boto Client Token Expiration due to `boto3_to_primitives`

### ISSUE THREAD

**Issue by russellbrooks** [awslabs/aws-data-wrangler#640]
**Describe the bug**
When concurrently chunking large parquet datasets using `to_parquet`,  the passed `boto3_session` param ultimately gets decomposed into the underlying token/session/etc using `boto3_to_primitives`. This effectively causes a race condition between the TTL of the original session and the write operations.

For most other operations in wrangler, the boto3 session does not seem to be converted to primitives, and therefore can utilize automatic credential refreshing using boto's `DeferredRefreshableCredentials`. In my case, the boto session being given to `to_parquet` is created in this way because it is assuming a cross-account AWS IAM role which normally have a 1 hour TTL.

Is there a reason that `boto3_to_primitives` is necessary rather than passing the session itself?

**To Reproduce**
Python 3.7.7 and awswrangler 2.3.0

* Create a boto session with a specified TTL
* Call `to_parquet` using the boto session, on a dataframe large enough to saturate the time window.

**Comment by maxispeicher** [comment]
I think it's probably related to the development guide of `boto3`, which basically recommends to create a separate `session` for each thread and process: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html?highlight=multithreading#multithreading-and-multiprocessing
So maybe it could be a solution to be able to provide a `Callable` which produces a `boto3` `session` in a new thread or process. However I'm not quite sure if that would be the best setup. What do you think about it?

**Comment by russellbrooks** [comment]
I think passing a callable could be a reasonable approach. I wonder if it could also be possible to pass the S3 client itself since it's thread-safe to each of the concurrent writes. It looks like those creds are ultimately getting used in `_S3ObjectBase` to create the S3 client.

**Comment by kukushking** [comment]
Unfortunately boto sessions aren't thread-safe :/ Creating a session per thread, however, has another, less obvious downside - for every session, boto has to load service definition from the disk which may add up to quite a number. This happens irrespective of whether the session is created from scratch or from primitives.

Client, according to the docs, is thread-safe and doesn't suffer from the above, in fact, we're already reusing the client across threads for [read requests](https://github.com/awslabs/aws-data-wrangler/pull/684). I think we're safe to do the same for writes, too.
