### ISSUE TITLE
Cannot get partition_filter argument in read_parquet() to work

### ISSUE THREAD

**Issue by geotheory** [awslabs/aws-data-wrangler#641]
I've detailed the problem fully in this [SO question](https://stackoverflow.com/questions/66977251/awswrangler-s3-read-parquet-ignores-partition-filter-argument).  But in short the following returns all my records i.e. the partition_filter is ignored.

```
wr.s3.read_parquet(path = s3_path,
                   partition_filter = lambda x: x["date"] >= "2021-04-02"
)
```
Am I missing something?  Version is 2.6.0.

Thanks :)

**Comment by maxispeicher** [comment]
It should be enough to add `dataset=True` also to the `read_parquet` call and not only the `write_parquet` call.
```python
df2 = wr.s3.read_parquet(s3_path, dataset=True, partition_filter = lambda x: x["date"] >= "2021-04-02")
```
should give the result that you are looking for 🙂

**Comment by jaidisido** [comment]
I have answered directly in [SO](https://stackoverflow.com/a/66982069/8178963) and @maxispeicher beat me to it here :)

**Comment by geotheory** [comment]
Thanks both :)
