### ISSUE TITLE
Enhance catalog.create_database with exist_ok option

### ISSUE THREAD

**Issue by impredicative** [awslabs/aws-data-wrangler#642]
**Is your idea related to a problem? Please describe.**
`catalog.create_database` currently raises an exception if the database already exists. As a user, my goal is simply to idempotently ensure that the database exists, preferably without having to deal with any exception.

**Describe the solution you'd like**
I request an **`exist_ok`** option motivated by the one in [`pathlib.Path.mkdir`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir). Just as in `mkdir`, its default value would be `False`. It would be used as for example:

    wr.catalog.create_database('foo_db', description='This is the foo db', exist_ok=True)

    wr.catalog.create_database('bar_db', exist_ok=True)

Additionally, if `exist_ok=True` but `description` is different from its preexisting value, its value must preferably still be updated.

**Comment by maxispeicher** [comment]
If you want, you can give the new `exist_ok` parameter a try 😉:
```
pip uninstall awswrangler -y
pip install git+https://github.com/maxispeicher/aws-data-wrangler.git@add_exist_flag_to_catalog_create
```

**Comment by jaidisido** [comment]
Covered in [2.7.0 release](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.7.0)
