### ISSUE TITLE
redshift.to_sql with identity key?

### ISSUE THREAD

**Issue by jeyalee** [awslabs/aws-data-wrangler#643]
Hello! I'm trying to insert into a table with an auto incrementing key. When I try to use the `to_sql` method, I get the following error: `cannot set an identity column to a value`

Does `to_sql` support this use case? Am I missing an attribute?

My data frame looks like the following.
```
user_id       current_pwd
0    testUser Dummypassword123
```

Here is my function call.

```python
wr.redshift.to_sql(
    df=user_df,
    table=table,
    schema=schema,
    index=False,
    mode='append',
    con=con
)
```

**Comment by maxispeicher** [comment]
You should be able to get your desired result by naming the `df` columns according to the table column names and setting `use_column_names` of `to_sql` to `True`.
