### ISSUE TITLE
Slow performance when using read_parquet from s3

### ISSUE THREAD

**Issue by konradsemsch** [awslabs/aws-data-wrangler#644]
Hi,

I would like to open an issue as we have seen quite unsatisfying performance using the `read_parquet` function. This is our setup and data below:

* data is in S3, there are 1164 individual date-time prefixes under the main folder, and the total size of all files is barely 25.6 MB. So quite a lot of small individual files organized by individual prefixes by date-time
* they way we gather these files is by passing path: `s3://.../` and using the `partition_filter`. The function call looks like this:

```python
wr.s3.read_parquet(
                path,
                dataset=True,
                partition_filter=filter(),
            )
```
I've run a couple of tests to verify whether there would be any speed improvement if I passed a list of prefixes for the function to combine instead of using the `partition_filter` but the gain was marginal. Enabling `use_threads=True` gave no improvement. Overall it takes around 13 minutes to collect all files... this is just too long. Downloading them with `aws sync` takes a few seconds.

Our main use case for operating on streams is in AWS Batch. We have some data loaders that use the data wrangler when we train our ML model in AWS Batch. We realized after some time that the main contributor to an extended training time, is the part where the data is collected from AWS using the data wrangler (primarily the `wr.s3.read_parquet`). Please also note that we're not taking of big data here. Most of our use cases is like described above.

At the moment we're wondering whether this can be optimized or if we should move away from the streaming approach, and simply download the data on the container for model training. Could you give some advice? What's your take on that?

**Comment by maxispeicher** [comment]
After having a first look I think one of the major slowdowns is that even with `use_threads=True` each file is downloaded with multiple threads but the different files are still loaded [sequentially.](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_read_parquet.py#L633) 
Some performance numbers from a first test:
```python
import time
import pandas as pd
import awswrangler as wr

i = 0
data = []
for day in range(1, 10):
    for hour in range(24):
        for _ in range(1000):
            data.append({"value": i, "year": 2021, "month": 3, "day": day, "hour": hour})
            i = i+1
df = pd.DataFrame(data)

s3_location = "s3://my_s3_location"
wr.s3.to_parquet(df, path=my_s3_location, partition_cols=["year", "month", "day", "hour"])

start_time = time.perf_counter()
df2 = wr.s3.read_parquet("s3://aws-wrangler-test-bucket/partition_test")
print(f"Loading complete data took {time.perf_counter() - start_time} seconds.")
# >>> Loading complete data took 260 seconds.

start_time = time.perf_counter()
df3 = wr.s3.read_parquet("s3://aws-wrangler-test-bucket/partition_test", partition_filter=lambda x: x["day"] == 1, dataset=True)
print(f"Loading one day took {time.perf_counter() - start_time} seconds.")
# >>> Loading one day took 29.34 seconds.
```

Then I tried to do a first draft implementation using `concurrent.futures.ThreadPoolExecutor` for downloading files in parallel instead of https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_read_parquet.py#L633:
```python
with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
    futures = []
    for p in paths:
        partial_func = functools.partial(_read_parquet, path=p)
        futures.append(executor.submit(partial_func, **args))
results = []
for completed in concurrent.futures.as_completed(futures):
    results.append(completed.result())
return _union(dfs=results, ignore_index=ignore_index)
```

resulting in
```python
start_time = time.perf_counter()
df3 = wr.s3.read_parquet("s3://aws-wrangler-test-bucket/partition_test", partition_filter=lambda x: x["day"] == 1, dataset=True)
print(f"Loading one day with threads took {time.perf_counter() - start_time} seconds.")
# >>> Loading one day with threads took 8.7 seconds.
```

**Comment by gvermillion** [comment]
Just dropping some support behind having `awswrangler` load files in parallel. We have a similar use case to that described above. We use AWS Batch to run large scale simulations, and `awswrangler` is used to pull the necessary input data sets down for cleaning, prepping, etc. Initially, the large input data sets are just buckets of CSV files (no partitioning logic/structure), and that initial load is a huge bottleneck.

**Comment by maxispeicher** [comment]
I've just pushed a very basic draft how the parallel downloading could be enabled. However just to be on the save side if it only increases performance for my synthetic example, it would be nice if you could test it for your scenarios (@konradsemsch, @gvermillion). Right it uses the number of available cores for downloading the files in parallel, but if the solution seems to work out I think we can also directly exhibit this parameter aswell.
If you want to test it, you can install it with
```
pip uninstall awswrangler -y
pip install git+https://github.com/maxispeicher/aws-data-wrangler.git@enable_parallel_s3_downloads
```

Right now it should support parallel downloads for `read_parquet`, ' read_csv`, `read_json`, `read_fwf` (however only `read_parquet` was tested by me until now).

**Comment by konradsemsch** [comment]
Hi @maxispeicher! Thanks for quick feedback and proposing a solution already :) However, we probably would need to wait anyways until this change is merged, as we need this for our production workloads...

**Comment by gvermillion** [comment]
@maxspeicher, I've slotted time to test this this week. I'll report back.

**Comment by konradsemsch** [comment]
@maxispeicher - I've tried out our implementation and I see a massive performance boost. Processing time of reading the files got down in our case by a factor of 4: from 8.5 mins to 2.2 mins! Good job! :)

**Comment by maxispeicher** [comment]
@konradsemsch Happy to hear that 🙂 
I've now also created a PR adressing the issue. It is now also possible to directly set the number of used threads via the `use_threads` parameter which might also be able to increase your speed performance even further 😉.
e.g.
```python
start_time = time.perf_counter()
df3 = wr.s3.read_parquet(s3_location, partition_filter=lambda x: x["day"] == 1, dataset=True, use_threads=16)
print(f"Loading one day with threads took {time.perf_counter() - start_time} seconds.")
# >>> Loading one day with threads took 4.47 seconds. (instead of ~9 seconds with just use_threads=True)
```

**Comment by rima317** [comment]
getting KeyError: 'credential_provider' which didn't happen with the original awswrangler, any suggestions?

**Comment by rima317** [comment]
@maxispeicher trying to use your branch and getting KeyError: 'endpoint_resolver' (didn't happen with the original awswrangler), any suggestions?

**Comment by maxispeicher** [comment]
@rima317 I'm not quite sure if my intention is right, because I didn't face the issue until now but it might be due to `boto3 session` not being thread-safe. I've just pushed some changes which should fix this (if it really is the issue). Could you maybe see if it works for you now? 🙂

**Comment by rima317** [comment]
Thanks for the quick response!
now getting this:
[2021-04-19 12:50:36,697] {{taskinstance.py:1145}} ERROR - 'credential_provider'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/infra/merge_parquet_dag.py", line 59, in merge_parquet_files
    df_merged = wr.s3.read_parquet(path=paths, ignore_index=True)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_read_parquet.py", line 642, in read_parquet
    dfs=_read_dfs_from_multiple_paths(read_func=_read_parquet, paths=paths, use_threads=use_threads, kwargs=args),
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_read.py", line 139, in _read_dfs_from_multiple_paths
    return list(df for df in executor.map(partial_read_func, paths))
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_read.py", line 139, in <genexpr>
    return list(df for df in executor.map(partial_read_func, paths))
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_read_parquet.py", line 432, in _read_parquet
    use_threads=use_threads,
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_read_parquet.py", line 377, in _read_parquet_file
    boto3_session=boto3_session,
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_fs.py", line 620, in open_s3_object
    newline=newline,
  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_fs.py", line 257, in __init__
    self._client: boto3.client = _utils.client(service_name="s3", session=self._boto3_session)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/_config.py", line 417, in wrapper
    return function(**args)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/_utils.py", line 109, in client
    config=default_botocore_config() if botocore_config is None else botocore_config,
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 839, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 442, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 941, in get_component
    del self._deferred[name]
KeyError: 'credential_provider'

**Comment by maxispeicher** [comment]
It seems like you still have the "old" version installed.

> `  File "/usr/local/lib/python3.7/site-packages/awswrangler/s3/_read.py", line 139, in _read_dfs_from_multiple_paths
    return list(df for df in executor.map(partial_read_func, paths))`

is in [line 140 in the patched commit.](https://github.com/maxispeicher/aws-data-wrangler/blob/enable_parallel_s3_downloads/awswrangler/s3/_read.py#L140)

So probably it's best to do a
```
pip uninstall awswrangler -y
```
before installing, in order to make sure it's the latest commit.

**Comment by rima317** [comment]
@maxispeicher tnx, works :)
general question: I don't see improvement in terms of times, I suspect it is because having large amount of small files ~5KB 
and using `wr.s3.read_parquet` with list of paths 1-50 in calling inside for loop attached code:
```
    for path_prefix, paths in paths_to_merge.items():
        df_merged = wr.s3.read_parquet(path=paths, ignore_index=True, use_threads=True)
        merged_folder_name = f'merged-{folder}'
        merged_output_path = f'{path_prefix.replace(folder, merged_folder_name)}/{merged_parquet_filename}'
        print(f'saving merged file to s3 in path: {merged_output_path}')
        wr.s3.to_parquet(df=df_merged, path=merged_output_path)
```
can you suggest additional tunings for the wrangler?

**Comment by maxispeicher** [comment]
In which setup/environment are you using `awswrangler`. If it's something like a small EC2 instance, Lambda, etc. which might only have 1 or 2 cpus, it might be worth setting the number of threads directly like:
```python
    for path_prefix, paths in paths_to_merge.items():
        df_merged = wr.s3.read_parquet(path=paths, ignore_index=True, use_threads=8)
        merged_folder_name = f'merged-{folder}'
        merged_output_path = f'{path_prefix.replace(folder, merged_folder_name)}/{merged_parquet_filename}'
        print(f'saving merged file to s3 in path: {merged_output_path}')
        wr.s3.to_parquet(df=df_merged, path=merged_output_path)
```

**Comment by rima317** [comment]
cool, currently using mac, increased number of threads to 16 and got x1.5 decrease.

**Comment by russellbrooks** [comment]
FWIW ran this through a fairly large dataset as well and saw a ~20% speedup and a 6% increase in memory usage.

Before:
```
peak memory: 273454.70 MiB, increment: 273326.68 MiB
CPU times: user 10min 22s, sys: 6min 5s, total: 16min 28s
Wall time: 12min 48s

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110985989 entries, 0 to 110985988
Data columns (total 99 columns):
...
dtypes: Int32(1), Int64(54), category(1), datetime64[ns](2), float64(35), string(6)
memory usage: 123.0 GB
```

After:
```
peak memory: 290745.77 MiB, increment: 290646.48 MiB
CPU times: user 12min 28s, sys: 7min 55s, total: 20min 23s
Wall time: 10min 32s

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110985989 entries, 0 to 110985988
Data columns (total 99 columns):
...
dtypes: Int32(1), Int64(54), category(1), datetime64[ns](2), float64(35), string(6)
memory usage: 123.0 GB
```

**Comment by jaidisido** [comment]
Now covered in [2.8.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.8.0).

**Comment by romin-ebrahimi** [comment]
Even when using use_threads = True, loading and writing data with awswrangler is extraordinarily slow. I have data partitioned by day and awswrangler takes at least 10x longer to read data than directly loading the parquet files.
