### ISSUE TITLE
qemu: uncaught target signal 4 (Illegal instruction) - core dumped

### ISSUE THREAD

**Issue by bart-gcs** [awslabs/aws-data-wrangler#649]
This is an issue with the apple M1 processor and was performed on a new MacBook Air.

Steps to reproduce

1.  Create a hello world app using `sam init` - below are the options I selected

 ```

          $ sam init
                  Which template source would you like to use?
	                  1 - AWS Quick Start Templates
                  	2 - Custom Template Location
                  Choice: 1
                  What package type would you like to use?
	                  1 - Zip (artifact is a zip uploaded to S3)	
         	         2 - Image (artifact is an image uploaded to an ECR image repository)
                  Package type: 1

         Which runtime would you like to use?
	         1 - nodejs14.x
         	2 - python3.8
         	3 - ruby2.7
	         4 - go1.x
         	5 - java11
	         6 - dotnetcore3.1
         	7 - nodejs12.x
	         8 - nodejs10.x
         	9 - python3.7
	         10 - python3.6
         	11 - python2.7
	         12 - ruby2.5
         	13 - java8.al2
	         14 - java8
         	15 - dotnetcore2.1
         Runtime: 2

         Project name [sam-app]: 

         Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates

         AWS quick start application templates:
	         1 - Hello World Example
         	2 - EventBridge Hello World
	         3 - EventBridge App from scratch (100+ Event Schemas)
         	4 - Step Functions Sample App (Stock Trader)
	         5 - Elastic File System Sample App
         Template selection: 1

             -----------------------
             Generating application:
             -----------------------
             Name: sam-app
             Runtime: python3.8
             Dependency Manager: pip
             Application Template: hello-world
             Output Directory: .
    
             Next steps can be found in the README file at ./sam-app/README.md
```

2. cd to sam-app
3. add `awswrangler` to `hello_world/requirements.txt`
3. add `import awswrangler as wr` to `hello_world/app.py`
4. increase the timeout in template.yaml to 300 
```
Globals:
        Function:
          Timeout: 300
```
4. build with `sam build  --cached --parallel --use-container`
5. run locally `sam local invoke HelloWorldFunction`
```
$ sam local invoke HelloWorldFunction           
Invoking app.lambda_handler (python3.8)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-python3.8:rapid-1.22.0.

Mounting /Users/bartspedden/work/a/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: e7c8bbe4-ee64-4e67-a01b-2bbb43c7872c Version: $LATEST
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
time="2021-04-14T19:39:38.787" level=error msg="Init failed" InvokeID= error="Runtime exited with error: signal: illegal instruction"
time="2021-04-14T19:39:38.794" level=error msg="INIT DONE failed: Runtime.ExitError"
```
6. and then to validate that things work without awswrangler you can edit hello_world/app.py and remove the awswrangler import.
7. build with `sam build  --cached --parallel --use-container`
8. run locally `sam local invoke HelloWorldFunction`

```
$ sam local invoke HelloWorldFunction           
Invoking app.lambda_handler (python3.8)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-python3.8:rapid-1.22.0.

Mounting /Users/bartspedden/work/a/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 305c2ee9-6396-49cd-bf6a-a7a43da2ecd8 Version: $LATEST
END RequestId: 305c2ee9-6396-49cd-bf6a-a7a43da2ecd8
REPORT RequestId: 305c2ee9-6396-49cd-bf6a-a7a43da2ecd8	Init Duration: 1.51 ms	Duration: 416.29 ms	Billed Duration: 500 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}%    
```

**Comment by jaidisido** [comment]
The full Wrangler package is too large to install on a Lambda function image. Instead, we produce custom Lambda layers with each [release](https://github.com/awslabs/aws-data-wrangler/releases) that must be attached to the Lambda function as a layer.

**Comment by bart-gcs** [comment]
docker version: Docker version 20.10.1, build 831ebeae96

Thanks for the direction. I added data-wrangler as a layer and I'm still receiving the same error. Here are the steps that I took:

1. I created a lambda layer using awswrangler-layer-2.6.0-py3.8.zip
2. From process_email/requirements.txt I remove awswrangler
3. I added the aws wrangler layer to template.yaml below my power tools layer.
3. I cleaned all docker images
4. I did a build using `sam build --use-container`
5. I executed locally using `sam local invoke ProcessEmailFunction` and received the following error:
```
arn:aws:lambda:us-east-2:111111111111:layer:aws-lambda-powertools-python-layer:8 is already cached. Skipping download
arn:aws:lambda:us-east-2:111111111111:layer:lambda_layer_awswrangler:1 is already cached. Skipping download
Skip pulling image and use local one: samcli/lambda:python3.8-ce744e85ceaed2f64031c7bfb.

Mounting /Users/bartspedden/work/meckley/process-email/.aws-sam/build/ProcessEmailFunction as /var/task:ro,delegated inside runtime container
START RequestId: 5cc30ac2-eb98-445a-adfd-21731729d4c0 Version: $LATEST
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
time="2021-04-15T17:08:42.518" level=error msg="Init failed" InvokeID= error="Runtime exited with error: signal: illegal instruction"
time="2021-04-15T17:08:42.524" level=error msg="INIT DONE failed: Runtime.ExitError"
```

**Comment by jaidisido** [comment]
I believe this is specific to the M1 processor as I cannot replicate the issue on x86 architecture. There is already a related [issue](https://github.com/awslabs/aws-data-wrangler/issues/557) where `pyarrow` installation must be adapted to run on ARM processors

**Comment by bart-gcs** [comment]
It's fine to close this, but just to be clear, aws data wrangler does not work within a locally running lambda within docker on an M1 processor. Therefore developers cannot code locally. 

If I can help solve this please let me know what to try. The PyArrow solution referenced above does give a hint of a direction but not really. I understand the need to compile PyArrow locally on the target chipset, however, this use case is a bit different. When I deploy to AWS, I'm running on x86 and everything works. But when I run locally I'm running on an M1 and docker exits.  The only thing I could think of was creating a separate Dockerfile that installs from source whatever I need, and then creating a separate sam template that uses a custom image runtime for local development. This all seems rather contrived to me and seems to fall into the category of "just because you can doesn't mean you should".  

I don't think developers are suddenly going to abandon macs, so this seems like a rather pertinent ticket to keep open an resolve.

**Comment by jaidisido** [comment]
We already have an issue open about this (#557) and we are asking for help from the community. This issue is referenced there as well but closed to avoid duplicates

**Comment by maxispeicher** [comment]
Maybe also this [issue ](https://github.com/docker/for-mac/issues/5251) goes a little bit more into the details about the Mac M1 processor. It seems to be somehow related to docker images which are not specifically build for arm.

**Comment by jaidisido** [comment]
A fix has been suggested and applied in issue #557. Hopefully it helps with your issue as well

**Comment by bart-gcs** [comment]
Thanks @jaidisido, this has resolved our issue!
