### ISSUE TITLE
Why is awswrangler always loading so many packages?

### ISSUE THREAD

**Issue by daniel1608** [awslabs/aws-data-wrangler#654]
Hey,

is there a specific reason why in `awswrangler/__init__.py` so many modules and external packages are getting loaded?

**My problem:**
I only want to read data from Athena. Therefore, I need the function `from awswrangler.athena import read_sql_query`. But If I load that function, awswrangler loads many other things and external packages. For example `pyodbc`. For `pyodbc` I need to install `libodbc1`. And if I'm not mistaken, `pyodbc` is not needed for Athena, right?
It's not a big problem to install `libodbc1` but I was wondering why awswrangler loads so many things it doesn't need.

**Comment by kukushking** [comment]
Hi there,

`pyodbc` is optional - you don't have to install it unless you intend to use ODBC. However, If it is installed in your env, the library will attempt to load it and that's where you'll need `libodbc1`. If you'd like to avoid that just remove `pyodbc` from your env.
