### ISSUE TITLE
AttributeError: '_S3ObjectBase' object has no attribute '_mode' when using to_parquet and to_csv

### ISSUE THREAD

**Issue by moukisei** [awslabs/aws-data-wrangler#656]
**Describe the bug**
When using to_parquet to write a data frame in S3, I get the following error:

`File "/home/ec2-user/.local/share/virtualenvs/dig-kbLugBx_/lib/python3.7/site-packages/awswrangler/s3/_fs.py", line 296, in __del__
    self.close()`
`File "/home/ec2-user/.local/share/virtualenvs/dig-kbLugBx_/lib/python3.7/site-packages/awswrangler/s3/_fs.py", line 502, in close
    if self.writable():`
 `File "/home/ec2-user/.local/share/virtualenvs/dig-kbLugBx_/lib/python3.7/site-packages/awswrangler/s3/_fs.py", line 496, in writable
    return "w" in self._mode`
`AttributeError: '_S3ObjectBase' object has no attribute '_mode'`

**To Reproduce**
Python version: 3.7.8
awswrangler version: 2.7.0

I would say that in order to reproduce my error, you would have to execute the following code:

`import awswrangler as wr`
`wr.s3.to_parquet(df, path=path, compression="snappy", index = False)`

This error appeared for me today as I upgraded awswrangler version from 1.8 to 2.7.0 as I wanted to use the parameter `chunked` in read_parquet_table for a partitioned table.

**Comment by jaidisido** [comment]
I am unable to reproduce this as the suggested code works fine in my environment. More information on your environment and the content of the dataframe is needed to debug further.

Additionally, could you please ensure that the correct version is installed (`wr.__version__`). And if so, have you tried the same command from a fresh python virtual environment?

**Comment by kukushking** [comment]
+1 unfortunately wasn't able to reproduce it as well.
