### ISSUE TITLE
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by gregshaws** [awslabs/aws-data-wrangler#663]
Thru Lake Formation with permissions set properly on the location and the DB and Table I get the following error message. If I add s3_additional_kwargs with the SSE setting and the Key I get the same error. I can run read_sql_query and read_sql_query and get results just fine, but it works because the KMS key is referenced in Athena for my workgroup. If I add a IAM policy, see below, for s3:GetObject on the resource it works. 

I should not have to set perms on S3 but instead we should be able to rely on Lake Formation.

Code:
df2 = wr.s3.read_parquet_table(
    database='datalake_dev1_edna',
    table='wrkr_cmpstn_cdc_test'
)
Error:
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-118-642e9418a7d0> in <module>
      6 df2 = wr.s3.read_parquet_table(
      7     database='datalake_dev1_edna',
----> 8     table='wrkr_cmpstn_cdc_test'
      9 )
     10 df2

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/_config.py in wrapper(*args_raw, **kwargs)
    415                 del args[name]
    416                 args = {**args, **keywords}
--> 417         return function(**args)
    418 
    419     wrapper.__doc__ = _inject_config_doc(doc=function.__doc__, available_configs=available_configs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py in read_parquet_table(table, database, filename_suffix, filename_ignore_suffix, catalog_id, partition_filter, columns, validate_schema, categories, safe, map_types, chunked, use_threads, boto3_session, s3_additional_kwargs)
    790         use_threads=use_threads,
    791         boto3_session=boto3_session,
--> 792         s3_additional_kwargs=s3_additional_kwargs,
    793     )
    794     partial_cast_function = functools.partial(

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py in read_parquet(path, path_suffix, path_ignore_suffix, ignore_empty, ignore_index, partition_filter, columns, validate_schema, chunked, dataset, categories, safe, map_types, use_threads, last_modified_begin, last_modified_end, boto3_session, s3_additional_kwargs)
    629             use_threads=True,
    630             boto3_session=boto3_session,
--> 631             s3_additional_kwargs=s3_additional_kwargs,
    632         )
    633     return _union(dfs=[_read_parquet(path=p, **args) for p in paths], ignore_index=ignore_index)

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py in _validate_schemas_from_files(paths, sampling, use_threads, boto3_session, s3_additional_kwargs)
    120         use_threads=use_threads,
    121         boto3_session=boto3_session,
--> 122         s3_additional_kwargs=s3_additional_kwargs,
    123     )
    124     _validate_schemas(schemas=schemas)

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py in _read_schemas_from_files(paths, sampling, use_threads, boto3_session, s3_additional_kwargs)
     88                     itertools.repeat(_utils.boto3_to_primitives(boto3_session=boto3_session)),  # Boto3.Session
     89                     itertools.repeat(s3_additional_kwargs),
---> 90                     itertools.repeat(use_threads),
     91                 )
     92             )

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/thread.py in run(self)
     54 
     55         try:
---> 56             result = self.fn(*self.args, **self.kwargs)
     57         except BaseException as exc:
     58             self.future.set_exception(exc)

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py in _read_parquet_metadata_file(path, boto3_session, s3_additional_kwargs, use_threads)
     54         s3_block_size=131_072,  # 128 KB (128 * 2**10)
     55         s3_additional_kwargs=s3_additional_kwargs,
---> 56         boto3_session=boto3_session,
     57     ) as f:
     58         pq_file: Optional[pyarrow.parquet.ParquetFile] = _pyarrow_parquet_file_wrapper(source=f)

~/anaconda3/envs/python3/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py in open_s3_object(path, mode, use_threads, s3_additional_kwargs, s3_block_size, boto3_session, newline, encoding)
    618             boto3_session=boto3_session,
    619             encoding=encoding,
--> 620             newline=newline,
    621         )
    622         if "b" in mode:  # binary

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py in __init__(self, path, s3_block_size, mode, use_threads, s3_additional_kwargs, boto3_session, newline, encoding)
    266                 use_threads=False,
    267                 boto3_session=self._boto3_session,
--> 268                 s3_additional_kwargs=self._s3_additional_kwargs,
    269             )[path]
    270             if size is None:

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_describe.py in size_objects(path, use_threads, s3_additional_kwargs, boto3_session)
    185     """
    186     desc_list: Dict[str, Dict[str, Any]] = describe_objects(
--> 187         path=path, use_threads=use_threads, boto3_session=boto3_session, s3_additional_kwargs=s3_additional_kwargs
    188     )
    189     size_dict: Dict[str, Optional[int]] = {k: d.get("ContentLength", None) for k, d in desc_list.items()}

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_describe.py in describe_objects(path, use_threads, last_modified_begin, last_modified_end, s3_additional_kwargs, boto3_session)
    117     if len(paths) == 1:
    118         resp_list = [
--> 119             _describe_object(path=paths[0], boto3_session=boto3_session, s3_additional_kwargs=s3_additional_kwargs)
    120         ]
    121     elif use_threads is False:

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_describe.py in _describe_object(path, boto3_session, s3_additional_kwargs)
     30         extra_kwargs = {}
     31     desc: Dict[str, Any] = _utils.try_it(
---> 32         f=client_s3.head_object, ex=client_s3.exceptions.NoSuchKey, Bucket=bucket, Key=key, **extra_kwargs
     33     )
     34     return path, desc

~/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/_utils.py in try_it(f, ex, ex_code, base, max_num_tries, **kwargs)
    324     for i in range(max_num_tries):
    325         try:
--> 326             return f(**kwargs)
    327         except ex as exception:
    328             if ex_code is not None and hasattr(exception, "response"):

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             error_code = parsed_response.get("Error", {}).get("Code")
    675             error_class = self.exceptions.from_code(error_code)
--> 676             raise error_class(parsed_response, operation_name)
    677         else:
    678             return parsed_response

ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

IAM Policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "kms:ReEncryptTo",
                "kms:GenerateDataKey",
                "kms:DescribeKey",
                "kms:ReEncryptFrom",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:kms:*:XXXXXXXXXX:key/*",
                "arn:aws:s3:::datalake-us-east-1-dev1-curated-secure/*"
            ]
        }
    ]
}

**Comment by jaidisido** [comment]
I am not sure I understand what you mean by "rely on Lake Formation"? Wrangler operations are agnostic to whether Lake Formation is enabled or not. It only relies on the permissions of the IAM role used to make the calls. If the role is missing permissions (like `s3:HeadObject` in your case), it's normal that the call will fail.

**Comment by gregshaws** [comment]
Lake Formation uses credential vending, see below. In my case I am running a SageMaker notebook that uses a role that had been granted permissions in Lake Formation on the DB, Table, and Location. Lake Formation simplifies data lake management we would not want to start granting direct S3 access. I am a AWS Proserve DataLake Architect working for a large airline. We can work around this by providing direct access but longer term would want to rely on Lake Formation to manage perms.

Each time a principal (user, group, or role) runs a query on data registered using Lake Formation, Lake Formation verifies that the principal has the appropriate Lake Formation permissions to the database, table, and Amazon S3 location registered in Lake Formation as appropriate for the query. If the principal has access, Lake Formation vends temporary credentials, and the query runs.

The following diagram illustrates the flow described above.
![image](https://user-images.githubusercontent.com/82610912/116130732-2d92db80-a691-11eb-8879-402872ba3f5b.png)

**Comment by jaidisido** [comment]
Closing as this level of Lake Formation support is not currently on the roadmap
