### ISSUE TITLE
The zip in the release throws error when deployed through cloudformation

### ISSUE THREAD

**Issue by pruthvirajksuresh** [awslabs/aws-data-wrangler#666]
*I am not sure if this is a bug or if I am missing something. Aws wrangler cannot be imported to a function if it's a part of cloudformation template but it works if I manually upload the zip file as layer. Not sure why this is happening *

**Comment by jaidisido** [comment]
Could you please describe what you mean by "cannot be imported to a function if it's part of a cloudformation template"? Do you have sample CFN code we can look at?

As you mention, the zip file in the release is meant to be used as a Lambda layer. So as long as it's created that way, I don't foresee issues related to the use of AWS CloudFormation

**Comment by kukushking** [comment]
@pruthvirajksuresh +1 Could you share your CFM, please? You also might find this useful: [AWS::Lambda::LayerVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html#aws-resource-lambda-layerversion--examples).

@jaidisido Idea in regards to that - how about hosting all wrangler releases in a public S3 bucket, specifically so it's easy to create layers?

**Comment by pruthvirajksuresh** [comment]
i have used cdk to generate the cfn template  

the zip from the release is placed under the layer/wrangler 
----------
wrngLayer = LayerVersion(
            self, 'WRNGLRLAYER',
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_8],
            code=Code.from_asset("layer/wrangler"),
            layer_version_name="aws-data-wrangler"
        )

        lmbdRst = _lambda.Function(
            self, 'LambdaHandler',
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.asset('lambda'),
            handler='index.handler',
            function_name=f"analytics-API-{env.value_as_string}",
            role=lambdaAPIRole,
            layers=[wrngLayer],
            timeout=core.Duration.seconds(25),
            memory_size=4096
        )
        
----------




WRNGLRLAYERE7B8158C:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParametersd31a438bab754f5704cca8ebef59191d10adecbbc318695d9efea699cf1fc0f4S3Bucket3F68134B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersd31a438bab754f5704cca8ebef59191d10adecbbc318695d9efea699cf1fc0f4S3VersionKeyC639FA7F
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersd31a438bab754f5704cca8ebef59191d10adecbbc318695d9efea699cf1fc0f4S3VersionKeyC639FA7F
      CompatibleRuntimes:
        - python3.8
      LayerName: aws-data-wrangler
    Metadata:
      aws:cdk:path: APP-RESTAPI-STAGING/WRNGLRLAYER/Resource
      aws:asset:path: asset.d31a438bab754f5704cca8ebef59191d10adecbbc318695d9efea699cf1fc0f4
      aws:asset:property: Content
  LambdaHandler212865DC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc66f176af93cc27e59b09712e3725450b604c031bc628e495bd621c506bda578S3Bucket0B60546E
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc66f176af93cc27e59b09712e3725450b604c031bc628e495bd621c506bda578S3VersionKeyB82B22C7
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc66f176af93cc27e59b09712e3725450b604c031bc628e495bd621c506bda578S3VersionKeyB82B22C7
      Role:
        Fn::GetAtt:
          - lambdaAPIRole094B9077
          - Arn
      Environment:
        Variables:
          stage:
            Ref: env
      FunctionName:
        Fn::Join:
          - ""
          - - analytics-API-
            - Ref: env
      Handler: index.handler
      Layers:
        - Ref: WRNGLRLAYERE7B8158C
      MemorySize: 4096
      Runtime: python3.8
      Timeout: 25

**Comment by pruthvirajksuresh** [comment]
> @pruthvirajksuresh +1 Could you share your CFM, please? You also might find this useful: [AWS::Lambda::LayerVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html#aws-resource-lambda-layerversion--examples).
> 
> @jaidisido Idea in regards to that - how about hosting all wrangler releases in a public S3 bucket, specifically so it's easy to create layers?

this would be awesome, but i am not sure if the production environment will refer to the public s3 bucket for layers

**Comment by jaidisido** [comment]
Alright, I have figured out what is your issue. By putting the zipped layer within the `layer/wrangler` directory and specifying `code=Code.from_asset("layer/wrangler")` in the LayerVersion definition, the zip gets **zipped** a second time! This is because the default behaviour of [`Code.from_asset`](code=Code.from_asset("layer/wrangler"),) is to zip any contents within the directory.  Sadly I don't see an option to disable this behaviour.

So I see two options:
1. Unzip the zip locally. Not a big fan of this if you are using version control as it would add a bunch of files. On the flip side, it allows you to enrich the layer with other components if you wish
2. Leverage the [`s3-assets`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-assets-readme.html) construct to fist upload your zip "as is" into an S3 bucket and then reference it within the layer

**Comment by jaidisido** [comment]
As a side note (and third option) following @kukushking's suggestion, we have created a public S3 bucket holding all the public artifacts from releases. So you can also create the layer like this:
```
        wrangler_layer = LayerVersion(
            self,
            "wrangler-layer",
            compatible_runtimes=[Runtime.PYTHON_3_8],
            code=S3Code(
                bucket=Bucket.from_bucket_arn(
                    self,
                    "wrangler-bucket",
                    bucket_arn="arn:aws:s3:::aws-data-wrangler-public-artifacts",
                ),
                key="releases/2.7.0/awswrangler-layer-2.7.0-py3.8.zip",
            ),
            layer_version_name="aws-data-wrangler"
        )
```

**Comment by pruthvirajksuresh** [comment]
@jaidisido thank you . i think it solves the problem (implemented the first option) . do you mind if close the issue? and thank you for creating a public artifact.
