### ISSUE TITLE
How to query PostgreSQL json as string

### ISSUE THREAD

**Issue by imanebosch** [awslabs/aws-data-wrangler#668]
Hi,

I’m using PostgreSQL function read_sql to query a table with some json data type columns. How can I get them as strings? Using pa.string() in dtypes parameter results in an error because the input is a dictionary.

Thanks

**Comment by jaidisido** [comment]
Could you please share a bit more details about the structure of the data so we can reproduce the issue? An example of a row in the Postgre table, the Wrangler version...
