### ISSUE TITLE
Pandas SettingWithCopyWarning

### ISSUE THREAD

**Issue by jasonamyers** [awslabs/aws-data-wrangler#67]
```
~/.virtualenvs/revisions/lib/python3.7/site-packages/awswrangler/pandas.py:896: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[name] = dataframe[name].astype("float64")
```

I keep getting a ton of these popping out of my runs. I'm running:
- pandas==0.25.3
- awswrangler==0.0.19

**Comment by igorborgest** [comment]
Hey @jasonamyers! Are you running on AWS lambdas or with some specific logging configuration?

**Comment by jasonamyers** [comment]
I'm running in a jupyter notebook on my desktop ATM.

**Comment by igorborgest** [comment]
Please, to solve this issue, update your version to the new [0.0.21](https://github.com/awslabs/aws-data-wrangler/releases/tag/0.0.21). Thank!

**Comment by jasonamyers** [comment]
Awesome thank you! it's working great!
