### ISSUE TITLE
Reading parquet files that contain pyarrow extension dtypes

### ISSUE THREAD

**Issue by marwan116** [awslabs/aws-data-wrangler#675]
**Describe the bug**
Calling `wr.s3.read_parquet` parses the `dtype` of a column incorrectly when the column data type is a pyarrow extension dtype (or so it seems to me). Note this behavior only happens when calling `wr.s3.read_parquet` in a new python session (see below for more details).

**To Reproduce**
python version: `3.8.7`
awswrangler version: `2.7.0`

We construct a data frame, write it and read it - so far so good
```
In [1]: import pandas as pd
In [2]: import awswrangler as wr
In [3]: df = pd.DataFrame({"col": ["2010-01"]})
   ...: df["col"] = pd.to_datetime(df["col"]).dt.to_period("M")
In [4]: df.head()
Out[4]: 
       col
0  2010-01
In [5]: df.dtypes
Out[5]: 
col    period[M]
dtype: object
In [6]: wr.s3.to_parquet(df, "s3://my-s3-bucket/wrangler-test/period.parquet")
{'paths': ['s3://my-s3-bucket/wrangler-test/period.parquet'],
 'partitions_values': {}}
In [7]: wr.s3.read_parquet("s3://my-s3-bucket/wrangler-test/period.parquet")
Out[7]: 
       col
0  2010-01
```

We attempt to read the data frame from a different python session - the same call returns a different output when called again:
```

In [1]: import awswrangler as wr

In [2]: wr.s3.read_parquet("s3://my-s3-bucket/wrangler-test/period.parquet")
Out[2]: 
   col
0  480

In [3]: wr.s3.read_parquet("s3://my-s3-bucket/wrangler-test/period.parquet")
Out[3]: 
       col
0  2010-01
```

**Comment by alexifm** [comment]
I checked version history.  This example works in 2.1.0 and none of the versions since.

**Comment by alexifm** [comment]
Pandas categoricals work.  It's the Pandas Period (and maybe other extension types) that don't.

```
df["col"] = df["col"].astype("category")
```

**Comment by alexifm** [comment]
I ran the same tests but with pandas and the pandas Period works fine.

```
In [1]: import pandas as pd
   ...: 
   ...: 
   ...: df = pd.DataFrame({"col": ["2010-01"]})
   ...: df["col"] = pd.to_datetime(df["col"]).dt.to_period("M")
   ...: print(df)
   ...: print(df.dtypes)
   ...: 
   ...: print(df.to_parquet(f"s3://infima-sandbox/wrangler-test/pandas/period.parquet"))
   ...: print(pd.read_parquet(f"s3://infima-sandbox/wrangler-test/pandas/period.parquet"))
       col
0  2010-01
col    period[M]
dtype: object
None
exit       col
0  2010-01
```

```
In [1]: import pandas as pd
   ...: first = pd.read_parquet(f"s3://infima-sandbox/wrangler-test/pandas/period.parquet")
   ...: print(first)
   ...: print(first.dtypes)
   ...: print(pd.read_parquet(f"s3://infima-sandbox/wrangler-test/pandas/period.parquet"))
   ...: 
       col
0  2010-01
col    period[M]
dtype: object
       col
0  2010-01
```

**Comment by maxispeicher** [comment]
Part of the problem seems to be originated in `pyarrow`. When trying to read the same file directly via `pyarrow` int normally reads the datatype as `int64`. However after doing a `to_pandas` call once the datatype is `ArrowPeriodType(DataType(int64))`:

```python
import pyarrow
import pyarrow.parquet

pq_table = pyarrow.parquet.read_table("s3://infima-sandbox/wrangler-test/pandas/period.parquet")
pq_table.schema.types
# Out[6]: [DataType(int64)]

pq_table.to_pandas()
# Out[7]: 
#        col
# 0  2010-01

pq_table = pyarrow.parquet.read_table("s3://infima-sandbox/wrangler-test/pandas/period.parquet")
pq_table.schema.types
# Out[9]: [ArrowPeriodType(DataType(int64))]
```

The reason why `awswrangler` diverts from the output of `pyarrow` in the first call is that it uses `ignore_metadata=True` (https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_read_parquet.py#L264). But maybe we could exhibit this parameter as a kwarg for `read_parquet`. What do you think about it?

**Comment by jaidisido** [comment]
I can confirm that this seems to be a pyarrow issue, specifically with the `to_pandas` method. I will have to raise it directly with the arrow team.

@maxispeicher Setting `ignore_metadata=False` was not enough for me to avoid the behaviour though, I also had to set [`types_mapper=None` ](https://github.com/awslabs/aws-data-wrangler/blob/dff4aa675d0c87e46afa22c06061320e33c7b7d8/awswrangler/s3/_read_parquet.py#L268) to get it to work.

The obscure part for me is why is the pyarrow [`read parquet file`](https://github.com/awslabs/aws-data-wrangler/blob/dff4aa675d0c87e46afa22c06061320e33c7b7d8/awswrangler/s3/_read_parquet.py#L423) operation not idempotent? I don't see what is causing that operation to interpret the type as int64 the first time, but then suddenly consider it a period on the second call?

**Comment by maxispeicher** [comment]
@jaidisido Yeah you're right I've also changed `types_mappers` to `None` for getting it to work.

But `pyarrow`'s behavior is really strange. I also don't quite understand what's going on 🤷.

**Comment by marwan116** [comment]
Just want to say Thank you for following up on this @jaidisido and for opening the issue on Arrow side...
