### ISSUE TITLE
Package numpy and pandas separately

### ISSUE THREAD

**Issue by lh-an** [awslabs/aws-data-wrangler#681]
Thank you for the library! It might be a good idea to package `pandas` and `numpy` separately for those of us who want to just use the basic Glue Catalog or Athena functions. 

It can cut down on package size and reduce exposure to vulnerabilities.

Similar to the existing `awswranger[sqlserver]`, we can have `awswranger[pandas]` and `awswrangler[numpy]` for those who need it.

**Comment by jaidisido** [comment]
Hi, thanks for your suggestion. However `numpy` is a prerequisite to `pyarrow` so would be installed with that regardless. As for `pandas` it's imported in almost all modules in the library, including the ones you mention (Glue catalog and Athena). Both are indispensable sadly.
