### ISSUE TITLE
Getting an error while running wr.athena.read_sql_query

### ISSUE THREAD

**Issue by aditya-cfa** [awslabs/aws-data-wrangler#682]
**Describe the bug**

I am running an Athena Query from a Python Lambda Function and getting the above error

[ERROR] UnsupportedType: Unsupported Athena type: real
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 118, in lambda_handler
    loc_df = wr.athena.read_sql_query(query, database, ctas_approach=False)
  File "/opt/python/awswrangler/athena.py", line 564, in read_sql_query
    query_execution_id=query_id, categories=categories, boto3_session=session
  File "/opt/python/awswrangler/athena.py", line 335, in _get_query_metadata
    pandas_type: str = _data_types.athena2pandas(dtype=col_type)
  File "/opt/python/awswrangler/_data_types.py", line 86, in athena2pandas
    raise exceptions.UnsupportedType(f"Unsupported Athena type: {dtype}")  # pragma: no cover

**To Reproduce**
Steps to reproduce the behavior. Also add details about Python and Wrangler's version and how the library was installed.
I am running an Athena Query from a Python Lambda Function and getting the above error, the Athena table does not contain any nested structures.

Code:
df = wr.athena.read_sql_query(query, database, ctas_approach=False)

Query:
Select * from table_name Limit 10;

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
Could you please share your pip freeze? Particularly your wrangler version. Athena `real` type is supported in the latest version. A way to reproduce through an input dataframe would also be good if possible
