### ISSUE TITLE
awswrangler.redshift.copy() fails when using sqlalchemy postgresql and sqlalchemy-redshift

### ISSUE THREAD

**Issue by els-pnw** [awslabs/aws-data-wrangler#683]
**Describe the bug**
I had previously been using awswrangler with sqlalchemy and it recently began failing so I decided to swap out for sqlalchemy-redshift, changing my db url from postgresql+psycopg2 to redshift+psycopg2. However, again awswranger.redshift.copy failed.

AttributeError: 'Connection' object has no attribute 'autocommit'

I have attempted execution_options and those did not seem to affect the behavior.

`engine = engine.execution_options(isolation_level="AUTOCOMMIT")`
and
`with engine.connect().execution_options(autocommit=True) as c:`
Both failed to correct the issue.

```
engine = create_engine(url)
engine = engine.execution_options(isolation_level="AUTOCOMMIT")
```

```
with engine.connect() as c:
    wr.redshift.copy(
        df = df,
        path=f"s3://{bucket}/{str(uuid4())}",
        con=c,
        boto3_session=boto_session,
        table=TABLE,
        schema=SCHEMA,
        iam_role=iam_role,
        keep_files=False,
        mode='overwrite',
        s3_additional_kwargs={'ServerSideEncryption':'AES256'}
    )
```

I've also tried  where I then receive the error `

```
I have also just recently tried:

with engine.connect() as c:
c.autocommit = True
    wr.redshift.copy(
        ...
    )
```

**To Reproduce**
See above in the description:
1. define engine using sqlalchemy or sqlalchemy-redshift.
2. call connect() on engine
3. Call awswrangler.redshift.copy() 
4. See Attribute Error. `AttributeError: 'Connection' object has no attribute 'rollback'`

So far the ONLY workaround I have found to this issue is to use redshift-connector; however, there are other issues related to redshift-connector and we'd really just prefer to use the more common and widely supported sqlalchemy.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by kukushking** [comment]
Could you share your pip freeze, please? 

You seem to be using SQLAlchemy 1.4 that isn't compatible with Python DB-API 2.0, among otherthings. [This](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-engine) could be of help.
