### ISSUE TITLE
Support to EMR on EKS

### ISSUE THREAD

**Issue by hudsondba** [awslabs/aws-data-wrangler#685]
**Is your feature request related to a problem? Please describe.**
Would be great to extend the EMR api to support EMR on EKS.

**Describe the solution you'd like**
Adding a option to submit Jobs inside the `emr.submit_spark_step` or with a new endpoint supporting the :
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr-containers.html
operations.

PS: If there aren't any plans to do it soon, I can help with a PR.

**Comment by jaidisido** [comment]
Thanks for the suggestion @hudsondba. EKS on EMR is not currently on our roadmap but we always welcome PRs from the community so happy to review it if you have plans to submit it
