### ISSUE TITLE
Trigger release for bump in pyarrow version

### ISSUE THREAD

**Issue by jmahlik** [awslabs/aws-data-wrangler#687]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Could there be a release triggered including the changes in #670 ? We'd like to bump pyarrow  to 4.0 but are currently blocked by the wrangler constraints on pyarrow.

**Describe the solution you'd like**

Trigger a release of main?

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
Release 2.8.0 is scheduled for early next week.
