### ISSUE TITLE
Support parquet logical type of MAP

### ISSUE THREAD

**Issue by robertaves** [awslabs/aws-data-wrangler#70]
Looking to get support for outputting Tuple[str, str] or non nested dictionary's (key value pairs ) outputted logical dt of MAP in parquet file.

I understand dependent libraries do not yet support it by looking at this pull https://github.com/apache/arrow/pull/5774. Looks like it might be wrapping up development soon, does it make sense to eventually support?

Thoughts?

**Comment by igorborgest** [comment]
Thanks for the contribution @robertaves, this makes total sense.

Let's keep following [this arrow's PR](https://github.com/apache/arrow/pull/5774) to develop our side when it is possible.

**Comment by sujayramaiah** [comment]
@igorborgest Looks like the arrow's PR has been closed.

**Comment by robertaves** [comment]
looks like pyarrow 0.16 added support for maparray. Can this be unblocked? would be great for athena maps

**Comment by igorborgest** [comment]
Thanks @robertaves! Let's work on that!

**Comment by igorborgest** [comment]
We will add support for nested types on version 1.0.0. Coming soon!

**Comment by igorborgest** [comment]
Hi! We will release AWS Data Wrangler 1.0.0 on `April 10` and we are collecting as much feedback as possible.

This issue should be resolved with this release. So, please test it if possible, and any feedback about the docs, the library or this specific functionality will be very welcome. 

- Install: `pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev-1.0.0`
- Docs: https://aws-data-wrangler.readthedocs.io/en/dev-1.0.0/
- Code: https://github.com/awslabs/aws-data-wrangler/tree/dev-1.0.0

**Comment by igorborgest** [comment]
Thank you for the contribution. Please, reopen the issue if it persists even after the version `1.0.0`.
