### ISSUE TITLE
how to add a vpc in the copy to redshift?

### ISSUE THREAD

**Issue by r0mymendez** [awslabs/aws-data-wrangler#701]
I want to use "awswrangler.redshift.copy" to append data to a redshift table, but I need to configure a vpc in a glue job with python shell.
Does anyone know how to do it?

**Comment by kev-dfs** [comment]
Hi,
You need create a [connection](https://docs.aws.amazon.com/glue/latest/dg/console-connections.html) in Glue (left menu) to redshift. After that, you must assign this connection in your glue job python shell.
Finally, you need (probably) create an Enpoint on VPC Service to glue, and asociate this endpoint with the security group asigned to your Job.

Regards!

**Comment by jaidisido** [comment]
As @kev-dfs mentioned you would need to first set up a Glue connection and a VPC endpoint. You can then establish a [connection](https://aws-data-wrangler.readthedocs.io/en/2.7.0/stubs/awswrangler.redshift.connect.html) to Redshift from Wrangler. The specific VPC endpoint can be specified in the Global [configuration](https://aws-data-wrangler.readthedocs.io/en/2.7.0/tutorials/021%20-%20Global%20Configurations.html)
