### ISSUE TITLE
s3.to_parquet: hash string suffix was added to table if mode = "overwrite"

### ISSUE THREAD

**Issue by shizidushu** [awslabs/aws-data-wrangler#702]
I got data from google analytics and write it to s3. The script runs everyday.

```python
wr.s3.to_parquet(
        df = df,
        path = "s3://**/ods/ods_ga_session_daily_cm",,
        dataset = True,
        database = "ods",
        table = "ods_ga_session_daily_cm",
        mode = "overwrite",
        compression = 'gzip',
        partition_cols = None,
        boto3_session = boto3_session
    )
```
It generate one additional table with hash string suffix. (According to doc, `If duplicate table names are encountered, the crawler adds a hash string suffix to the name. `) 

For other table, I set `mode` to `overwrite_partitions`, no problem.

Here is a screenshot of glue table.
![图片](https://user-images.githubusercontent.com/13694980/118792036-db2c8f80-b8c9-11eb-9f5b-97c675724fcc.png)

**Comment by jaidisido** [comment]
I assume the "docs" you mention are about the Glue [crawler](https://docs.aws.amazon.com/glue/latest/dg/crawler-running.html)?

Why do you need to run a Glue crawler on top of the data? By specifying `database` and `table` parameters in the `to_parquet` call you are already updating the table metadata. So not sure why a crawler is also required?

**Comment by shizidushu** [comment]
@jaidisido Thanks for your reply. I see the screenshot (there is hash string), and guess it is glue crawler. In fact, I don't know why.

I define a function to do small data upsert. In my case, one new row per day. The problem is additional table with hash string suffix appears in glue catalog.
```python
def write_parquet_to_s3(
    df: pd.DataFrame,
    boto3_session: boto3.Session,
    path: str,
    do_upsert: Optional[bool] = False,
    drop_dups_subset: Optional[List[str]] = None,
    dataset: bool = False,
    mode: Optional[str] = None,
    compression: str = "gzip",
    partition_cols: Optional[List[str]] = None,
    database: Optional[str] = None,
    table: Optional[str] = None,
    additional_read_parquet_kwargs: Optional[Dict] = None,
    **kwargs,
):
    additional_read_parquet_kwargs = additional_read_parquet_kwargs or {}


    if do_upsert:
        if mode != 'overwrite':
            raise Exception("do_upsert is only availbe when mode is overwrite")
        if partition_cols is not None:
            raise Exception("do_upsert can not be enabled when partition_cols is not None")
        try:
            df_s3 = wr.s3.read_parquet(
                path=path,
                boto3_session = boto3_session,
                dataset=dataset,
                **additional_read_parquet_kwargs
            )
            logging.info("The shape of old dataframe from s3 is: %s", df_s3.shape) #type: ignore
        except wr.exceptions.NoFilesFound as e:
            logging.info(e)
            df_s3 = None
        df = upsert_dataframe(df1=df, df2=df_s3, drop_dups_subset=drop_dups_subset)  # type: ignore

    result = wr.s3.to_parquet(
        df = df,
        path = path,
        dataset = dataset,
        database = database,
        table = table,
        mode = mode,
        compression = compression,
        partition_cols = partition_cols,
        boto3_session = boto3_session,
        **kwargs
    )
    logging.info("The resutlt of write parquet to s3: %s", result)
    return result


write_parquet_to_s3(
    df = df,
    path = "s3://**/ods/ods_ga_session_daily_cm",
    do_upsert=True,
    dataset = True,
    database = "ods",
    table = "ods_ga_session_daily_cm",
    mode = "overwrite",
    compression = 'gzip',
    drop_dups_subset =["part_dt"],
    partition_cols = None,
    boto3_session = boto3_session
)
```

**Comment by jaidisido** [comment]
Can you please confirm if there is a Glue crawler running in your account at the moment?

If yes, then I think your issue is entirely caused by the crawler and has nothing to do with Wrangler. As I have mentioned, I do not actually see the point of having the crawler in the first place, as it is already handled by the `to_parquet` method

**Comment by shizidushu** [comment]
@jaidisido Yes. I find Glue crawlers running based on a schedule. Just remove them.

Thanks for your patience.
