### ISSUE TITLE
v2.8.0 Public layer artifact authorization error

### ISSUE THREAD

**Issue by cojmcc** [awslabs/aws-data-wrangler#709]
**Describe the bug**

The public layer artifact for v. 2.8.0 is returning an authorization error indicating the SigV4 is now required to download the zip file. This is changed from previous versions and doesn't seem to align with the documentation [here](https://aws-data-wrangler.readthedocs.io/en/2.8.0/install.html#public-artifacts).

**Environment**

```
<Error>
<Code>InvalidArgument</Code>
<Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message>
<ArgumentName>Authorization</ArgumentName>
<ArgumentValue>null</ArgumentValue>
<RequestId>GP7VHD1VN0W2DW2J</RequestId>
<HostId>7boNcjrL/wVGKA0WhCU1/HJXcYzyrz892Dj+z6RZGoydhXO2eTxk3QOgkAZVmEXwaQgM2A3F6dE=</HostId>
</Error>
```

We use Terraform to generate layers and using the following configuration, it generates the error below
```
resource "aws_lambda_layer_version" "lambda_layer" {
  s3_bucket = "aws-data-wrangler-public-artifacts"
  s3_key = "/releases/2.8.0/awswrangler-layer-2.8.0-py3.8.zip"

  layer_name = "aws_data_wrangler"

  compatible_runtimes = ["python3.8"]
}
```

```
│ Error: Error creating lambda layer: AccessDeniedException: 
│       status code: 403, request id: cf10481d-306b-4a1c-87f8-ab3cf0640473
```

**To Reproduce**

Steps to reproduce the behavior.

Attempt to download the file directly via the following link: 

https://s3.amazonaws.com/aws-data-wrangler-public-artifacts/releases/2.8.0/awswrangler-layer-2.8.0-py3.8.zip

Previous working example:

https://s3.amazonaws.com/aws-data-wrangler-public-artifacts/releases/2.7.0/awswrangler-layer-2.7.0-py3.8.zip

**Comment by jaidisido** [comment]
Encryption was inadvertently enabled on this version. Now removed. Thank you for raising it!
