### ISSUE TITLE
Get date "Last Modified" paquet files 

### ISSUE THREAD

**Issue by sergei-sp27** [awslabs/aws-data-wrangler#711]
Hi,
I need to read the paquet files from the S3 bucket.
I can do this from wr. read_parquet.
I mean, is it possible other than reading files from a certain modified date/time, to actually get the "Last Modified" to commit to its data. Like when using boto3
```
parquet = self._parquet_client.list_objects(Bucket=self._bucket)
for parquet_inforamtion in parquet["Contents"]:
LastModified = parquet_inforamtion["LastModified"]
```

**Comment by jaidisido** [comment]
You are looking for this method: https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.describe_objects.html#awswrangler.s3.describe_objects which describes S3 objects under a given prefix, including their last modified date
