### ISSUE TITLE
Date Range Partitioning by Month

### ISSUE THREAD

**Issue by jdwil** [awslabs/aws-data-wrangler#716]
According to the docs for projected partitioning, it looks like it's possible to partition a normal datetime column by arbitrary time intervals (1 month, in my case). However, the awswrangler code seems to only be able to generate partitions as datetimes or dates. For example, if I store a record with start_time = 2021-05-25T08:04:23.000000, I'd like this record to be stored in a partition, 2021-05. Right now, I'm turning start_time into a string and partitioning on that, but that means I can't use projection and I have to add an extra where clause to my sql to ensure the partitions are utilized.

Am I misunderstanding the docs for projected partitioning, or does awswrangler just not handle this? Also, this library is great, so thank you.

**Comment by jaidisido** [comment]
Could you please share a minimal example of what you are trying to achieve and the exact Wrangler call you are making? Perhaps with a dummy dataframe. Thanks
