### ISSUE TITLE
Allow name-prefix when using awswrangler.redshift.unload_to_files

### ISSUE THREAD

**Issue by Falydoor** [awslabs/aws-data-wrangler#717]
**Is your idea related to a problem? Please describe.**

When using _awswrangler.redshift.unload_to_files_, I would like to be able to use a **name-prefix** for the parquet files (https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html).

**Describe the solution you'd like**

I believe this line can just be removed (I can do a PR):

https://github.com/awslabs/aws-data-wrangler/blob/2da313473e6426128fff0111ae819fb55ccc87ee/awswrangler/redshift.py#L924

**Comment by jaidisido** [comment]
Thanks for the suggestion. This can be enabled for the `unload_to_files` Wrangler method but not the `unload` method. This is because the latter call expects a S3 prefix for subsequent read parquet calls. More details in PR #729
