### ISSUE TITLE
Support VersionId for S3 reads

### ISSUE THREAD

**Issue by tomkam-python** [awslabs/aws-data-wrangler#721]
**Is your idea related to a problem? Please describe.**
I'm working on a Lambda triggered by an S3 object upload to a versioned bucket. I would like to ensure that I am reading the version of the object reference in the upload event triggering said lambda.

`client.get_object()` of `boto3` allows users to get a hold of a specific object version by passing it as an optional keyword argument `VersionId`, but this is not surfaced to any of the `wr.s3.read*` methods.

**Describe the solution you'd like**
There are 3 options of handling this:
1. Optionally parsing the `path` argument to retrieve in the same format as in the S3 REST API: `?versionId=${VERSION_ID}`
2. Adding `VersionId` to the list of allowed `s3_additional_kwargs` and use where appropriate
3. Adding `VersionId` as another optional parameter to `wr.s3.read*` methods.

Which option would be preferable, and are there any concerns with adding this functionality at all?

**Comment by kukushking** [comment]
I think option 3 - adding `VersionId` parameter would be the best. If I'm not mistaken, you can already use `s3_additional_kwargs` for what you are trying to achieve, but having a dedicated parameter is way more user-friendly.

**Comment by kukushking** [comment]
Added the feature - it be included in the next release. Until then, you can test it as follows:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
Thanks for your interest!
