### ISSUE TITLE
[docs] say that s3.to_csv might save as a non-csv format

### ISSUE THREAD

**Issue by mdavis-xyz** [awslabs/aws-data-wrangler#724]
[The docs for s3.to_csv](https://aws-data-wrangler.readthedocs.io/en/2.7.0/stubs/awswrangler.s3.to_csv.html#awswrangler.s3.to_csv) say:

> dataset (bool) – If True store a parquet dataset instead of a ordinary file(s)

I don't understand this.
So if true, then a function called "to csv" will save as something that is *not* csv? (Parquet is an alternative to CSV, as far as I understand.)
Is the function named sub-optimally, or is this argument not really an argument? Or is the documentation of that argument not right?
What exactly is the use case for this?

**Comment by kukushking** [comment]
Hi, this is some unfortunate copy-paste in the docs - it would not actually be producing parquet. What dataset parameter really means here is that your output may result into more than one CSV file, like if it would be partitioned / _bucketed_. This is what we call a dataset. I'll clarify the docs.
