### ISSUE TITLE
start_query_execution is missing sql params. Formatting the sql query before might lead to sql injection attack

### ISSUE THREAD

**Issue by chanansh** [awslabs/aws-data-wrangler#725]
The current version of `start_query_execution` misses support for sql parameters (whereas `read_sql_query` support it, see `params`).

If the user need to format the sql string before passing it into `start_query_execution`, the query is sensitive to sql-injection attack.
See https://realpython.com/prevent-python-sql-injection/

**Comment by jaidisido** [comment]
Addressed in latest [commit](https://github.com/awslabs/aws-data-wrangler/commit/520a55798eeaee8e6aa74a41bfee2cea97047bfa)
