### ISSUE TITLE
Athena Verify False Option

### ISSUE THREAD

**Issue by asheeshgarg** [awslabs/aws-data-wrangler#741]
When creating a client with boto on Athena we have a option to disable the SSL verification by setting verify False. I don't see an option to pass to the boto session. So when I am using the session with Aws wrangler I am always getting SSL errors. Please suggest if there is a way to pass verify False when using Athena with wrangler api

**Comment by kukushking** [comment]
Hi, thanks for opening the issue. We don't recommend disabling SSL and wouldn't want to add that functionality into wrangler as it would expose our customers to MIM attacks and put their data at risk. However, I acknowledge it might simplify the development so here's a couple of things you can do:

1. Consider still using SSL. The only thing you'd need to do is to add Amazon CA certificates to the trust store of your system.
2. If the above isn't possible and you still would like to disable SSL you can do this by "monkey-patching" the client factory like below:

```
import boto3
import botocore
import awswrangler as wr

from awswrangler._utils import ensure_session, _get_endpoint_url, default_botocore_config, apply_configs
from typing import Optional

@apply_configs
def client(
    service_name: str, session: Optional[boto3.Session] = None, botocore_config: Optional[botocore.config.Config] = None
) -> boto3.client:
    """Create a valid boto3.client."""
    endpoint_url: Optional[str] = _get_endpoint_url(service_name=service_name)
    return ensure_session(session=session).client(
        service_name=service_name,
        endpoint_url=endpoint_url,
        use_ssl=False,
        config=default_botocore_config() if botocore_config is None else botocore_config,
    )

wr._utils.client = client  # "monkey-patch" the client
```

Hope this helps!

**Comment by asheeshgarg** [comment]
I agree we will use SSL enable this is jus to test the dev tests. Following is the issue I am getting 
I am able to use below to query the athena fine 
athena_client = boto3.client('athena', **credentials, verify=False, region_name="us-east-1")

When I tried 
b_session=boto3.session.Session(region_name="us-east-1",**credentials,)
wr._utils.client = client  # "Monkey-patch" the client
wr.athena.read_sql_query(query,database="testdb")
I am getting A communication error occurred: "Connection refused"

Is it some thing I am missing to instantiate the client correctly fro wrangler?

**Comment by kukushking** [comment]
Can you post the full code sample, please?

**Comment by asheeshgarg** [comment]
import boto3
import botocore
import awswrangler as wr

from awswrangler._utils import ensure_session, _get_endpoint_url, default_botocore_config, apply_configs
from typing import Optional

@apply_configs
def client(
    service_name: str, session: Optional[boto3.Session] = None, botocore_config: Optional[botocore.config.Config] = None
) -> boto3.client:
    """Create a valid boto3.client."""
    endpoint_url: Optional[str] = _get_endpoint_url(service_name=service_name)
    return ensure_session(session=session).client(
        service_name=service_name,
        endpoint_url=endpoint_url,
        use_ssl=False,  # Disable SSL
        config=default_botocore_config() if botocore_config is None else botocore_config,
    )

athena_client = boto3.client('athena', **credentials, verify=False, region_name="us-east-1")
b_session=boto3.session.Session(region_name="us-east-1",**credentials,)
wr._utils.client = client  # "Monkey-patch" the client

This is the full example the athena client works. The credentials we get is after the authentication and include the aws key, secret and token.

**Comment by kukushking** [comment]
Hi, I think there's a bit of confusion - you seem to be using a separate client still. After patching you should be good to use the default client created by wrangler. Here's full code sample that:
1) Patches the client factory to disable SSL for all clients created by awswrangler
2) Executes athena query. SSL is disabled at this point because of step 1.

```
import boto3
import botocore
import awswrangler as wr

from awswrangler._utils import ensure_session, _get_endpoint_url, default_botocore_config, apply_configs
from typing import Optional

@apply_configs
def client(
    service_name: str, session: Optional[boto3.Session] = None, botocore_config: Optional[botocore.config.Config] = None
) -> boto3.client:
    """Create a valid boto3.client."""
    endpoint_url: Optional[str] = _get_endpoint_url(service_name=service_name)
    return ensure_session(session=session).client(
        service_name=service_name,
        endpoint_url=endpoint_url,
        use_ssl=False,  # Disable SSL
        config=default_botocore_config() if botocore_config is None else botocore_config,
    )

wr._utils.client = client  # 1 - "Monkey-patch" the client to disable SSL.

wr.athena.read_sql_query(query,database="testdb")  # 2 - Run Athena query. SSL is disabled at this point.
```
Please give it a try.

**Comment by kukushking** [comment]
Closing - feel free to reopen if required.
