### ISSUE TITLE
using AWS Wrangler in Glue where internet is not allow

### ISSUE THREAD

**Issue by josecw** [awslabs/aws-data-wrangler#75]
How do you resolve library dependencies? 
Tried adding each module as .whl file but it take more time to install, and also failed because deeper-dependencies or module installation sequence.

**Comment by josecw** [comment]
any possibilities that aws wrangler using the base libraries in Glue? or it must use newer libraries from pypi?

**Comment by corvuslee** [comment]
@igorborgest Can we take Glue as a special case and bundle all dependencies into the wheel file?

**Comment by corvuslee** [comment]
Just tested a workaround. Basically we can download all dependencies (and awswrangler itself), zip and upload to s3. Then within the Glue job python script, run `pip3 install --no-index --find-links ...`. For details you may refer to https://github.com/corvuslee/public/blob/master/awswrangler_glue.md

**Comment by josecw** [comment]
Nice work Corvus.
However, we found there are some other issues, like no connection to other boto3 api endpoints (sts, glue, athena, etc). I think this is more on VPC design.

**Comment by igorborgest** [comment]
Blocking because it is a limitation from the service itself.

**Comment by igorborgest** [comment]
Closing because it is a limitation from the service itself.
