### ISSUE TITLE
Increasing Chunk Size on awswrangler::postgres::to_sql() causes struct packing error

### ISSUE THREAD

**Issue by alistaim** [awslabs/aws-data-wrangler#757]
**Describe the bug**
Increasing chunk size parameter in the postgres::to_sql() call eventually leads to the following failure :

============================= test session starts ==============================
platform darwin -- Python 3.8.2, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/mclean/code/aws-data-wrangler/bin/pyth
cachedir: .pytest_cache
rootdir: /Users/mclean/code/aws-data-wrangler, configfile: pytest.ini
plugins: cov-2.12.1, xdist-2.2.1, anyio-3.1.0, timeout-1.4.2, forked-1.3.0, rerunfailures-10.0
collecting ... collected 1 item

tests/test_postgresql.py::test_to_sql_large FAILED                       [100%]

=================================== FAILURES ===================================
______________________________ test_to_sql_large _______________________________

postgresql_table = 'tbl_20210618191415120540_8a0c0b'
postgresql_con = <pg8000.legacy.Connection object at 0x7fc7a51c9fa0>

    def test_to_sql_large(postgresql_table, postgresql_con):
        df = pd.DataFrame({"c0": [i for i in range(50000)], "c1": ["foo" for _ in range(50000)]})
>       wr.postgresql.to_sql(df, postgresql_con, postgresql_table, "public", "overwrite", True, chunksize=25600)

tests/test_postgresql.py:49:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
awswrangler/_config.py:417: in wrapper
    return function(**args)
awswrangler/postgresql.py:358: in to_sql
    cursor.executemany(sql, (parameters,))
lib/python3.8/site-packages/pg8000/legacy.py:299: in executemany
    self.execute(operation, parameters)
lib/python3.8/site-packages/pg8000/legacy.py:249: in execute
    self._context = self._c.execute_unnamed(
lib/python3.8/site-packages/pg8000/core.py:590: in execute_unnamed
    self.send_PARSE(NULL_BYTE, statement, oids)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pg8000.legacy.Connection object at 0x7fc7a51c9fa0>
statement_name_bin = b'\x00'
statement = 'INSERT INTO "public"."tbl_20210618191415120540_8a0c0b"  VALUES ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($
oids = (21, 21, 705, 21, 21, 705, ...)

    def send_PARSE(self, statement_name_bin, statement, oids):

        val = bytearray(statement_name_bin)
        val.extend(statement.encode(self._client_encoding) + NULL_BYTE)
>       val.extend(h_pack(len(oids)))
E       struct.error: 'h' format requires -32768 <= number <= 32767

lib/python3.8/site-packages/pg8000/core.py:562: error
---------------------------- Captured stdout setup -----------------------------
Table name: tbl_20210618191415120540_8a0c0b
------------------------------ Captured log setup ------------------------------
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
------------------------------ Captured log call -------------------------------
DEBUG    awswrangler.postgresql:postgresql.py:32 Drop table query:
DROP TABLE IF EXISTS "public"."tbl_20210618191415120540_8a0c0b"
DEBUG    awswrangler._data_types:_data_types.py:442 Inferring PyArrow type from column: c0
DEBUG    awswrangler._data_types:_data_types.py:442 Inferring PyArrow type from column: c1
DEBUG    awswrangler._data_types:_data_types.py:467 Inferring PyArrow type from index: __index_level_0__
DEBUG    awswrangler._data_types:_data_types.py:477 columns_types: {'__index_level_0__': DataType(int64), 'c0': DataType
DEBUG    awswrangler._data_types:_data_types.py:692 database_types: {'__index_level_0__': 'BIGINT', 'c0': 'BIGINT', 'c1'
DEBUG    awswrangler.postgresql:postgresql.py:71 Create table query:
CREATE TABLE IF NOT EXISTS "public"."tbl_20210618191415120540_8a0c0b" (
__index_level_0__ BIGINT,
c0 BIGINT,
c1 TEXT)
DEBUG    awswrangler.postgresql:postgresql.py:357 sql: INSERT INTO "public"."tbl_20210618191415120540_8a0c0b"  VALUES (%
ERROR    awswrangler.postgresql:postgresql.py:362 'h' format requires -32768 <= number <= 32767
---------------------------- Captured log teardown -----------------------------
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
============================== slowest durations ===============================
0.81s teardown tests/test_postgresql.py::test_to_sql_large
0.71s setup    tests/test_postgresql.py::test_to_sql_large
 ESCOC

8a0c0b"  VALUES ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($10, $11, $...76787, $76788), ($76789, $76790, $76791), ($767

):

 NULL_BYTE)

= 32767

--------------------

--------------------
 config argument botocore_config with value None.
 config argument botocore_config with value None.
--------------------
query:
0b"
g PyArrow type from column: c0
g PyArrow type from column: c1
g PyArrow type from index: __index_level_0__
types: {'__index_level_0__': DataType(int64), 'c0': DataType(int64), 'c1': DataType(string)}
_types: {'__index_level_0__': 'BIGINT', 'c0': 'BIGINT', 'c1': 'TEXT'}
e query:
0_8a0c0b" (

T INTO "public"."tbl_20210618191415120540_8a0c0b"  VALUES (%s, %s, %s), (%s, %s, %s), (%s, %s, %s), (%s, %s, %s), (%s, %
 requires -32768 <= number <= 32767
--------------------
 config argument botocore_config with value None.
 config argument botocore_config with value None.
====================

 ESCOD

self = <pg8000.legacy.Connection object at 0x7fc7a51c9fa0>
statement_name_bin = b'\x00'
statement = 'INSERT INTO "public"."tbl_20210618191415120540_8a0c0b"  VALUES ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($
statement = 'INSERT INTO "public"."tbl_20210618191415120540_8a0c0b"  VALUES ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($
oids = (21, 21, 705, 21, 21, 705, ...)

    def send_PARSE(self, statement_name_bin, statement, oids):

        val = bytearray(statement_name_bin)
        val.extend(statement.encode(self._client_encoding) + NULL_BYTE)
>       val.extend(h_pack(len(oids)))
E       struct.error: 'h' format requires -32768 <= number <= 32767

lib/python3.8/site-packages/pg8000/core.py:562: error
---------------------------- Captured stdout setup -----------------------------
Table name: tbl_20210618191415120540_8a0c0b
------------------------------ Captured log setup ------------------------------
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
------------------------------ Captured log call -------------------------------
DEBUG    awswrangler.postgresql:postgresql.py:32 Drop table query:
DROP TABLE IF EXISTS "public"."tbl_20210618191415120540_8a0c0b"
DEBUG    awswrangler._data_types:_data_types.py:442 Inferring PyArrow type from column: c0
DEBUG    awswrangler._data_types:_data_types.py:442 Inferring PyArrow type from column: c1
DEBUG    awswrangler._data_types:_data_types.py:467 Inferring PyArrow type from index: __index_level_0__
DEBUG    awswrangler._data_types:_data_types.py:477 columns_types: {'__index_level_0__': DataType(int64), 'c0': DataType
DEBUG    awswrangler._data_types:_data_types.py:692 database_types: {'__index_level_0__': 'BIGINT', 'c0': 'BIGINT', 'c1'
DEBUG    awswrangler.postgresql:postgresql.py:71 Create table query:
CREATE TABLE IF NOT EXISTS "public"."tbl_20210618191415120540_8a0c0b" (
__index_level_0__ BIGINT,
c0 BIGINT,
c1 TEXT)
DEBUG    awswrangler.postgresql:postgresql.py:357 sql: INSERT INTO "public"."tbl_20210618191415120540_8a0c0b"  VALUES (%
ERROR    awswrangler.postgresql:postgresql.py:362 'h' format requires -32768 <= number <= 32767
---------------------------- Captured log teardown -----------------------------
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
DEBUG    awswrangler._config:_config.py:405 Applying default config argument botocore_config with value None.
============================== slowest durations ===============================
0.81s teardown tests/test_postgresql.py::test_to_sql_large
0.71s setup    tests/test_postgresql.py::test_to_sql_large
0.59s call     tests/test_postgresql.py::test_to_sql_large
=========================== short test summary info ============================
FAILED tests/test_postgresql.py::test_to_sql_large - struct.error: 'h' format...
============================== 1 failed in 29.73s ==============================

**Environment**
Package                            Version   Location
---------------------------------- --------- ------------------------------------
alabaster                          0.7.12
anyio                              3.1.0
appdirs                            1.4.4
appnope                            0.1.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.5.6
async-generator                    1.10
attrs                              20.3.0
aws-cdk.assets                     1.109.0
aws-cdk.aws-applicationautoscaling 1.109.0
aws-cdk.aws-autoscaling-common     1.109.0
aws-cdk.aws-cloudwatch             1.109.0
aws-cdk.aws-codeguruprofiler       1.109.0
aws-cdk.aws-ec2                    1.109.0
aws-cdk.aws-ecr                    1.109.0
aws-cdk.aws-ecr-assets             1.109.0
aws-cdk.aws-efs                    1.109.0
aws-cdk.aws-events                 1.109.0
aws-cdk.aws-glue                   1.109.0
aws-cdk.aws-iam                    1.109.0
aws-cdk.aws-kms                    1.109.0
aws-cdk.aws-lambda                 1.109.0
aws-cdk.aws-logs                   1.109.0
aws-cdk.aws-rds                    1.109.0
aws-cdk.aws-redshift               1.109.0
aws-cdk.aws-s3                     1.109.0
aws-cdk.aws-s3-assets              1.109.0
aws-cdk.aws-sam                    1.109.0
aws-cdk.aws-secretsmanager         1.109.0
aws-cdk.aws-signer                 1.109.0
aws-cdk.aws-sqs                    1.109.0
aws-cdk.aws-ssm                    1.109.0
aws-cdk.cloud-assembly-schema      1.109.0
aws-cdk.core                       1.109.0
aws-cdk.cx-api                     1.109.0
aws-cdk.region-info                1.109.0
awswrangler                        2.8.0     /Users/mclean/code/aws-data-wrangler
Babel                              2.9.1
backcall                           0.2.0
beautifulsoup4                     4.9.3
black                              21.6b0
bleach                             3.3.0
boto3                              1.17.96
botocore                           1.20.96
bump2version                       1.0.1
cattrs                             1.5.0
certifi                            2021.5.30
cffi                               1.14.5
cfn-flip                           1.2.3
chardet                            4.0.0
click                              8.0.1
colorama                           0.4.4
constructs                         3.3.84
coverage                           5.5
cryptography                       3.4.7
decorator                          5.0.9
defusedxml                         0.7.1
distlib                            0.3.2
doc8                               0.8.1
docutils                           0.17.1
entrypoints                        0.3
et-xmlfile                         1.1.0
execnet                            1.9.0
filelock                           3.0.12
flake8                             3.9.2
fsspec                             2021.6.0
idna                               2.10
imagesize                          1.2.0
importlib-metadata                 4.5.0
iniconfig                          1.1.1
ipykernel                          5.5.5
ipython                            7.24.1
ipython-genutils                   0.2.0
isort                              5.8.0
jedi                               0.18.0
Jinja2                             3.0.1
jmespath                           0.10.0
jsii                               1.30.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter-client                     6.1.12
jupyter-core                       4.7.1
jupyter-server                     1.8.0
jupyterlab                         3.0.16
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.6.0
keyring                            23.0.1
lazy-object-proxy                  1.6.0
lxml                               4.6.3
MarkupSafe                         2.0.1
matplotlib-inline                  0.1.2
mccabe                             0.6.1
mistune                            0.8.4
more-itertools                     8.8.0
moto                               2.0.9
mypy                               0.902
mypy-extensions                    0.4.3
nbclassic                          0.3.1
nbclient                           0.5.3
nbconvert                          6.0.7
nbformat                           5.1.3
nbsphinx                           0.8.6
nbsphinx-link                      1.3.0
nest-asyncio                       1.5.1
notebook                           6.4.0
numpy                              1.20.3
openpyxl                           3.0.7
packaging                          20.9
pandas                             1.2.4
pandocfilters                      1.4.3
parso                              0.8.2
pathspec                           0.8.1
pbr                                5.6.0
pexpect                            4.8.0
pg8000                             1.19.5
pickleshare                        0.7.5
pip                                19.2.3
pkginfo                            1.7.0
pluggy                             0.13.1
prometheus-client                  0.11.0
prompt-toolkit                     3.0.18
ptyprocess                         0.7.0
publication                        0.0.3
py                                 1.10.0
pyarrow                            4.0.1
pycodestyle                        2.7.0
pycparser                          2.20
pydocstyle                         6.1.1
pydot                              1.4.2
pyflakes                           2.3.1
Pygments                           2.9.0
pylint                             2.8.3
PyMySQL                            1.0.2
pyodbc                             4.0.30
pyparsing                          2.4.7
pyrsistent                         0.17.3
pytest                             6.2.4
pytest-cov                         2.12.1
pytest-forked                      1.3.0
pytest-rerunfailures               10.0
pytest-timeout                     1.4.2
pytest-xdist                       2.2.1
python-dateutil                    2.8.1
python-Levenshtein                 0.12.2
pytz                               2021.1
PyYAML                             5.4.1
pyzmq                              22.1.0
readme-renderer                    29.0
redshift-connector                 2.0.881
regex                              2021.4.4
requests                           2.25.1
requests-toolbelt                  0.9.1
responses                          0.13.3
restructuredtext-lint              1.3.2
rfc3986                            1.5.0
s3fs                               0.4.2
s3transfer                         0.4.2
scramp                             1.4.0
Send2Trash                         1.5.0
setuptools                         41.2.0
six                                1.16.0
sniffio                            1.2.0
snowballstemmer                    2.1.0
soupsieve                          2.2.1
Sphinx                             4.0.2
sphinx-bootstrap-theme             0.7.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
stevedore                          3.3.0
terminado                          0.10.1
testpath                           0.5.0
toml                               0.10.2
tornado                            6.1
tox                                3.23.1
tqdm                               4.61.1
traitlets                          5.0.5
twine                              3.4.1
typing-extensions                  3.10.0.0
urllib3                            1.26.5
virtualenv                         20.4.7
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   1.1.0
Werkzeug                           2.0.1
wheel                              0.36.2
wrapt                              1.12.1
xmltodict                          0.12.0
zipp                               3.4.1

**To Reproduce**
The following code will reproduce this bug

`
def test_to_sql_large(postgresql_table, postgresql_con):
    df = pd.DataFrame({"c0": [i for i in range(50000)], "c1": ["foo" for _ in range(50000)]})
    wr.postgresql.to_sql(df, postgresql_con, postgresql_table, "public", "overwrite", True, chunksize=3200)
`
Increasing chunksize past 6400 will cause the failure above.

**Comment by kukushking** [comment]
Thanks for opening this -- there is indeed a hard limit on a number of placeholders (`%s`) in a single PostgreSQL query:
```
INSERT INTO "public"."tbl_20210622104459807368_92c8f5"  VALUES (%s, %s, %s), ...
```
```
struct.error: 'h' format requires -32768 <= number <= 32767
```
By the looks of it, placeholder counter is `smallint` so you can't put more than that.

**Comment by kukushking** [comment]
Closing - feel free to reopen if required.
