### ISSUE TITLE
wr.s3.read_excel() fails in AWS Glue Python Shell Job

### ISSUE THREAD

**Issue by johntelforduk** [awslabs/aws-data-wrangler#758]
**Describe the bug**

I have a simple script which reads a single sheet spreadsheet in .xlsx format from S3 into a dataframe. I'm running it using the latest version of Data Wrangler, 2.9.0.

The script runs fine when I run it in my IDE (Cloud9). But, when I run it as a Glue Python Shell Job it fails (with .whl file for Data Wrangler 2.9.0 configured in my Glue Job).

Error message is, `ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.`

Note, the Glue Job works fine if I regress to a wheel file for an earlier version of Data Wrangler, for example 2.3.0.

**Environment**

This is the output from `pip freeze` in my IDE (Cloud9). This is not necessarily the same as the environment that my Glue Job runs in.
```
asn1crypto==1.4.0
astroid==2.3.0
awswrangler==2.9.0
backcall==0.2.0
beautifulsoup4==4.9.3
boto3==1.17.86
botocore==1.20.45
certifi==2021.5.30
chardet==4.0.0
decorator==5.0.5
Django==2.0.2
et-xmlfile==1.1.0
git-remote-codecommit==1.15.1
idna==2.10
ikp3db==1.4.1
importlib-metadata==3.10.0
ipython==7.22.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.18.0
jmespath==0.10.0
lazy-object-proxy==1.6.0
lxml==4.6.3
mccabe==0.6.1
numpy==1.20.3
openpyxl==3.0.7
pandas==1.2.4
parso==0.8.2
pbr==5.5.1
pexpect==4.8.0
pg8000==1.19.5
pickleshare==0.7.5
prompt-toolkit==3.0.18
ptyprocess==0.7.0
pyarrow==4.0.1
Pygments==2.8.1
pylint==2.4.4
pylint-django==2.3.0
pylint-flask==0.6
pylint-plugin-utils==0.6
PyMySQL==1.0.2
python-dateutil==2.8.1
pytz==2021.1
redshift-connector==2.0.881
requests==2.25.1
s3transfer==0.4.2
scramp==1.4.0
six==1.15.0
soupsieve==2.2.1
stevedore==3.3.0
traitlets==5.0.5
typed-ast==1.4.2
typing-extensions==3.7.4.3
urllib3==1.26.4
virtualenv==16.2.0
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
wcwidth==0.2.5
wrapt==1.12.1
xlrd==2.0.1
zipp==3.4.1
```

**To Reproduce**

1. In Excel, create a simple, table like spreadsheet with a singe sheet. Save it as `demo_excel.xlsx`.
2. Upload the spreadsheet to `<your bucket>` in S3.
3. Run the script below as a Glue Python Shell Job, with `Python library path` configured to use, `awswrangler-2.9.0-py3-none-any.whl`. The job is confgured to use Python 3, and Glue Version 1.0.
4. The job fails with error message `ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.`

Script,
```
import awswrangler as wr
import pandas as pd
import boto3
import io

data_bucket = 'data-976763253578'
xlsx_object = 'demo_excel.xlsx'

xlsx_s3_df = wr.s3.read_excel('s3://' + data_bucket + '/' + xlsx_object)
print(xlsx_s3_df.head())
```

**Comment by jaidisido** [comment]
Could you please try:
```
xlsx_s3_df = wr.s3.read_excel('s3://' + data_bucket + '/' + xlsx_object, engine="openpyxl")
```
In short, it seems that pandas is not recognizing the file as a "xlsx" for some reason and defaults to the "xlrd" engine instead which is used for "xls" files. Previous versions had the engine hardcoded thus the difference.

Your Cloud9 instance already has "xlrd" installed which explains the difference in behavior.

My advice would be to specify the appropriate engine explicitly as much as possible to avoid relying on Pandas.

**Comment by johntelforduk** [comment]
I tried adding the `engine="openpyxl"` parm that you advised. It has fixed my problem.
Many thanks. If OK with you, I'm happy to close this issue.
