### ISSUE TITLE
API Manual is wrong for awswrangler.catalog.get_columns_comments

### ISSUE THREAD

**Issue by samliuq** [awslabs/aws-data-wrangler#759]
**Describe the bug**
The contents is wr.catalog.get_table_parameters
https://aws-data-wrangler.readthedocs.io/en/2.9.0/stubs/awswrangler.catalog.get_columns_comments.html#awswrangler.catalog.get_columns_comments

**Environment**
NA

**To Reproduce**

NA

**Comment by jaidisido** [comment]
Thanks for raising this, now fixed in [latest](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.catalog.get_columns_comments.html#awswrangler.catalog.get_columns_comments) version of documentation (please make sure to hard refresh the browser to see the change)
