### ISSUE TITLE
support for np.uint64

### ISSUE THREAD

**Issue by robertaves** [awslabs/aws-data-wrangler#76]
data sets i deal with have a lot of unsigned 64 bit numbers and i'm struggling finding the best way for parquet not to mess them up on load/unload.

 May be some issues within pyarrow for support?

**Comment by igorborgest** [comment]
Hey @robertaves, sorry about this ancient issue!

I've just added full uint8, uint16 and uint32 support.

I also added support to uint64, but unfortunately it is not supported on Athena, so you will only be able to use it reading directly from s3.

**Comment by robertaves** [comment]
Awesome, this is all i can ask for, i'll close this out as it meets my needs. Thanks again

**Comment by igorborgest** [comment]
Available on version [1.1.2](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.1.2)
