### ISSUE TITLE
Output format should also be an optional parameter in unload to files method

### ISSUE THREAD

**Issue by mohdaliiqbal** [awslabs/aws-data-wrangler#760]
https://github.com/awslabs/aws-data-wrangler/blob/e25f4294f137f368e4e3d1d1596bc29bcb5e9a63/awswrangler/redshift.py#L951

Many times data scientists would need to unload files in CSV format for training models. Parquet may not be supported by all libraries. Unload should support choosing format.

**Comment by jaidisido** [comment]
Thank you for suggesting this @mohdaliiqbal, it's a fair ask. A [PR](https://github.com/awslabs/aws-data-wrangler/pull/761) has been raised.

**Comment by jaidisido** [comment]
This has now been merged to `main` and can be tested:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
until it's available in the next release.
