### ISSUE TITLE
AttributeError: '_S3ObjectBase' object has no attribute '_mode' in data deletion

### ISSUE THREAD

**Issue by samliuq** [awslabs/aws-data-wrangler#762]
**Describe the bug**
Happens in either the following two steps.
    
    # 1. Write to catalog, use the first $n rows as sampler object, for glue to infer schema
    wr.s3.to_csv(df.iloc[:30]
                 , path = write_path
                 , dataset = True
                 , database = dbname
                 , table = save_as_table
                 , index = False
                 , description = description
                 , boto3_session = boto3_session
                 , s3_additional_kwargs={'ACL': 'bucket-owner-full-control'}     
                )
    
    # 2. Delete the sampler object we wrote in step 1
    wr.s3.delete_objects(write_path) 

* Error Message
Exception ignored in: <bound method _S3ObjectBase.__del__ of <awswrangler.s3._fs._S3ObjectBase object at 0x7fbeefc3c160>>
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py", line 294, in __del__
    self.close()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py", line 500, in close
    if self.writable():
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py", line 494, in writable
    return "w" in self._mode
AttributeError: '_S3ObjectBase' object has no attribute '_mode'

**Environment**

Provide your `pip list` output, particularly the version of the AWS Data Wrangler library you used. Providing this information may significantly improve resolution times.
Package                            Version
---------------------------------- -----------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0
atomicwrites                       1.3.0
attrs                              20.3.0
Automat                            20.2.0
autopep8                           1.4.4
autovizwidget                      0.17.1
awscli                             1.18.197
awswrangler                        2.8.0
Babel                              2.8.0
backcall                           0.1.0
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.2.0
beautifulsoup4                     4.8.2
bitarray                           1.2.1
bkcharts                           0.2
bleach                             3.2.1
bokeh                              1.4.0
boto                               2.49.0
boto3                              1.16.37
botocore                           1.19.37
Bottleneck                         1.3.2
cached-property                    1.5.2
certifi                            2020.11.8
cffi                               1.14.0
chardet                            3.0.4
Click                              7.0
cloudpickle                        1.3.0
clyent                             1.2.2
colorama                           0.4.3
contextlib2                        0.6.0.post1
cryptography                       2.8
cycler                             0.10.0
Cython                             0.29.15
cytoolz                            0.10.1
dask                               2.11.0
decorator                          4.4.1
defusedxml                         0.6.0
diff-match-patch                   20181111
dill                               0.3.3
distributed                        2.11.0
distro                             1.5.0
docker                             4.4.0
docker-compose                     1.27.4
dockerpty                          0.4.1
docopt                             0.6.2
docutils                           0.15.2
entrypoints                        0.3
environment-kernels                1.1.1
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.7.9
Flask                              1.1.1
fsspec                             0.6.2
future                             0.18.2
gevent                             1.4.0
glob2                              0.7
gmpy2                              2.0.8
google-pasta                       0.2.0
greenlet                           0.4.15
h5py                               2.10.0
hdijupyterutils                    0.17.1
HeapDict                           1.0.1
html5lib                           1.0.1
hypothesis                         5.5.4
idna                               2.10
imageio                            2.6.1
imagesize                          1.2.0
importlib-metadata                 3.1.0
intervaltree                       3.0.2
ipykernel                          5.1.4
ipyparallel                        6.3.0
ipython                            7.12.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.14.1
jeepney                            0.4.2
Jinja2                             2.11.1
jmespath                           0.10.0
joblib                             0.14.1
json5                              0.9.1
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     5.3.4
jupyter-console                    6.1.0
jupyter-core                       4.6.1
jupyterlab                         1.2.6
jupyterlab-server                  1.0.6
keyring                            21.1.0
kiwisolver                         1.1.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.8
lief                               0.9.0
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.6.2
MarkupSafe                         1.1.1
matplotlib                         3.1.3
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.0.15
mkl-random                         1.1.0
mkl-service                        2.3.0
mock                               4.0.1
more-itertools                     8.2.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
nb-conda                           2.2.1
nb-conda-kernels                   2.2.4
nbconvert                          5.6.1
nbformat                           5.0.4
networkx                           2.4
nltk                               3.4.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.4
numpydoc                           0.9.2
nvidia-ml-py                       10.418.84
olefile                            0.46
opencv-python                      4.2.0.32
openpyxl                           3.0.3
packaging                          20.7
pandas                             1.1.5
pandocfilters                      1.4.2
paramiko                           2.7.2
parso                              0.5.2
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pg8000                             1.19.5
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.3
pkginfo                            1.5.0.1
plotly                             4.13.0
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.7.1
prompt-toolkit                     3.0.3
protobuf                           3.14.0
protobuf3-to-dict                  0.1.5
psutil                             5.6.7
psycopg2                           2.7.5
ptyprocess                         0.6.0
py                                 1.8.1
py3cli                             1.0.1
py4j                               0.10.7
pyarrow                            2.0.0
pyasn1                             0.4.8
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.5
pydocstyle                         4.0.1
pyfiglet                           0.7
pyflakes                           2.1.1
pyfunctional                       1.4.2
pygal                              2.4.0
Pygments                           2.5.2
pykerberos                         1.2.1
pylint                             2.6.0
PyMySQL                            1.0.2
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyrsistent                         0.15.7
PySocks                            1.7.1
pyspark                            2.3.4
pytest                             5.3.5
pytest-arraydiff                   0.3
pytest-astropy                     0.8.0
pytest-astropy-header              0.1.2
pytest-doctestplus                 0.5.0
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
python-dotenv                      0.15.0
python-jsonrpc-server              0.3.4
python-language-server             0.31.7
pytz                               2021.1
PyWavelets                         1.1.1
pyxdg                              0.26
PyYAML                             5.3.1
pyzmq                              18.1.1
QDarkStyle                         2.8
QtAwesome                          0.6.1
qtconsole                          4.6.0
QtPy                               1.9.0
redshift-connector                 2.0.881
requests                           2.25.0
requests-kerberos                  0.12.0
retrying                           1.3.3
rope                               0.16.0
rsa                                4.5
Rtree                              0.9.3
ruamel-yaml                        0.15.87
s3fs                               0.4.2
s3transfer                         0.3.3
sagemaker                          2.19.0
sagemaker-pyspark                  1.4.1
scikit-image                       0.16.2
scikit-learn                       0.22.1
scipy                              1.4.1
scramp                             1.4.0
seaborn                            0.10.0
SecretStorage                      3.1.2
Send2Trash                         1.5.0
setuptools                         50.3.2
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.15.0
sklearn                            0.0
smclarify                          0.1
smdebug-rulesconfig                1.0.0
snowballstemmer                    2.0.0
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.9.5
sparkmagic                         0.15.0
Sphinx                             3.3.1
sphinxcontrib-applehelp            1.0.1
sphinxcontrib-devhelp              1.0.1
sphinxcontrib-htmlhelp             1.0.2
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.2
sphinxcontrib-serializinghtml      1.1.3
sphinxcontrib-websupport           1.2.0
spyder                             4.0.1
spyder-kernels                     1.8.1
SQLAlchemy                         1.3.13
statsmodels                        0.11.0
sympy                              1.5.1
tables                             3.6.1
tabulate                           0.8.7
tblib                              1.6.0
terminado                          0.8.3
testpath                           0.4.4
texttable                          1.6.3
toml                               0.10.2
toolz                              0.10.0
tornado                            6.0.3
tqdm                               4.42.1
traitlets                          4.3.3
typed-ast                          1.4.1
ujson                              1.35
unicodecsv                         0.14.1
urllib3                            1.25.11
watchdog                           0.10.2
wcwidth                            0.1.8
webencodings                       0.5.1
websocket-client                   0.57.0
Werkzeug                           1.0.0
wheel                              0.34.2
widgetsnbextension                 3.5.1
wrapt                              1.11.2
wurlitzer                          2.0.0
xlrd                               1.2.0
XlsxWriter                         1.2.7
xlwt                               1.3.0
yapf                               0.28.0
zict                               1.0.0
zipp                               3.4.0
WARNING: You are using pip version 20.3; however, version 21.1.2 is available.
You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.
​

**To Reproduce**

Steps to reproduce the behavior.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
We will need a specific example to reproduce this please. The only reason I can think of is if you are making a large number of concurrent calls to S3 which might lead to race conditions. Perhaps try to space the calls
