### ISSUE TITLE
How to read nested json files using wr.sw.read_json()

### ISSUE THREAD

**Issue by Diegofisie** [awslabs/aws-data-wrangler#763]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
Hi, So im trying to read a nested json file and converting it to parquet. with this code. 

 df = wr.s3.read_json(path=PATH,path_suffix='.json', orient="record", lines=True)
 wr.s3.to_parquet(df=df, path=PATH2, dataset=True, mode="append")

However, when I run it it shows this error.
errorMessage": "Expected object or value",
  "errorType": "ValueError",
 

I tried with another json file that is not nested and it works, so Im kind of stuck here.

**Comment by kukushking** [comment]
Do you mind sharing the JSON or at least something resembling the similar structure you are trying to read? 

Also please note:

`orient=records` means you expect a JSON array like [{column -> value}, ... , {column -> value}]
`lines=True` reads the file as a json object per line

So according to these flags your file must contain something like (note the nested JSON as well):
```
[{"id": {"0": 4, "1": 5, "2": 6}, "value": {"0": "foo", "1": "boo", "2": {"0": "buzz"}}}]
[{"id": {"0": 4, "1": 5, "2": 6}, "value": {"0": "foo", "1": "boo", "2": {"0": "buzz"}}}]
[{"id": {"0": 4, "1": 5, "2": 6}, "value": {"0": "foo", "1": "boo", "2": {"0": "buzz"}}}]
```
Which is read fine by:
```
df1 = wr.s3.read_json(path="s3://<dummy>/df.json", orient="record", lines=True)
```

**Comment by Diegofisie** [comment]
Ok, let me try it. But I think I found the problem. My json doesnt have the square brackets between the registries.
`{"id": {"0": 4, "1": 5, "2": 6}, "value": {"0": "foo", "1": "boo", "2": {"0": "buzz"}}},
{"id": {"0": 4, "1": 5, "2": 6}, "value": {"0": "foo", "1": "boo", "2": {"0": "buzz"}}},
{"id": {"0": 4, "1": 5, "2": 6}, "value": {"0": "foo", "1": "boo", "2": {"0": "buzz"}}}
`
This is sort of what I have

**Comment by kukushking** [comment]
Yes, missing square brackets is definitely going to cause problems. Adding them works:
```
[{"id":{"0":4,"1":5,"2":6},"value":{"0":"foo","1":"boo","2":{"0":"buzz"}}},{"id":{"0":4,"1":5,"2":6},"value":{"0":"foo","1":"boo","2":{"0":"buzz"}}},{"id":{"0":4,"1":5,"2":6},"value":{"0":"foo","1":"boo","2":{"0":"buzz"}}}]
```
```
In[4]: df = wr.s3.read_json(path="s3://antonkuk/json/df.json", orient="record", lines=True)
In[5]: df
                                                   0  ...                                                  2
0  {'id': {'0': 4, '1': 5, '2': 6}, 'value': {'0'...  ...  {'id': {'0': 4, '1': 5, '2': 6}, 'value': {'0'...
[1 rows x 3 columns]
```
