### ISSUE TITLE
Add function overwrite_table_description()

### ISSUE THREAD

**Issue by samliuq** [awslabs/aws-data-wrangler#766]
**Is your idea related to a problem? Please describe.**
Need this function for user to manage and take memos on the datasets they created.
Current version seems we can only update table description by overwrite the table.

**Describe the solution you'd like**
Add a function overwrite_table_description(), which should allow user to overwrite existing table description.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
The `update_table` in boto3 already implements this feature:
```
import boto3
client = boto3.client("glue")
client.update_table(
    DatabaseName="my_db",
    TableInput={
        "Name": "my_table",
        "Description": "my_desc",
    }
)
```
Wrangler does not aim to duplicate methods already covered by boto3, only to complement them.
