### ISSUE TITLE
Documentation Error on page : https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.redshift.connect_temp.html#awswrangler.redshift.connect_temp

### ISSUE THREAD

**Issue by priyabratapatnaik** [awslabs/aws-data-wrangler#771]
Hello,

The example on this page https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.redshift.connect_temp.html#awswrangler.redshift.connect_temp is for connect not connect_temp. Please update documentation on the page with correct example.

**Comment by kukushking** [comment]
Thanks! [updated](https://github.com/awslabs/aws-data-wrangler/commit/a0b3b67d217e2bfe7b2eaefda0d1df1a5f9a6f3d)
