### ISSUE TITLE
wr.s3.to_parquet() fails to write to existing table with struct columns

### ISSUE THREAD

**Issue by DrIgor** [awslabs/aws-data-wrangler#772]
`s3.to_parquet()` fails to write dataframe if table already exists in glue catalog and has `struct` columns

**Environment**
awswrangler==2.9.0
python 3.7

**To Reproduce**
Try this snippet:
```
import awswrangler as wr
import pandas as pd

df = pd.DataFrame([{"foo": {"bar": "bar", "baz": "baz"}}])

wr.catalog.create_parquet_table(database="database", table="test", path="s3://bucket/prefix/", columns_types={"foo": "struct<bar: string, baz: string>"})
wr.s3.to_parquet(df, dataset=True, database="database", table="test")
```
exception is thrown during `to_parquet` call:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../lib/python3.7/site-packages/awswrangler/_config.py", line 417, in wrapper
    return function(**args)
  File ".../lib/python3.7/site-packages/awswrangler/s3/_write_parquet.py", line 608, in to_parquet
    catalog_table_input=catalog_table_input,
  File ".../lib/python3.7/site-packages/awswrangler/catalog/_create.py", line 249, in _create_parquet_table
    f"Data type change detected on column {c} (Old type: {catalog_cols[c]} / New type {t})."
awswrangler.exceptions.InvalidArgumentValue: Data type change detected on column foo (Old type: struct<bar: string, baz: string> / New type struct<bar:string,baz:string>).
```
Type of struct column is considered as changed. But in fact the only difference is in whitespaces.

Moreover, Athena allows comments for struct fields (see https://docs.aws.amazon.com/athena/latest/ug/data-types.html). 
For example: `columns_types={"foo": "struct<bar: string comment bar comment, baz: string>"}`
In this case I get exception:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../lib/python3.7/site-packages/awswrangler/_config.py", line 417, in wrapper
    return function(**args)
  File ".../lib/python3.7/site-packages/awswrangler/s3/_write_parquet.py", line 537, in to_parquet
    df=df, index=index, ignore_cols=partition_cols, dtype=dtype
  File ".../lib/python3.7/site-packages/awswrangler/_data_types.py", line 581, in pyarrow_schema_from_pandas
    columns_types[k] = athena2pyarrow(dtype=v)
  File ".../lib/python3.7/site-packages/awswrangler/_data_types.py", line 288, in athena2pyarrow
    [(f.split(":", 1)[0], athena2pyarrow(f.split(":", 1)[1])) for f in _split_struct(orig_dtype[7:-1])]
  File ".../lib/python3.7/site-packages/awswrangler/_data_types.py", line 288, in <listcomp>
    [(f.split(":", 1)[0], athena2pyarrow(f.split(":", 1)[1])) for f in _split_struct(orig_dtype[7:-1])]
  File ".../lib/python3.7/site-packages/awswrangler/_data_types.py", line 293, in athena2pyarrow
    raise exceptions.UnsupportedType(f"Unsupported Athena type: {dtype}")
awswrangler.exceptions.UnsupportedType: Unsupported Athena type: stringcommentbarcomment
```

**Comment by jaidisido** [comment]
Given the number of type comparison/conversions involved in the library (Arrow, Athena, Pandas...), Wrangler tries to standardize types to ease comparison. This includes removing [spaces](https://github.com/awslabs/aws-data-wrangler/blob/f98d6bab99afb3c77baa237b59081c4c6650ba47/awswrangler/_data_types.py#L525). So it's up to the user to provide sanitized types as inputs, by removing spaces in your case.

**Comment by DrIgor** [comment]
Thank you for reply!

Yes, it works if I remove spaces from table definition. But unfortunately table may have been created for a long time ago

As I understand, `s3.to_parquet()` loads schema from glue catalog. I think, it is possible to sanitize types in this schema before usage

**Comment by jaidisido** [comment]
If this is specific to a table,  perhaps you could monkey patch your Wrangler version to accommodate this particular use case. It would be as simple as changing this [line](https://github.com/awslabs/aws-data-wrangler/blob/f98d6bab99afb3c77baa237b59081c4c6650ba47/awswrangler/_data_types.py#L525) to:
```
athena_columns_types[k] = casts[k]
```
and your `to_parquet` should succeed.
