### ISSUE TITLE
awswrangler.s3.describe_objects() fails with client error 403 in version 2.9 when a wildcard path contains multiple objects

### ISSUE THREAD

**Issue by fractionalhare** [awslabs/aws-data-wrangler#780]
**Describe the bug**

Given an S3 path of the form `s3://example_bucket/path/to/key/prefix_*` that you have access to, if there are multiple objects under this path, then the call `awswrangler.s3.describe_objects()` will fail with error `botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`. This does not occur when there only exists a single object under the path, in which case the outcome matches the expected behavior and the call succeeds. This is unrelated to authentication.

Testing confirms that this issue does not exist on major versions 2.7 and 2.8. It is new in 2.9.

**Environment**

I can't share all of our dependencies, but here are the relevant AWS packages from our `environment.yml` file:

```
- awswrangler=2.9
- boto3~=1.17
- botocore~=1.20
```

**To Reproduce**

1. To show that the issue is `awswrangler.s3.describe_objects()` and not an e.g. auth issue, attempt both `awswrangler.s3.describe_objects()` and `awswrangler.s3.list_objects()` on a path you have access to with the form described in the foregoing bug description, i.e. `s3://example_bucket/path/to/key/prefix_*` and compare the outputs. Only the `describe_objects` call results in a 403 client error.

2. To show that the issue is related to paths including shell-style wildcards, attempt an `awswrangler.s3.describe_objects()` call on a regular bucket path you have access to, containing multiple objects under it, without a wildcard in the path: e.g. `s3://bucket_name/path/to/key/prefix/`, where under `prefix` there is `object1, object2, ...`

3. To confirm that this issue is new in major version 2.9, attempt the two previous reproduction steps with major versions 2.7, 2.8.

4. To confirm that this is an issue in awswrangler, and not e.g. boto3 or botocore, hold those versions constant while changing awswrangler versions and confirming that the issue is not present in earlier major versions of awswrangler.

**Comment by jaidisido** [comment]
Hi @fractionalhare, first of all thank you for this issue description, it's clear and thorough.

I am finding it difficult to reproduce it however. In my test setup, I have uploaded 4 files with the same prefix:
- s3://my-bucket/my-prefix/dummy_1.txt
- s3://my-bucket/my-prefix/dummy_2.txt
- s3://my-bucket/my-prefix/dummy_3.txt
- s3://my-bucket/my-prefix/dummy_4.txt

Then ran the below commands which match your description:
```
path = "s3://my-bucket/my-prefix/"
prefix = "dummy"

print("Version: ", wr.__version__)
print("List Objects: ", wr.s3.list_objects(path=f"{path}{prefix}*"))
print("Describe Object: ", wr.s3.describe_objects(path=path).keys())
print("Describe Object: ", wr.s3.describe_objects(path=f"{path}{prefix}_1.txt").keys())
print("Describe Objects: ", wr.s3.describe_objects(path=f"{path}{prefix}*").keys())
```
Results are as expected, event the last call which you mention is failing for you:
```
Version:  2.9.0
List Objects:  ['s3://my-bucket/my-prefix/dummy_1.txt', 's3://my-bucket/my-prefix/dummy_2.txt', 's3://my-bucket/my-prefix/dummy_3.txt', 's3://my-bucket/my-prefix/dummy_4.txt']
Describe Object:  dict_keys(['s3://my-bucket/my-prefix/dummy_1.txt', 's3://my-bucket/my-prefix/dummy_2.txt', 's3://my-bucket/my-prefix/dummy_3.txt', 's3://my-bucket/my-prefix/dummy_4.txt'])
Describe Object:  dict_keys(['s3://my-bucket/my-prefix/dummy_1.txt'])
Describe Objects:  dict_keys(['s3://my-bucket/my-prefix/dummy_1.txt', 's3://my-bucket/my-prefix/dummy_2.txt', 's3://my-bucket/my-prefix/dummy_3.txt', 's3://my-bucket/my-prefix/dummy_4.txt'])
```

I have also created multiple paths with the same prefix:
- s3://my-bucket/dummy_1/dummy_1.txt
- s3://my-bucket/dummy_1/dummy_2.txt
- s3://my-bucket/dummy_2/dummy_1.txt
- s3://my-bucket/dummy_2/dummy_2.txt
- s3://my-bucket/dummy_3/dummy_1.txt
- s3://my-bucket/dummy_3/dummy_2.txt

and ran:
```
path = "s3://my-bucket/dummy"

print("Version: ", wr.__version__)
print("List Objects: ", wr.s3.list_objects(path=f"{path}*"))
print("Describe Object: ", wr.s3.describe_objects(path=f"{path}_1/").keys())
print("Describe Objects: ", wr.s3.describe_objects(path=f"{path}*").keys())
```
again without any issue:
```
Version:  2.9.0
List Objects:  ['s3://my-bucket/dummy_1/dummy_1.txt', 's3://my-bucket/dummy_1/dummy_2.txt', 's3://my-bucket/dummy_2/dummy_1.txt', 's3://my-bucket/dummy_2/dummy_2.txt', 's3://my-bucket/dummy_3/dummy_1.txt', 's3://my-bucket/dummy_3/dummy_2.txt']
Describe Object:  dict_keys(['s3://my-bucket/dummy_1/dummy_1.txt', 's3://my-bucket/dummy_1/dummy_2.txt'])
Describe Objects:  dict_keys(['s3://my-bucket/dummy_1/dummy_1.txt', 's3://my-bucket/dummy_1/dummy_2.txt', 's3://my-bucket/dummy_2/dummy_1.txt', 's3://my-bucket/dummy_2/dummy_2.txt', 's3://my-bucket/dummy_3/dummy_1.txt', 's3://my-bucket/dummy_3/dummy_2.txt'])
```

I must admit that the fact it's failing for you for a specific Wrangler version is perplexing. Could you please provide more details on how the files are stored in the bucket? Likewise, if you could provide more details on the Wrangler commands you are running and the parameters used. Ideally we would want a snippet of code with actual Wrangler commands that reproduces your issue.

Finally, the IAM role used for my tests is an admin, not that it should matter but you never know...

**Comment by jaidisido** [comment]
Closing for now as no response. Feel free to reopen in the future
