### ISSUE TITLE
Schema Evolution parameter on awswrangler.s3.to_csv method

### ISSUE THREAD

**Issue by raulmeza** [awslabs/aws-data-wrangler#787]
Hi, good morning.

I have a doubt if the method awswrangler.s3.to_csv has **schema_evolution** parameter support. I don't see as Parameter in documentation but if I see the **dataset** parameter definition, this is mentioned. 

> dataset (bool) – If True store as a dataset instead of ordinary file(s) If True, enable all follow arguments: partition_cols, mode, database, table, description, parameters, columns_comments, concurrent_partitioning, catalog_versioning, projection_enabled, projection_types, projection_ranges, projection_values, projection_intervals, projection_digits, catalog_id, **schema_evolution**

Is posibble use **schema_evolution** on awswrangler.s3.to_csv method ?

**PD:** I am using AWS Data Wrangler version 2.9

Thanks,
Regards

**Comment by kukushking** [comment]
Hi @raulmeza, no, at the moment schema evolution is not available for `wr.s3.to_csv`, however this looks like a good moment to add it.
