### ISSUE TITLE
Read DynamoDB json data from s3 using awswrangler.s3.read_json()

### ISSUE THREAD

**Issue by veera-nunna** [awslabs/aws-data-wrangler#790]
**Is your feature request related to a problem? Please describe.**
When I read Dynamodb Json data from S3 using `awswrangler.s3.read_json()`, all the column data types are read as object, for ex:
`"title":{"s":"some-string"}` is read as :
```
0       {'s': 'some-string'}
1       {'s': 'some-string'}
2       {'s': 'some-string'}
3       {'s': 'some-string'}
4       {'s': 'some-string'}
           ...    

Name: title, Length: 8381, dtype: object 
```

**Describe the solution you'd like**

Right now I am reading json in native python, deserializing it and then converting it into pandas dataframe which might not be efficient. 

If `awswrangler.s3.read_json()` API support DynamoDB json I can use the API to read DynamoDB data from S3 directly.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
Hi @veera-nunna, adapting a Wrangler method to a particular use case (i.e. reading DynamoDB data from S3 in your case) would be too specific. The real question in my view is why is the DynamoDB JSON data stored in S3 with data types in the first place? You could just get the items without the data types ([example](https://stackoverflow.com/questions/45421939/dynamodb-get-item-and-put-item-without-data-types-in-python)) and store them in S3.
