### ISSUE TITLE
AWS Wrangler - Read CSV with chuncksize = 100000

### ISSUE THREAD

**Issue by rvasconcelossilva** [awslabs/aws-data-wrangler#796]
**Describe the bug**

I have a lambda function that will convert the csv file to parquet. My file has 3.5GB compressed (gzip). I am using the chunksize to help to run it and I set it to 100000 however when I am in my loop it stops running. I am debugging it using SAM. This file has around 450 columns. Unfortunately I can't share the file.

No error message is presented only my code stops running.

**Environment**

Lambda code:

I am using awswrangler-layer-2.9.0-py3.8.zip with Python 3.8. It is running in a docker container as required by SAM.

**To Reproduce**

```
import json
import awswrangler

def lambda_handler(event, context):
    s3_bucket = event['detail']['requestParameters']['bucketName']
    key = event['detail']['requestParameters']['key']
    file_path =  's3://{0}/{1}'.format(s3_bucket, key)

    try:
        print(file_path)
        #reading original file
        df_smrtr = awswrangler.s3.read_csv(path=file_path, 
                                           compression="gzip",
                                           sep='\t',
                                           s3_additional_kwargs={
                                               'ServerSideEncryption': 'AES256'
                                           },
                                           chunksize=100000
                                           )
                                          
        file_path_to =  's3://{0}/raw/dataset/'.format(s3_bucket)
        table_to = 'tb_consumerprofile' 


        #writing
        awswrangler.s3.delete_objects(file_path_to)

        for df in df_smrtr:
            awswrangler.s3.to_parquet(df=df,path=file_path_to, dataset=True, database="db_insights_raw", table=table_to)
                                                       
        return {
            "statusCode": 200,
            "body": json.dumps({
                "message": "dataset ingested with success.",
            }),
        }        

    except Exception as e:
        return {
            "statusCode": 400,
            "body": json.dumps({
                "message": str(e),
            }),
        } 
```

Template:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  raw_transformation

  Sample SAM Template for smrtr_raw_transformation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 15
      Layers:
        - !Ref AWSWranglerLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  AWSWranglerLayer:            
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes: 
        - python3.8
      ContentUri: ../../../../awswrangler-layer-2.9.0-py3.8.zip
      Description: 'awswrangler library'
      LayerName: 'awswrangler'
      LicenseInfo: MIT
      RetentionPolicy: Retain            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Hi, I had a quick look at your SAM Lambda function configuration and your  timeout is set to 15 seconds (`Timeout: 15`). That is way too short to process anything really. Likewise the memory size is not specified which means that it's set to the default (256 Mb), again too low. Regardless, I would not advise using a Lambda function to process files of this size, even with the largest memory and timeout available and using the `chunksize` parameter. EC2 and Glue jobs are far better options. If you do insist on using Lambda, I would at least consider using the [container image](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html) feature.

**Comment by rvasconcelossilva** [comment]
Hi @jaidisido thank you for your reply. My bad I thought was minutes and with your comment I added more memory. One addition, questions, anyway, still have some performance issues although my dataset is big, do you know how I can improve performance on writing as well?

**Comment by jaidisido** [comment]
By "writing" I suppose you are referring to the [to_parquet](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) method? If so, I would look to leverage the available function parameters, mostly `use_threads`, `compression` and `concurrent_partitioning`, to help with performance.

**Comment by rvasconcelossilva** [comment]
Thanks. I am closing this item.
