### ISSUE TITLE
Support Redshift Data API and RDS Data Service

### ISSUE THREAD

**Issue by pwithams** [awslabs/aws-data-wrangler#798]
**Is your feature request related to a problem? Please describe.**
I have started using the Redshift Data API via boto3 but needed to create a wrapper class to make it practical to use. As my class returns a Pandas dataframe and simplifies an AWS data interface, this seems well suited as an awswrangler feature. Additionally, the Redshift Data API looks similar to RDS Data Service so it would make sense to also support that.

**Describe the solution you'd like**
Two classes `RedshiftConnector` and `RDSConnector` (or something similar).

I have already created a `RedshiftConnector` class for personal use - here is the interface:

```
conn = redshift.RedshiftConnector(database_name, cluster_id)
conn.set_authentication(db_user=db_user) # if using temporary credentials
conn.set_authentication(secret_arn=secret_arn) # if using credentials from secrets manager

query: str = f"SELECT * FROM my_schema.my_table LIMIT 10"
results_df: pd.DataFrame = conn.execute_statement(query)
```

seeing as the boto3 RDS API appears similar to the redshift one, I'd imagine `RDSConnector` would have a very similar interface, potentially both extending from a shared data API class.

**Comment by pwithams** [comment]
I just saw https://github.com/awslabs/aws-data-wrangler/issues/207 which seems related - I can look into submitting a PR if that's an option.

**Comment by jaidisido** [comment]
@pwithams thanks for suggesting this, PRs are always welcome and this seems like a good use case!

**Comment by pwithams** [comment]
Closing as https://github.com/awslabs/aws-data-wrangler/pull/828 supports this feature and has been merged.
