### ISSUE TITLE
reading csv and writing parquet in chunks in overwrite mode

### ISSUE THREAD

**Issue by chtorr** [awslabs/aws-data-wrangler#80]
Hello!  I have some larger CSV's that I need to read from S3 in chunks using `max_results_size` and write each chunk to parquet.  I can't fit the entire pandas df in memory, so I was hoping to loop over the iterator of dataframes and write each chunk.  However, every flow to write to S3 in overwrite mode seems to include deleting any file not associated with that specific operation chain, so it ends up deleting parquet files from previously written chunks.  Do you have any suggestions on how I could accomplish this?

Thanks!

**Comment by igorborgest** [comment]
Hi @chtorr!
We have three modes actually:

- overwrite: replaces all files in the destination
- append: only add the new data without touch in the one that already exists in the destination
- overwrite_partitions: is like “overwrite” but only for for a partition scope. Good for updates.

The “append” looks to fit perfect for your case! What you think?

P.S. If ou need to reset the table before every loop, run session.s3.delete_objects() and session.glue.delete_table_if_exists() before it!

**Comment by chtorr** [comment]
Hi Igor,

Thank you for the quick response!  In this case I want the behavior of `overwrite`, I just don’t want it to clear out the path on every loop.  I can definitely handle the delete before I start looping and force `append` mode on writing each chunk, I just wanted to check if you had ideas for ways to make the `overwrite` modes iteration-aware before I started down that path.

Thanks again!
