### ISSUE TITLE
ClientError: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.

### ISSUE THREAD

**Issue by chanansh** [awslabs/aws-data-wrangler#813]
**Describe the bug**

If I parallelize get_query I get the following error:
ClientError: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.

**Environment**
latest awswrangler

**To Reproduce**

Hard, it depends on my own data.  I used joblib.Parallel

**Comment by jaidisido** [comment]
This might be related to this recent [change](https://github.com/awslabs/aws-data-wrangler/pull/738/files). Need to investigate

**Comment by jaidisido** [comment]
This has now been merged to main and can be tested:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
until it's available in the next release.
