### ISSUE TITLE
ability to "upsert" to redshift via a staging table

### ISSUE THREAD

**Issue by robertaves** [awslabs/aws-data-wrangler#83]
Abilty to use a pandas dataframe to upsert records in redshift.

https://gist.github.com/mmautner/c102bff31d386679f021 Example
https://docs.aws.amazon.com/redshift/latest/dg/t_updating-inserting-using-staging-tables-.html Redshift docs

**Comment by igorborgest** [comment]
Available on versions >= 0.1.3 🎉
