### ISSUE TITLE
Convert .tgz in S3 bucket to .parquet without storing locally

### ISSUE THREAD

**Issue by rrpelgrim** [awslabs/aws-data-wrangler#830]
I have a .tgz file in a public s3 bucket that I need to convert into .parquet without storing it locally. Is that possible with `aws-wrangler`?

I have tried using `df = wr.s3.read_csv(path1)` and then passing that `df` to `wr.s3.to_parquet()` but this seems to download the data locally first, which I need to avoid (dataset is 200GB uncompressed).

[EDIT] One solution I see is having the `aws-wrangler` load into a Dask dataframe located in the cloud instead. Is that possible?

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by maxispeicher** [comment]
`S3` does not support modifying the files inplace directly. The default workflow is to download the data, do what you want it with it and upload again. You could try to stream the data and directly upload it again. You can have a look at [SO1](https://stackoverflow.com/a/53490126/10608063) or [SO2](https://stackoverflow.com/a/51277382/10608063) for some inspiration.

You can also just spin up an EC2 instance or an EMR cluster which uses the `awswrangler` commands and downloads the complete file and then does the unpacking and uploading.

**Comment by jaidisido** [comment]
[S3 select](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/029%20-%20S3%20Select.html) might be a good candidate for your use case, bearing in mind all the limitations in terms of max length of record, max uncompressed group size... It can handle gzip compressed CSV files (not sure about tar gzip though) with most of the heavy lifting done server-side. However, I would recommend applying as many filters as possible in the SQL query to limit the amount of memory required client-side.

Regardless, as Maxi mentioned, your laptop is unlikely to handle the load given the file size and you might want to consider a more suitable option such an EC2 instance, Glue job or EMR cluster.
