### ISSUE TITLE
redshift.to_sql() makes column name with double quotes when creating the sql statement

### ISSUE THREAD

**Issue by dragonH** [awslabs/aws-data-wrangler#837]
**Is your idea related to a problem? Please describe.**

When using `redshift.to_sql()`

the function would load dataframe to redshift

but seems it did not consider the `preserve word` issue

if i have a dataframe like below:

a|group|
--|--|
a|b|

when it create a sql statement and execute it

it would meet an error since the sql statement created by the function looks like this:

```sql
CREATE TABLE IF NOT EXISTS "public"."test_table" (
a VARCHAR(65535),
group VARCHAR(65535),
PRIMARY KEY (a))
DISTSTYLE AUTO
```

**Describe the solution you'd like**

Add double quotes when creating sql statement

the following sql seems workable

```sql
CREATE TABLE IF NOT EXISTS "public"."test_table" (
a VARCHAR(65535),
"group" VARCHAR(65535),
PRIMARY KEY (a))
DISTSTYLE AUTO
```
i know we could modify the column name with `'\"{column name}\"'`

but it might not be a bad idea to do in awswrangler ?

**Comment by kukushking** [comment]
Linking #806
