### ISSUE TITLE
ModuleNotFoundError: No module named 'awswrangler' [AWS Glue Pyspark] due to package versions and dependencies for v2.10.0

### ISSUE THREAD

**Issue by sandeepmohan** [awslabs/aws-data-wrangler#839]
**Describe the bug**

Glue Pyspark jobs throw error after multiple prior successful runs when trying to import awswrangler into the glue job script. AWS Support and I looked into this and it looks like there is a new Pandas version out and when pip tries to pull that down for use as part of the awswrangler download, it throws an error. Immediate fix is to hardcode the pandas version in job parameters and run the code again. We had a job failing in Prod for a day prreventing data from moving downstream to redshift because of it.

That having been said, way to mitigate Production jobs leveraging awswrangler from failing because of upstream version upgrades would be:

1. Provide a list of packages and versions that we need to specify as additional values to the '--additional-python-modules' flag in Glue jobs or
2. Hardcode the versions specific to a particular aws wrangler release as part of the  release's dependencies or build file

That way pip would only pull the versions that the Wrangler team has qualified to work.

Thanks in advance,

Sandeep

**Comment by kukushking** [comment]
Thanks @sandeepmohan . This links back to #805 & #817 after which we've decided to be a bit less strict on the dependency versions and pin only up to major. Unfortunately that does have side effects and we'll reconsider for the next release.

As a general best practice in production consider pinning the version of wrangler that you are using as things may break between releases and impact production workloads.
