### ISSUE TITLE
NoRegionError; For queries that return 0 result

### ISSUE THREAD

**Issue by 15aditya** [awslabs/aws-data-wrangler#840]
We are using awsdatawrangler for reading data through Athena. The `read_sql_query` method works fine when we have a query that returns some result set but when we pass an query that will result in 0 records we get `NoRegionError` instead of getting an empty dataframe.

Same query returns 0 record, if we run it through AWS Console. I am not sure if it is a bug or I am missing on something.

**Comment by jaidisido** [comment]
Could you please provide an example of the commands you used so we can reproduce it?

Here is a simple example we ran:
```
import awswrangler as wr
import pandas as pd

wr.s3.to_parquet(
    df=pd.DataFrame({
        'col': [1, 2, 3],
        'col2': ['A', 'A', 'B']
    }),
    path="s3://my-bucket/my_table",
    dataset=True,
    partition_cols=["col2"],
    database="my_db", 
    table="my_table"
)

df = wr.athena.read_sql_query(sql="SELECT * FROM my_table WHERE col=4", database="my_db")
print(df)
```
which returns an empty dataframe as expected

**Comment by 15aditya** [comment]
Here is the snippet of code we are using. It's pretty straight-forward.

Below query returns records as expected.

![image](https://user-images.githubusercontent.com/22195749/128595969-fcc1823c-fd1f-4226-9e0a-d5c2e3e68d26.png)

But, when I just change the product_code in my query to 'XYZ' it throws an error rather than returning 0 records.

![image](https://user-images.githubusercontent.com/22195749/128596033-d3f28b9e-d1cd-4253-b513-757464ace1e3.png)

Also, when run same query on athena it works fine.

![image](https://user-images.githubusercontent.com/22195749/128596058-adc207fd-c06f-43ed-aec5-7e23fa7cd366.png)

**Comment by jaidisido** [comment]
Thanks for these additional details, I still cannot reproduce sadly despite using the same input parameters. Could you please confirm that you are using the latest Wrangler version (2.10.0) and could you share the full error trace so we can check where it breaks exactly? Thanks

**Comment by 15aditya** [comment]
Hey thanks man, I upgraded the version to 2.10.0 and everything worked. I was earlier using 2.9.0 seems like something got fixed :).

Anyways thanks again .
