### ISSUE TITLE
Read_csv with version_id does not work if file has been removed

### ISSUE THREAD

**Issue by stigviaene** [awslabs/aws-data-wrangler#845]
**Describe the bug**

`s3.read_csv` fails with 'No files found' if calling with an object URI that has been removed:
```
---------------------------------------------------------------------------
NoFilesFound                              Traceback (most recent call last)
<ipython-input-7-ea952b057dd8> in <module>
      3 wr.s3.read_csv(path='xxx', 
----> 4                version_id='xxx', boto3_session=sesh)

~/.../.env/lib/python3.6/site-packages/awswrangler/s3/_read_text.py in read_csv(path, path_suffix, path_ignore_suffix, version_id, ignore_empty, use_threads, last_modified_begin, last_modified_end, boto3_session, s3_additional_kwargs, chunksize, dataset, partition_filter, **pandas_kwargs)
    308         last_modified_end=last_modified_end,
    309         ignore_index=ignore_index,
--> 310         **pandas_kwargs,
    311     )
    312 

~/.../.env/lib/python3.6/site-packages/awswrangler/s3/_read_text.py in _read_text(parser_func, path, path_suffix, path_ignore_suffix, ignore_empty, use_threads, last_modified_begin, last_modified_end, boto3_session, s3_additional_kwargs, chunksize, dataset, partition_filter, ignore_index, version_id, **pandas_kwargs)
    128         paths = _apply_partition_filter(path_root=path_root, paths=paths, filter_func=partition_filter)
    129     if len(paths) < 1:
--> 130         raise exceptions.NoFilesFound(f"No files Found on: {path}.")
    131     _logger.debug("paths:\n%s", paths)
    132 

NoFilesFound: No files Found on: s3://uri_to_removed_file.
```

I believe this is due to [_path2list](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_list.py#L17) using list_objects_v2 under the hood.

**Environment**

Provide your `pip list` output, particularly the version of the AWS Data Wrangler library you used. Providing this information may significantly improve resolution times.
```
Package             Version
------------------- ---------
awswrangler         2.10.0

```

**To Reproduce**

1. Upload CSV file to S3 in a bucket with versioning enabled.
2. Delete same file from S3
3. Get the version ID of the file that's been removed
4. Call `wr.s3.read_csv(path='path_to_removed_file', version_id='version_before_deletion')`

**Comment by jaidisido** [comment]
You are right @stigviaene, the issue is with the `ListObjectV2` API call used to retrieve S3 objects. It does not take a version_id or delete marker as input and thus cannot retrieve a deleted file. We are looking at workarounds.
