### ISSUE TITLE
Error On Athena to Pandas (CTAS Approach)

### ISSUE THREAD

**Issue by BellyTheMagnificent** [awslabs/aws-data-wrangler#86]
Encountered error below when using the new approach:

> awswrangler.exceptions.QueryFailed: NOT_SUPPORTED: Unsupported Hive type: timestamp with time zone. You may need to manually clean the data at location 's3://aws-athena-query-results/tables/<_hash-name_>' before retrying. Athena will not delete data in your account.

**Comment by igorborgest** [comment]
Unfortunately it is an Athena's limitation for CTAS and views. And we will not be able to handle timestamps with timezones with this approach by now.

You could cast it to regular timestamp or fallback to the default Pandas.read_sql_athena() approach if the time zone matters for you.

**Comment by BellyTheMagnificent** [comment]
The `timestamp with time zone` column was result from awswrangler.pandas.to_csv(parse_dates=parse_dates). How to make it become regular timestamp?

**Comment by BellyTheMagnificent** [comment]
I just realized my query use CURRENT_TIMESTAMP function which hit the problem. I change to localtimestamp
The timestamp which already written in the parquet file won't hit the problem
Please close the issue.
