### ISSUE TITLE
failed to process partitioned parquet from s3 to sql

### ISSUE THREAD

**Issue by eskuai** [awslabs/aws-data-wrangler#865]
Hello,

I need to process using sql sintaxis a partitioned parquet file from s3.

Reading doc, I can write the following code:

```
df3 = wr.s3.select_query(
        sql='SELECT * FROM s3object',        
        path='s3://mkn-mkn/pandas/pandas_fake_data-30.parquet/state/city',
        input_serialization="Parquet",
        input_serialization_params={},
        use_threads = True
)
```
And I expect to a dataframe with the 'select * from ' execution.

But, I got the following error message:

```
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

can i run s3-select_query applying partitioned parquet?

Using python 3.8, wrangler  0.1.8.6

Tx

**Comment by jaidisido** [comment]
Based on your example, it seems that your S3 path is incorrect: `s3://mkn-mkn/pandas/pandas_fake_data-30.parquet/state/city`. Should it not be something along the lines of: `s3://mkn-mkn/pandas/state/city/pandas_fake_data-30.parquet` perhaps?

**Comment by eskuai** [comment]
Hi @jaidisido ,

Thank you for your response.

You are right, my mistake  but using pandas_fake_data-30.parquet as s3 bucket name , i got the same error code.

I can undestand that it seems to be as file not found, but be sure,  partitioned parquet file is there.

how can i set the right  s3 bucket and parque file using partitions??

Tx

**Comment by jaidisido** [comment]
S3 select should be able to read a single parquet file if it exists. Whether the data is partitioned should not matter.
Here is an example with public data:
```
import awswrangler as wr

df = wr.s3.select_query(
        sql="SELECT * FROM s3object s where s.\"star_rating\" >= 5",
        path="s3://amazon-reviews-pds/parquet/product_category=Gift_Card/part-00000-495c48e6-96d6-4650-aa65-3c36a3516ddd.c000.snappy.parquet",
        input_serialization="Parquet",
        input_serialization_params={},
        use_threads=True,
)
```
The data in the bucket is partitioned by `product_category` but S3 select can still read a single parquet file (not multiple though).

Did you try querying the file using S3 select but from the AWS S3 console?

**Comment by eskuai** [comment]
Hi @jaidisido 

I am testing using simple python from doc ... 

```
df = wr.s3.read_parquet(
    path='s3://mkn-dojo/pandas/pandas_fake_data-30.parquet', # i dont know how set if partitioned and multiple keys/files
    dataset=True,
    partition_filter=lambda x: x['state'] == 'Nevada', # a example filter ... 
    use_threads=True
)
print(df)
df3 = wr.s3.select_query(
        sql='SELECT * FROM s3object',        
        path='s3://mkn-dojo/pandas/pandas_fake_data-30.parquet',
        input_serialization="Parquet",
        input_serialization_params={},
        use_threads = True
)
  
#df.loc[:, df.columns != "product_title"].head()
print (df3)
```

Running and shows error 
```
$ c:/85-python/parquet/p3.py
          full_name                         email                   datetime   state       city
0  Shelby Mcconnell  gritstone2068@protonmail.com 2007-09-19 04:49:34.599171  Nevada  Las Vegas

<stack trace error >

    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```
About the s3 bucket, 

![imagen](https://user-images.githubusercontent.com/1777753/129240980-f41a5fe2-fa57-49d4-adf7-ba6850db83bc.png)

Using aws cli,

![imagen](https://user-images.githubusercontent.com/1777753/129242015-8c2f462d-d674-473a-9238-6175b98e9545.png)

what am i doing wrong?

can i use multiple partitiosn and files parquet s3 files?

Tx

**Comment by jaidisido** [comment]
@eskuai, as stated in the [tutorial](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/029%20-%20S3%20Select.html), S3 select operates on a single S3 object, you cannot read multiple objects at once. It's meant to be used for very large files (up to several TBs) where the user wishes to delegate the querying and filtering server-side instead of client-side (See [blog](https://aws.amazon.com/blogs/aws/s3-glacier-select/) for more details).

For the use case that you have in mind (i.e. reading multiple partitions), `wr.s3.read_parquet` is the right method and your first example is correct.

**Comment by eskuai** [comment]
Hi @jaidisido 

I understand the scene, but i dont need to used TBs ... i want to use MBs ... 
Then, I have to read again all parquet files to make a big dataframe and launch sql queries on it?

```
def s3_url(bucket, prefix, folder=False):
    return "s3://{bucket}/{prefix}{folder}".format(bucket=bucket,prefix=prefix,folder="/" if folder else "")

def mysql(q):
    return sqldf(q, globals())

clientS3 = boto3.client('s3')
bucket_name='mkn-dojo'
bucket_prefix='pandas/pandas_fake_data-30.parquet'
rows=None
print ("start reading all parquets files")
for my_bucket_object in clientS3.list_objects_v2(Bucket=bucket_name, Prefix=bucket_prefix)['Contents']:
    if my_bucket_object['Key'].endswith('.parquet'):        
        s3_path = s3_url(bucket=bucket_name, prefix=(my_bucket_object['Key']))                 
        df = wr.s3.read_parquet(path=s3_path)
        rows = pd.concat([df, rows])

print ("all parquet recollected as one")
print (mysql("SELECT * FROM rows where full_name like '%M%' ;"))
```

I think that a PR about may be considered ...

Tx

**Comment by jaidisido** [comment]
You don't need to loop over objects, this is already handled by  the `wr.s3.read_parquet` method which unlike `wr.s3.select_query` can read multiple objects and partitions:
```
wr.s3.read_parquet(path='s3://mkn-dojo/pandas/pandas_fake_data-30.parquet/')
```
should read all the partitions and objects under that path. I am not sure what you think is missing.
