### ISSUE TITLE
wr.s3.to_parquet() producing intermittent, inconsistent typing

### ISSUE THREAD

**Issue by seungjoonrim** [awslabs/aws-data-wrangler#867]
**Describe the bug**

I have an ETL pipeline implemented to load s3 .json to s3 .parquet like so:
```
df = pandas.read_json(data)
wr.s3.to_parquet(df=df, path='', dataset=True, mode='overwrite', boto3_session=session)
```
the .json input looks like:
```
{
    "from": "2021-04-26T15:00:00-04:00",
    "to": "2021-06-06T11:00:00-04:00",
    "pickedReservations": 0,
    "created": "2021-04-25T10:31:50.666471-04:00",
    "modified": "2021-04-26T18:40:58.082501-04:00"
}
```
but the .parquet output produces:
```
{
    "from": "2021-04-26T15:00:00-04:00",
    "to": "2021-06-06T11:00:00-04:00",
    "pickedReservations": 0,
    "created": "2021-04-25T10:31:50.666471-04:00",
    "modified": 4.5366649549621843367829896e+25
}
```
as you can see, `created` and `modified` are the same format in .json, but the .parquet result is different. this also doesn't happen with every record. some of them have the `modified` field typed correctly. the job also runs without errors but produces `HIVE_BAD_DATA` error when trying to query with athena. This is happening with more than one table and datatype

**Comment by jaidisido** [comment]
This issue usually arises when you have empty, mixed or undetermined types in your data. In which case, it's advised to leverage the `dtype` parameter of [`to_parquet`](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) to explicitly declare your data types. Example:
```
wr.s3.to_parquet(
    df=df,
    path='s3://my-bucket/my_tbl/',
    dataset=True,
    table="my_tbl",
    database="default",
    dtype={"modified": "timestamp"},
    mode='overwrite'
)
```
