### ISSUE TITLE
Proposal to rename project

### ISSUE THREAD

**Issue by brianmingus2** [awslabs/aws-data-wrangler#869]
Propose we rename AWS Data Wrangler, conceding defeat to AWS SageMaker Data Wrangler. 

Gone, then, are the days of having to explain to clients that they aren't the same thing.

Proposed alternatives (no acknowledgement required):

AWS Data Star
AWS Data All-Star
AWS Data Rake
AWS Data Plumber
AWS Keep Track
AWS Data Lambda
AWS PyDataRegex
AWS Data Graph
AWS Data Vapor
AWS Data Fork
AWS Data Framer

**Comment by jaidisido** [comment]
Thanks for the suggestion @brianmingus2. There is a number of reasons why that would not be feasible/desirable however. Setting aside the fact that AWS Data Wrangler was created way before its homonymous counterpart, changing names this late in the project would mean:

- Moving the repository to a new one and thus losing the accumulated stars, forks, issues, artifacts (e.g. Lambda layers...) and having to rebuild the community. Likewise for the docs which would need to move to a new URL. Same for the PyPi project which would have to be recreated losing the accumulated downloads and versions...
- Breaking existing urls, docs, PyPi packages and other references as we cannot maintain two versions of the repos, hostnames... That is likely to confuse users or worse break some of their processes
- The library would lose its spot/hits on search engines like Google that it earned over time
- Figuring out a way to reach out to all existing users and the community to redirect them to this new project

I have found that users understand the difference between the two fairly quickly when explained properly but also understand that it's unfortunate that we have to explain it. Based on the above however, the cost significantly outweighs any benefit from renaming.

Love the names suggestions though :)
