### ISSUE TITLE
Doc clarification: sqlserver.connect secret_id

### ISSUE THREAD

**Issue by mdavis-xyz** [awslabs/aws-data-wrangler#871]
[The documentation](https://aws-data-wrangler.readthedocs.io/en/2.7.0/stubs/awswrangler.sqlserver.connect.html#awswrangler.sqlserver.connect) for sqlserver.connect says:

> secret_id (Optional[str]:) – Specifies the secret containing the version that you want to retrieve. You can specify either the Amazon Resource Name (ARN) or the friendly name of the secret.

I have 2 questions.

1. Why does it say "containing the *version* that you want to retrieve". Is that a typo? Version of what? Secrets don't have version. The version of SQL Server I'm using or ODBC driver version is not a secret, that's just config.

2. What should the secret be structured like? 
e.g. is the entire secret value considered the password? (If so, where do I put the username?)
Does it expect:

```
{
   "user": "john",
   "password": "blah"
}
```

or

```
{
   "username": "john",
   "password": "blah"
}
```

or something else?

I note that there's no mention of `secret` on [the SQL tutorial page](https://aws-data-wrangler.readthedocs.io/en/2.7.0/tutorials/007%20-%20Redshift%2C%20MySQL%2C%20PostgreSQL%2C%20SQL%20Server.html).

Looking [here](https://github.com/awslabs/aws-data-wrangler/blob/9de83bb941a8b6a407ea86c42fc99accae980778/awswrangler/_databases.py#L84), it seems it wants:

```
{
    "username": ...
    "password": ...
    "host": ...
    "port": ...
}
```
and optionally `dbname`.

Is that right?
If so, let's update the documentation for `.connect()` to say those fields are expected in the secret.

**Comment by mdavis-xyz** [comment]
It seems `engine` is required, but I don't know what value to put there.

**Comment by mdavis-xyz** [comment]
A related doc issue, the example for `sqlserver.read_sql_query` is not formatted correctly.
We need to add a blank line [here](https://github.com/awslabs/aws-data-wrangler/blob/8b2d43dd6c5475849f944a6b26fd553048043f5a/awswrangler/sqlserver.py#L212).

**Comment by jaidisido** [comment]
Thanks for raising this @mdavis-xyz I have clarified the docs accordingly in this [commit](https://github.com/awslabs/aws-data-wrangler/commit/d1de947f5817452857240fcacbb10bcf2bf8b14f). It's visible in the [latest](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.sqlserver.connect.html#awswrangler.sqlserver.connect) docs.

Also fixed the minor [issue](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.sqlserver.read_sql_query.html) with `read_sql_query`.
