### ISSUE TITLE
feat: Add read support for Delta Lake files

### ISSUE THREAD

**Issue by brightsparc** [awslabs/aws-data-wrangler#873]
**Is your feature request related to a problem? Please describe.**
Add the ability to read files stored in a delta lake formation in S3.

**Describe the solution you'd like**
Extend the s3 api support the following command `wr.s3.read_delta(path, version="1", dataset=True)` which takes an optional version argument.  

Databricks has created a Rust API with [python bindings](https://delta-io.github.io/delta-rs/python/) that would allow reading and optionally writing data to S3 backend.

The library is built onto of PyArrow so should be compatible with most of the other implementation for reading datasets.

**Comment by jaidisido** [comment]
Thanks for this feature suggestion @brightsparc. This is not currently on our roadmap but we always welcome PRs from the community so happy to review it if you have plans to submit it
