### ISSUE TITLE
redshift.read_sql_query doesn't return column names when existing table / view is empty

### ISSUE THREAD

**Issue by jaklan** [awslabs/aws-data-wrangler#874]
**Describe the bug**
If I run some SQL query on an existing Redshift table / view with defined columns, but being empty, I expect to get the result DataFrame in such a form:
```
Empty DataFrame
Columns: [a, b, c]
Index: []
```
But instead I get this:
```
Empty DataFrame
Columns: []
Index: []
```
so information about column names is lost.

**Environment**

`awswrangler 2.10.0`

**To Reproduce**

```python
import awswrangler as wr

with wr.redshift.connect(connection="SOME_CONNECTION") as connection:
    df = wr.redshift.read_sql_query(sql="SELECT * FROM schema.some_existing_table_or_view_with_no_data", con=connection)
    print(df)
```

**Comment by jaklan** [comment]
@jaidisido thanks for that! I've just seen there are new answers there and it seems that the solution should be provided on Wrangler side:
>If you want to create an actual empty table with columns, you will need to pass a list of zero-length arrays.

**Comment by jaidisido** [comment]
Now merged to main and can be tested:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
until it's available in the next release
