### ISSUE TITLE
Pandas.to_csv() output single file

### ISSUE THREAD

**Issue by BellyTheMagnificent** [awslabs/aws-data-wrangler#88]
Is it possible for Pandas.to_csv() to output single file and have option to put in file name? 

The reason is that for RDS it don't have a COPY mechanism like redshift that able to take in multiple files.

**Comment by igorborgest** [comment]
Hi @BellyTheMagnificent!

You can achieve that passing *procs_cpu_bound=1* and then using the return of the Pandas.to_csv():

```py3
import awswrangler as wr

s3_paths = wr.pandas.to_csv(
    dataframe=df,
    path=path,
    procs_cpu_bound=1)

print(f"My single path: {s3_paths[0]}")
```

I don't think that you really need to specify the filename, right? Receive that should be enough.

**Comment by igorborgest** [comment]
@BellyTheMagnificent let me know if it not address your issue!
