### ISSUE TITLE
Documentation regarding using local DynamoDB

### ISSUE THREAD

**Issue by fsiler** [awslabs/aws-data-wrangler#881]
**Is your idea related to a problem? Please describe.**
I cannot for the life of me figure out how to set up a boto3 session that knows to talk to the local DynamoDB session.  It's easy enough to set up eg

    import boto3
    import awswrangler as wr
    boto3_session = boto3.session.Session(region_name='localhost')
    wr.dynamodb.put_df(df=df, table_name=USERS_TABLE, boto3_session=boto3_session)

But here, `awswrangler` will try to communicate with the cloud instance, and `boto3.session.Session` does not have any kind of endpoint parameter- those can only be specified for the `client` or `resource` objects.

**Describe the solution you'd like**
Some way of telling `awswrangler` to please use the local DynamoDB instance, whether that's by just adding an endpoint_url parameter, or by documenting how it works.  I just can't figure it out based on available `boto3` and `awswrangler` docs.

**Comment by jaidisido** [comment]
Wrangler enables users to set global boto3 [configuration](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/021%20-%20Global%20Configurations.html), including service endpoint URLs. However, this is currently missing for DynamoDB which I am fixing in PR #887. Thanks for raising this, I will update this thread once it's merged

**Comment by jaidisido** [comment]
Now merged to main and can be tested:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
until it's available in the next release
