### ISSUE TITLE
EMR jobs concurrency

### ISSUE THREAD

**Issue by MaxEhrhart** [awslabs/aws-data-wrangler#889]
Hi, currently in our AWS environment we process a lot of jobs in EMR.

There are several cases where we could use the EMR concurrency option. But our environment is created from lambdas scripts with awswrangler and from what we saw, there is no parameter for creating an emr cluster with awswrangler that allows configuring the concurrency of jobs.

It would be very valuable to us if this parameter or argument existed.

Thanks!
![image](https://user-images.githubusercontent.com/22263628/132057891-5c2efa30-a2d9-4db6-97e2-65b3db4e265a.png)

**Comment by jaidisido** [comment]
Thanks for the suggestion @MaxEhrhart, PR #890 should address that

**Comment by jaidisido** [comment]
Now merged to main and can be tested:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
until it's available in the next release
