### ISSUE TITLE
Document on how to use lambda layer

### ISSUE THREAD

**Issue by dirkgomez** [awslabs/aws-data-wrangler#89]
Can you please document on how to use the lambda layer instead of just refering to that it exists. I do not immediately know how to use it. (Refering to: P.S. Lambda Layer's bundle and Glue's wheel/egg are available to download. Just upload it and run! 🚀)

Thanks a lot

**Comment by igorborgest** [comment]
Done!

https://aws-data-wrangler.readthedocs.io/en/latest/stepbystep.html#setting-up-lambda-layer

or

https://github.com/awslabs/aws-data-wrangler#setting-up-lambda-layer

**Comment by dirkgomez** [comment]
Thanks a lot!
