### ISSUE TITLE
Add Support for Opensearch

### ISSUE THREAD

**Issue by mureddy19** [awslabs/aws-data-wrangler#891]
**Is your feature request related to a problem? Please describe.**
Datawrangler does not have the functionality to Read/Write data to/from Pandas, This feature aims to add Opensearch capability to Datawrangler

**Describe the solution you'd like**
Solution should allow users to search Indices and return Pandas Dataframe and to write existing Dataframe to Opensearch Indices. Connect,Read & Write methods to be available for users.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
Thanks for the suggestion @mureddy19, looking forward to the contribution
