### ISSUE TITLE
Will I need paid AWS account to learn what this project does? am exploring this repo

### ISSUE THREAD

**Issue by anildhage** [awslabs/aws-data-wrangler#892]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
Hi @anildhage, thanks for this question. You will indeed need an AWS account to explore aws-data-wrangler, but you can benefit from the [AWS Free Tier](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all). As long as you keep your testing within these limits, you should be able to use the library without incurring significant costs.
