### ISSUE TITLE
pyodbc error with awswrangler lambda layer

### ISSUE THREAD

**Issue by kvr981** [awslabs/aws-data-wrangler#896]
I have downloaded awswrangler-layer-2.11.0-py3.8.zip and added this as layer in my lambda
and my lambda imports awswrangler

import awswrangler as wr
 con = wr.sqlserver.connect(connection="MY_GLUE_CONNECTION", odbc_driver_version=17)

and getting below error.. 

{
  "errorMessage": "You need to install pyodbc respectively the AWS Data Wrangler package with the `sqlserver` extra for using the sqlserver module",
  "errorType": "ModuleNotFoundError",
  "stackTrace": [
    "  File \"/opt/dynatrace-python-agent/wrapt/wrappers.py\", line 566, in __call__\n    return self._self_wrapper(self.__wrapped__, self._self_instance,\n",
    "  File \"/opt/dynatrace-python-agent/dynatrace/otel/sensors/awslambda/incoming/__init__.py\", line 192, in instrumented_handler\n    result = wrapped(*args, **kwargs)\n",
    "  File \"/var/task/onpremSqlHandler.py\", line 14, in onprem_sql_handler\n    con = wr.sqlserver.connect(connection=\"MY_GLUE_CONNECTION\", odbc_driver_version=17)\n",
    "  File \"/opt/python/awswrangler/sqlserver.py\", line 31, in inner\n    raise ModuleNotFoundError(\n"
  ]
}

any help is much appreciated

**Comment by jaidisido** [comment]
Hi @kvr981, from the [docs](https://aws-data-wrangler.readthedocs.io/en/stable/install.html#notes-for-microsoft-sql-server):

```
If you want to connect to Microsoft SQL Server from AWS Lambda, you can build a separate Layer including the needed ODBC drivers and pyobdc.
```

There are two reasons why `pyodbc` is not included in the default Wrangler Lambda layer:
1. Including the library and its drivers would make the layer too large and exceed the limit
2. The licensing of the `pyodbc` library does not allow us to package it in a zip or wheel file

For these two reasons, it's up to the customer to create an additional layer containing both `pyodbc` and the ODBC drivers.

**Comment by kvr981** [comment]
I added pyodbc layer but still i am getting errors
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/python/lib/python3.8/site-packages/pyodbc.cpython-38-x86_64-linux-gnu.so)",

any idea what I am missing here?
