### ISSUE TITLE
Support for Aurora Postgresql

### ISSUE THREAD

**Issue by ankurshri** [awslabs/aws-data-wrangler#90]
Hi,
I just lovely utility, thanks. Does this utility supports Aurora PostgreSQL just similar to what we have for Redshift? If not, can we have plan to implement in future?
Thanks

**Comment by igorborgest** [comment]
Hi @ankurshri! Thank you very much for your inputs.

We just developed a Aurora+Pandas integration available on version +**[0.1.4](https://github.com/awslabs/aws-data-wrangler/releases/tag/0.1.4)**.

Now you can LOAD (MySQL/PostgreSQL) and UNLOAD (MySQL) to/from Pandas DataFrames using the HIGH throughput S3 integration:

```py3
import awswrangler as wr

wr.pandas.to_aurora(
    dataframe=df,
    connection=con,
    schema="...",
    table="..."
)

df = wr.pandas.read_sql_aurora(
    sql="SELECT ...",
    connection=con
)
```

For those operation and databases that does not have S3 integration, please keep using the native Pandas/PySpark APIs:

1. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html
2. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html
3. https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=jdbc#pyspark.sql.DataFrameReader.jdbc
4. https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=jdbc#pyspark.sql.DataFrameWriter.jdbc

Please, test it and give us some feedbacks! 🚀
