### ISSUE TITLE
S3 GetObject opetation. The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by durja** [awslabs/aws-data-wrangler#904]
I am getting the following error when calling any s3 related method calls to read json/ parquet and get the below error: 

botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetObject operation: The request signature does not match the signature you provided. Check your key and signing method. 

However, I am able to read the s3 object using boto3 directly and not getting this exception. 

Methods I am getting this error: 

wr.s3.read_parquet('s3_uri')
wr.s3.read_json('s3_uri')

May I know what could be the reason I am getting this error while using wrangler?

**Comment by jaidisido** [comment]
Wrangler simply [relies](https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/002%20-%20Sessions.html) on boto3 sessions to manage credentials and will use the default boto3 session if none is provided. It looks like there might be an issue with your AWS credentials configuration. It could be misconfigured local environmental variables or an issue with the config file.

If your boto3 calls are working correctly, one thing to try is to explicitly pass your boto3 session to the Wrangler calls:
```
wr.s3.read_parquet("s3uri", boto3_session=my_session)
```

**Comment by durja** [comment]
Thank you. I have tried with boto3_session param and for some reason its working on mac but not on windows.

**Comment by jaidisido** [comment]
Pleasure! Closing for now.
