### ISSUE TITLE
Zip release for python 3.9

### ISSUE THREAD

**Issue by jaidisido** [awslabs/aws-data-wrangler#906]
### Discussed in https://github.com/awslabs/aws-data-wrangler/discussions/898

<div type='discussions-op-text'>

<sup>Originally posted by **membra** September 12, 2021</sup>
Hello,

I can't see a release zip for python 3.9 here though I see that support was added earlier this year,
https://github.com/awslabs/aws-data-wrangler/releases

Could zip for 3.9 version be added please?

Thanks!</div>

**Comment by jaidisido** [comment]
Thanks for the suggestion @membra, support for the Lambda Python 3.9 docker image is required for us to build for that version.

An issue is already [open](https://github.com/lambci/docker-lambda/issues/343) with the relevant team and we will track it.

**Comment by spmacdonald** [comment]
Any reason why you wouldn't use `public.ecr.aws/lambda/python:3.9` instead?

**Comment by kukushking** [comment]
I suppose we could, but wold need to add a couple build dependencies. 

`public.ecr.aws/sam/build-python3.9` actually does look like something we could use rightaway. I'll have a look.
