### ISSUE TITLE
Add feature to allow custom AMI for EMR

### ISSUE THREAD

**Issue by BrainMonkey** [awslabs/aws-data-wrangler#907]
**Is your feature request related to a problem? Please describe.**

No, this is to add the functionality to allow for a custom AMI when creating an EMR cluster.

**Describe the solution you'd like**

Would like to pass in a ami-id to as an argument to the create_cluster function. 

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by kukushking** [comment]
Hi @BrainMonkey I have published a PR above adding custom AMI parameter, once merged you can install dev version via:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
To try it out, or wait until the next release.
