### ISSUE TITLE
Implement X-Ray tracing segments

### ISSUE THREAD

**Issue by instagendleg** [awslabs/aws-data-wrangler#909]
**Is your feature request related to a problem? Please describe.**

As of today, it is possible to trace X-Ray events from the application. But, traces are not linked to parent segments. This leads to really complicated analysis.

**Describe the solution you'd like**

Transfer entity from thread context to thread context, as it is described into the X-Ray Python SDK: https://github.com/aws/aws-xray-sdk-python/blob/master/README.md#trace-threadpoolexecutor.

Like:

```python
import concurrent.futures

import requests

from aws_xray_sdk.core import xray_recorder
from aws_xray_sdk.core import patch

patch(('requests',))

URLS = ['http://www.amazon.com/',
        'http://aws.amazon.com/',
        'http://example.com/',
        'http://www.bilibili.com/',
        'http://invalid-domain.com/']

def load_url(url, trace_entity):
    # Set the parent X-Ray entity for the worker thread.
    xray_recorder.set_trace_entity(trace_entity)
    # Subsegment captured from the following HTTP GET will be
    # a child of parent entity passed from the main thread.
    resp = requests.get(url)
    # prevent thread pollution
    xray_recorder.clear_trace_entities()
    return resp

# Get the current active segment or subsegment from the main thread.
current_entity = xray_recorder.get_trace_entity()
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    # Pass the active entity from main thread to worker threads.
    future_to_url = {executor.submit(load_url, url, current_entity): url for url in URLS}
    for future in concurrent.futures.as_completed(future_to_url):
        url = future_to_url[future]
        try:
            data = future.result()
        except Exception:
            pass
```

**Comment by jaidisido** [comment]
Thanks @instagendleg, I want to first make sure you are opening the issue in the right repository. Is this feature related to AWS Data Wrangler? If so can you provide a bit more details about how it would be used? If not, I will transfer the issue to the AWS Xray Python SDK

**Comment by instagendleg** [comment]
Hello @jaidisido, this is actually something to add into this library.

During multithreaded operations, X-ray cannot detect code workflow (parent segment/subsegment to be precise).

**Comment by jaidisido** [comment]
Is your idea to add Xray to this library? Because I don't believe it's used at all at the moment and we don't see how it relates to your specific issue of parent/subsegment threading
