### ISSUE TITLE
arhena.read_sql_query() returns rows  ordered randomly

### ISSUE THREAD

**Issue by seyoongit** [awslabs/aws-data-wrangler#911]
# Data
my dataset is here.

[data.gz](https://github.com/awslabs/aws-data-wrangler/files/7172331/data.gz)

# Query
my query is here. (replace the `<your-database-name>` and etc with yours)
returned rows should be ordered by `timestamp` column. (please check sql last line)

```code
SELECT stockcode, price, volume, timestamp, isBull as is_bull FROM (
  SELECT row_number() over() AS rn, * FROM (
    SELECT * FROM <your-database-name>.<your-table-name>
      WHERE  "$path"='s3://<your-s3-bucket-name>/data.gz'  
      AND (stockcode='057030') 
      AND (true)
      ORDER BY from_iso8601_timestamp(timestamp), sortkey
  )
) ;
```

# Bug Description
I executed `wr.athena.read_sql_query()` with above query and  every time I've got rows which is ordered randomly.

![스크린샷 2021-09-16 오전 3 02 11](https://user-images.githubusercontent.com/47002080/133486157-4667c2c8-264c-4035-a1ab-5ce6e83541a3.png)

but the query works well in athena console. it is ordered by timestamp well as I intended

![스크린샷 2021-09-16 오전 3 11 30](https://user-images.githubusercontent.com/47002080/133486997-40642ce5-e965-4970-b3dd-3c7a11c2993a.png)

**Comment by kukushking** [comment]
Hi @seyoongit, pass `ctas_approach=False` to turn off CTAS [docs](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) or use the solution described in #785 to force a single query result file.
