### ISSUE TITLE
Malformed column value of type numeric received when using DECIMAL or NUMERIC in redshift query

### ISSUE THREAD

**Issue by ullikeuthe** [awslabs/aws-data-wrangler#912]
**Describe the bug**

cast(400 as DECIMAL(10,2)) in redshift.read_sql_query causes malformed column value exception.

**Environment**

Python 3.8.5

Package                Version   Location
---------------------- --------- -------------------------------------------------------------
appdirs                1.4.4
asn1crypto             1.4.0
attrs                  20.1.0
aws-lambda-powertools  1.10.5
aws-requests-auth      0.4.3
aws-xray-sdk           2.6.0
awscli                 1.20.19
awswrangler            2.11.0
beautifulsoup4         4.10.0
bleach                 3.3.0
blessed                1.17.6
boto3                  1.18.19
botocore               1.21.19
certifi                2020.6.20
chardet                3.0.4
colorama               0.4.3
decorator              4.4.2
distlib                0.3.1
docopt                 0.6.2
docutils               0.15.2
dynamodb-json          1.3
elasticsearch          7.9.1
elementpath            2.0.1
et-xmlfile             1.1.0
Faker                  5.8.0
fastjsonschema         2.15.0
filelock               3.0.12
future                 0.18.2
idna                   2.10
inquirer               2.7.0
jmespath               0.10.0
jsonpickle             2.0.0
jsonschema             3.2.0
keyring                22.0.1
lxml                   4.6.3
netifaces              0.10.9
numpy                  1.21.2
openpyxl               3.0.8
packaging              20.9
pandas                 1.3.3
pg8000                 1.21.2
pip                    21.0.1
pipenv                 2021.5.29
pkginfo                1.7.0
psycopg2-binary        2.8.6
pyarrow                5.0.0
pyasn1                 0.4.8
Pygments               2.8.0
PyMySQL                1.0.2
pyparsing              2.4.7
PyPDF2                 1.26.0
pyrsistent             0.16.0
python-dateutil        2.8.1
python-editor          1.0.4
pytz                   2020.1
PyYAML                 5.3.1
readchar               2.0.1
readme-renderer        28.0
redis                  3.5.3
redshift-connector     2.0.887
requests               2.24.0
requests-aws4auth      1.0
requests-toolbelt      0.9.1
retrying               1.3.3
rfc3986                1.4.0
rsa                    4.7.2
s3transfer             0.5.0
scramp                 1.4.1
setuptools             47.1.0
setuptools-git-version 1.0.3
simplejson             3.17.2
six                    1.15.0
soupsieve              2.2.1
stomp.py               7.0.0
strict-rfc3339         0.7
tabulate               0.8.9
termcolor              1.1.0
text-unidecode         1.3
tqdm                   4.57.0
twine                  3.3.0
urllib3                1.25.10
validators             0.18.0
virtualenv             20.3.0
virtualenv-clone       0.5.4
wcwidth                0.2.5
webencodings           0.5.1
wheel                  0.36.2
wrapt                  1.12.1
xmlschema              1.2.3
xmltodict              0.12.0

**To Reproduce**

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import awswrangler as wr

con = wr.redshift.connect("GLUE_CONNECTION)
wr.redshift.read_sql_query("select cast(410 / 100 as DECIMAL(10,2)) as amount", con=con)
```

The exception is raised in type_utils.numeric_in_binary() which seems to support DECIMALS of 8 or 16 bytes.
According to the documentation redshift DECIMALS have variable length and the function fails for DECIMALS with length other than 8 and 16.

For the given example the DECIMAL length is 10.

Any help is greatly appreciated.

**Comment by jaklan** [comment]
Bump this one, I've experienced exactly the same bug.

**Comment by ullikeuthe** [comment]
Apparently type_utils.numeric_in_binary belongs to the python redshift driver and not aws-data-wrangler. Thanks to dirkgomez for pointing that out and opening an issue there.
