### ISSUE TITLE
s3.to_parquet() - Row group size option?

### ISSUE THREAD

**Issue by Manerone** [awslabs/aws-data-wrangler#913]
Hello, is there an option to define the size of row groups when writing a parquet file to s3? Something like:
```Python
import awswrangler as wr
import pandas as pd
wr.s3.to_parquet(
    df=pd.DataFrame(...),
    path='s3://...',
    row_group_size=64_000_000, # 64MB
)
```

I checked the docs and the issues here but could not find it. Sorry if I missed it :)

**Comment by kukushking** [comment]
You're looking for `max_rows_by_file` parameter [(docs)](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet).

**Comment by Manerone** [comment]
Hi @kukushking, sorry for not answering before.
I don't think it is the same thing, from what I understand of Parquet, each file can have one or more Row Groups. The option I mentioned is about the number of rows (or size) in each Row Group and not in the entire file. If you look at the docs of PyArrow (https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html) you can see _row_group_size_.

**Comment by kukushking** [comment]
Ah I see, in that case we recently added `pyarrow_additional_kwargs` that you should be able to use to pass any additional arguments to pyarrow, including `row_group_size`. 
```
wr.s3.to_parquet(..., pyarrow_additional_kwargs={"row_group_size": 100})
```

It will be available in the next release, meanwhile you can install it from the trunk of the repo and try it out:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
Feel free to reopen if there are any more questions.

**Comment by Philser** [comment]
Just now stumbled on the same problem. @ocrease Did you happen to find a solution?

**Comment by ocrease** [comment]
@Philser In the end I used the `ParquetWriter` directly and called `ParquetWriter.write(table_or_batch, row_group_size=None)` multiple times. I don't use the `row_group_size` parameter here either, but instead I implemented my own batching to call `write` when the `table_or_batch` is approximately the desired size
