### ISSUE TITLE
wr.redshift.unload_to_files empty the S3 folder instead of overwriting existing files

### ISSUE THREAD

**Issue by Falydoor** [awslabs/aws-data-wrangler#914]
Currently when I use `wr.redshift.unload_to_files` (https://aws-data-wrangler.readthedocs.io/en/2.11.0/stubs/awswrangler.redshift.unload_to_files.html#awswrangler.redshift.unload_to_files) everything in the S3 path gets removed which is a little bit annoying when doing multiple unloads in the same path.

I believe it is because of this line:

https://github.com/awslabs/aws-data-wrangler/blob/1b8ffa5c81ac05a4d3c55bfeab6138b25f87245d/awswrangler/redshift.py#L944

Would it be possible to avoid such behavior? I have a job that unloads daily files and I just want to unload new content instead of everything.

**Comment by kukushking** [comment]
Reading `UNLOAD` [docs](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html), particularly for `ALLOWOVERWRITE` flag sadly it looks like it would not be possible to unload into the same prefix -  the last unload will either overwrite the content, or fail.

**Comment by Falydoor** [comment]
@kukushking You are correct, it only works if you specify `PARTITION BY` because only the partition with data will be overwrite. My process unloads using a `WHERE` clause so the old partition folders are not touched.

Now I'm curious on why `s3.delete_objects` is run before doing the UNLOAD? Especially if `ALLOWOVERWRITE` is used, is it just for cleaning purpose?

**Comment by kukushking** [comment]
Yes, I think it's just cleaning. So do I understand correctly then, that this extra cleaning is causing an issue for you because it's cleaning everything, and you'd like to overwrite only a specific partition?

**Comment by Falydoor** [comment]
Yes exactly!  I feel like it's either `ALLOWOVERWRITE` or `s3.delete_objects`.

**Comment by kukushking** [comment]
Merged! Will be included in the next release. To install the dev version from the trunk:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
Feel free to reopen if any questions.
