### ISSUE TITLE
Add catalog_id arg to wr.catalog.does_table_exist

### ISSUE THREAD

**Issue by Xiangyu-C** [awslabs/aws-data-wrangler#920]
Hi, I am wondering if you could add catalog_id as an argument to the wr.catalog.does_table_exist method and pass it to the underlying boto3 glue client get_table call. I can see that right now it can only defaults to account id of the user. But we'd like to use cross account access so we'd need to specify the catalog id. Thank you.

**Comment by jaidisido** [comment]
Hi, it's a fair ask. Covered in this [PR](https://github.com/awslabs/aws-data-wrangler/pull/933/files)

**Comment by jaidisido** [comment]
Merged and will be available in the next release

**Comment by Xiangyu-C** [comment]
Thank you.
