### ISSUE TITLE
Wrangler removing records with NULL partitions on writing to S3 Parquet instead of default partition __HIVE_DEFAULT_PARTITION__

### ISSUE THREAD

**Issue by AnushSR** [awslabs/aws-data-wrangler#921]
Using Wrangler to write to S3 as a partitioned table. Wrangler is removing records with None/NaN as the partition column value instead of using HIVE_DEFAULT_PARTITION (used by Spark/Athena/Hive for null values)

Any workarounds to overcome this? So that records with null partitions aren't discarded while writing to a partitioned table.

`import pandas as pd
import awswrangler as wr

df = pd.DataFrame({'timestamp': ["1632524081000", 1632511081111, '1539826200000', '1539824400000', None, "junk"]})
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms', utc=True, errors='coerce').dt.tz_convert('Europe/Brussels').dt.tz_localize(None)
df['date'] = df['timestamp'].dt.strftime('%Y-%m-%d')
df['hour'] = df['timestamp'].dt.strftime('%H')

wr.s3.to_parquet(df,
            path = "s3://test-bucket/test_part_tbl',
            dataset=True,
            schema_evolution=True,
            compression='snappy', 
            partition_cols = ['date','hour'],
            database='test_db',
            table='test_part_tbl',
	    use_threads=True
            )`

**Comment by jprafael** [comment]
Also got affected by this. A simple workaround is to manually set the partition column to `__HIVE_DEFAULT_PARTITION__` before the call to `to_parquet`

**Comment by jaidisido** [comment]
Thanks @jprafael, closing as this is a simple solution
