### ISSUE TITLE
Public Resource Bucket Not Available to SAM deployment in West-2

### ISSUE THREAD

**Issue by jt3po** [awslabs/aws-data-wrangler#923]
**Describe the bug**

When using CloudFormation in a us-west-2 CodePipeline deployment to create a Lambda Layer using the public artifact bucket we get the following error: 

qa/infra/serverless WranglerLayer07dd4e9c62 AWS::Lambda::LayerVersion CREATE_FAILED Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ce35e94f-2668-4f53-ba55-d17ca9d7daff; Proxy: null)

SAM Template snippet: 

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM CloudFormation Template for gcs-reles Serverless Applications

...

Resources:

...

  WranglerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: REDACTED
      Description: AWS Wrangler Layer
      CompatibleRuntimes:
        - python3.8
      ContentUri:
        Bucket: aws-data-wrangler-public-artifacts
        Key: releases/2.10.0/awswrangler-layer-2.10.0-py3.8.zip
      RetentionPolicy: Retain

Is it possible to use this technique to create a layer in a region outside of us-east-1? We have to run this deployment in us-west-2 for disaster recovery purposes.

**Environment**

us-west-2 , CodePipeline / Codebuild CloudFormation SAM template deployment

**To Reproduce**

Create a SAM Template with the later as defined above, try to deploy in us-west-2

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Indeed that method is region specific and only supports us-east-1 at the moment. You can however, download the layer from the public bucket and store in your own bucket in the region of your choice instead

**Comment by jt3po** [comment]
Thanks for the answer. Any plans to expand region support?

**Comment by jaidisido** [comment]
There are currently 25 regions and 8 more in the work. Replicating/managing each of them would be too convoluted. Instead, we wanted to show an example with us-east-1 and let users replicate in their own regions instead
