### ISSUE TITLE
utilize glue connections for db connections parameters

### ISSUE THREAD

**Issue by robertaves** [awslabs/aws-data-wrangler#95]
A nice utility function to enable building database connections from glue connection parameters ( by connection name )

today i'm using boto to lookup the connection by name and extract the JDBC JDBC_CONNECTION_URL and parse to build the connections.. something like the below.. 

def pg_glue_connection(name):

    cli = boto3.client("glue")
    conn_props = list(filter(lambda x: x["Name"] == name, cli.get_connections()["ConnectionList"]))[0]["ConnectionProperties"]

    url = conn_props["JDBC_CONNECTION_URL"]
    host = url.split("://")[1].split(":")[0]
    port = url.split("://")[1].split(":")[1].split("/")[0]
    dbname = url.split("://")[1].split(":")[1].split("/")[1]
    user = conn_props["USERNAME"]
    password = conn_props["PASSWORD"]

    return pg8000.connect(
        database=dbname, host=host, port=int(port), user=user, password=password, ssl=True, application_name="glue"
    )

**Comment by igorborgest** [comment]
Thanks for your contribution @robertaves!
It's already developed and will be in the next release!

**Comment by robertaves** [comment]
Thanks again for this lib!
