### ISSUE TITLE
to_json with partition columns 

### ISSUE THREAD

**Issue by islandereleven** [awslabs/aws-data-wrangler#962]
I would like to migrate large amounts of non sanitized data in an orderly fashion as partitioned json files. 

Would it be possible to mimic the awswrangler.s3.to_parquet **partition_cols** parameter in awswrangler.s3.to_json

related https://stackoverflow.com/questions/64275874/how-to-save-pandas-dataframe-into-partitioned-json

**Comment by kukushking** [comment]
Hi @islandereleven - added. You can try it out now by installing from the trunk like below:

```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```

The feature will be included with the next release. Feel free to reopen if any questions!
