### ISSUE TITLE
Request for glue.get_table_pandas_types

### ISSUE THREAD

**Issue by josecw** [awslabs/aws-data-wrangler#97]
Is there a quick way to get metadata from glue catalog and then pass into pandas.read_csv()? 
Specifically for files without metadata/headers

Scenario:
metadata is created into glue catalog first as data file do not have header. The job get metadata from glue catalog then serialize input file in pandas.read_csv() before writing to parquet.  
However,  partition column affect column position created in glue catalog (position and the end)

`In traditional ETL context`
1. Define file structure in data store
2. Use the defined file template as source in data flow
3. Parameterize file name for each run (for source file with running date as name)
4. Update file structure when there is update

`In Glue Python:`
1. Define 'table' structure in Glue Catalog (no data underlying, not queryable)
2. Based on file name grab table meta from glue catalog, pass into read_csv() for serialize for the headerless file.
3. Transform the input file to parquet (with same structure), but output to a new database + table for data lake query.

By doing this, file structure changes will not need to modify python script. 
- Does this make sense?  or it is better to use Glue Spark + Grok expression for this purpose? (multiple files but small in size)

**Comment by BellyTheMagnificent** [comment]
Updated with some clarification and scenario.

**Comment by igorborgest** [comment]
Thanks for the precise explanation @josecw!

Now it is possible combining two function:

[wr.catalog.get_table_types()](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.catalog.get_table_types.html#awswrangler.catalog.get_table_types)
[wr.s3.to_csv()](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.s3.to_csv.html#awswrangler.s3.to_csv) with the `dtype` argument.

available on version `1.0.2`.
