### ISSUE TITLE
add dynamodb.put_items for one item ej: dynamodb.put_item 

### ISSUE THREAD

**Issue by jhonnattan123** [awslabs/aws-data-wrangler#971]
**Is your idea related to a problem? Please describe.**
sometimes it is necessary to insert a single item in DynamoDB. however the library only allows to work with multiple items, using the dynamodb.put_items method this forces to add the dynamodb:BatchWriteItem permission to the roles.

**Describe the solution you'd like**
add a new method called dynamodb.put_item that allows to insert a single item.

**Comment by jaidisido** [comment]
Wrangler is meant to be used with pandas data frames as an input. We believe very few use cases would involve a pandas data frame with a single row so would not consider `put_item` as an additional method, especially that this use case is already covered here but simply requires an additional IAM action
