### ISSUE TITLE
glue catalog delete_column does not fully respect catalog_id passed in

### ISSUE THREAD

**Issue by rpmchale** [awslabs/aws-data-wrangler#975]
**Describe the bug**

When providing a different account for the catalog_id the get_table function within delete_column does not utilize the different catalog_id. I suspect the get_table() parameters need to be wrapped in the **_catalog_id() function similar to the update_table function within delete_column.

**Environment**

awswrangler==2.10.0

**To Reproduce**

Try to delete a column from a table that resides in a different account than where the code is currently executing. In my scenario, the exception indicates an access issue but the getTable is not using the catalog_id provided via the delete_column parameters. I event tried setting the catalog_id via the wr.config.catalog_id which did not work.

not authorized to perform: glue:GetTable on resource: arn:aws:glue:us-east-1:{ACCOUNT}:catalog

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Good catch, will be covered by above PR and included in next release. Thanks
