### ISSUE TITLE
Return Version Id after S3 Create Method call

### ISSUE THREAD

**Issue by updiversity** [awslabs/aws-data-wrangler#978]
For the S3 methods that write to S3, is it possible to know what is the Version ID that has been associated to the objects uploaded ?

**Comment by jaidisido** [comment]
No, that information is not available in the response returned by the boto3 calls for those methods. Adding it would require an additional S3 get call which would be costly, potentially requests intensive and require more IAM permissions when most users don't need that info. The S3 paths are returned in the call though so you can always run the GET call on that output
