### ISSUE TITLE
Custom parquet name

### ISSUE THREAD

**Issue by alicehua11** [awslabs/aws-data-wrangler#988]
https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_write_parquet.py#L508

It would be nice to have a flag that we can pass in so that we can just use our filename without the hex added while calling `wr.s3.to_parquet()`

**Comment by jaidisido** [comment]
This is a duplicate of https://github.com/awslabs/aws-data-wrangler/issues/617

If you are writing a single file you can specify the full name. But when `dataset=True`, more than a single file could be written and a random hex is added (see issue)
