### ISSUE TITLE
EmptyDataFrame exceptions raised by API lack message

### ISSUE THREAD

**Issue by dhritimanb** [awslabs/aws-data-wrangler#989]
**Describe the bug**

If an empty data frame is provided to functions to write data to [S3](https://github.com/awslabs/aws-data-wrangler/blob/e42809006c20d9d05ab708a9422f9a2e75bbd3c9/awswrangler/s3/_write_text.py#L43), [mysql](https://github.com/awslabs/aws-data-wrangler/blob/80d900b5727181abd467584378e55013627e6a80/awswrangler/mysql.py#L363), [redshift](https://github.com/awslabs/aws-data-wrangler/blob/2eaba7687c87f152471137735e46a79bf33dcc1d/awswrangler/redshift.py#L800) and others, the code raises `EmptyDataFrame` exception with **no args**.

I had a try/catch block around a call to `to_parquet`, and I was logging the exception, but I was getting empty error messages. The onus on ensuring that the dataframe is not empty is on the user. But, the corresponding error message is not meaningful. It would have saved me some time, if a more usable error message was returned.

**Environment**

Python=3.7
awswrangler>=2.8

**To Reproduce**
```python
import pandas as pd
import awswrangler as wr
from awswrangler.exceptions import EmptyDataFrame

# Create boto3_session variable if required
# Set destination s3 path
df = pd.DataFrame({'a':[], 'b':[]})
try:
    wr.s3.to_parquet(df=df, path=s3_path, boto3_session=boto3_session)
except EmptyDataFrame as err:
    print(f"Error: {err} occured")
```
will generate the following output
```
Error:  occured
```

**Comment by jaidisido** [comment]
This is fair enough. It will be covered by #991. Thanks

**Comment by dhritimanb** [comment]
Thank you.
