### ISSUE TITLE
Cache read_sql_athena

### ISSUE THREAD

**Issue by luigift** [awslabs/aws-data-wrangler#99]
Read the athena query result from s3 instead of re-running the query again for identical queries

**Comment by BellyTheMagnificent** [comment]
Can re-use the athena query result (temp files) for to_aurora()?

**Comment by igorborgest** [comment]
Released on version [1.6.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.6.0)! 🎉 🎉 🎉
