### ISSUE TITLE
There's no Change log or Release History file in the code base

### ISSUE THREAD

**Issue by MacHu-GWU** [awslabs/aws-data-wrangler#992]
Hi, I cannot find the common Change log file in this Repo and also not in PyPI. It is better to have it as a open source project.

**Comment by jaidisido** [comment]
The [releases](https://github.com/awslabs/aws-data-wrangler/releases) section of the repo is listing major changes with every release. What do you feel is missing there? I am not a fan of commit based automated change log generators as I find they often contain too much junk, making them hard to read
