### ISSUE TITLE
wr.s3.delete_object() not work with prefix

### ISSUE THREAD

**Issue by kev-dfs** [awslabs/aws-data-wrangler#995]
Hi,
I'm trying delete objects on a "folder" in s3, but the code is not working. Only work fine with a complete key.

Example don't work:
```
s3_path = 's3://bucket_name/partition1=2020/patition2=09'
wr.s3.delete_object([s3_path])
```

Example work:
```
s3_key = 's3://bucket_name/partition1=2020/patition2=09/file.parquet'
wr.s3.delete_object([s3_key])
```

Tools:
Glue Joib
    Type | Spark
    Glue version | 2.0
    Python version | 3
    ETL language | python
    awswrangler version: 2.7.0

**Comment by jaidisido** [comment]
From the [docs example](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.delete_objects.html#awswrangler.s3.delete_objects),  you should not pass a list when deleting objects in an S3 path, just a string:
```
wr.s3.delete_objects('s3://bucket/prefix')  # Delete all objects under the received prefix
```
Notice that a string is passed, not a list

**Comment by kev-dfs** [comment]
Hi @jaidisido 

So, If I can delete a list of object on different prefix, I must execute a "delete_object" for each prefix?

Thanks.
