### ISSUE TITLE
EventStreamError

### ISSUE THREAD

**Issue by mandywoo** [awslabs/aws-data-wrangler#996]
I am running wr.s3.select_query and am getting this error: EventStreamError: An error occurred (InternalError) when calling the SelectObjectContent operation: We encountered an internal error. Please try again.

**Comment by jaidisido** [comment]
[InternalError](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) is considered a server side error, meaning S3 was unable to process your request.

Have you been able to run this same operation directly in the AWS S3 Select [console](https://medium.com/geekculture/how-to-query-s3-objects-with-s3-select-from-the-console-72fdad76160c)?

Here are as well some [suggestions](https://stackoverflow.com/a/49898120/8178963) as to the potential cause
